### ISSUE TITLE
br --sizes problem

### ISSUE THREAD

**Issue by GrosSacASac** [Canop/broot#100]
**From** https://news.ycombinator.com/item?id=22001726

**Is everything clear?**
We prefer you come to the chat and speak about the problem first.
Broot chat room: https://miaou.dystroy.org/3490?broot 

**Describe the bug**
Love it. Thanks for sharing.

But I found one issue which might be a critical one:

When you start broot with "br --sizes", it shows you all the folder sizes. The tree than takes a while to render all the different files and folders, since they probably have to be recursively evaluated in size.

However, when you select a specific file, press space and then `rm` to delete it, the pointer might change to another file randomly. This is because the file list is still not rendered-out because of the file sizes beeing calculated, however, the pointer to the selected file should be persistant or you might accidentaly delete an important file. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
- Relevant configuration items

**Additional context**

**Comment by Canop** [comment]
Rephrasing for me:
 ensure that the selected index is correctly updated when lines are reordered so that the selected path is always the same.

**Comment by epitron** [comment]
Another issue with `--sizes`: You can move the selection bar up past the top of the list, and out of the window, which does weird things.

**Comment by Canop** [comment]
@epitron I think what you observed is just selection cycling: going up is a way to go to the bottom (and vice-versa). Can you confirm or did I misunderstand you ?

**Comment by epitron** [comment]
Not cycling, out-of-bounds movement, which breaks the display and cursor movement until you quit.
