### ISSUE TITLE
broot --sizes reports nominal size for sparse files rather than actual disk usage

### ISSUE THREAD

**Issue by fredcy** [Canop/broot#102]
**Did a discussion occur before?**
Yes, I brought this up in the chat room today.

**Is your feature request related to a problem? Please describe.**
Here is a way to show the problem on MacOS.

Create a sparse file with a small but non-zero actual disk usage but large nominal size. (Non-zero because broot already has a special case for zero-actual-size.)  The equivalent `dd` command on linux uses `seek=1G`.

```
echo "test" > sparsetest
dd if=/dev/zero of=sparsetest bs=1 count=0 seek=1g
ls -lks sparsetest
```

The `ls` command reports a file size of 1073741824 (1G) but disk usage of 4 (K) because the 5 bytes of actual file content require one (and only one) 4K block.

When I then run `br --size` the sparsetest file is reported with a size of "1024M".

**Describe the solution you'd like**
I would like broot to report the actual file size (blocks used times block size) for sparse files. That could either be a command line option similar to `ls -ks`, or it could be code that looks for the case of sparse files and reports them differently. Something like this:

```
let file_size = if md.blocks() * md.blksize() < md.size() { md.blocks() * md.blksize() } else { md.size() };
```

**Describe alternatives you've considered**
None

**Additional context**
Per chat discussion, the code involved is here: https://github.com/Canop/broot/blob/a0477be58aecb84335becf5424802718bf8fbdbf/src/file_sizes/file_sizes_unix.rs#L57

**Comment by fredcy** [comment]
NB: The whalespotter program seems to report file size the same way, making sparse files look like bigger "whales" than they actually are in terms of disk usage.

**Comment by Canop** [comment]
The remaining question is about ergonomics.

For a folder, we're almost always only interested by the "real" size (that is the number of blocks multiplied by the block size). I'll definitely base the folder computation on this.

But for a simple file, the nominal size makes probably more sense. The solutions might be, for them, to

1. just display nominal size, this might lead to many bug reports...
2. display the nominal size as number with a small 's' when it's an attribute, and use the "real" size for the size bar and for sorting
3. add a second column for the nominal size, use the "real" one for the bar and sorting
4. same than 3 but using a toggle for the nominal size display
5. same than 3, but only if at least one file is sparse

**Comment by fredcy** [comment]
FWIW, I believe the code I suggested will report the nominal size for all but sparse files.

**Comment by Canop** [comment]
yes but that doesn't mean we can't display this size without hint as to why it's different from what ls report.
I'll try to report the real size *but* with a small 's' to show that it's a sparse file.

**Comment by fredcy** [comment]
That sounds good to me, if I understand you correctly.

**Comment by Canop** [comment]
![image](https://user-images.githubusercontent.com/617006/72454076-7ab2ad00-37c0-11ea-8285-f37c1d7daf57.png)

I don't feel at ease regarding Windows. Should I do the same on non unix platforms ?

**Comment by fredcy** [comment]
The "s" suffix looks good to me. I don't know enough about Windows to weigh in on what should happen there.

Thanks for addressing this problem.
