### ISSUE TITLE
Deletes directory it was launched from

### ISSUE THREAD

**Issue by Lensi** [Canop/broot#104]
**Describe the bug**
Trying to delete a file, deciding to cancel (ctrl+c) and navigating elsewhere can lead to deleting current working directory

**To Reproduce**
1. Setup test data and run br from inside:
```
mkdir -p br-test/folder-to-delete
cd br-test
br
```
2. Navigate to folder-to-delete by e.g. writing `folder`
3. Append `:rm`
4. Press ctrl+c
5. Press escape
6. Press enter

**Expected behavior**
I would expect to go up a level

**Configuration (please complete the following information):**
 - OS: Linux
 - Version 0.11.0, reproduced on 0.11.6

Edit: Github decided to just post the template the first time around, so updated 24 hours later

**Comment by Canop** [comment]
You're supposed to fill the template. Right now I have no idea of what is the bug you want to report or the feature you request.

**Comment by Lensi** [comment]
Yeah sorry, Github screwed me and just ignored my input. But I had more time to properly reproduce now. This is a nasty one.

**Comment by Canop** [comment]
I reproduce the problem!

**Comment by Canop** [comment]
This was a major bug. I issued a twitter alert but unfortunately I don't really see a proper way to make people upgrade.

**Comment by briangordon** [comment]
@svenstaro Could you update your Arch package? 😰 https://www.archlinux.org/packages/community/x86_64/broot/

**Comment by svenstaro** [comment]
In a bit. We're all volunteers.

**Comment by briangordon** [comment]
No problem, I know. Just wanted to make sure you were aware, as this is a particularly serious one.

**Comment by Lensi** [comment]
This might be a chance to reconsider if `:rm` really should mean `rm -rf`.
Everyone knows `rm -rf` is dangerous and try to be extra cautious when typing it out, but here you're not typing it. Why not introduce `:rm-rf` or similar?

**Comment by Canop** [comment]
The problem here wouldn't really have been different with rm. rm on the wrong target, or any action on the wrong target is bad.

Something a little relevant I hesitated to add is a confirmation dialog required on some verbs. There's already the attribute in the verb. But as the command is normally shown before execution, it's not so interesting.

**Comment by Lucretiel** [comment]
> The problem here wouldn't really have been different with rm. rm on the wrong target, or any action on the wrong target is bad.
> 
> Something a little relevant I hesitated to add is a confirmation dialog required on some verbs. There's already the attribute in the verb. But as the command is normally shown before execution, it's not so interesting.

I agree; the issue is some sort of race with the command, where it can change its target unexpectedly. I think that's the thing to focus on.

**Comment by Canop** [comment]
It's fixed, normally. The problem was that the verb wasn't removed from the command.

**Comment by Lensi** [comment]
Forgetting the bug, my point is:
1. You are typing `rm`, but `rm -rf` is being executed. This in itself isn't intuitive.
2. Combine that with that fact that deleting the the wrong file (or whole directory because of 1) is just another (arrow) key press away.

**Comment by Canop** [comment]
The command which is executed is
* displayed in the status line
* modifiable in the config
The problem was with the bug

**Comment by Lucretiel** [comment]
We should considering disallowing `rm` in `--cmd` mode, though, because that loses all of the protections granted by interactive mode.

**Comment by Canop** [comment]
We could have another command just for the --cmd, like `:rm-file`.
And alert in the doc about the danger.
At this point if somebody decides to add it in a --cmd sequence, it's probably with a reason.
