### ISSUE TITLE
Truncated listing for current directory

### ISSUE THREAD

**Issue by alexforencich** [Canop/broot#106]
**Describe the bug**
broot truncates the current folder listing and displays 'X unlisted' at the bottom for the current directory.  

**To Reproduce**
From a directory with a lot of files in it, run br.  

**Expected behavior**
The current directory should never be truncated.  This is what scrolling is for.  Truncation should be limited to subdirectories only.  

**Screenshots**
![image](https://user-images.githubusercontent.com/508807/72122205-fe2c5400-3311-11ea-8dbb-d6a2a8eaec02.png)

**Configuration (please complete the following information):**
 - OS: Arch Linux
 - Version 0.11.4

**Additional context**
None that I am aware of.

**Comment by alexforencich** [comment]
Still present in 0.11.5.

**Comment by Canop** [comment]
I'm not sure you understand the idea of broot.

If you really want to display all the root files, you may use the :t command, but that's not how you're supposed to use it.

Here's the documentation: https://dystroy.org/broot/documentation/usage/

**Comment by alexforencich** [comment]
Ah, I didn't see that when I glanced over the documentation.  How do I change that to be the default?  And what is the rationale for trimming the current directory being the default setting, besides simply allowing scrolling?

**Comment by Canop** [comment]
The first goal is to offer an overview. In the rare case the root doesn't fit the screen it's probably because there's too much to see. Scrolling takes a lot of time. I prefer to filter, with only one key.

If you want by default to see the root untrimmed, you may launch broot with

     broot --cmd ":t"

(you may do an alias for it).

In the future, I'm planning to offer the ability to define default values for toggles in the conf file.

**Comment by alexforencich** [comment]
Makes sense, but what's the advantage of trimming vs showing a scroll bar?  The default behavior is rather confusing.

**Comment by ralt** [comment]
I believe he answered your question in his last message:

> In the rare case the root doesn't fit the screen it's probably because there's too much to see. Scrolling takes a lot of time. I prefer to filter, with only one key.

**Comment by ralt** [comment]
As for the "confusing" part, this feature is the first one that is mentioned on the homepage: https://dystroy.org/broot/

**Comment by alexforencich** [comment]
That does not answer the question.  It seems to me that there is no appreciable difference between a truncated list and a list that extends off the bottom of the screen.  However, in one case, it is impossible to scroll down and see other elements, in the other case it is.  I still see no reason why the root should ever be truncated, aside from perhaps something related to performance.  

It's confusing because truncating subidirectories makes sense, but truncating the current directory does not make sense.  In that first picture, a small sampling of files in each subdirectory are shown.  Makes sense.

**Comment by Canop** [comment]
I now think the scrollbar does make sense **for root elements**. It's still a little alien because most of broot usage doesn't involve it and you might not even notice it while you're trained to notice the "5 files unlisted" at the bottom.

I keep in mind (and in my notes) that this is something to let possible in configuration, and maybe more.

**Comment by alexforencich** [comment]
Yeah, I like the truncated view of subfolders.  That's a nice feature so you can get an idea of what's buried without being overwhelmed.  But I don't think it makes any sense to do so for the root element, as you can simply scroll down to see those elements (or not, if you don't like scrolling).

**Comment by alexforencich** [comment]
Actually, if you like the '5 files unlisted' at the bottom, then maybe you could show '5 more files [down arrow]' or something along those lines if it overflows

**Comment by graynk** [comment]
I agree that default behaviour is rather confusing, and all mentions of unlisted feature in the documentation are always in conjunction with mentioning .gitignore files, while saying nothing about truncating root elements.

**Comment by survb** [comment]
Agree that "unlisted" default setup is really confusing. Wording in documentation on t verb does not reflect "unlisted",  "delete node" - scary expression - sounds like node are going to be erased from file system.  I spend 20 minutes digging out solution and was close to give up on using otherwise good product.

**Comment by Canop** [comment]
@survb where do you read "delete node" ? I don't find it.

**Comment by Canop** [comment]
I've decided to change the default value of the toggle_trim_root setting to false, meaning the initial display of a directory with many direct children might exhibit a scrollbar.

**Comment by Rmano** [comment]
Hi, sorry for chiming in on a closed issued, but: I just intalled `broot` 0.18.5, and if I call it with `br -s` in my home dir, I have the following:

![image](https://user-images.githubusercontent.com/6414907/86906562-06741900-c114-11ea-8e84-8ae46633faf9.png)

...and I can't find a way to scroll down to see the 23 unlisted here. I can type something and I will have a selection (which is good and I understand is the main mode of `broot`), but shouldn't be showing a scroll bar? 

I found that I can fix it adding `default_flags = "gT"` --- but I expected it to be a default off-the-box. 

So I hope that this message can help other people looking for it...

**Comment by jmce** [comment]
A similar problem occurs with search results, truncated according to terminal size as illustrated here, and there seems to be no way to toggle this into the full scrollable listing (quite desirable, in some cases, at least inside a single directory). 

![truncated search](https://user-images.githubusercontent.com/580605/111871019-ef164c80-897f-11eb-8054-d07da8e66188.png)

**Comment by Canop** [comment]
Use :toggle_trim_root to toggle behavior, or `default_flags: T` in conf

**Comment by jmce** [comment]
toggle_trim_root doesn't change broot's behavior for search results, using broot 1.2.8 (recently compiled here). And the default behavior without search is the non-truncating one corresponding to default_flags: T.  
Same behavior in 1.2.9 (pre-compiled binary, downloaded a few minutes ago).

**Comment by Canop** [comment]
I see.
