### ISSUE TITLE
Cannot define a shortcut for br with zsh.

### ISSUE THREAD

**Issue by Avi-D-coder** [Canop/broot#107]
Errors when pressing shortcut, with both xterm and kitty.
`Termimad Error : "Crossterm error"`
**To Reproduce**
Add the following to `.zshrc`
```zsh
function br {
    f=$(mktemp)
    (
	set +e
	broot --outcmd "$f" "$@"
	code=$?
	if [ "$code" != 0 ]; then
	    rm -f "$f"
	    exit "$code"
	fi
    )
    code=$?
    if [ "$code" != 0 ]; then
	return "$code"
    fi
    d=$(<"$f")
    rm -f "$f"
    eval "$d"
}

zle -N br
bindkey '^@' br
```

**Configuration**
 - OS: Arch Linux
 - broot 0.11.5
 - zsh 5.7.1

**Comment by Canop** [comment]
Why did you add the function to .zshrc ? Was there a problem with the automatic installation (which only add a line to source the function definition script) ?

**Comment by Avi-D-coder** [comment]
Performance. The fewer files read the faster zsh starts.

**Comment by boazy** [comment]
Confirmed this also happens with the automatic installation.
It even happens if I just do this:
```
function br() {
  broot
}
zle -N br
bindkey '^@' br 
```

**Comment by rpolve** [comment]
You can get it to work by using the following line:

bindkey -s '^@' 'br\n'

No need to declare a new widget with zle -N.

Reference: http://zsh.sourceforge.net/Intro/intro_11.html

**Comment by nkh** [comment]
fd | cat | br

generates the same error
