### ISSUE TITLE
Cannot install br command under Ubuntu 18.04

### ISSUE THREAD

**Issue by flaiming** [Canop/broot#108]
**Is everything clear?**
I tried chat first, but no one answered.

**Describe the bug**
I'm not able to install broot properly under Ubuntu 18.04. I downloaded precompiled broot, run it (working), `broot --install` seem to work OK, but when I try to use "br" command, it cannot find it, even if I open new terminal or source .bashrc. Bashrc itself is patched.
I even tried full system restart, no change.
```
$ ./broot --install
You requested a clean (re)install.
Removing /home/flaim/.config/broot/launcher/installed-v1.
Removing /home/flaim/.local/share/broot/launcher/bash/1.
Writing br shell function in /home/flaim/.local/share/broot/launcher/bash/1.
Removing /home/flaim/.config/broot/launcher/bash/br.
Creating link from /home/flaim/.config/broot/launcher/bash/br to /home/flaim/.local/share/broot/launcher/bash/1.
/home/flaim/.bashrc already patched, no change made.

The br function has been installed.
You may have to restart your shell or source your shell init files.
Afterwards, you should start broot with br in order to use its full power.
$ br

Příkaz 'broot' nebyl nalezen, možná jste měli na mysli:

  příkaz 'brook' ze snapu brook (c95e9a9)
  příkaz 'proot' z deb balíku proot
  příkaz 'brot' z deb balíku fortunes-de

Viz 'snap info <jméno snapu>' pro další verze.
$ . ~/.bashrc
$ br

Příkaz 'broot' nebyl nalezen, možná jste měli na mysli:

  příkaz 'brook' ze snapu brook (c95e9a9)
  příkaz 'brot' z deb balíku fortunes-de
  příkaz 'proot' z deb balíku proot

Viz 'snap info <jméno snapu>' pro další verze.
```
(sorry for czech locale)

**To Reproduce**
Just try try to install broot under Ubuntu 18.04

**Expected behavior**
`br` command should be working

**Configuration (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04
- GNU bash, version 4.4.20(1)-release
 I installed this OS recently (this week), so it shouldn't be bloated.

**Additional context**

**Comment by Canop** [comment]
It looks like the problem isn't with the br function but with broot (which is called by br). `broot` must be somewhere where it will be found (for example you can put an alias to it in /usr/local/bin/broot).

(sorry to have missed your message in the chat, the last 30 hours have been unusually noisy and it wasn't easy following everything)

**Comment by flaiming** [comment]
Ah, I thought that installation process will take care of putting broot in some /bin/ folder. I didn't find any instruction in install docs that I have to do that manually. 
I moved broot in my ~/bin/ foler and it works perfectly :)

**Comment by Canop** [comment]
OK. I need to think about making this more obvious. I can see how the `--install` argument can be misleading...

**Comment by Opfour** [comment]
user@host:~$ sudo cp /home/user/Downloads/broot /usr/local/bin/broot
user@host:~$ which broot
/usr/local/bin/broot
user@host:~$ alias br='/usr/local/bin/broot'
user@host:~$ br
New Configuration file written in "/home/user/.config/broot/conf.toml".
You should have a look at it.

Worked using this option.

**Comment by harmlessdrudge** [comment]
`broot --install`

doesn't work under Linux Mint 19.3. Moving the `broot` file to /bin resolved. Pity to omit telling new Linux users to use `sudo` if using any of the relevant distros (Debian, Ubuntu, Mint etc.). The help page shows two little boxes with 0s and 1s where I think images of arrow keys are supposed to be displayed. No idea what's going on here. A missing font? 

A nice addition to the toolbox. Thanks. Only suggestion for 1.0: a check for updates function, either automatic or manual. Automatic:

config file

`CheckForUpdateOnStart: true`

**Comment by Canop** [comment]
> Only suggestion for 1.0: a check for updates function, either automatic or manual

@harmlessdrudge  I almost missed that. I added it to the todo but next time please try to post it in a more visible place ;)
