### ISSUE TITLE
allow selection by mouse click

### ISSUE THREAD

**Issue by deathtrip** [Canop/broot#11]
Currently you can move through entries with the mouse scrollwheel, i think i would make sense to complement it with the ability to select an entry with the mouse click. It would make working with the mouse much more productive.

**Comment by Canop** [comment]
I wouldn't use that but why not. I'll try to implement it.

**Comment by Canop** [comment]
It looks like there are problems in termion.
https://gitlab.redox-os.org/redox-os/termion/issues/164

**Comment by Canop** [comment]
Switching from termion to crossterm made it easy to have mouse click support. It's done.
