### ISSUE TITLE
Left and right arrows should have sane behavior

### ISSUE THREAD

**Issue by briangordon** [Canop/broot#111]
**Describe the bug**
The up/down arrows work correctly, but the left/right arrows seem to take on the behavior of the last vertical arrow you pressed. So:

- If I'm scrolling up with the up arrow and then press either the left or right arrow, the left or right arrow will _continue_ scrolling up.
- If I'm scrolling down with the down arrow and then press either the left or right arrow, the left or right arrow will _continue_ scrolling down.

**To Reproduce**
1. Hit the up or down arrow.
2. Hit the left or right arrow.

**Expected behavior**
Perhaps the left arrow can go up to the parent directory, and the right arrow can drill down to the selected directory (or do nothing if the selected line is not a directory).

**Screenshots**
N/A

**Configuration (please complete the following information):**
 - OS: Arch Linux
 - Version 0.11.4
 - Default configuration

**Additional context**
I'm not sure if this matters at the level of your code but I'm sshing into a headless server and my terminal emulator is using xterm emulation.

**Comment by Canop** [comment]
I reproduce the bug.

Left and right arrows should normally only be used for input edition and should not impact navigation.
