### ISSUE TITLE
Scrolling past the end of the window doesn't reset the view

### ISSUE THREAD

**Issue by briangordon** [Canop/broot#112]
**Describe the bug**
If I have enough items on screen that they can't all be displayed on screen at once, the scrolling behavior is broken. 

**To Reproduce**
1. Set your terminal emulator height to display, say, 40 lines.
2. Have broot enter a directory with more than 40 files.
3. Use the `:t` command to untrim the root and show all files.
4. Use the down arrow to scroll down to the very last file.
5. Continue hitting the down arrow.

**Expected behavior**
The window redraws the list from the beginning, displaying the first item in the list highlighted by the selection bar.

**Actual behavior**
The first item in the list seems to be selected, but it remains off-screen. You can keep scrolling through off-screen items but you won't be able to see the selection bar until it comes down close enough to your view of the end of the list.

**Screenshots**
N/A

**Configuration (please complete the following information):**
 - OS: Arch Linux
 - Version 0.11.4
 - Default configuration

**Comment by Canop** [comment]
I reproduce.
