### ISSUE TITLE
:e when $EDITOR has flags crashes

### ISSUE THREAD

**Issue by carlpett** [Canop/broot#114]
**Describe the bug**
I have set `$EDITOR` to `subl -nw`. If I do `enter` or `alt+enter` in broot, the editor is opened correctly. However, if I issue `:e` within broot, it crashes with `Unable to launch subl -nw: No such file or directory (os error 2)`. It seems to exec the entire string?

**Configuration (please complete the following information):**
 - OS: Fedora Linux
 - Version: 31
 - Relevant configuration items: `export EDITOR="subl -nw"`

**Comment by Canop** [comment]
The problem may be because the command isn't searched from your shell, so doesn't know all the paths. Can you check with using the complete path to subl ?

**Comment by carlpett** [comment]
Doesn't seem to help: `Unable to launch /bin/subl -nw: No such file or directory (os error 2)`

I think what is happening is similar to this:
```shell
$ "subl -nw" test
-bash: subl -nw: command not found
```

**Comment by Canop** [comment]
You're probably right.

**Comment by carlpett** [comment]
I have no Rust skills at all, but I'm guessing it happens here:
https://github.com/Canop/broot/blob/dcfa01906e72980ab7a77c627309336e18eb5b47/src/external.rs#L102-L110

`exe` is `subl -nw`, but "some magic" needs to happen to split ` -nw` out into `args`?

**Comment by Canop** [comment]
@carlpett I'd appreciate if you can confirm it's OK for you (you may want to wait for a release)

**Comment by carlpett** [comment]
Yes, seems to work, tested with 0.11.7.
Thanks! :tada:
