### ISSUE TITLE
add documentation on why broot should be launched using a shell function

### ISSUE THREAD

**Issue by zachvalenta** [Canop/broot#115]
**Describe the solution you'd like**

Just a line or two in the docs to explain:

```log
Broot should be launched using a shell function (see https://github.com/Canop/broot for explanations).
The function is either missing, old or badly installed.
Can I add a line in ".bashrc and .zshrc" ? [Y n]
```

I've never come across this using a CLI, which might just be my ignorance but I assume a fair number of other users might be in the same boat.

**Comment by Canop** [comment]
The explanation is interesting but rather technical, so I'm not sure where to put it.

**Comment by Canop** [comment]
For reference, the explanation:

You can't do a cd from a terminal application : you're into a subshell.
So the trick here is to have the br function launch broot, wait for its end, fetch the resulting (optional) cd destination, and do the cd in the original shell.

**Comment by zachvalenta** [comment]
This is very helpful. Let me dig around the docs and see if I can find a home for it.

**Comment by Canop** [comment]
In fact this should be explained where I introduce the `from_shell` verb attribute: https://dystroy.org/broot/documentation/configuration/#verb-definition-attributes
