### ISSUE TITLE
Use terminal's colors

### ISSUE THREAD

**Issue by dynobo** [Canop/broot#116]
First: Thanks for this great tool! :-)

Would it be possible to use/respect the colors that are configured for the console? Most tools do this (e.g `ranger` or `cmus`), and it would be cool if broot would blend in as well :-)

The text in the directory listing already seems to take to colors correctly, but not the background, the command-bar and the yellowish accent color.

In the following screenshot you see on the left ranger which shows according to my terminals colors, and broot:
![2020-01-10_15-19](https://user-images.githubusercontent.com/11071876/72159484-bd3d4980-33bc-11ea-8824-d658d3c6de1b.png)
Thanks!

**Comment by Canop** [comment]
I'll have to dive into it before I can tell you what I (can) do, so don't expect anything super soon, but I'm not rejecting the request at all.

**Comment by anotherchrisatwork** [comment]
Don't know how many separate colors are used/needed, but could it use underline and bold instead of colors?

**Comment by Canop** [comment]
Note that you can always override broot default colors by defining your own skin, and the skin syntax allow underline and bold

**Comment by muellerj** [comment]
As mentioned in #140: Maybe it's worth investigating, how difficult it would be to respect `LS_COLORS`, which is what `ls` and `tree` etc. do. It would make switching colorschemes a lot easier, without the need to rewrite `broot`s config every time.

**Comment by dessalines** [comment]
This would be nice to have, seems like all terminal file managers, nnn, ranger, etc all just use default terminal colors. I was pretty weirded out when loading up broot for the first time and it put a background over my transparent terminal.

**Comment by Canop** [comment]
Broot needs a lot of nuances (selection, difference between focused and unfocused tree, matched chars etc.), things that aren't defined or parameterized in LS_COLORS and the small ANSI color range doesn't enable the computation of the intermediate colors (faded ones for example).
I won't implement this.

**Comment by isene** [comment]
LS_COLORS potentially implementes the whole range of colors in a terminal (not just the basic 16) with backgrounds, italics and bold. Take a look at my implementation here: https://github.com/isene/LS_COLORS

It would indeed elevate broot if a parser for LS_COLORS were to be implemented.

**Comment by chtenb** [comment]
Wouldn't this be possible to implement by defining a skin that only uses the 16 (extended) ansi colors? If I'm not mistaken, this is already fully supported. Is there already such a skin around? I'm new to broot and I'm interested in having it use default colors, so I'll have a crack at defining one at some point, if no such thing exists yet.
