### ISSUE TITLE
Default Foreground/background colors, support for reverse attribute

### ISSUE THREAD

**Issue by wavexx** [Canop/broot#117]
**Is your feature request related to a problem? Please describe.**
There are terminal sequences that allow to select the default foreground and background color:

```
ESC[ 38;5;⟨n⟩ m Select foreground color
ESC[ 48;5;⟨n⟩ m Select background color
```

These are usually mapped to some of the default ansi colors, but can be completely different. I cannot see a way to select those. I also don't see a way to select the "reverse video" attribute, which can also result in a different color compared by simply swapping foreground and background.

**Describe the solution you'd like**
Implementing "foreground", "background" as valid colors and using them as the default text and background respectively should be the norm for terminal applications. If done correctly, and when using only the first 8 ansi colors for the default skin you'd likely fix #116 "the right way".

Implementing "reverse" would be an added bonus, as "foreground background reverse" is usually the correct way to implement a status bar which blends in with most terminal setups.

**Comment by Canop** [comment]
When you don't set a "default" color to none, it means it's the system color.

```
[skin]
default = "none none / gray(20) none"
```

**Comment by Canop** [comment]
The new commit added the `reverse` attribute.
