### ISSUE TITLE
Release a version for Mac

### ISSUE THREAD

**Issue by robertveloso** [Canop/broot#12]
Make a release for Mac OS X, maybe a brew package if possible.

**Comment by Canop** [comment]
No objection but I'd need help, I have no mac.

**Comment by hellow554** [comment]
@robertveloso why not installing it the rust way? `cargo install broot`?

**Comment by Canop** [comment]
I guess the homebrew solution is meant for people not wanting to install the rust dev env.

**Comment by delucks** [comment]
@Canop, you could modify the Travis CI used by this repository to cross-compile `broot` for every supported target architecture. It would build compiled binaries for not just Mac, but also *BSD, Windows, and non-x86 architectures, and upload them to the releases page on Github each time you create an annotated git tag. An example of cross-compiling Rust in Travis for (many) target architectures [can be found here](https://github.com/japaric/trust/blob/master/.travis.yml).

**Comment by Canop** [comment]
The problem isn't just compiling, but testing. I already know that broot isn't compatible with Windows (termion isn't, and part of my code isn't (but could be adapted if TTY wasn't a problem)). So I'd need some people to test and report, and maybe help on adaptations, before starting to make a brew package.

**Comment by felipesere** [comment]
It might be worth re-visiting the location for the config file on macOS too?
`/Users/......./Library/Preferences/org.dystroy.broot/conf.toml`  is not really the first place I'd look.
a dotfile in the home directory or maybe in `$HOME/.config/broot/config.toml` would be more intuitive.
Or offer a flag to open or print the path to the config file.

**Comment by Canop** [comment]
The location is given by XDG and seem to be canonical

https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x

*(disclaimer: I didn't use a mac since before MacOsX)*

**Comment by bradparks** [comment]
I'm on a mac, but know nothing about rust/cargo, and tried to run `cargo install broot`, and got a compilation error:

``` Downloading ansi_term v0.11.0
   Compiling lazy_static v1.2.0
   Compiling cfg-if v0.1.6
   Compiling glob v0.2.11
   Compiling num-integer v0.1.39
   Compiling ansi_term v0.11.0
   Compiling fs_extra v1.1.0
   Compiling strsim v0.7.0
   Compiling ucd-util v0.1.3
   Compiling byteorder v1.3.1
   Compiling vec_map v0.8.1
   Compiling libc v0.2.48
   Compiling custom_error v1.3.0
   Compiling unicode-width v0.1.5
   Compiling cc v1.0.29
   Compiling bitflags v1.0.4
   Compiling serde v1.0.87
error: expected one of `,` or `as`, found `::`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/custom_error-1.3.0/src/lib.rs:261:28
    |
261 |         use std::{io, error::Error};
    |                            ^^

error: expected one of `;` or `as`, found `::`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/custom_error-1.3.0/src/lib.rs:261:28
    |
261 |         use std::{io, error::Error};
    |                            ^^

error: expected item, found `;`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/custom_error-1.3.0/src/lib.rs:261:36
    |
261 |         use std::{io, error::Error};
    |                                    ^

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: associated constants are experimental (see issue #29646)
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.2.0/src/inline_lazy.rs:20:5
   |
20 |     pub const INIT: Self = Lazy(Cell::new(None), ONCE_INIT);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error[E0432]: unresolved import `self::Difference::*`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.11.0/src/display.rs:230:13
    |
230 |         use self::Difference::*;
    |             ^^^^^^^^^^^^^^^^^^^^ Could not find `Difference` in `display`

error[E0531]: unresolved variant or struct `ExtraStyles`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.11.0/src/display.rs:242:17
    |
242 |                 ExtraStyles(style) => write!(w, "{}", style.prefix())?,
    |                 ^^^^^^^^^^^

error: this needs a `'static` lifetime or the `static_in_const` feature, see #35897
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/ansi_term-0.11.0/src/ansi.rs:80:19
   |
80 | pub static RESET: &str = "\x1B[0m";
   |                   ^^^^

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: failed to compile `broot v0.5.2`, intermediate artifacts can be found at `/var/folders/rv/qv098x1d31db_vllk60gcv_j3fzc15/T/cargo-install.4RQxmY8rYz8c`

Caused by:
  Could not compile `custom_error`.

To learn more, run the command again with --verbose.
```

**Comment by bradparks** [comment]
running `rustup update` fixed the compilation issue... I now have it installed.. thanks!

**Comment by Canop** [comment]
broot works on mac.
