### ISSUE TITLE
Vim mode?

### ISSUE THREAD

**Issue by ests** [Canop/broot#120]
Is it possible right now to configure broot to work in (sort of) vim mode? I.e. to be able to use `j`, `k`, `g`, `G`, (`/` for all kings of searches) and ect. keys for navigating (and not arrows, which f.i. on most MacBooks are very small and uncomfortable). Similar keys also are used in `less`/`more`, `man` and other pagers, jumping from classic unix tools to broot for me is very uncomfortable and confusing.

**Comment by certik** [comment]
In Vim mode, more keys become available, so `q` could be used for Quit.

**Comment by Canop** [comment]
Not a complete answer (still thinking about the real one) but it's easy to configure broot to use for example ctrl-j and ctrl-k to replace arrow keys.

**Comment by madhermit** [comment]
> Not a complete answer (still thinking about the real one) but it's easy to configure broot to use for example ctrl-j and ctrl-k to replace arrow keys.

I'm interested in this solution (or, more preferably, it being a default). How would one go about configuring broot to use ctrl-j and ctrl-k to replace the arrow keys? Thanks!

**Comment by Canop** [comment]
Look here: https://github.com/Canop/broot/issues/24#issuecomment-572481660

And the relevant documentation is here : https://dystroy.org/broot/documentation/configuration/#verbs-shortcuts-and-keys 

I think I'll start to collect various user configuration to propose them on the site

**Comment by lotsoffood** [comment]
@Canop That would be fantastic to have a set of example configurations to get as close to `vim` keybindings as possible.

**Comment by harterrt** [comment]
I would use this as well! I spent some time noodling with the config trying to get close to vim but I just couldn't get close enough to make it feel natural. Maybe it's finally time for me to get comfortable with rust.

Thanks so much for this software, canop!

**Comment by allan-simon** [comment]
yes thanks for this tool !  having a vim mode will permit to easily  toggle size for example

**Comment by bigbrett** [comment]
oh my lord this would be rad, as someone who wishes everything in life had vim bindings

**Comment by jhonrocha** [comment]
I have just installed it using Pacman and I see this on the config file:
```
# A popular set of shorctuts for going up and down:
#
# [[verbs]]
# key = "ctrl-j"
# execution = ":line_down"
#
# [[verbs]]
# key = "ctrl-k"
# execution = ":line_up"
#
# [[verbs]]
# key = "ctrl-d"
# execution = ":page_down"
#
# [[verbs]]
# key = "ctrl-u"
# execution = ":page_up"
```
It is great! Thx, @Canop!
