### ISSUE TITLE
Some directories that are not empty, are listed as empty?

### ISSUE THREAD

**Issue by curioustolearn** [Canop/broot#122]
**Describe the bug**
When I focus on some directories through broot, the contents of these directories are not listed. They come up as empty, when in fact they have other folders and files in them.

**To Reproduce**
Usual navigation using broot. For me, for example, I type 
br and enter -> then type Drop (which brings up Dropbox) -> Hit enter to get into Dropbox -> then type ab (a folder called AB becomes highlighted) -> Hit enter (nothing is listed here)

In some other folders I have seen that files are listed but folders are not listed.

**Expected behavior**
Complete listing of contents in Broot (especially when they are way less than a page length)

**Configuration (please complete the following information):**
 - OS: Mojave 10.14.4

**Comment by Canop** [comment]
Are you sure those folders aren't hidden because
* of the gitignore filter
* of the hidden files filter (name starting with a dot on most OS)
* of a filter you typed ?

**Comment by curioustolearn** [comment]
Thank you for responding. 
No, the folder does not have a git repo in it. 

Many are regular .docx files and then other standard folders (they do not start with a dot). Some folder names, for example, are Data, Old 

I do type AB to search/filter the AB folder. But then when that gets highlighted, I hit enter key to enter that folder. After that I do not type anything.

**Comment by Canop** [comment]
As I can't reproduce the bug, I'd need
- a detailed test set I can use
- or other people reproducing it

**Comment by curioustolearn** [comment]
So sorry about the error on my end. While the folder I was looking at does not have a git repo in it, one two levels above does. That is what was causing this issue.

**Comment by pi43r** [comment]
oh, my home folder is a git repo using a gitignore with a `*` except my dotfiles ... therefore I can not see any files and folders except I'm in another repo?
How can I change that for broot. I tried the `-gh` flag but no luck

**Comment by Canop** [comment]
> I tried the `-gh` flag but no luck

Try with `-hi`.
