### ISSUE TITLE
Homebrew only provides version 0.10.3

### ISSUE THREAD

**Issue by zachvalenta** [Canop/broot#123]
Just providing a issue to house the outdated Homebrew versions, separate from the `alt-enter` issue https://github.com/Canop/broot/issues/86 (which I how I realized I was running an outdated version)

```
$ brew info broot
broot: stable 0.10.3 (bottled), HEAD

$ brew upgrade broot
Warning: broot 0.10.3 already installed

$ brew uninstall broot
Uninstalling /usr/local/Cellar/broot/0.10.3... (7 files, 2.7MB)

$ brew install broot
==> Pouring broot-0.10.3.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/broot/0.10.3: 7 files, 2.7MB
```

**Comment by chenrui333** [comment]
There is ongoing PR for this work, https://github.com/Homebrew/homebrew-core/pull/48138

Unfortunately, right now I am blocked with the test step:

```
==> /usr/local/Cellar/broot/0.11.7/bin/broot --dates

Broot should be launched using a shell function (see https://github.com/Canop/b
root for explanations).
The function is either missing, old or badly installed.
Can I install it now? [Y n]
```

**Comment by chenrui333** [comment]
Also relates to https://github.com/Canop/broot/issues/77

**Comment by chenrui333** [comment]
Should be fixed now 

Latest v0.11.8 has been released per https://github.com/Homebrew/homebrew-core/pull/48947

**Comment by dakira** [comment]
@chenrui333 no.. that PR was not merged, it was auto-closed.

**Comment by Canop** [comment]
The new `--set-install-state` launch argument can help tests:
![image](https://user-images.githubusercontent.com/617006/72369259-fd276800-36ff-11ea-91fc-38ad56809e71.png)
