### ISSUE TITLE
hotkeys should be disabled when entering a verb

### ISSUE THREAD

**Issue by JonathanDCohen** [Canop/broot#124]
**Describe the bug**
Hotkeys get executed while I'm typing a verb

**To Reproduce**
Place the following in your `conf.toml`:
```
[[verbs]]
name = "exec"
key = "x"
invocation = "exec"
execution = "{file}"
```

then navigate to a file in `br` and attempt to write ":exec"

**Expected behavior**
exec is typed out in the verb input area and "x" doesn't trigger the verb as a hotkey

**Comment by Canop** [comment]
It could be detected during verb typing but what about filtering ? How would you search for a file whose name starts with a x ?

Today's normal use of broot more or less implies the hot keys you define are either rare keys, special keys (for example function keys) or in combinations (for example ctrl-x).

**Comment by JonathanDCohen** [comment]
That makes sense.  It's still very jarring behavior from a verb, whereas when filtering I'd expect it as I'm in the regular mode

**Comment by Canop** [comment]
I also often use hot keys after having started typing a verb (most typical example: I start doing something and I change my mind so I do ctrl-q).

**Comment by Canop** [comment]
This isn't compatible with the current ergonomics of broot and there are several other registered requests related to vi mode. I close this issue.
