### ISSUE TITLE
Can't run an executable from broot

### ISSUE THREAD

**Issue by JonathanDCohen** [Canop/broot#125]
**Describe the bug**
I attempted to make a verb to run an executable file but it fails mysteriously

**To Reproduce**
Place the following in your conf.toml
[[verbs]]
invocation = "run"
execution = "{file}"

And attempt to use it from broot on an executable.  You will get

`Unable to launch /tmp/test.sh: Exec format error (os error 8)`

**Expected behavior**
The file is run

**Comment by Canop** [comment]
If simply hitting enter doesn't work for your scripts (it's system dependent), then you can define an adequate verb like this:

```
[[verbs]]
key = "ctrl-e"
execution = "bash {file}"
```

(assuming bash)

**Comment by JonathanDCohen** [comment]
On my system hitting enter simply exits

**Comment by Canop** [comment]
exiting is normal. broot just asks the standard system solution (probably xdg-open) to take care of opening the file. For a non script executable, it normally means executing it
