### ISSUE TITLE
Can't seem to rebind :cd

### ISSUE THREAD

**Issue by amasover** [Canop/broot#126]
**Describe the bug**
I want to change the default cd keybind (alt-enter doesn't work for me, similar to #86 ). I defined the following in my `~/.config/broot/conf.toml`:

```
[[verbs]]
invocation = "cd"
execution = ":cd"
key = "ctrl-o"
```

The result is this:

```
Unable to launch :cd: No such file or directory (os error 2)
```

Putting other commands into the execution field (e.g., `:help`, `:quit`, `:focus`, etc seems to work fine).

**Configuration (please complete the following information):**
 - OS: Arch Linux
 - Version 0.11.6

**Comment by Canop** [comment]
A `cd` must be done from the parent shell. Here's the proper configuration:

```
[[verbs]]
key = "ctrl-o"
from_shell = true
execution = "cd {directory}"
```
(and there's no internal `:cd`, just use the shell `cd`)

Yes, I know it's a little tricky. I should try to make [this page](https://dystroy.org/broot/documentation/configuration/#verb-definition-attributes) clearer.

**Comment by amasover** [comment]
Thanks a lot @Canop. Yes, I agree, the documentation could be clearer.
