### ISSUE TITLE
Suggestion: format tree view with metadata more like exa

### ISSUE THREAD

**Issue by kbd** [Canop/broot#127]
Compare [`exa`'s formatting of tree view with metadata](https://github.com/ogham/exa#screenshots) (right screenshot) to [`broot`'s similar view](https://dystroy.org/broot/#replace-ls-and-its-clones).

`exa` puts the "ascii art" showing the hierarchy closest to the filename, which makes all the metadata (date, user, etc.) line up vertically, while still giving an easy-to-read tree view. `broot` puts the tree ascii art at the beginning of the line, which makes the metadata not line up, making it harder to read.

**Comment by Lucretiel** [comment]
Agree. Additionally, I'd suggest doing the thing that `exa` does, where each mode bit gets its own color. It makes it much easier to read what can be a very dense piece of information.

**Comment by Canop** [comment]
I'll experiment with this.

**Comment by Canop** [comment]
I just tried moving the tree branches right of the metadata. I'm not convinced: when all the metadata are aligned you lose the sense of hierarchy and it's visually harder to link metadata to the file.
I'll have to think a little more about this one.

For the color per bit, I'll at least make it configurable, and I'll see later if it really helps to have different colors.

**Comment by Canop** [comment]
Here's with rwx mode colored:
![image](https://user-images.githubusercontent.com/617006/72208311-71180500-34a1-11ea-82e1-6c32bc4c13a2.png)
I'm not sure the mode is clearer this way, but I'll try. It's of course possible to tone it down in the skin.

**Comment by boxed** [comment]
exas view is nicer, but I went here to suggest putting that metadata right aligned. That way when you turn it on the _tree doesn't move at all_. This seems way nicer to me.

**Comment by erifire** [comment]
I would prefer it left aligned, but perhaps this could be a configurable? In-tree, left or right aligned.

Another thing I really like about exa is --time-style=long-iso
