### ISSUE TITLE
Make broot install the shell helper function

### ISSUE THREAD

**Issue by delucks** [Canop/broot#13]
Hello! Thanks for writing this tool, it's novel and I'm excited to use it more. I am wondering if you're open to a helper flag in `broot` itself that outputs the entire `br` shell function to standard output. With this flag (let's call it `--shell-helper` for example), you could recommend users set up broot by downloading the binary and running `broot --shell-helper | tee -a ~/.bashrc` or similar. For additional flexibility, you could even read the value of the `$SHELL` env variable and output a version of `br` that's compatible with the user's shell (if it's not `bash`).

**Comment by Canop** [comment]
Having broot providing the shell function looks like a very good idea.

I'm not 100% convinced right now that a helper flag is the right way. I'll need to think more about it.

What about coming and discuss it on [Miaou](https://miaou.dystroy.org/84) ?

**Comment by delucks** [comment]
I'd prefer to discuss here if that's okay with you- I try to minimize my oauth2 credential use. It's pretty awesome that you use your own chat software for the purpose though!

What other methods for exposing the function contents are you thinking? A few off the top of my head: 
- On first run, write to a file somewhere in `$HOME` a bash script that contains the function definition. Print a message to the user saying "To use the automatic cd functionality, please add `source ~/.broot.sh` to your bash profile."
- On first run, output the full shell script into a file that's executed by the user (by putting it in `$PATH`). Print a message saying "If you would like to use the automatic cd functionality, please move `~/br` to a directory in `$PATH`"
- Environment variables. Reading an env var to guard this feature would introduce other questions and might not be obvious to newcomers. I am not a big fan of this option.

**Comment by delucks** [comment]
That's also a good option. You could distribute it alongside the binary in a zip file or similar.

**Comment by Canop** [comment]
`br` as a script would have the same problem as the `broot` program: it wouldn't be able to change the parent shell directory.

**Comment by ralt** [comment]
There isn't a good solution there; the "sanest" one I can think of is:

- On first run, ask if the user wants to add the snippet to `~/."$SHELL"rc`. If yes, append the snippet to the file.
- Write a `$XDG_CONFIG_HOME/broot/installed/$SHELL` empty file. This way, broot will know that it won't need to ask again.

And maybe add a `broot --install-shell-helper [SHELL]` option in case the user wants to do it again?

**Comment by Canop** [comment]
@ralt  Instead of an empty file, we could manage to store the version of the installed shell function. This way we could propose to update it if needed.

**Comment by Canop** [comment]
The same logic more or less applies to both the configuration file, and the $SHELLrc : we may want to install it or modify it, initially or on application change, and we don't want to ask when the user refused a change (or an initial install in the case of `br`).

So my current plan is:

1) define a file as proposed by @ralt but storing for both the conf file and `br`

- the installed version (version independent from broot's version, we shouldn't change them often)
- whether the user refused the last proposed change or not
- on what version was the last proposition

2) ensure that the shell function can be properly rewritten (either by with proper guard comments in the $SHELLrc file or by sourcing another file from the $SHELLrc)  

3) define AppStates dedicated to asking whether files should be installed/rewritten or not, with explanations (the mechanism of such "dialog" states is needed for other commands anyway)

Does that sound OK ?

**Comment by ralt** [comment]
A simple way to handle the version is to have e.g.:

```
$XDG_CONFIG_HOME/broot/helper/
├── 3
└── br -> 3
```

Where the `~/."$SHELL"rc` sources the `br` file, and broot only has to update the symlink. No need to keep a version, it's in the filename.

**Comment by bradparks** [comment]
and fwiw, i'm using `zsh` and would like to see it take this into account as well....

**Comment by ralt** [comment]
Yes, we've been saying `$SHELL` and not bash :)

**Comment by bradparks** [comment]
for sure, i just think the `zsh` helper will have to be a bit different is all ;-)

**Comment by bradparks** [comment]
I'll see if I can get it working....

**Comment by ralt** [comment]
You could try the existing version already, zsh has a lot of bash compatibility features.

**Comment by bradparks** [comment]
hey.... i tried this tonight, and it worked fine... I didn't include it exactly the same way as suggested in the readme, and that's where my issue was. Tonight I put it in my `~/.zshrc` and it worked straight off....

**Comment by Canop** [comment]
Good to know.
If somebody's willing to write and test an a function for another shell, please do it.

**Comment by Canop** [comment]
I've pushed a new branch, shell, with this feature, which I tested on bash.

I'd be grateful for anybody testing it before I merge it into master.

**Comment by ralt** [comment]
So, a bunch of bugs:

If you start `zsh` from `bash`, `$SHELL` is still `/bin/bash`.

You can instead rely on `$shell`, which returns the shell name, e.g.:

```
[ralt@zap]~% echo $shell
zsh
[ralt@zap]~$ echo $shell
bash
```

Another bug: if you install the helper in bash, change `$SHELL` to `/usr/bin/zsh`, then run `broot` again, it doesn't detect that the helper isn't installed in the current shell.

Otherwise it looks good :+1:

**Comment by ralt** [comment]
Another minor point: the `installed` file doesn't have a trailing newline.

**Comment by Canop** [comment]
`$shell` is a shell variable, not an env variable.

I'm not sure there's a reliable way to detect the parent shell and it probably doesn't matter. I should just apply the patch to all files present among ".zshrc" and ".bashrc".

**Comment by Canop** [comment]
I pushed a new version seemingly fixing the last concerns.

I'd like some tests and maybe some contributions for other shells before I merge and bump the version.

**Comment by Canop** [comment]
It's now in master. I'll close this issue if no problem is noticed.
Right now only bash and zsh are supported.
We'll open new issues for other shells if necessary.
