### ISSUE TITLE
Broot on FreeBSD

### ISSUE THREAD

**Issue by vermaden** [Canop/broot#134]
Hi,

I successfully compiled and run `broot` on FreeBSD, details here:
https://vermaden.wordpress.com/2020/01/10/run-broot-on-freebsd/

I needed to make one patch, this one:

```
% diff -u \
  /home/vermaden/.cargo/registry/src/github.com-1ecc6299db9ec823/crossterm-0.14.1/src/terminal/sys/unix.rs.ORG \
  /home/vermaden/.cargo/registry/src/github.com-1ecc6299db9ec823/crossterm-0.14.1/src/terminal/sys/unix.rs
--- /home/vermaden/.cargo/registry/src/github.com-1ecc6299db9ec823/crossterm-0.14.1/src/terminal/sys/unix.rs.ORG  2020-01-10 23:41:29.825912000 +0100
+++ /home/vermaden/.cargo/registry/src/github.com-1ecc6299db9ec823/crossterm-0.14.1/src/terminal/sys/unix.rs      2020-01-10 23:41:07.703471000 +0100
@@ -33,7 +33,7 @@
         ws_ypixel: 0,
     };
 
-    if let Ok(true) = wrap_with_result(unsafe { ioctl(STDOUT_FILENO, TIOCGWINSZ, &mut size) }) {
+    if let Ok(true) = wrap_with_result(unsafe { ioctl(STDOUT_FILENO, TIOCGWINSZ.into(), &mut size) }) {
         Ok((size.ws_col, size.ws_row))
     } else {
         tput_size().ok_or_else(|| std::io::Error::last_os_error().into())

```

Without this patch it failed like that:
https://vermaden.files.wordpress.com/2020/01/broot-fail.jpg

Can we add that patch upstream so it will not be needed to patch it by hand everytime on FreeBSD?

... is it good? I do not know Rust :)

Regards,
vermaden

**Comment by Canop** [comment]
Interesting. I'll summon the crossterm experts!

**Comment by Canop** [comment]
So there's already a PR on crossterm: https://github.com/crossterm-rs/crossterm/pull/361

**Comment by TimonPost** [comment]
This one can be patched and released by the end of this week. Or beginning next week.

**Comment by Canop** [comment]
Of course I'll make a new broot version as soon as crossterm is patched.

**Comment by TimonPost** [comment]
Then ill do it even this night.

**Comment by TimonPost** [comment]
https://crates.io/crates/crossterm

**Comment by Canop** [comment]
The fix is in master, not in a release. I'd like freeBSD users able to compile broot to confirm me it's OK before I distribute the release.

**Comment by vermaden** [comment]
Now it successfully builds and works on FreeBSD without any patches, thanks: https://vermaden.files.wordpress.com/2020/01/broot-update-fixed.jpg

**Comment by aleksuss** [comment]
The same error occurs while compiling 0.2.10:
```
error[E0308]: mismatched types
  --> /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/broot-1.2.10/src/display/cell_size.rs:32:43
   |
32 |     let r = unsafe { ioctl(STDOUT_FILENO, TIOCGWINSZ, &w) };
   |                                           ^^^^^^^^^^
   |                                           |
   |                                           expected `u64`, found `u32`
   |                                           help: you can convert a `u32` to a `u64`: `TIOCGWINSZ.into()`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `broot`
```

The reason is that on freebsd host a size of type `TIOCGWINSZ` constant is 4 bytes, rather than 8 bytes.
```rust
use std::mem::{size_of, size_of_val};
use libc::{c_ulong, TIOCGWINSZ};

fn main() {
    assert_eq!(size_of_val(&TIOCGWINSZ), 4);
    assert_eq!(size_of::<c_ulong>(), 8);
}
```
But on linux host it's [8 bytes](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4694fe5f44c2513d3aecdcf106dc2f87).

I've investigated a little and found out than the binary linking with `/lib/libc.so.7`:
```shell
$ ldd playground/target/debug/playground
playground/target/debug/playground:
	libthr.so.3 => /lib/libthr.so.3 (0x8010b2000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x8010df000)
	libc.so.7 => /lib/libc.so.7 (0x8010f9000)
```
And it seems that used `libc.so.7` had been compiled for `amd64` arch.
```shell
$ objdump -f /lib/libc.so.7

/lib/libc.so.7:     file format elf64-x86-64-freebsd
architecture: i386:x86-64, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x000000000007fc90
```

And at last:
```c
#include <stdio.h>
#include <sys/ioctl.h>

int main() {
    printf("%lu\n", sizeof(TIOCGWINSZ));
    return 0;
}
```
outputs 8 !!!

But why 4 bytes in rust ???

**Comment by Canop** [comment]
@aleksuss You seem to have determined a rather precise location of the problem. Could you create a new issue on that specific compilation problem ?

**Comment by aleksuss** [comment]
@Canop yes, sure.
