### ISSUE TITLE
Make installation instructions clearer for non-expert users

### ISSUE THREAD

**Issue by susie1991** [Canop/broot#135]
I have just spent a couple of hours trying to install this program. The problem was that I didn't know how to use "precompiled binaries". I am used to installing programs on Linux with apt-get and .deb files, so much of this was new to me.

The broot program itself is very simple and intuitive, so I think it would be a good idea to make its installation easier so that non-expert users can enjoy it too. Most advanced users will take it for granted, but the following are not obvious to many of us.

- The command `chmod a+x` is needed to make the file executable
- The precompiled binary file is then run with `./broot`
- To make broot available system-white, you need to move the broot file to a folder where it can be accessed
- This folder is /usr/bin/ on Linux
- Now when broot --install is run, the `br` command is also available system-wide

**Comment by Canop** [comment]
Noted.
