### ISSUE TITLE
Cleanup using rm. What is rm is aliased to something else? How to fix?

### ISSUE THREAD

**Issue by curioustolearn** [Canop/broot#136]
**Describe the bug**
Not really a bug with `broot`. I have aliased `rm` to something else. Specifically, 
`use rmtrash. If want to use rm, use full path - /bin/rm` 

As a result, whenever I exit `broot`, I get the message:
`use rmtrash. If want to use rm, use full path - /bin/rm -f /var/folders/zg/8815rs2s4dzc3s464lynykww0000gn/T/tmp.ENicR1kG
`
I am worried that broot is not able to perform the necessary cleanup. Is there something I can change to get this fixed. If I want to perform the clean up manually, what would I delete?

**Configuration (please complete the following information):**
 - OS: Mojave 10.14.4

**Comment by Canop** [comment]
I'm sorry, I don't understand your problem.

The `rm` in broot is called by full path, that is `/bin/rm -rf {file}`

**Comment by curioustolearn** [comment]
This is strange. I have the following line in my `.zshrc`

`alias rm="echo use rmtrash. If want to use rm, use full path - '/bin/rm'"`

I checked that when I use `rm` the above message is shown on the screen. But if I use `/bin/rm` the file is deleted correctly. Using `/bin/rm -rf` also deletes a folder as expected. 

But everytime I exit broot, I get 

`use rmtrash. If want to use rm, use full path - /bin/rm -f /var/folders/zg/8815rs2s4dzc3s464lynykww0000gn/T/tmp.VqTg1bDy`

More importantly, if I comment out the `alias rm =` line from the `.zshrc` and then run broot then I don't get that message.

**Comment by Lucretiel** [comment]
Is this an `--outcmd` thing? Can you run `broot --outcmd ./testfile` and look at the contents of `testfile`?

**Comment by rkumar** [comment]
I am also having an issue with `rmtrash -f` upon exiting broot. I am on Mac OS High Sierra using rmtrash provided by homebrew. `rmtrash` does not support a `- f` option. A `br` function has been installed which executes `rmtrash -f` upon exit, and this gives an error.

Perhaps, I should modify the function and replace rmtrash with just `/bin/rm` or else remove the `f` option ?

**Comment by ssendev** [comment]
I guess the problem is in the `br` script https://github.com/Canop/broot/blob/a0477be58aecb84335becf5424802718bf8fbdbf/src/shell_install/bash.rs#L53

**Comment by curioustolearn** [comment]
Hi Lucretiel,

If I run `broot --outcmd ./test.txt` (which is a standard txt file) that does not show me the contents of the text file. It opens up the directory containing `test.txt` in `broot`.

**Comment by brettinternet** [comment]
I also alias `rm` in order to self-promote `trash-cli` usage. Could we change the `br` function to use `/bin/rm` explicitly instead?

**Comment by Canop** [comment]
You can change the function called on rm in broot by defining a new verb with the same shortcut.

```
[[verbs]]
invocation = "remove"
shortcut = "rm"
execution = "/bin/rm {file}"
```

**Comment by BourgeoisBear** [comment]
@Canop, how do I replace the built-in `rm` entirely?  I added the suggested verb, and now I have two:

![image](https://user-images.githubusercontent.com/8608535/181530557-a20ffffe-0177-44f8-b7d2-a4a9f3836f93.png)

BTW: I'm doing this to remove the `-r` flag.  I don't trust myself with that in a shortcut.

**Comment by Canop** [comment]
@BourgeoisBear There's nothing today for removing a previous verb but used defined verbs are tried before. Change the "invocation" to be "rm" too, and it will be the one executed (you'll have the preview to feel confident).

For example, if I add this in my verbs.hjson file:

        {
            invocation: "rm"
            shortcut: "rm"
            execution: "cp {file} {file}-COPY"
            leave_broot: false
        }

Then the help also shows both (with the user defined first):
![image](https://user-images.githubusercontent.com/617006/181548397-682e2b67-e254-4adc-82d5-f1fafaa68276.png)

And on typing the command, I'll see this:
![image](https://user-images.githubusercontent.com/617006/181551637-a1f9eb41-0b8f-47b0-a0eb-b53625ee7f6e.png)

Now, I don't think it's a good idea to remove the `f` but it's another question.

**Comment by Canop** [comment]
Broot could be smarter and detect a verb isn't callable anymore because of user configuration. I note that for the future.
