### ISSUE TITLE
Next Versions - Please tell me what seems missing or desired

### ISSUE THREAD

**Issue by Canop** [Canop/broot#140]
There's an issue asking for what is needed for 1.0.

But 1.0 is meant to be available very soon. When there's no bug or no visible hole.

Most ideas are for later. And here they can be written.

**Comment by Lucretiel** [comment]
The number one thing for me is a shell mode. Basically, I'd like a `shell` command that, when run, launches a shell and suspends broot to the background. The shell is run in the current working directory. When the shell exits, broot returns to the foreground.

This could be done as an executable command, except that additional word would be needed to pause and restore broot.

**Comment by Canop** [comment]
@Lucretiel This need keeps being asked, in several forms. I'll definitely investigate that.

**Comment by adworacz** [comment]
**Reading colors from the terminal (matching the terminal's color theme) or reaching colors from Xresources**

It's nice being able to specify colors using the config file, but it'd be great if broot read the color scheme from my terminal (which is also setup via Xresources).

**Comment by kakulukia** [comment]
What about arrow navigation "<" directory up / ">" enter directory ?
Escape and enter are so far apart, its no fun at all.

**Comment by Canop** [comment]
@kakulukia this, you can do today: https://github.com/Canop/broot/issues/152#issuecomment-573761440

**Comment by Maxzor** [comment]
Just discovered broot, bravo.

- Do chmod-chown-chattr from broot in a visual way?
- Allow multiple broot panes ; basically rewrite mc / incorporate broot into mc ?
- Make ln visually from broot ?

(I am not commissioned to turn your nice software into bloat)

**Comment by Canop** [comment]
@Maxzor chmod (and similar ones) can be added with just this in the conf.toml file:

```
[[verbs]]
invocation = "chmod {modechange}"
execution = "chmod {modechange} {file}"
```

Then you just have to type for example `ch +x` on your selection :

![image](https://user-images.githubusercontent.com/617006/72677528-9c9c8000-3a9d-11ea-8b4e-4fbcbd4bd158.png)

It might be a good idea to have them in standard.

**Comment by Canop** [comment]
@Maxzor The two panels mode is something I think about but I'll be very cautious not to make broot complicated or slow to use. I have to think more on this.

@Maxzor  I don't understand this *"Make ln visually from broot ?"*. Maybe come tomorrow on my chat ( https://miaou.dystroy.org/3 ) ?

**Comment by Maxzor** [comment]
> @Maxzor I don't understand this _"Make ln visually from broot ?"_. Maybe come tomorrow on my chat ( https://miaou.dystroy.org/3 ) ?

With two panes as a prerequisite, one inode selected in each, ":ln -s mysymlink" : boom paneA/inode1/mysymlink --> paneB/inode2 ? Puny things

Not a fan of multiplying chatrooms, already in freenode gcu as maxzor :)

**Comment by Canop** [comment]
Damn... "ln" and "In" can't be distinguished here... I thought this was "make in"...

**Comment by dclift** [comment]
Excellent project Canop, well done. 

Personally issue #120 is the most critical, i.e. vim mode. And a true vim mode -  j,k for up and down, / for search, h,l to :parent and :focus, etc. This would necessitate adding the concept of modes to broot, so I understand it's a big design call.

But really you'll never please everyone so the smart thing would be to decouple the key bindings so you can define your own, and not just for verbs. 

Using broot as a vim plugin makes a lot of sense as well (as a kind of hybrid nerdtree / ctrl-p replacement).

The other thing would be the ability to select multiple files in order to perform a command/verb. For example rm several items or copy several items. Right now you can only select one file at a time (as far as I can tell, except for using expressions). 

Also, a small annoyance for me is that once you do perform an action on a file, the cursor jumps back to the root instead of the item or search result above it, so that you have navigate back to where you were with the arrow keys in order to perform an additional action. 

Again, well done - the :size command is particularly useful. And the design decision to keep the entirety of the directory tree within the screen is brilliant.

**Comment by Canop** [comment]
@dclift for the "vim mode", I don't really like that, because broot favor fast navigation, and thus immediate search without typing any other letter. I do think that arrows and ctrl-keys for up and down are acceptable as you often fall on your target with just filtering.

The vim plugin is on my TODO list too, just like trying to select several paths. But that might take time.

Regarding your "small annoyance", you really mean when the initial file is missing after action (mv, or rm action), right ? I hadn't thought about trying to select the following one in list. I'll look into it, I've added it to my fast TODO list.

**Comment by dclift** [comment]
@Canop - re the "small annoyance", that's correct. I'm glad you're adding it to your TODO list.

As far as the "vim mode", I get it, it's a big design decision. I know to vim users it would be ideal, but it does compete with your primary goal of immediate search. 

If you go with the ctrl keys perhaps a ctrl-h for parent and ctrl-l for focus as well?

**Comment by Canop** [comment]
@dclift the shortcuts you ask for can already be easily configured. See https://github.com/Canop/broot/issues/152#issuecomment-573761440 and https://github.com/Canop/broot/issues/24#issuecomment-572481660 for example.

BTW I *am* a vim user, but to me the essence of vim philosophy is more about efficiency with the minimum amount of obvious keystrokes than about a specific set of shortcuts.

**Comment by dclift** [comment]
@Canop Thank you. BTW was there any way to select more than one file with broot?

Re vim philosophy, true in theory - but in practice remembering different shortcuts between all the programs we use day to day requires a lot of context switching. I think that's where most of the vim users are coming from - muscle memory means a lot.

**Comment by Canop** [comment]
No, there's no way today to select more than one file. I have several leads for some ways to do that but I have to go deeper and experiment.

**Comment by vanhtuan0409** [comment]
Amazing project @Canop  I really appreciate your work.

Command completion using `tab` would be nice to have (similar from Vim)

**Comment by Canop** [comment]
@vanhtuan0409 can you come to the chat to see this mapping problem ?

**Comment by muellerj** [comment]
Re: colorschemes etc: Maybe it's worth investigating, how difficult it would be to respect `LS_COLORS`, which is what `ls` and `tree` etc. do. It would make switching colorschemes a lot easier, without the need to rewrite `broot`s config.

**Comment by matclab** [comment]
I sometimes seek for a way to do a multiple search term (à la FZF). For example, I have a complicated file hierarchy and I look for related file xxx and yyy and it would be nice to see both matches at once.
Perhaps with a `|` like separator… 
If you find this useful I may investigate in a PR (no promise as I tend to be over optimistic about my free time).

**Comment by Canop** [comment]
@matclab As I'm currently investigating for an extended search syntax, I'd like to register your need but I don't understand it. Could you please come to the chat and explain ? https://miaou.dystroy.org/3

**Comment by pi3141** [comment]
I have just discovered broot 2 weeks ago and it seems a great tool ! Thanks for it.
I have just two little problems I can solve :
− could I use tab for autocompletion ? when I use mv I am note able to write the full path.
− when I open a file, broot is stuck until the file is closed. Sometimes I need to open multiple files.

**Comment by Canop** [comment]
@pi3141 

tab autocompletion is something which seems indeed to be missing from verb argument composition.

As for file opening, this is a wide question. You can either
- open files in the same terminal (i.e. in emacs or vim) but closing broot
- open files out of the terminal (using xdg-open in standard, or an other application if you configure a verb for that)

but there's currently no direct way to be back in broot just on closing your editor which was opened by broot.

**Comment by noyannus** [comment]
First, a big THANK YOU for this tool!

I suggest using a single whitespace character that is less common than the nonbreaking space. 

For me and maybe only one other [guy](https://gitlab.com/therwe/marknonbreakingspace) in the world, his hack makes 
nonbreaking spaces visible in iTerm. In Broot that looks distracting:
![Screenshot](https://user-images.githubusercontent.com/6339921/74602636-08790500-50ab-11ea-9782-eedc26918191.png)

The problem with NBSPs is not very frequent, but they are easily mistyped or copy-pasted into terminal, and then waste A LOT of your time in finding the problem why the command didn't work. Others have been working on NBSP-related issues, too, e.g. [here](https://askubuntu.com/questions/623743/keyboards-writes-bad-space-characters-in-gnome-terminal) and [here](https://stackoverflow.com/questions/59254764/how-can-i-have-non-breaking-spaces-show-differently-in-terminal)

Therefore, the use of some other character that does not get collapsed with spaces would be nice.

**Comment by noyannus** [comment]
More colour schemes would be nice. 

Broot could use some presets unaltered, e.g. in xml/plist form from [here](https://iterm2colorschemes.com/). If there are rights issues with a source, a small script to convert xml to toml for the user to run would allow legal access.

Or Broot could have a second config file for skins only, with a commented-out list of colour scheme names on top, and all the colour schemes below. To select a colour scheme, just uncomment its name.

**Comment by Canop** [comment]
@noyannus I note the ideas for separated schemes. They could also be downloaded by broot.

Regarding the nbsp problem, I won't be able to know if the problem is fixed for you. Are you able to try and compile broot yourself ? Maybe come discuss in the chat ? https://miaou.dystroy.org/3

**Comment by Maxzor** [comment]
**BURB - BURB is Undo Redo Branching** (j'ai trouvé que le nom :) ) 
![burb](https://user-images.githubusercontent.com/16599683/74604703-b04cfd80-50c0-11ea-82fb-a61afaab5074.jpg)
J'ai dessiné un DAG, plus simple pour commencer. La notion de retour ici c'est 'cd -' et la popd, voire le 'd' 'N' (4 parents, 5 parents...) de oh-my-zsh.
Naviguer sur cet historique facilement peut avoir un bel intérêt à mon avis.
J'imagine pouvoir modeler sa stack _dirs_ de bash (qui est juste une liste, alors qu'ici c'est le niveau d'au dessus) ou déposer des _mark_ à la vim depuis ce graphe, il y a des trucs à faire sans bloater.
Je rêve de cte fonctionnalité dans un browser, mais aussi dans une suite office... c'est très générique comme besoin, ça peut s'appliquer à n'importe quel logiciel qui a des interactions utilisateur dans le temps et un concept de undo(/redo stack).

Bon broot c'est peut-être pas le meilleur endroit pour implémenter ça en premier, ça aurait plus de sens direct dans un shell, mais vu que vous avez un sacré niveau!

**Comment by noyannus** [comment]
@Canop 
 
> Regarding the nbsp problem, I won't be able to know if the problem is fixed for you. Are you able to try and compile broot yourself ? Maybe come discuss in the chat ? [miaou.dystroy.org/3](https://miaou.dystroy.org/3)

Pefect now.
![Screenshot](https://user-images.githubusercontent.com/6339921/74607697-0e86da00-50db-11ea-82f6-9c0350d50193.png)

**Comment by MrCustomizer** [comment]
Broot ist great. I just discovered it a few days ago after reading an article about it in Germany's computer magazine c't.
The thing I'm missing most, has already been mentioned several times in this issue: Better handling of commands that need two paths (for example cp or move) and multi-selection.
Several ways to improve handling of two paths have been mentioned:

- Two panel-mode
- Tab completion

I would like to add a third option, although I'm not sure if it would be better than two panels: Allow searching the second path with Broot's file/directory-search mechanism. There would have to be some trigger (for example a keyboard shortcut) to change to the search mode for the second path.

**Comment by mihaigalos** [comment]
How about syntax highlighting support for [bazel](https://github.com/bazelbuild/bazel)?

**Comment by yungcheeze** [comment]
Is it possible to interactively `mv` a file?

for example a verb `:mvi`, that will remember the selected file and start a new broot to interactively select the destination to move the file to.

**Comment by skoskie** [comment]
I would also like to echo how wonderful this app is, and also contribute my one suggestion for consideration. 

#### When `<pattern>` begins with a dot, ignore the hidden setting. 

This is the default behavior for Alfred (MacOS app), of which I am an avid user.  I made a quick screencast to demonstrate the behavior.  https://www.dropbox.com/s/4j9vdh22d8e8rn1/2020-03-12%20broot%20hidden%20directory%20example.mov?dl=1

**Comment by Canop** [comment]
This is interesting but it could be a little confusing. For example I sometimes have a leading dot because I'm looking for files by extension.
Not discarding your proposal, it could maybe be solved by a hint in the status bar.

**Comment by skoskie** [comment]
Config option makes the most sense to me, because I can see how your current use of the dot ~basically puts you into file-only mode — Directories can contain dots but most just don't.  And I can see how that would be very handy as well.

**Comment by shlomi-aknin** [comment]
> No, there's no way today to select more than one file. I have several leads for some ways to do that but I have to go deeper and experiment.

@Canop  Great work on this project.
I've been trying several cli file managers one is nnn it has the ability to handle multiple files via session like file.
I've been trying to mimic this with your project. see files in this link:
https://send.firefox.com/download/dd6c29f02c50f140/#xqRss9ADbr3e6epJfExzuw

**Comment by Canop** [comment]
Part of what was mentioned here was done, some problems are solved other ways. This issue isn't really usable as is, so I'll close it.
Thanks for all for your input!

**Comment by sucrecacao** [comment]
What is the current state of the  "select multi file" feature  ?

**Comment by Canop** [comment]
> What is the current state of the "select multi file" feature ?

It's in the todo list but not yet specified or designed.
