### ISSUE TITLE
add a launch argument to specify a conf.toml file to use for a specific execution

### ISSUE THREAD

**Issue by Canop** [Canop/broot#141]
A possible use case is the use of broot in composition in tools using for example the path returned on stdout by `:print_path`

**Comment by jcassee** [comment]
Because my use-case would be to override keyboard keys for a specific execution of broot while already having a default conf.toml file, it would be nice to be able to specify the option multiple times, specify an "override" configuration file, or something else that would have the same effect.

**Comment by jcassee** [comment]
By the way, I tried to override `ctrl-enter` and `alt-enter` in conf.toml, but neither worked.

```
[[verbs]]
key = "ctrl-enter"
execution = ":print_path"
```

```
[[verbs]]
key = "alt-enter"
execution = ":print_path"
```

**Comment by Canop** [comment]
I'm sorry, I was misleading yesterday. Right now the code explicitly prevents overriding enter (when the input isn't empty), alt-enter, esc and the '?'. I'll have to think a little more for that.

**Comment by jcassee** [comment]
No problem. Could be that I'm trying to push a square peg into a round hole. Broot is a "framework", in the sense that you perform actions within broot. I'm trying to use it as "library", in the sense that I'm trying to use it as a ZSH widget to insert a path. Maybe this should not be the highest priority.

I have set up alt-t for my widget, and set alt-t as a keyboard key for print_path. Let's see how that works out.

**Comment by Canop** [comment]
This is totally part of what broot is designed for (you could count also use it as a vim plugin). It's just not finished enough.

**Comment by jcassee** [comment]
Thanks @Canop!
```
