### ISSUE TITLE
Proposal for revised --cmd syntax

### ISSUE THREAD

**Issue by Lucretiel** [Canop/broot#142]
**Did a discussion occur before?**
Yes, in the chat room: https://miaou.dystroy.org/3490?broot

**Is your feature request related to a problem? Please describe.**
Not a specific problem; however, it is intended to solve the inconsistencies between interactive use and `--cmd` parsing

**Describe the solution you'd like**
A formal syntax is established for `--cmd` which is consistent with interactive use, but which also allows concise sequences of command without excessive boilerplate syntax. The current system is somewhat hacked together based on ongoing requests for added features, to the point where it only works for simple cases and is very inconsistent with the interactive interface. In particular:

- It fully tokenizes its input, even though the interactive parser and verb regexes do not
- The tokenizer doesn't actually produce tokens; it retains the control characters `"` and emits them verbatim.
- The implementation *attempts* to use the verb regex to validate arguments and smartly transition between states, but this ends up:
    - being difficult to implement in practice
    - usually not mattering, because most argument parsers take a `.*` at the end, so they'll accept any tail anyway

**Additional context**
My proposal for the syntax is as follows:

- A `--cmd` string is interpreted as a series of commands. Each command is either verb-like or search-like.
- A token is:
    - A string matching `[^\s\";]+`, or
    - The contents of a double quoted string matching `"[^"]*"`.
    - Note that:
        - There is no facility for escaping characters in a token, though this can be added if anyone feels it's important.
        - Tokens may contain a `:` character; that is, `:` is not a token separator. A token is interpreted as a verb only if it follows a `:` character when searching for tokens. 
        - The input is not fully tokenized; these tokens are only parsed when searching for a command. Verbs can take arbitrary strings as arguments, and do their own parsing via regular expression (see the verb-like command section for details).
- A search-like command is a single token. Search-like verbs do not take arguments, and therefore subsequent tokens are subsequent commands. Valid search-like commands include `abc`, `a:b`, `"ab cd"`, `/[abc]`, `"/abc *def"`, and `""`.
- A verb-like command is `:` followed by a token, as described above (note that the : cannot be inside the quotes, if it is a quoted token. Valid verb-like commands include `:abc`, `:"ab cd"`, `:""`, and `:ab:cd`.
    - Note that looking up verbs in the verb database is NOT considered a part of this syntax. A command can successfully parse only to fail later if that verb doesn't exist or is ambiguous.
- A verb-like command can have arguments. Because verb commands can have arbitrary arguments that are parsed via regular expression, we should be very generous in what we accept. Therefore, after parsing a verb name, the entire following string is parsed, until:
    - A semicolon is found. This can be anywhere in the string. Note that the input after the verb is accepted verbatim, without tokenization, which means that it can even be inside of a double quote. While this feels weird, it is consistent with the interactive interface, which does not do any normalization or tokenization of input before passing it to the verb's argument regex.
    - Another verb is found, prefixed by whitespace. That is, `abc:def` is parsed as an argument for the current verb, but `abc :def` takes `abc` as the end of the verb arguments, and `:def` is the next verb.
- `;` is the command separator. It is acceptable but optional after a search-like command, but it is necessary to follow a verb-like command with a search-like command.

**Examples:**

This example shows all of the behavior to be aware of:

```
search1 search2 "search 3" :cmd1 a b c :cmd2 ab:c; "/regex *search"; :cmd "unclosed; :"cmd6"
```

This is interpreted as the following commands:
```
[
    Search("search1"),
    Search("search2"),
    Search("search 3"),
    Command("cmd1", "a b c"),
    Command("cmd2", "ab:c"),
    Search("/regex *search"),
    Command("cmd", "\"unclosed"),
    Command("cmd6"),
]
```

**Discussion**

The proposed syntax is effectively identical to the one used by the UI, with the following exceptions:

- Multiple space-separated tokens are interpreted as separate searches, rather than a search followed by a verb. It's preferable to require an explicit `:` when distinguishing between verb and search
- Subsequent `:verb`s are detected. This makes it easier to chain commands together. If there is an explicit need to have commands that can take arguments prefixed with :, we can add escape sequence support
- We use `;` as a command separator. This is consistent with most other scripting languages and gives us extra flexibility that isn't necessary in interactive use.

After the command is parsed, it is sent into the commands for interpretation, which can also fail. This is the part where verbs are looked up in the database, and their arguments strings are parsed and accepted or rejected via regex.

**Implementation**

Once the syntax is agreed upon, I'll implement it with a nom-based parser, which is well-suited to this sort of parsing.

**Comment by Canop** [comment]
Thanks for this work.

As you noticed, this syntax prevents verb arguments starting wit a colon. This kind of problem is quite impossible to avoid unless we make the separator mandatory, which should be done IMO.

What I'd rather have is a sequence of tokens with the same form than the the input:

     <pattern><space-or-colon><verb>

(both pattern and verb optional, as in the input)

and all of those "inputs" separated by a mandatory separator (for example the semicolon you suggested).

Assuming separated inputs, parsing seems to be just applying `CommandParts::from(&str)` (note that I also don't want to import nom, I want to keep broot as small as reasonably possible).

As it's also possible that the semicolon isn't always acceptable, I propose to make the input separator optionally defined in the sequence, as the first character (if the first character is a colon, a slash or in \w, then we assume the separator is the semicolon).

**Comment by Lucretiel** [comment]
So, just to be clear, your updated proposal is that you *must* use a semicolon to separate subsequent verbs?

**Comment by Lucretiel** [comment]
that is, you'd do

```
<pattern><space-or-colon><verb-with-args>;<verb-with-args>;...
```

**Comment by Canop** [comment]
Yes, my proposal is that you must use a separator.
Additionally, that you can specify an alternate separator, but not having one wouldn't be an option anymore.

**Comment by Lucretiel** [comment]
That all sounds good. imo, the separator should be specified with a flag (like `--cmd-sep`) or, even better, an environment variable, like `$BROOT_CMD_SEP`. This is because I expect that in practice people will very rarely need to change the separator, because it's so ubiquitous in shell scripting as a separator that people rarely need is as a real argument

**Comment by Lucretiel** [comment]
I'm currently working on a lot of additions to `crossterm` that will end up making this work easier. I'll start on this when that's taken care of.

**Comment by Canop** [comment]
You're right with the separate flag *and* env variable.
I don't get how crossterm is related, though.

**Comment by Lucretiel** [comment]
It isn't directly related to this feature, but some other pull requests I'm working on for broot, related to cleanup issues when `--cmd` encounters an error (specifically that it doesn't always call App::end before returning from run, which means that certain terminal settings are left in the wrong state.)

**Comment by Canop** [comment]
@Lucretiel the command parsing should now be trivial (there's more doc to do than code, I guess). I'll need it soon. Do you want to write that part or do I do it?

**Comment by Lucretiel** [comment]
I should be able to do it today

**Comment by Lucretiel** [comment]
Follow up: Do you have preference about search pattern tokenization? The interactive prompt does *no* tokenization; I assume we prefer that behavior in the command sequence, for consistency?

**Comment by Canop** [comment]
Is there a reason not to build the commands using Command::from(str) ?

**Comment by Lucretiel** [comment]
Nope! I'll do the simple parsing, without tokens. working on it now.

**Comment by Canop** [comment]
Following this issue and this discussion, a new --cmd syntax was implemented. I think this issue can be closed.
