### ISSUE TITLE
Generate shell completion files

### ISSUE THREAD

**Issue by Canop** [Canop/broot#143]
This is a follow-up of this suggestion: https://github.com/Canop/broot/issues/76#issuecomment-573348801

The goal is to make available shell completion scripts.

**Comment by evanjs** [comment]
Once these files are available, we can still include them in the code using e.g. [include_str!](https://doc.rust-lang.org/stable/std/macro.include_str.html), and perform whatever operations from before like normal. 
___
I’d imagine we’d also want to check if the functions exist before prompting the user to install them, as well.

Then write “refused” or whatever so the user isn’t prompted. 

It looks like the install function does most of this already, though 😁

**Comment by Canop** [comment]
@evanjs  Are you talking of the shell completion scripts or of the shell function br ?

**Comment by Canop** [comment]
Shell completion scripts are now generated on build (deep inside the target folder. You may do `br -c ":gi bash$/"` to find them).

I'd like to have some confirmation it looks OK, suggestions, etc.

**Comment by evanjs** [comment]
> Shell completion scripts are now generated on build (deep inside the target folder. You may do `br -c ":gi bash$/"` to find them).
> 
> I'd like to have some confirmation it looks OK, suggestions, etc.

Sweet! I’ll check it out.
And I was just referring to the br function, if it needed to be accessed from both the code and completion, though I’m not sure we’ll need to do that with how you did it.

**Comment by Canop** [comment]
released with 0.11.8

**Comment by evanjs** [comment]
I can confirm tab completions are working with my home-manager setup on with zsh and bash after https://github.com/NixOS/nixpkgs/pull/77415/commits/68a5f9f073f36669638aa0bcb43c8a1c76f57935 which includes the changes made available in 0.11.8.

Thanks for such a quick first implementation!

**Comment by Canop** [comment]
Shell completion files are now made available at every release.
See https://dystroy.org/broot/documentation/installation/
