### ISSUE TITLE
make it possible to not leave broot when entering a terminal

### ISSUE THREAD

**Issue by mhusmann** [Canop/broot#144]
**I'd like to stay in broot when invoking a terminal by ALT-ENTER or when editing a file by hitting F2 or :e.**

Currently broot is left once I started a terminal. In order to come back to broot broot must be started again with br in the terminal. It would be very convenient to stay in broot after I left the terminal or I left an editor.

**Comment by Lucretiel** [comment]
I'd really like this as well. It would also make it possible to run broot without `br`, because rather than having to cd in the parent process, it could just launch a new shell in the correct directory. While it's (relatively) easy to launch a shell as a child process, we need to add support for switching away from the broot UI, and back to it when the shell is complete.

**Comment by Lucretiel** [comment]
Sorry, I think I missed how to do the shell part specifically. Would that just be a custom invocation in the config file?

**Comment by Canop** [comment]
Sorry @Lucretiel I had overlooked the *shell* part of this issue as I focused on launching terminal editors from broot.

There was a remaining problem: the terminal was left in raw mode during sub-process execution which prevented a shell from running correctly.

I just commited a fix and at first sight it looks OK with a verb like this one:

```
[[verbs]]
key = "ctrl-t"
execution = "$SHELL"
leave_broot = false
```

<kbd>ctrl</kbd><kbd>T</kbd> launches a terminal and you're back in broot when you exit.

I reopen. Tell me if you think I can close again.

**Comment by Lucretiel** [comment]
Two bugs to report:

- It seems like something is still wrong with the terminal mode; newlines aren't being handled correctly: 
![image](https://user-images.githubusercontent.com/1823405/89062928-4e621680-d335-11ea-9982-e4531e1e7cec.png)
- The shell doesn't launch in the currently highlighted directory (For instance, if I start broot in `~`, then navigate to `~/code/broot`, then launch the shell, the shell's working directory is still `~`). My proposal to fix this would be either:
    - Add a configuration flag to [[verbs]] that allows specifying the working directory of the executed verb
    - Automatically run all verbs with the working directory set to the currently active broot directory

**Comment by Lucretiel** [comment]
Some other examples of this in practice: 
![image](https://user-images.githubusercontent.com/1823405/89063682-a2b9c600-d336-11ea-88a4-87a3404cd89d.png)

As you can see, my command point (`❯ `) isn't being reset to column 0.

![image](https://user-images.githubusercontent.com/1823405/89063753-c3821b80-d336-11ea-8e65-16036866e6b7.png)

When I manually send a carriage return in addition to a newline, it works correctly.

![image](https://user-images.githubusercontent.com/1823405/89063828-e14f8080-d336-11ea-8ae4-1e637ed6e3c5.png)

Attempting to highlight text also doesn't work; it appears the mouse escape sequences are not being properly forwarded to the underlying terminal. This issue also impacts text editors.

**Comment by Lucretiel** [comment]
Aside from these glitches, though, it works perfectly, thank you! Being able to drop into a shell, run some git commands, and then drop back into broot is *exactly* what I was looking for. It also means I don't have to run broot with `--outcmd`, which feels cleaner to me.

**Comment by Canop** [comment]
I don't reproduce the newline problem and I've no problems with editors which run in the sub shell.

I'll see what I can do for the working directory but I'll be away for a few weeks so it won't be fast.

**Comment by Lucretiel** [comment]
No problem. I'll dig deeper and see if I can find anything.

**Comment by Canop** [comment]
I just checked that doing [set_current_dir](https://doc.rust-lang.org/std/env/fn.set_current_dir.html) before launching the sub-process does work. I'll see if doing it systematically is OK or if that can be a problem for some verbs.

**Comment by Canop** [comment]
@Lucretiel I just pushed a change making the selection the working dir for subprocesses launched from broot

**Comment by Lucretiel** [comment]
Excellent, thank you!

**Comment by Lucretiel** [comment]
Works great on the master!

**Comment by Canop** [comment]
There's a breaking change in the last commit which directly impacts this feature: the working dir of external processes isn't set to the selected directory anymore by default.

If you want it to be set, which usually makes sense for a terminal, you can set up with the new verb parameter `set_working_dir`:

```
[[verbs]]
key = "ctrl-t"
execution = "$SHELL"
leave_broot = false
set_working_dir = true
```

**Comment by Lucretiel** [comment]
Thanks for the heads up!
