### ISSUE TITLE
Feature request: add a flag to print shell helper to stdout

### ISSUE THREAD

**Issue by K900** [Canop/broot#145]
Some people (me included) keep track of their dotfiles in version control or some other tool, and don't want `broot --install` messing with the configuration. An option to instead print the helper code to stdout would let you simply add `eval $(broot --eval=bash)` or `eval $(broot --eval=zsh)` (exact syntax very much up to bikeshedding) to the respective shell's configuration file and have broot "just work", as long as the executable is present in $PATH.

**Comment by Canop** [comment]
I plan to have

    broot --print-shell-function bash

or

    broot --print-shell-function fish

**Comment by Canop** [comment]
@K900 Can you please test (now from source or when I release broot v0.11.8) and tell me if it's OK or needs changes ?

**Comment by K900** [comment]
I'll wait for the 0.11.8 release, but it looks good

**Comment by Canop** [comment]
0.11.8 released

**Comment by K900** [comment]
0.11.8 works great for me, thank you!
