### ISSUE TITLE
How to install on a Raspberry?

### ISSUE THREAD

**Issue by timaschew** [Canop/broot#146]
I'm getting this error when trying to execute broot

```
$ ./broot
-bash: ./broot: cannot execute binary file: Exec format error
```

**Comment by Canop** [comment]
A relevant target would probably have to be defined in order to compile broot for Raspberry but that would probably be only the start. I'd need somebody with the relevant hardware and competences to chime in.

**Comment by Pofilo** [comment]
Even if the binary is not for arm nor 32 bits, you can still install it via Cargo. I Just try it myself.

https://dystroy.org/broot/documentation/installation/#from-cratesio

**Comment by Canop** [comment]
@Pofilo  and does broot run fine on raspberry ? Alt-enter and similar features ?

**Comment by Pofilo** [comment]
@Canop it seems to work as on Debian. I use the same configuration and everything seems to work on the same way.
I don't know rust enough to know how we could create the binary with chroot or something similar to put it in github releases.

**Comment by Canop** [comment]
Creating the binary should be easy for me. I could include the target in my scripts to deploy it with next releases.

**Comment by Canop** [comment]
The binary is now downloadable from https://dystroy.org/broot/documentation/installation/

Can somebody check the downloadable I built using cross-compilation *do* work on Pi ?

**Comment by Pofilo** [comment]
It seems to work on an updated Raspberry (last Raspbian version up to date).

Thanks :)

**Comment by Canop** [comment]
ok, so let's close this issue

**Comment by Canop** [comment]
BTW @Pofilo  as you were interested: https://github.com/Canop/broot/blob/master/compile-all-targets.sh

**Comment by Pofilo** [comment]
I saw that on a commit thanks :)

**Comment by abulka** [comment]
I ran the downloadable binary https://dystroy.org/broot/download/x86_64-unknown-linux-musl/broot on my Raspberry Pi running Ubuntu 21.10 64bit and got the same error as the OP.  Is that binary Raspbian specific or something?

    -bash: ./broot: cannot execute binary file: Exec format error

So I installed using the instructions at https://dystroy.org/broot/documentation/installation/#from-cratesio which worked!

**Comment by Canop** [comment]
@abulka 
I have no Raspberry, and no specific knowledge, so I can't really dive into this. But if you think there's a problem with the produced binary, please reopen the issue.

**Comment by bdurrani** [comment]
@abulka You need the arm7 version. Rasp pi is not x86

https://dystroy.org/broot/download/armv7-unknown-linux-gnueabihf/broot

**Comment by abulka** [comment]
@bdurrani Ah - clicked on the wrong link - sorry about that - thanks.

Though, am still unable to run the correct binary - getting a weird `./broot: No such file or directory` message

```
$ wget https://dystroy.org/broot/download/armv7-unknown-linux-gnueabihf/broot
$ chmod +x broot
$ ./broot
-bash: ./broot: No such file or directory
```

the file is definitely there.

```
$ type ./broot
./broot is ./broot
$ which ./broot
./broot
```
