### ISSUE TITLE
'enter' during a search does not focus

### ISSUE THREAD

**Issue by azdavis** [Canop/broot#147]
First: Thanks for this tool! It came in handy the other day when I was looking for space to free up on my computer (:.

Now, here's the bug report:

## The bug

If the following is true:
- You have a current search
- The selected line is not the top
- You continue adding to your search (causing a second search)
- The selected line does not change during the second search
- You press enter during the second search

Then you will go up a level (as if the selected line was the top line, i.e. "hit enter to go up"), instead of interacting with the currently selected line.

## Steps to reproduce

1. Open br in a folder with many things inside (so searches take a long time)
1. Start a search
1. Select a line that's not the top
1. Continue the search
1. Press enter before the new search is done

## Expected behavior

During the second search, the selected line is still whatever line I was on, and the status bar still says "hit enter to focus", so I would expect hitting enter to focus the current line.

## Actual behavior

I go up a level.

## Screenshots

https://asciinema.org/a/P5FFadoP4QiL9dBKkrkTIiYAh

In this example, right before I go up a level, I add to the 'foo' search by typing '3'. Then broot begins searching, but I am still visually selected on 'foo0'.

I made many folders with the following. Note that this may take a minute or two.

```sh
set -eu
for a in {0..30}; do
  mkdir "foo$a"
  for b in {0..30}; do
    mkdir "foo$a/$b"
    for c in {0..30}; do
      mkdir "foo$a/$b/$c"
    done
  done
done
```

## Configuration

Built from source at `16a9cba1910b6d1615e80d70fcad1c0c5cef8be6`

```
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G1012
$ br --version
broot 0.11.7
```

**Comment by Canop** [comment]
I didn't manage to reproduce the problem for now.
I suspect you hit enter just after the second search finished.

**Comment by azdavis** [comment]
I don't think so.

Given the folder structure created with the following script:

```sh
set -eu
cd ~/Desktop
mkdir sandbox
cd sandbox
for a in {0..25}; do
  mkdir "f$a"
  for b in {0..25}; do
    mkdir "f$a/$b"
    for c in {0..25}; do
      mkdir "f$a/$b/$c"
    done
  done
done
```

And with the following patch on top of 2581ed4e94a400d5e4457a875afccaf33463360e:

```patch
diff --git a/src/browser_states.rs b/src/browser_states.rs
index 708440c..10a29cd 100644
--- a/src/browser_states.rs
+++ b/src/browser_states.rs
@@ -285,6 +285,8 @@ impl AppState for BrowserState {
         screen: &mut Screen,
         con: &AppContext,
     ) -> Result<AppStateCmdResult, ProgramError> {
+        let line = self.displayed_tree().selected_line();
+        debug!("hi there. selected line: {:?}", line.path);
         self.pending_pattern = Pattern::None;
         let page_height = BrowserState::page_height(screen);
         match &cmd.action {
@@ -406,6 +408,7 @@ impl AppState for BrowserState {
                 filtered_tree.try_select_best_match();
                 filtered_tree.make_selection_visible(BrowserState::page_height(screen));
             } // if none: task was cancelled from elsewhere
+            debug!("new filter tree is none: {}", filtered_tree.is_none());
             self.filtered_tree = filtered_tree;
             return;
         }
```

I get [this](https://asciinema.org/a/ZjDIUI0DCB5RXsdsLNnHMdE3x) behavior, with [this](https://github.com/Canop/broot/files/4054925/dev.log) log, the crucial lines of which are:

```
17:45:50 [ INFO] Tree search with pattern Fuzzy(f) took 471.359586ms
17:45:50 [DEBUG] (1) broot::browser_states: was it total search ? true
17:45:50 [DEBUG] (1) broot::browser_states: new filter tree is none: false
17:45:52 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Char('1'), modifiers: (empty) })
17:45:52 [DEBUG] (1) broot::app: command after add_event: Command { raw: "f1", parts: CommandParts { pattern: Some("f1"), regex_flags: None, verb_invocation: None }, action: FuzzyPatternEdit("f1") }
17:45:52 [DEBUG] (1) broot::app: action: FuzzyPatternEdit("f1")
17:45:52 [DEBUG] (1) broot::browser_states: hi there. selected line: "/Users/azdavis/Desktop/sandbox/f0"
17:45:52 [DEBUG] (1) broot::tree_build::builder: start building - total=false pattern=Fuzzy(f1)
17:45:52 [ INFO] task expired (core build - inner loop)
17:45:52 [DEBUG] (1) broot::browser_states: new filter tree is none: true
17:45:52 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Enter, modifiers: (empty) })
17:45:52 [DEBUG] (1) broot::app: command after add_event: Command { raw: "f1", parts: CommandParts { pattern: Some("f1"), regex_flags: None, verb_invocation: None }, action: OpenSelection }
17:45:52 [DEBUG] (1) broot::app: action: OpenSelection
17:45:52 [DEBUG] (1) broot::browser_states: hi there. selected line: "/Users/azdavis/Desktop/sandbox"
17:45:52 [DEBUG] (1) broot::tree_build::builder: start building - total=false pattern=None
```

Note the difference between the two "hi there. selected line" log lines.

This, I believe, shows that because the search was interrupted, a `None` filter tree is give back in `do_pending_task`, which means the next time we run `apply_command`, the selected line is the default (first) line, even though we don't update the screen to reflect that.

**Comment by Canop** [comment]
OK, I get what you mean.

**Comment by azdavis** [comment]
I tried moving the `self.filtered_tree = filtered_tree` into the `if`. (I also renamed a variable to avoid clashing.) That means we only change `self.filtered_tree` if we got a `Some` back from the `TreeBuilder`. It seemed to fix my issue, but I wonder if that breaks other desired behavior elsewhere.

```patch
--- a/src/browser_states.rs
+++ b/src/browser_states.rs
@@ -396,17 +398,17 @@ impl AppState for BrowserState {
                 }
             };
             self.total_search_required = false;
-            if let Some(ref mut filtered_tree) = filtered_tree {
+            if let Some(ref mut ft) = filtered_tree {
                 info!(
                     "Tree search with pattern {} took {:?}",
-                    &filtered_tree.options.pattern,
+                    &ft.options.pattern,
                     start.elapsed()
                 );
-                debug!("was it total search ? {}", filtered_tree.total_search);
-                filtered_tree.try_select_best_match();
-                filtered_tree.make_selection_visible(BrowserState::page_height(screen));
+                debug!("was it total search ? {}", ft.total_search);
+                ft.try_select_best_match();
+                ft.make_selection_visible(BrowserState::page_height(screen));
+                self.filtered_tree = filtered_tree;
             } // if none: task was cancelled from elsewhere
-            self.filtered_tree = filtered_tree;
             return;
         }
         self.displayed_tree_mut().fetch_some_missing_dir_size(tl);
```

**Comment by Canop** [comment]
That's what I'm looking at.

**Comment by Canop** [comment]
It seems OK. I'll have to think about it a little more but if I see no problem I'll do that.

Thanks for your investigation!
