### ISSUE TITLE
Question: Can the opener be configured? (rifle instead of xdg-open)

### ISSUE THREAD

**Issue by ahbnr** [Canop/broot#151]
Hello!
As far as I can see, broot already tries to choose the opener depending on the system. In my case that should be xdg-open.

I personally prefer ranger's "rifle" over xdg-open  (https://github.com/ranger/ranger, https://github.com/ranger/ranger/blob/master/ranger/ext/rifle.py). Is it possible to manually set the opener used by broot? (Or do I read the code/dependencies correctly that broot is using https://github.com/Byron/open-rs which does not seem to support configuring the opener?)

Thanks!

**Comment by Canop** [comment]
Yes you can. See https://dystroy.org/broot/documentation/tricks/#open-files-without-a-windowing-system

**Comment by ahbnr** [comment]
thank you for the quick answer!

Since I want to leave ":edit" as it is (calling the text editor), I decided to reconfigure the "open" functions.

This configuration works for open_leave:
```
[[verbs]]
invocation = "open_leave"
key = "alt-enter"
shortcut = "ol"
execution = "rifle {file}"
```

However, am I assuming correctly, that open_stay can not be reconfigured to use rifle without closing broot?

**Comment by Canop** [comment]
> However, am I assuming correctly that open_stay can not be reconfigured to use rifle without closing broot?

It's rather than in the current version it's not possible to override the enter key. I have to review this.

**Comment by Canop** [comment]
I never tried rifle but I don't see why you can't do
```
[[verbs]]
key = "enter"
execution = "rifle {file}"
```

**Comment by ahbnr** [comment]
> I never tried rifle but I don't see why you can't do
> 
> ```
> [[verbs]]
> key = "enter"
> execution = "rifle {file}"
> ```

that does work, but also quits broot

**Comment by Canop** [comment]
oh sorry. Updating the previous comment

**Comment by ahbnr** [comment]
> oh sorry. Updating the previous comment

That works, thank you very much! I missed that "leave_broot" option.

For everyone else who wants to configure their broot similary, I added this to my configuration:
```
[[verbs]]
invocation = "open_leave"
key = "alt-enter"
shortcut = "ol"
execution = "rifle {file}"

[[verbs]]
invocation = "open_stay"
key = "enter"
shortcut = "os"
execution = "rifle {file}"
leave_broot = false
```

**Comment by max-sixty** [comment]
This was really helpful, thanks!
