### ISSUE TITLE
broot --install failing for non-root users

### ISSUE THREAD

**Issue by maxnbk** [Canop/broot#155]
My issue with `broot` is singular, which is that I am trying to package up broot for use by users consuming packages from a rather obscure package manager, but the users running broot will not have root access, so this happens when running `br`:
```
$ br

Broot should be launched using a shell function (see https://github.com/Canop/broot for explanations).
The function is either missing, old or badly installed.
Can I install it now? [Y n]
Y
Removing /home/maxnbk/.local/share/broot/launcher/bash/1.
Writing br shell function in /home/maxnbk/.local/share/broot/launcher/bash/1.
Removing /home/maxnbk/.config/broot/launcher/bash/br.
Creating link from /home/maxnbk/.config/broot/launcher/bash/br to /home/maxnbk/.local/share/broot/launcher/bash/1.
IO Error : "Permission denied (os error 13)"
```

Wrinkle: I am able to predefine the `br` function for them, and do, as something that is installed alongside broot and sourced when the users enter the package-managed shell, but broot still thinks it's not installed properly, presumably because the files don't exist in the correct place.

Is there something I can do to fix this on my end?

**Comment by maxnbk** [comment]
even weirder, after it declares permission denied, the right files are in the right places, but this does not cause any `br` function to be sourced correctly in our shells

**Comment by Canop** [comment]
Should user need root access to change their own bash config files ?

**Comment by Pofilo** [comment]
I think you should check the permissions under `/home/maxnbk/` and its sub-directories, and also the `.bashrc` file.

Which OS/distribution do you use ?

**Comment by maxnbk** [comment]
We use CentOS-7.6, but users are not allowed to configure their own .bashrc, and instead configure their .mybashrc, as the .bashrc contains facility definitions for tools they are all given in a managed way. (Like broot, for example.)

**Comment by Canop** [comment]
Oh, so what you need si probably the new `--set-install-state` launch argument to tell broot not to bother users with install anymore

**Comment by maxnbk** [comment]
Yes, that would certainly be adequate - we can ensure the `br` func is present and up to date - I think when I was looking for issues, there was something about a way to print the br func to stdout, which would be nice to have as well, because then I can inject it dynamically for my users.

**Comment by maxnbk** [comment]
Tested with new --set-install-state flag and this obviates the need for me to have any other way of dealing with the issue, so I am closing this issue. Thank you @Canop .
