### ISSUE TITLE
Substitute for NerdTree in Vim

### ISSUE THREAD

**Issue by jeyraof** [Canop/broot#156]
Like [NerdTree](https://github.com/preservim/nerdtree), can I use broot as filetree in Vim?

![NerdTree](https://raw.githubusercontent.com/preservim/nerdtree/master/screenshot.png)

**Comment by Canop** [comment]
Not yet. It's a project I have too, replacing ctrl-p and nerdtree. But it's not available.

**Comment by jeyraof** [comment]
@Canop Oh, is this reserved plan for next on your milestone?

**Comment by Canop** [comment]
@jeyraof unfortunately I can't promise anything. I have many things on the TODO lists and I have a job and family.
But it's definitely something I'd like to to.

**Comment by jeyraof** [comment]
I entirely got it! thanks you for awesome project.
