### ISSUE TITLE
No/incorrect rendering on Windows 7

### ISSUE THREAD

**Issue by stinos** [Canop/broot#157]
**Describe the bug**
None of the shells I tried on Windows 7 manage to produce output (see screenshots below): either the screen just stays blank (cmd, powershell) or it shows a bunch of escape sequences (color codes I think) together with the actual file/directory names (cygwin, msys2 shells). broot is functional, i.e. reacts to Esc etc, just shows no output. 

No such problem on Windows 10, so it's likely a known problem with how Rust talks to the terminal, but adding this as an issue by means of documentation. Also not sure if it's worth fixing since Windows 7 is pretty much EOL.

**To Reproduce**
- download broot release
- open cmd/powershell/... and run broot.exe, choose `n` when asked to install

**Screenshots**
Powershell:
![Capture](https://user-images.githubusercontent.com/1902997/72326633-d2adbe80-36af-11ea-9e0f-4a937ed02205.PNG)
Cygwin:
![Capture](https://user-images.githubusercontent.com/1902997/72326827-3e902700-36b0-11ea-9bbb-61738a59086b.PNG)

**Configuration (please complete the following information):**
 - OS: Windows 7
 - Version 0.11.3

**Comment by Hrxn** [comment]
Yeah, as far as I know, ANSI Terminal Control, or the "Virtual Terminal" setting is Windows 10 only.

I mean you could still try to manually enforce the option, maybe some late Windows 7 update changed something here:

> Fortunately, the global default can be changed from opt-in to opt-out. The registry key at `HKEY_CURRENT_USER\Console\VirtualTerminalLevel` sets the global default behavior for processing ANSI escape sequences. Create a `DWORD` key (if necessary) and set its value to `1` to globally enable (or `0` to disable`) ANSI processing by default.

`[HKEY_CURRENT_USER\Console]`
`"VirtualTerminalLevel"=dword:00000001`

**Comment by Canop** [comment]
Given that Win7 has reached end of life, I'm not sure it's worth the pain.

**Comment by stinos** [comment]
> VirtualTerminalLevel

Doesn't do anything for me, but I agree it's not really worth it

**Comment by bbigras** [comment]
I have something similar with Windows server 2012 R2 which is not end of life.

`VirtualTerminalLevel` doesn't seem to change anything.

broot 0.12.2

![image](https://user-images.githubusercontent.com/24027/73870744-9ab31a80-481a-11ea-940a-7aeb70884b28.png)
