### ISSUE TITLE
Behaviour change: Don't use .gitignore files of super repositories 

### ISSUE THREAD

**Issue by kakulukia** [Canop/broot#160]
**Describe the bug**
broot is hiding more than it should - i could find out why in the mean time with your help @Canop 

**To Reproduce**
Use any git repo and put it inside another new git repo with a .gitignore that features a * (ignoring all).
Use broot to browse the parent directory. It shall and wont display anything. 
But now go into the contained repo and use broot - still nothing.
Git on the other hand will not use .gitignore files beyond the project root other than your global definitions in the home folder.

Test this with this little alias:

    alias gfi="find . -type f  | git check-ignore -v --stdin" # git find ignored files

**Expected behavior**
Show no files in the parent dir. ✔️
Show all files in the child repo. 

**Screenshots**
<img width="1043" alt="Bildschirmfoto 2020-01-14 um 22 03 18" src="https://user-images.githubusercontent.com/96352/72382529-ba728980-3719-11ea-90f7-b2d5652dee12.png">

**Configuration (please complete the following information):**
 - OS: OSX 10.14
 - broot 0.11.8
 - git version 2.24.0

**Comment by aengl** [comment]
It's quite common to use git for configuration management in the home directory, with a `.gitignore` that ignores everything. It took me a while to figure out why broot wouldn't work in any of my project folders.

**Comment by Canop** [comment]
The specification precises that the parent .gitignore should be used in a git project. I don't know if this applies to submodules.

I see two solutions:

1. use only the last git_ignore file (looking at parent)
2. reset the git_ignore chain when there's also a .git folder (i.e. ignore super modules)

The first 1 would be faster to compute and cover 99% of cases, I guess.

**Comment by aengl** [comment]
Solution 1 is good in my opinion. Even when using multiple ignore files in a single project, it's usually the most immediate one that is relevant to the current folder.

And it's better to err on the side of showing too many files.

**Comment by Canop** [comment]
I changed the title to better reflect the problem and solution.

**Comment by kakulukia** [comment]
Well actually you should use all ignore files up until the repo root dir plus the global ignore file. But I agree that using the deepest one might be an option that works well enough.

**Comment by Canop** [comment]
I switched to solution 2.
