### ISSUE TITLE
New Input Syntax Specification

### ISSUE THREAD

**Issue by Canop** [Canop/broot#164]
This is a draft, shared for thoughts. I welcome opinions of people who played enough with broot to have one.

## Preambule

I want to keep the immediate interactive search, and keep allowing the current syntax:

	<pattern>[ :]<verb_invocation>

where pattern can be either fuzzy or a regex ([formal syntax](https://github.com/Canop/broot/blob/master/src/commands.rs#L60)).

## New Goals

1. allow colons or spaces in the pattern
2. allow/combine other types of search in the future, for example search on paths or file content (instead of filenames)

## Proposal

The proposal is to introduce new compatible syntaxes

	[ :]<search_verb><sep><pattern><sep><verb_invocation>

where

* `<search_verb>` would be optional (maybe not immediately implemented) and would later be used to specify the way the pattern is used (paths or file content, for example).
* `<sep>` would be made of "special characters" (most of `\W`) chosen by the user (so that it's not in the pattern). The second sep isn't necessary if there's no verb_invocation.

### Examples of a fuzzy search for `"bla"` followed by a `cp`:

(yes it didn't change, it's just a comparison point)

	bla cp dest
	bla:cp dest

### Examples of a fuzzy search for `":bla:"` followed by a `cp`:

	:#:bla:#cp dest
	: :bla: cp dest
	  :bla: cp dest
	 ":bla:"cp dest
	:name=:bla:=cp dest

(assuming `name` is the `search_verb` for applying patterns to file names)

A consequence of this syntax is that you can search for a pattern containing colons by just prefixing the pattern with two spaces, and that you can search for a pattern contain spaces by just prefixing it with two colons. This should fast feel natural enough.

### Examples of a fuzzy search for `":bla :"` followed by a `cp`:

	:#:bla :#cp dest
	:#:bla :#:cp dest
	:":bla :":cp dest
	 #:bla :#cp dest
	:name":bla :"cp dest

**Note:** In order to make it clearer, I'll probably implement syntax coloring of the input. But interactive display should make it clear enough.

## Drawbacks

Search verbs and action verbs would share the same name space, which implies some restrictions and could be confusing.

**Comment by thunderrabbit** [comment]
I think allowing spaces in the search is a great idea.

For me, backtick (`) came to mind as a way to start the search term.

**Comment by Canop** [comment]
backticks are painful to type on several keyboards

**Comment by Canop** [comment]
(for now?) I've settled on a simpler syntax which is available on master. This one was more powerful but also clearly a nightmare to explain.
