### ISSUE TITLE
size display: base 2 or base 10

### ISSUE THREAD

**Issue by Canop** [Canop/broot#167]
Right now the K, M, G of broot are based on the classical base 2.

Many tools switched to the base 10, which the notation of the International System of Units and is probably more readable for humans.

What would you like broot to use ?

**Comment by ralt** [comment]
Could it use MiB etc?

**Comment by Canop** [comment]
I switched to base 10. It's easier when broot gives the same result than standard tools.

**Comment by Canop** [comment]
Problem with having the option is that either you show it with the right unit (ie 541MiB) but it takes a lot of screen space, or you don't make it visible but you don't know what you're looking at without checking the settings. That's why I think it's better to use only SI units (and hope the old software will at least abandon the old units which don't make any sense anymore).
