### ISSUE TITLE
Sort Mode

### ISSUE THREAD

**Issue by Canop** [Canop/broot#170]
This still needs to be described.

In two words, it should be a generalization of the "fat whales hunt" mode, allowing other types of sort.

**Comment by 100ideas** [comment]
I for one would love to be able to sort (and filter) by date. cheers for broot!

**Comment by 100ideas** [comment]
using the following command in the meantime

```bash
# list $size most recently edited files beneath current dir
find . -type f -not -path '*/\node_modules*' -not -path '*/\.*' -print0 | xargs -0 ls -lrt | tail -$size | cut -c 39-
```

**Comment by Canop** [comment]
It's done since 0.18.0
