### ISSUE TITLE
broot fails to compile on ubuntu 18.04

### ISSUE THREAD

**Issue by ubuntupunk** [Canop/broot#173]
**Is everything clear?**
We prefer you come to the chat and speak about the problem first.
Broot chat room: https://miaou.dystroy.org/3490?broot 

**Describe the bug**
cargo install broot fails

**To Reproduce**
'cannot bind by-move into a pattern guard'
**Expected behavior**
cargo installs broot
![Screenshot from 2020-01-21 08-53-31](https://user-images.githubusercontent.com/246662/72782103-9b00c280-3c2b-11ea-8fe5-0227c87b88cd.png)

**Screenshots**

**Configuration (please complete the following information):**
 - OS: Ubuntu 189.04

**Comment by Canop** [comment]
This bug happens with a "old" compiler. Please update to the current version. If you manage the rust toolchain with rustup, do

    rustup update

**Comment by matrixise** [comment]
you can also use the rust docker image.

**Comment by ubuntupunk** [comment]
I removed rust:
apt remove rust*
then installed via rustup:
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
Installed broot:
cargo install broot

works like a charm,

thanks
