### ISSUE TITLE
typing /// panics

### ISSUE THREAD

**Issue by sigfriedmcwild** [Canop/broot#175]
Typing 3 `'/'` characters in a row inside broot causes it to panic with the following message:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:1165:5
```

broot 0.12.0 built with rustc 1.40.0 on macOS and Windows

**Comment by Canop** [comment]
Confirmed. Thanks.

**Comment by Canop** [comment]
The current fix handles it as a fuzzy pattern. Which isn't useful but doesn't panic.

I'll consider this case for the new input syntax I'm working on.
