### ISSUE TITLE
Trouble installing for Cygwin on Win10

### ISSUE THREAD

**Issue by aagha** [Canop/broot#178]
When trying to run broot for the first time in a Cygwin shell, there's an IO privilege error.

**To Reproduce**
1. Install broot.exe in the cygwin/bin dir
2. Open a cygwin shell
3. Type "broot"

**Expected behavior**
I expected the install to take place without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/5522103/72948937-a17e5f80-3d3b-11ea-8369-f4aae3f1b50e.png)

**Configuration (please complete the following information):**
 - OS: Win 10 Pro
 - Version broot 0.11.4

**Comment by Canop** [comment]
This looks like the problem some people reported on windows native shell: that you need admin rights at the first run in order to write your preferences (cf warning at top of this page: https://dystroy.org/broot/documentation/installation/).

**Comment by aagha** [comment]
Hmm... I get the same error if I launch the mintty window as an Administrator.  Do you know what kind of rights?

**Comment by Canop** [comment]
I don't. And I'm not sure it's really a problem of rights. I don't think crossterm is cygwin compatible and I can't investigate this (I don't have any windows computer).

**Comment by aagha** [comment]
Got it. Thanks @Canop.

**Comment by Canop** [comment]
@aagha The fact that I can't personally investigate the problem doesn't mean the problem is solved or can't be solved.

**Comment by aagha** [comment]
Ah. I got it @Canop . I just closed the issue because I figured that this might be resolved when #98 was resolved.
