### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by vks** [Canop/broot#18]
In the automatically generated config the following link is given:

```
https://github.com/Canop/broot/documentation.md
```

This link does not work. It should probably be replaced with `https://github.com/Canop/broot/blob/master/documentation.md` or similar.

**Comment by Canop** [comment]
Well spotted.

This is a painfully long URL. I should probably set up some github pages or use a URL shortener.

**Comment by hellow554** [comment]
I can understand why you would want to use a shortener, but please be aware, that you expose everybody that clicks on that link to bit.ly. Better provide the real link. You embedd it anyway, so there is no need for a shorter one. (this isn't twitter ^^)

**Comment by Canop** [comment]
@hellow554 you're not wrong
