### ISSUE TITLE
Ctrl+C to exit

### ISSUE THREAD

**Issue by alexreg** [Canop/broot#183]
Would it be possible to intercept Ctrl+C and/or Ctrl+D to exit Broot? (In addition to the usual `:q` command.)

**Comment by Canop** [comment]
New installations of broot define this in the configuration file:

```
[[verbs]]
key = "ctrl-c"
execution = ":quit"
```

You can define the same shortcut for ctrl-D.

I won't add ctrl-D in standard as it's often dedicated to other uses, like going a page down.

**Comment by alexreg** [comment]
Okay, sounds good, thank you!

Not sure why this doesn't exist in the default `conf.toml` for the Homebrew installation.

**Comment by Canop** [comment]
This probably does but if your conf.toml file is old, it's not replaced when you upgrade broot.

**Comment by alexreg** [comment]
Ah right, makes sense. Ta.
