### ISSUE TITLE
[Feature request] Provide arm64 binaries for Android

### ISSUE THREAD

**Issue by neitsab** [Canop/broot#186]
Hi! I wanted to try out broot on my Android phone, so I downloaded the rpi binary in Termux, placed it in my `$PATH`, gave it execution permission and tried to run it:

```
$ broot
bash: /data/data/com.termux/files/home/bin/broot: No such file or directory
```

On a hunch I checked the binary with `file`: I realized that the RPI binary targets 32-bit ARM while my device is arm64:

```
$ file bin/broot
bin/broot: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=ba1d76ea6f6bc078ffb5bd4c2439c65581c053fd, with debug_info, not stripped
$ uname -a
Linux localhost 3.10.108-lineageos-g6e870147270 #1 SMP PREEMPT Wed Jan 8 09:24:04 UTC 2020 aarch64 Android
```
**edit**: after re-reading the `file` output and Termux [Package Management wiki entry](https://wiki.termux.com/wiki/Package_Management), it seems the issue could as well stem from the libc/dynamic linking part... I don't know a lot about those subjects 😁

Would you consider providing arm64 binaries for Android users? I will also ask for its inclusion in Termux repository to make it proper :)

Thanks for your work! 👍

**Comment by Canop** [comment]
@neitsab This is interesting. I'm willing to look at it. Can you maybe come to my chat and provide some lights ? https://miaou.dystroy.org/3

**Comment by Canop** [comment]
Current status: failing to compile, link or execute
Help welcome

**Comment by Canop** [comment]
Note that broot itself would need some small adjustements, at least to not use the `users` crate (which looks for the user id). But I have more important compilation, linking or execution problems even for my other rust programs. When they seem to be compiled for the right architecture they're "not found" at launch.

![image](https://user-images.githubusercontent.com/617006/73540848-3f0b1a80-4431-11ea-8a51-301d94ec829f.png)

**Comment by nikey02** [comment]
![Screenshot_2020-09-19-11-55-11-438_com termux](https://user-images.githubusercontent.com/68458326/93660701-37a38a80-fa6f-11ea-868b-4ac6ab346e0a.jpg)

On device build gives above error using
`cargo install broot`

**Comment by Canop** [comment]
the line with posix_madvise is optional and could be removed by modifying the compilation guard:

        // we tell the system how we intent to use the mmap
        // to increase the likehod the memory is available
        // for our loop
        #[cfg(unix)]
        unsafe {
            libc::posix_madvise(
                hay.as_ptr() as *mut std::ffi::c_void,
                hay.len(),
                libc::POSIX_MADV_SEQUENTIAL,
            );
            // TODO the Windows equivalent might be PrefetchVirtualMemory
        }

**Comment by nikey02** [comment]
BTW 
`whalespotter`
Build successfully in termux by 
`cargo install whalespotter`
![Screenshot_2020-09-19-12-02-18-757_com termux](https://user-images.githubusercontent.com/68458326/93660812-5c4c3200-fa70-11ea-90a2-f530c1c978fe.jpg)

![Screenshot_2020-09-19-12-02-31-513_com termux](https://user-images.githubusercontent.com/68458326/93660920-5440c200-fa71-11ea-8656-4cfe76f69267.jpg)

**Comment by nikey02** [comment]
> the line with posix_madvise is optional and could be removed by modifying the compilation guard:

Please try to compile without these lines 
Broot is must have command line app for termux 
I am using old version of broot 
For newer versions this is only error

**Comment by nikey02** [comment]
> It's probable somebody with experience of cross compiling rust programs on linux for termux would be able to solve that.

This may help

`cargo install cross`

And in broot src folder

`cross build -vv --target aarch64-linux-android`

**Comment by Canop** [comment]
I'll have a look, I already use cross (see https://github.com/Canop/broot/blob/master/compile-all-targets.sh). I just can't do that today.

**Comment by nikey02** [comment]
> removed by modifying the compilation guard

How to ? Where ? 
Sorry I'm not familiar with rust that much

**Comment by nikey02** [comment]
> I just can't do that today.

Thanks for swift reply .
I will try.

**Comment by Canop** [comment]
Try just removing the block with posix_madvise to check it compiles, for a start.

**Comment by nikey02** [comment]
Finally I have latest broot
Thanks @Canop 
I just change `#[cfg(unix)]` to `#[cfg(not(unix))]`
(I don't know how this affects ) but it did the job
And recompile 

![Screenshot_2020-09-19-13-02-10-568_com termux](https://user-images.githubusercontent.com/68458326/93661918-4bec8500-fa79-11ea-97d8-fd44862ee65d.jpg)

**Comment by nikey02** [comment]
Now you can able to provide ARM binaries for android too.
Please add android binaries to your releases.

**Comment by Canop** [comment]
@nikey02 @neitsab 
With the new commit, I build the Android version of broot. But I'd like somebody to test, either by compiling themselves or by trying the executable I've put at https://dystroy.org/broot/download/aarch64-linux-android/

**Comment by nikey02** [comment]
> But I'd like somebody to test, either by compiling themselves or by trying the executable I've put at https://dystroy.org/broot/download/aarch64-linux-android/

@Canop looking good .
Tried your provided binary , if you want to some specific thing let me know.
Thanks

**Comment by Canop** [comment]
@nikey02  Good thing it works: I've included the android binary in the official 1.0.1 release!

**Comment by nikey02** [comment]
Sorry but I can't .
I'm not author of this issue @neitsab is.

**Comment by Canop** [comment]
I was merely asking if everybody agreed for the closure. I can close it without the author when it's clear it's OK.

**Comment by nikey02** [comment]
Ohh sorry!  my bad  I read in hurry .
You can close this issue

**Comment by Canop** [comment]
Closing. If there's a problem on Android, please create a new issue.
