### ISSUE TITLE
Bad configuration: unable to read from the file

### ISSUE THREAD

**Issue by mikelty** [Canop/broot#187]
So I got that "bad configuration" error when I try to install it on ubuntu (18.04). I set the execute permission (chmod a+x broot) and tried twice. I looked online but could not find any good solution to this. I was able to get "br" installed but it still says the same thing. Help please.

**Comment by Canop** [comment]
Did you change the conf.toml file ? 
The permission file is normally in `~/.config/broot/conf.toml`. Is it readable ?
You may try to delete it and relaunch broot.

**Comment by mikelty** [comment]
it just says no such file or directory. i don't think it exists.

**Comment by Canop** [comment]
Please try creating the `~/.config` directory and ensure it's writable, then retry.

**Comment by mikelty** [comment]
I think the write permission is what it needs. It works now. Thanks.
