### ISSUE TITLE
Alt-enter, change shortcut on Mac OS - more like help needed, hopefully no RTFM

### ISSUE THREAD

**Issue by HachimanSec** [Canop/broot#189]
Hello there, 
I just installed the latest version of broot 0.12.2 in iTerm Build 3.3.8 on a Mac OS Catalina 10.15.3. 

It looks like a pretty amazing tool! Thanks for all the hard work*

One question, Alt+Enter is the default to bring the current windows into full size. 
How can I change this? In the config file at /Users/USER/Library/Preferences/org.dystroy.broot/conf.toml, there is no Alt+Enter visible.

Is it just me or am I missing something? Please point me into the right direction for reading up the documentation, in case of RTFM.

PS: Backspace is not working on DE keyboard layouts, it requires ⌥+⌫ (the iTerm is configured to accept normal backspace). 
Is this expected behaviour?

Cheers
Tom

**Comment by matthiasdebernardini** [comment]
So there is a  [https://dystroy.org/broot/documentation/configuration/](config) page but not sure what I should put. 

Also, the config file got written to a weird location on macOS, mine giot put in $HOME/Library/Preferences/org.dystroy.broot/conf.toml. 

I would expect this type of file to be put in $HOME/.config. 

as far the cd goes, I think we can put 
```
[[verbs]]
invocation = "cd"
key = "ctrl-enter"
shortcut = "cd"
execution = ":cd"```

Is there a better way?

**Comment by Canop** [comment]
The "ctrl-enter" configuration you made seems OK/

@matthiasdebernardini there's already an issue for the location of the configuration file on MacOS: #103

@HachimanSec The backspace problem is not expected at all. Please follow the instructions [here](https://dystroy.org/broot/community/#log) to give me the log so that I can try to see what happens.

**Comment by HachimanSec** [comment]
Hi @Canop 
thanks for your patience. I just found some time to generate the log with the backspace not working as expected:
13:52:22 [ INFO] Starting Broot v0.12.2 with log level DEBUG
13:52:22 [DEBUG] (1) broot::shell_install: Shell script already installed. Doing nothing.
13:52:22 [DEBUG] (1) broot::app: we're on screen
13:52:22 [DEBUG] (1) broot::git_ignore: searching applicable gifs for "/Users/USER"
13:52:22 [DEBUG] (1) broot::git_ignore:   looking in "/Users/USER"
13:52:22 [DEBUG] (1) broot::git_ignore:   looking in "/Users"
13:52:22 [DEBUG] (1) broot::git_ignore:   looking in "/"
13:52:22 [DEBUG] (1) broot::tree_build::builder: start building - total=false pattern=None
13:52:23 [DEBUG] (1) broot::tree_build::builder: Trimming: we have 24 lines for a goal of 23
13:52:23 [DEBUG] (1) broot::flat_tree: turning "/Users/USER/Library/Accessibility" into Pruning
13:52:23 [DEBUG] (1) broot::flat_tree: turning "/Users/USER/Downloads/BL_0001.pdf" into Pruning
13:52:23 [DEBUG] (1) broot::flat_tree: turning "/Users/USER/Documents/1 Administrative" into Pruning
13:52:27 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Char('l'), modifiers: (empty) })
13:52:27 [DEBUG] (1) broot::app: command after add_event: Command { raw: "l", parts: CommandParts { pattern: Some("l"), regex_flags: None, verb_invocation: None }, action: FuzzyPatternEdit("l") }
13:52:27 [DEBUG] (1) broot::app: action: FuzzyPatternEdit("l")
13:52:27 [DEBUG] (1) broot::git_ignore: searching applicable gifs for "/Users/USER"
13:52:27 [DEBUG] (1) broot::git_ignore:   looking in "/Users/USER"
13:52:27 [DEBUG] (1) broot::git_ignore:   looking in "/Users"
13:52:27 [DEBUG] (1) broot::git_ignore:   looking in "/"
13:52:27 [DEBUG] (1) broot::tree_build::builder: start building - total=false pattern=Fuzzy(l)
13:52:27 [ INFO] task expired (core build - inner loop)
13:52:27 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Char('l'), modifiers: (empty) })
13:52:27 [DEBUG] (1) broot::app: command after add_event: Command { raw: "ll", parts: CommandParts { pattern: Some("ll"), regex_flags: None, verb_invocation: None }, action: FuzzyPatternEdit("ll") }
13:52:27 [DEBUG] (1) broot::app: action: FuzzyPatternEdit("ll")
13:52:27 [DEBUG] (1) broot::git_ignore: searching applicable gifs for "/Users/USER"
13:52:27 [DEBUG] (1) broot::git_ignore:   looking in "/Users/USER"
13:52:27 [DEBUG] (1) broot::git_ignore:   looking in "/Users"
13:52:27 [DEBUG] (1) broot::git_ignore:   looking in "/"
13:52:27 [DEBUG] (1) broot::tree_build::builder: start building - total=false pattern=Fuzzy(ll)
13:52:27 [DEBUG] (1) broot::tree_build::builder: Trimming: we have 270 lines for a goal of 23
13:52:27 [DEBUG] (1) broot::flat_tree: turning "/Users/USER/Zotero/translators/Cell Press.js" into Pruning
13:52:27 [DEBUG] (1) broot::flat_tree: Avoiding to prune the line with best score
13:52:27 [DEBUG] (1) broot::flat_tree: turning "/Users/USER/Library/FontCollections/Web.collection" into Pruning
13:52:27 [DEBUG] (1) broot::flat_tree: turning "/Users/USER/Library/Application Support/CallHistoryDB" into Pruning
13:52:27 [ INFO] Tree search with pattern Fuzzy(ll) took 30.187356ms
13:52:27 [DEBUG] (1) broot::browser_states: was it total search ? false
13:52:28 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Char('h'), modifiers: CONTROL })
13:52:28 [DEBUG] (1) broot::app: command after add_event: Command { raw: "ll", parts: CommandParts { pattern: Some("ll"), regex_flags: None, verb_invocation: None }, action: Unparsed }
13:52:28 [DEBUG] (1) broot::app: action: Unparsed
13:52:29 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Char('h'), modifiers: CONTROL })
13:52:29 [DEBUG] (1) broot::app: command after add_event: Command { raw: "ll", parts: CommandParts { pattern: Some("ll"), regex_flags: None, verb_invocation: None }, action: Unparsed }
13:52:29 [DEBUG] (1) broot::app: action: Unparsed
13:52:31 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Esc, modifiers: (empty) })
13:52:31 [DEBUG] (1) broot::app: command after add_event: Command { raw: "", parts: CommandParts { pattern: None, regex_flags: None, verb_invocation: None }, action: Back }
13:52:31 [DEBUG] (1) broot::app: action: Back
13:52:32 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Char(':'), modifiers: (empty) })
13:52:32 [DEBUG] (1) broot::app: command after add_event: Command { raw: ":", parts: CommandParts { pattern: None, regex_flags: None, verb_invocation: Some(VerbInvocation { name: "", args: None }) }, action: VerbEdit(VerbInvocation { name: "", args: None }) }
13:52:32 [DEBUG] (1) broot::app: action: VerbEdit(VerbInvocation { name: "", args: None })
13:52:33 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Char('q'), modifiers: (empty) })
13:52:33 [DEBUG] (1) broot::app: command after add_event: Command { raw: ":q", parts: CommandParts { pattern: None, regex_flags: None, verb_invocation: Some(VerbInvocation { name: "q", args: None }) }, action: VerbEdit(VerbInvocation { name: "q", args: None }) }
13:52:33 [DEBUG] (1) broot::app: action: VerbEdit(VerbInvocation { name: "q", args: None })
13:52:34 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Enter, modifiers: (empty) })
13:52:34 [DEBUG] (1) broot::app: command after add_event: Command { raw: ":q", parts: CommandParts { pattern: None, regex_flags: None, verb_invocation: Some(VerbInvocation { name: "q", args: None }) }, action: VerbInvocate(VerbInvocation { name: "q", args: None }) }
13:52:34 [DEBUG] (1) broot::app: action: VerbInvocate(VerbInvocation { name: "q", args: None })
13:52:34 [DEBUG] (1) broot::app: cmd result quit
13:52:34 [DEBUG] (1) broot::app: we left the screen
13:52:34 [ INFO] bye

**Comment by Canop** [comment]
Can you tell when you did try the backspace in this log ? What does exactly mean "Backspace is not working on DE keyboard layouts" ? No reaction at all ? Unexpected reaction ?

**Comment by HachimanSec** [comment]
Hi @Canop 
please excuse my late reply, the issue got buried in my backlog. 

When I start iTerm on my Mac, execute broot and then enter some text, I cant delete it via backspace. Only via ⌥ + ⌦
![image](https://user-images.githubusercontent.com/20123996/76706943-a7fdd780-66eb-11ea-8105-24b6333f4b4e.png)

**Comment by Canop** [comment]
@HachimanSec Please tell me what appears in the log when you hit the backspace key.

**Comment by HachimanSec** [comment]
There you go:
```
21:03:59 [ INFO] Starting Broot v0.12.2 with log level DEBUG
21:03:59 [DEBUG] (1) broot::shell_install: Shell script already installed. Doing nothing.
21:03:59 [DEBUG] (1) broot::app: we're on screen
21:03:59 [DEBUG] (1) broot::git_ignore: searching applicable gifs for "/Users/tom"
21:03:59 [DEBUG] (1) broot::git_ignore:   looking in "/Users/tom"
21:03:59 [DEBUG] (1) broot::git_ignore:   looking in "/Users"
21:03:59 [DEBUG] (1) broot::git_ignore:   looking in "/"
21:03:59 [DEBUG] (1) broot::tree_build::builder: start building - total=false pattern=None
21:03:59 [DEBUG] (1) broot::tree_build::builder: Trimming: we have 57 lines for a goal of 56
21:04:00 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Zotero/translators" into Pruning
21:04:00 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/VirtualBox VMs/Victims" into Pruning
21:04:00 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Pictures/Photo Booth Library" into Pruning
21:04:00 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Library/ApplicationSupport" into Pruning
21:04:00 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Downloads/Eminem - Music To Be Murdered By" into Pruning
21:04:00 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Documents/5 Projects" into Pruning
21:04:00 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Desktop/Fragebogen_Testimonials_englisch_A.docx" into Pruning
21:04:02 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Char('d'), modifiers: (empty) })
21:04:02 [DEBUG] (1) broot::app: command after add_event: Command { raw: "d", parts: CommandParts { pattern: Some("d"), regex_flags: None, verb_invocation: None }, action: FuzzyPatternEdit("d") }
21:04:02 [DEBUG] (1) broot::app: action: FuzzyPatternEdit("d")
21:04:02 [DEBUG] (1) broot::git_ignore: searching applicable gifs for "/Users/tom"
21:04:02 [DEBUG] (1) broot::git_ignore:   looking in "/Users/tom"
21:04:02 [DEBUG] (1) broot::git_ignore:   looking in "/Users"
21:04:02 [DEBUG] (1) broot::git_ignore:   looking in "/"
21:04:02 [DEBUG] (1) broot::tree_build::builder: start building - total=false pattern=Fuzzy(d)
21:04:02 [DEBUG] (1) broot::tree_build::builder: Trimming: we have 601 lines for a goal of 56
21:04:02 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Zotero/translators/digibib.net.js" into Pruning
21:04:02 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Zotero/storage/DY6B7YUE" into Pruning
21:04:02 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Library/WebKit/Databases" into Pruning
21:04:02 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Library/LanguageModeling/de-dynamic.lm" into Pruning
21:04:02 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Library/Keyboard/de-dynamic.lm" into Pruning
21:04:02 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Library/Application Support/icdd" into Pruning
21:04:02 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Downloads/Eminem - Music To Be Murdered By/Darkness.mp3" into Pruning
21:04:02 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Documents/8 Publications/Design_Thinking" into Pruning
21:04:02 [DEBUG] (1) broot::flat_tree: turning "/Users/tom/Documents/7 Security/g0d dumps" into Pruning
21:04:02 [ INFO] Tree search with pattern Fuzzy(d) took 184.855531ms
21:04:02 [DEBUG] (1) broot::browser_states: was it total search ? false
21:04:03 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Char('h'), modifiers: CONTROL })
21:04:03 [DEBUG] (1) broot::app: command after add_event: Command { raw: "d", parts: CommandParts { pattern: Some("d"), regex_flags: None, verb_invocation: None }, action: Unparsed }
21:04:03 [DEBUG] (1) broot::app: action: Unparsed
21:04:07 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Backspace, modifiers: (empty) })
21:04:07 [DEBUG] (1) broot::app: command after add_event: Command { raw: "", parts: CommandParts { pattern: None, regex_flags: None, verb_invocation: None }, action: FuzzyPatternEdit("") }
21:04:07 [DEBUG] (1) broot::app: action: FuzzyPatternEdit("")
21:04:09 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Char('c'), modifiers: CONTROL })
21:04:09 [DEBUG] (1) broot::app: command after add_event: Command { raw: "", parts: CommandParts { pattern: None, regex_flags: None, verb_invocation: None }, action: VerbIndex(1) }
21:04:09 [DEBUG] (1) broot::app: action: VerbIndex(1)
21:04:09 [DEBUG] (1) broot::app: cmd result quit
21:04:09 [DEBUG] (1) broot::app: we left the screen
21:04:09 [ INFO] bye
```

**Comment by Canop** [comment]
A lot has changed since this issue. Before I dive into it, can I know whether the problem still exists ?
