### ISSUE TITLE
[Feature request] Allow rebinding enter

### ISSUE THREAD

**Issue by jcassee** [Canop/broot#190]
**Did a discussion occur before?**

See #65 and 40c57d2485c67be7489bc64a40b210b342f5b711:

> allow more keys as verb triggers

But also #141:

> Right now the code explicitly prevents overriding enter (when the input isn't empty), alt-enter, esc and the '?'. I'll have to think a little more for that.

**Is your feature request related to a problem? Please describe.**
When using broot as a widget for selecting files or directories, it is useful to call pretty_print on enter (or alt-enter if we still want to be able to focus on a directory).

**Describe the solution you'd like**
The possibility of rebinding enter and/or alt-enter.

**Describe alternatives you've considered**
I am currently rebinding a different key, but keep hitting enter anyway. :smile:

**Comment by Canop** [comment]
@jcassee those comments might be obsolete. Binding has been quite freed. See https://dystroy.org/broot/documentation/tricks/#open-files-without-a-windowing-system

**Comment by jcassee** [comment]
I'm currently trying this:

widget-conf.toml:
```
[[verbs]]
key = "alt-enter"
execution = ":print_path"
```

And then call `broot --conf widget-conf.toml`. Unfortunately, that does not work.

However, I could probably redefine the execution of the "edit" invocation...

**Comment by Canop** [comment]
You're right, alt-enter isn't bindable now: https://github.com/Canop/broot/blob/master/src/commands.rs#L199

And I don't remember why... I'll have to look into it. I'll come back to you on that.

**Comment by jcassee** [comment]
Yes, perfect. Thanks, @Canop!
