### ISSUE TITLE
error[E0008]: cannot bind by-move into a pattern guard

### ISSUE THREAD

**Issue by rj-dsl** [Canop/broot#191]
**Describe the bug**
When installing via cargo on Linux Mint 19.3 i get the following error:

```
error[E0008]: cannot bind by-move into a pattern guard
  --> /home/rj/.cargo/registry/src/github.com-1ecc6299db9ec823/broot-0.12.2/src/command_parsing.rs:27:12
   |
27 |         Ok(sep) if !sep.is_empty() => sep,
   |            ^^^ moves value into pattern guard

error: aborting due to previous error

For more information about this error, try `rustc --explain E0008`.
error: failed to compile `broot v0.12.2`, intermediate artifacts can be found at `/tmp/cargo-installTobo4q`

Caused by:
  Could not compile `broot`.
```

**To Reproduce**
apt install cargo

cargo install broot

**Expected behavior**
It installs.

**Screenshots**

**Configuration (please complete the following information):**
 - OS: Linux Mint
 - Version 19.3
- Relevant configuration items
apt get install of cargo, no modifications

**Comment by Canop** [comment]
You're using an old compiler. Please upgrade it.
If you installed it with rustup, please do

    rustup update

**Comment by rj-dsl** [comment]
Ty it installs now.
