### ISSUE TITLE
Does not respect default_flags

### ISSUE THREAD

**Issue by sQVe** [Canop/broot#192]
**Describe the bug**
I just installed `broot` and I cannot for the life of me get it to respect the `default_flags` setting. All other settings are falling through fine, ie. verbs etc.

**To Reproduce**
Set `default_flags = "gh"` in `conf.toml`.

**Expected behavior**
It should launch `broot` with the `-g` and `-h` flag.

**Configuration (please complete the following information):**
 - OS: Arch Linux, kernel 5.5.2
 - Version: broot 0.12.2

**Comment by Canop** [comment]
This feature needs broot 0.13.0. 

The reason you have only broot 0.12.2 is  that I messed the deployement yesterday, sorry for that.

Broot 0.13.0 should now be available on most channels.

**Comment by sQVe** [comment]
@Canop Alright. I'll update as soon as as possible then. Cheers.

Closing.
