### ISSUE TITLE
Background color to "none" messing up the theme.

### ISSUE THREAD

**Issue by SpunkyMaXimz** [Canop/broot#194]
In my configuration, under [skin], if I change the default color as:
`default = "gray(20) none"`
then the the 'selected foreground' color kind of messes up. It is hard to explain, see the images.
![20200208_130917](https://user-images.githubusercontent.com/50173278/74081483-7ef78080-4a75-11ea-94aa-9223edcdd9b7.png)

This will get weirder if the selected line is the last
![20200208_130927](https://user-images.githubusercontent.com/50173278/74081548-3f7d6400-4a76-11ea-8d41-9162338da6ac.png)

What I want to do: remove the background color. (make the background transparent)
This **was not** a problem before that last update. I was able to make the background transparent.

I am using Arch Linux and my broot version is 0.13.0

**Comment by Canop** [comment]
I didn't think about testing on a transparent terminal.
I'll fix that ASAP.

**Comment by SpunkyMaXimz** [comment]
Thanks.
It was working for me. But for some reason, this bug.
