### ISSUE TITLE
Ability to enter archives (jar, tar, zip, 7z, etc.)

### ISSUE THREAD

**Issue by bric3** [Canop/broot#197]
**Did a discussion occur before?** => Yes
**Is your feature request related to a problem? Please describe.** => Nope
**Describe the solution you'd like**
Coming from both midnight commander (`mc`), and `ranger` sometimes, I'd like the ability to enter archives to navigate them in broot.
Eventually have to possibility to extract a specific file inside the archive / and or see it if it's text.

**Describe alternatives you've considered**
I'm using `mc` instead for this purpose.

**Additional context**
Of course I think broot should not display files in the archive automatically, the user would have to enter the archive.

**Comment by snieda** [comment]
you could configure it in your conf.toml:

[[verbs]]
invocation = "archivemount"
shortcut = "am"
external = "am.sh {file-name}"
leave_broot = false
auto_exec = true
set_working_dir = true
apply_to = "file"

[[verbs]]
invocation = "viewarchivemount"
key = "ctrl-shift-F6"
shortcut = "vam"
auto_exec = true
set_working_dir = true
cmd = ":mkdir -p /tmp/{file-name};:am;:!focus /tmp/{file-name}.archivemount"

[[verbs]]
invocation = "unmountarchivemount"
key = "ctrl-shift-F7"
shortcut = "uam"
external = "umount /tmp/{file-name}.archivemount"
leave_broot = true
auto_exec = false
set_working_dir = true





with am.sh:

mkdir -p /tmp/"$1".archivemount; archivemount -o nonempty "$1" /tmp/"$1".archivemount

**Comment by seomwan** [comment]
Another alternative to @snieda's, using `7z` (or other compatible archiver), and `nushell` parsing functions:

```hjson
{
    name: zip_list_files
    invocation: zipl
    external: [
        "nu"
        "-e"
        '''
        let zip_list_files_all = (
            7z l '{file}'
            | lines
        )
        let zip_meta = (
            $zip_list_files_all
            | range ..16
        )
        let zip_content_index = (
            $zip_meta
            | range 8..
            | reduce --fold 5 {|it, acc|
                    if ($it | str starts-with '   Date') {return $acc} else {$acc + 1}
                }
        )
        # print ($zip_content_index | describe)
        # print ($zip_list_files_all | get $zip_content_index)
        print (
            $zip_meta
            | range 9..($zip_content_index - 2)
            | parse '{key} = {value}'
            | transpose --header-row
            | update 'Physical Size' {|| into filesize }
        )
        let zipl_header_Name_index = (
            $zip_list_files_all
            | get $zip_content_index
            | str index-of Name
        )
        let zipl_files = (
            $zip_list_files_all
            | range ($zip_content_index + 1)..-3
            | each {|| str substring $zipl_header_Name_index..}
        )
        print $zipl_files
        let zipl = (
            $zip_list_files_all
            | range ($zip_content_index)..-3
            | str join "\n"
            | from ssv -m 1
            | drop nth 0
            | update Size {|| into filesize }
            | update Compressed {|| into filesize }
            | update Date {|row|
                $'($row.Date) $($row.Time)'
                | into datetime
            }
            | reject Time
            | update Name $zipl_files
            | sort-by Size
        )
        print $zipl
        echo `$zipl`
        '''
    ]
    apply_to: file
    extensions: [
        zip
        rar
        7z
        7zip
        lzma
    ]
    leave_broot: false
}
```

You can adapt it to your own shell, archiver, and remove the stuff you don't need

**Comment by Canop** [comment]
I explored this question and I decided not to have broot browse archives the same way it browses the standard filesystems.

I explain it here: https://dystroy.org/blog/why-broot-doesnt-enter-zip/

**Comment by eulores** [comment]
A different tackle, based on [mxmlnkn/ratarmount](https://github.com/mxmlnkn/ratarmount).

* The tool **ratarmount** uses **Fuse** to open the compressed file and mount it under `/tmp`.
* Then a new instance of **br** is launched to inspect the mounted contents.
* Once this interim **br** instance is exited, the compressed file is unmounted and the original instance of **br** launched again.
* Recursion (opening compressed files within compressed files) also works.

Add this section to the broot configuration file, for example, under `~/.config/broot/verbs.hjson`

```
    {
        invocation: ratarmount
        key: enter
        apply_to: binary_file
        panels: [tree]
        from_shell: true
        external: "ratarmount -d0 {file} /tmp/{file-stem};br /tmp/{file-stem};ratarmount -u /tmp/{file-stem};br -c \":select {file}\" {parent}"
        extensions: [
            gz
            tgz
            bz2
            zip
            tar
            rar
            7z
            cpio
            lz4
            cab
            rpm
            deb
            iso
        ]
    }
```

**Comment by Canop** [comment]
Oh this is a cool one @eulores !

**Comment by eulores** [comment]
Hi @mac1202, in theory you can replace all instances of {file-stem} with a fixed random string. The two remaining {file} instances have to be wrapped in quotes, and these might require some escaping. I need to try it on my end first, but I never had that case before.

**Comment by mac1202** [comment]
Thanks for your answer, if it can help you here is the error I got : 
`ratarmount: error: unrecognized arguments: :select '/home/mac/Téléchargements/MAME (bios-devices).zip' /home/mac/Téléchargements`
