### ISSUE TITLE
What files are broot looking for??????

### ISSUE THREAD

**Issue by qzmfranklin** [Canop/broot#199]
Ubuntu 18.04.3
x86-64

broot 0.13.1

Repro:
- Copy over broot to PATH.
- Run `sudo rm -rf ~/.config/broot`
- Populate the following directory by hand:
```text
zhongming@zhongming:~/.config/broot$ tree
.
├── conf.toml
└── launcher
    ├── bash
    │   └── br -> /home/zhongming/.local/share/broot/launcher/bash/1
    └── installed-v1
```
- run `br` or `broot`.

Expect to see:

`br` works nicely.

Actual result:

```text
Bad configuration: unable to read from the file
```

Propose to do:

- At least show which file it is trying to read so I can debug.
- Looks like `br` stores files in places other than `~/.config/broot`. I hate utilities that scatter files all over the places.

Question:
- How many files are broot creating and visiting?
- I can and want to manually install the shell function. I don't want `br` to care about it.
- My `.bashrc` and `.bash_profile` are configured by sysadmins and are `root:root`. I cannot modify them. I don't expect command line utilities to auto-modify my `bashrc` in a way that I cannot change. Instead, I want advices so that **I** get to determine how the shell scripts are modified.

**Comment by Canop** [comment]
Is your `~/.config/broot/conf.toml` readable ? Please check the rights

**Comment by qzmfranklin** [comment]
They are all 644

**Comment by qzmfranklin** [comment]
Odd enough, if I run

```bash
sudo broot --install
sudo broot
```

It works.

Afterwards, running `br` without `sudo` works.

The `~/.config/broot` directory has exactly the same files as shown above, with the same permissions, ownership, and content.

But if I remove `~/.config/broot` and re-install broot in the way I described, it just gives the error I am reporting.

And, I really do not like command line tools to control exactly how to modify my bashrc. I want to control it.

**Comment by qzmfranklin** [comment]
What files are `broot` creating and visiting though? If I know that, I can continue the debugging.

**Comment by Canop** [comment]
>  it just gives the error I am reporting.
I guess there's a bug. If your redo the process with `BROOT_LOG=debug broot` we might find the failure point in the dev.log file

> And, I really do not like command line tools to control exactly how to modify my bashrc. I want to control it.
There are launch options specifically for that purpose.  You can for example launch broot with `broot --set-install-state refused` so that it doesn't even look at the install state. And you can use `broot --print-shell-function > my-own-function-file` to install as you want the br function

**Comment by Canop** [comment]
> What files are broot creating and visiting though? If I know that, I can continue the debugging.

broot tells you everything:

![image](https://user-images.githubusercontent.com/617006/74343064-bedaa280-4daa-11ea-9323-17c3fe8ba119.png)

**Comment by qzmfranklin** [comment]
Thanks for the info. I'll give it a shot.
