### ISSUE TITLE
Unable To Bind Control with Space

### ISSUE THREAD

**Issue by Rayqan** [Canop/broot#201]
- OS: Arch Linux
 - Version:  latest

Binding any verbs to the control and space key results in an error.

**Comment by Canop** [comment]
There's a problem with crossterm here, I get `Key(KeyEvent { code: Null, modifiers: (empty) })` on `ctrl-space`. I'll see with Timon.

**Comment by TimonPost** [comment]
![image](https://user-images.githubusercontent.com/19969910/77470568-2ad01200-6e11-11ea-9972-2b095d23c3ad.png)

**Comment by Canop** [comment]
@TimonPost It seems to be OK with the current crossterm.

I close the issue, then.
