### ISSUE TITLE
Nested path search

### ISSUE THREAD

**Issue by maverickdas** [Canop/broot#204]
I'd like to be able to look for nested paths in one go. This could be enabled if the absolute path (relative to root) is used for fuzzy matching. 

Example: To search for file - `src/utils/query.py`, a search via "sutilsquery" should suffice.

This is currently possible in fzf, which I use via custom shell functions for moving about. Having this feature would let me replace it.

**Comment by Canop** [comment]
This is something I plan to do. It's (a little) mentioned here: https://github.com/Canop/broot/issues/164

I'll try to put it a little more near the top of the TODO list

**Comment by chschmitz** [comment]
I second @maverickdas's idea. An alternative way to specify that search could be something like "s/ut/qu" (with slashes), so we don't match too many irrelevant results.

**Comment by Canop** [comment]
This is now available on master (not released):

![image](https://user-images.githubusercontent.com/617006/84025787-731cbc00-a98c-11ea-9bea-2393c42396f3.png)

More details here: https://dystroy.org/broot-master/input/#the-filtering-pattern
