### ISSUE TITLE
Follow symbolic links in search

### ISSUE THREAD

**Issue by mms-neuro** [Canop/broot#205]
Hi,
I really like your work, thanks!

It would however be great if the search could follow (maybe optional) symbolic links. I use them to organize stuff and in the current version, one has to go into the directories until one can look for lower directories.

Thanks in advance!

**Comment by mms-neuro** [comment]
There might be a problem, that the trees might not be unique anymore, but if that is a problem one could also maybe specify certain links in the config to be followed.

**Comment by Canop** [comment]
A problem is that it's simply not a tree anymore. And one result could be seen several times.

A solution could be to store a list of visited inodes to avoid redundancies but then the resulting tree could be far from obvious.

A configured list of a few links to follow could be used but keeping such a list up to date might be tedious.

**Comment by Canop** [comment]
It's ,now possible to define in configuration the paths for which we
want a special behavior:

* "not-enter": don't list the content - useful for slow devices
* "enter": list the content even if it's a link (to a dir)
* "hide": don't show the file or directory

Exemple configuration:

```
[special-paths]
"/media/slow-backup-disk" = "no-enter"
"/home/dys/**/useless" = "hide"
"/home/dys/my-link-I-want-to-explore" = "enter"
```

**Comment by Canop** [comment]
That's right, content search doesn't follow links to files. It could probably be changed. I'll create an issue.
