### ISSUE TITLE
Stop printing line like "removed '/tmp/tmp.PnBgiBPflb'" after exiting broot

### ISSUE THREAD

**Issue by c02y** [Canop/broot#206]
**Is your feature request related to a problem? Please describe.**
Whenever I quit broot like `Ctrl-q` or `Ctrl-c` or simply using `broot --help` to print the usage message, there always be a line like "removed '/tmp/tmp.PnBgiBPflb'" printed, could you please remove this line?

**Comment by Canop** [comment]
I've never seen such line.
Can you please show me the log of broot on a very short session ?
You can get it with
    BROOT_LOG=debug broot

**Comment by c02y** [comment]
> BROOT_LOG=debug broot

Running `BROOT_LOG=debug broot` in bash, there is no "removed '/tmp/tmp.PnBgiBPflb'" line after quitting broot(using `Ctrl-q`).

dev.log file:
~~~
[chz@chz-pc tmp]$ less dev.log
13:17:53 [ INFO] Starting Broot v0.13.2 with log level DEBUG
13:17:53 [DEBUG] (1) broot::shell_install: Shell script already installed. Doing nothing.
13:17:53 [DEBUG] (1) broot::cli: Applying default flags "pdFI" from conf
13:17:53 [DEBUG] (1) broot::cli: modified tree options: TreeOptions { show_hidden: false, only_folders: false, show_sizes: false, show_dates: true, show_git_file_info: false, trim_root: true, show_permissions: true, respect_git_ignore: true, filter_by_git_status: false, pattern: None }
13:17:53 [DEBUG] (1) broot::app: we're on screen
13:17:53 [DEBUG] (1) broot::tree_build::builder: GitIgnorer::new took 388.059µs
13:17:53 [DEBUG] (1) broot::git_ignore: searching applicable gifs for "/home/chz/tmp"
13:17:53 [DEBUG] (1) broot::git_ignore:   looking in "/home/chz/tmp"
13:17:53 [DEBUG] (1) broot::git_ignore:   looking in "/home/chz"
13:17:53 [DEBUG] (1) broot::git_ignore:   looking in "/home"
13:17:53 [DEBUG] (1) broot::git_ignore:   looking in "/"
13:17:53 [DEBUG] (1) broot::tree_build::builder: Building - total=false pattern=None
13:17:53 [DEBUG] (1) broot::tree_build::builder: Trimming: we have 2 lines for a goal of 48
13:17:54 [DEBUG] (1) broot::commands: add_event Key(KeyEvent { code: Char('q'), modifiers: CONTROL })
13:17:54 [DEBUG] (1) broot::app: command after add_event: Command { raw: "", parts: CommandParts { pattern: None, regex_flags: None, verb_invocation: None }, action: VerbIndex(30) }
13:17:54 [DEBUG] (1) broot::app: action: VerbIndex(30)
13:17:54 [DEBUG] (1) broot::app: cmd result quit
13:17:54 [DEBUG] (1) broot::task_sync: dead dam
13:17:54 [DEBUG] (1) broot::app: we left the screen
13:17:54 [ INFO] bye
[chz@chz-pc tmp]$
~~~
![image](https://user-images.githubusercontent.com/2135996/75092997-9e83c280-55b8-11ea-94bb-feeebd814415.png)

**Comment by Canop** [comment]
ok, I don't know why, but I guess something in your system notifies you when the br function removes its tmp file (and it's probably the one at https://github.com/Canop/broot/blob/master/src/shell_install/bash.rs#L68)

**Comment by c02y** [comment]
The reason is that I define an alias for builtin `rm` like `alias rm='rm -v'`, so `rm` command in broot program is using my alias (which will print the process of `rm` command). Could you please use command line like:
~
command rm -f "$f"
or
rm -f "$f" > /dev/null
~

to avoid this problem?

**Comment by Canop** [comment]
@c02y you can overload the verb in the config file in order to call the command of your choice or with your desired arguments, for example

```
[[verbs]]
name = "rm"
invocation = "rm"
execution = "/usr/bin/rm  -rf {file}"
leave_broot = false
```

Does that solve your problem ?

**Comment by c02y** [comment]
This works for `broot` command not for `br`.

Actually I'm using fish shell, so `br` command is from br.fish which is a link of `~/.local/share/broot/launcher/fish/br.fish` and I have to add `^/dev/null >/dev/null` at the end of `rm` command line to solve this, since `rm` command in br.fish uses my rm alias.

In case any one using bash shell has this issue, I suggest modifying the `rm -f "$file"` in the upstream code.

**Comment by orientnab** [comment]
Not sure if this will reopen the Issue. Just dropping here what I did to fix my problem in case it may help someone in the future. c02y was right, I just couldn't get my head around with his explanation.

If I'm not mistaken, `broot` creates a script the first time it is used so it can use cd (this is pretty neatly explained in the doc).
This script uses `rm`, which in my case it is aliased to `rm -v`.
I just modified by hand that script. I guess this file might get overwritten at some point, but the fix is easy enough to do.

In my system the file is in `.config/broot/launcher/bash/br`. (It says bash even though I'm using zsh.)
There are two lines to modify. But they just need changing 
`rm` to `address/to/your/bin/rm` which in my case is `/usr/bin/rm`
So both the lines become
`/usr/bin/rm -f "$f"`

**Comment by Canop** [comment]
>  I guess this file might get overwritten at some point
not without your agreement

> It says bash even though I'm using zsh
because the same script is used for all bash compatible shells and it was shorter to write "bash" than "bash-compatible"
