### ISSUE TITLE
100% CPU usage when network interface disconnects while computer is asleep

### ISSUE THREAD

**Issue by ReagentX** [Canop/broot#207]
**Describe the bug**
Broot will use 100% of the CPU until quit when the network interface disconnects while computer is asleep

**To Reproduce**
- Plug in an ethernet adapter
- Tell Broot to watch that interface
- Put computer to sleep
- Unplug adapter
- Wake computer

**Expected behavior**
Broot is still using normal amounts of CPU

**Screenshots**

**Configuration (please complete the following information):**
 - OS: 10.14.6
 - Version (18G3020)

**Comment by Canop** [comment]
What do you exactly mean by "Tell Broot to watch that interface" ?

**Comment by ReagentX** [comment]
Wow, I opened this in the wrong repo.

**Comment by Canop** [comment]
Ahaha... Don't worry for the embarrassment I'm happy not to have this very unexpected problem.

And now I wonder what file watcher is called broot.
