### ISSUE TITLE
Dealing with slow, remote directories. 

### ISSUE THREAD

**Issue by pordyna** [Canop/broot#208]
I often have some remote directories mounted via `sshfs`. Whenever I do this the fuzzy search becomes extremely slow and `broot` basically breaks.  I assume it has something to do with the remote not being pre-indexed and just too large. 

It would be great if there was a way to exclude remote directories from the search or somehow handle them differently. 
 
 And btw, I love this tool, it's just so intuitive!  :rocket: :smile:

**Comment by Canop** [comment]
There are other reasons to exclude directories or to have special behaviors for some of them.

Request accepted, then.

(I should also worry about broot breaking, I hope it's not just a slow listing)

**Comment by pordyna** [comment]
I moved my remote mount point outside the home directory and as long as I don't deliberately go there `broot` behaves as usual.
I compared a bit my listing speeds. I compared `cd` followed by `ls` in bash, a terminal-based file manager (`ranger`), a GUI file manager `pcmanfm`, and `broot`. When browsing my local files there is no noticeable difference.  While moving through the remote directories  ` cd & ls` are very fast, `ranger` has a small lag, the GUI manager needs a second maybe two to load a directory.  `broot` needs a considerable amount of time, depending on the directory size similar or longer than GUI.  Navigating by typing is very very slow but gets faster in small directories with not many sub-directories.

Maybe that can be useful :)

**Comment by Canop** [comment]
The problem with broot is that it needs to list many directories, not just the top level one, in order to get a tree.

**Comment by pordyna** [comment]
That makes a lot of sense. I guess a full tree is needed for the fuzzy search. Maybe a limitation to a certain tree level for some directories would be an option. This could be then possibly overridden by `:total_search`.

**Comment by Canop** [comment]
Not a full tree at all, the algorithm is more complex. But definitely more than just one level in most cases, especially when you do a search.

**Comment by taziden** [comment]
Hi, I have the same issue and it prevents me from using broot on a daily basis. It would be great to have this feature!

**Comment by Canop** [comment]
It's now possible to define in configuration the paths for which we
want a special behavior:

* "not-enter": don't list the content - useful for slow devices
* "enter": list the content even if it's a link (to a dir)
* "hide": don't show the file or directory

Exemple configuration:

```
[special-paths]
"/media/slow-backup-disk" = "no-enter"
"/home/dys/**/useless" = "hide"
"/home/dys/my-link-I-want-to-explore" = "enter"
```
