### ISSUE TITLE
Regex capture groups in custom verbs are passed as literal strings when they don't match anything

### ISSUE THREAD

**Issue by Ryujinra** [Canop/broot#210]
Firstly, thanks for your continued work on this project. 

If you have a custom verb like so:

```
[[verbs]]
name = "mpv"
invocation = "mpv (?P<args>.*)?"
execution = "mpv {args} {file}"
from_shell = true
```

and use the verb with no arguments as `:mpv` (with a file selected), the literal string `{args}` will also be passed to the resultant command (as `mpv {args} somefilename`, which will make programs complain about `{args}` not being a valid argument). 

Expected behavior is that additional arguments that would be captured by the `{args}` capture group are optional in this case, and nothing but `{file}` should be passed to `mpv` in the absence of additional arguments. At the very least, the `?` quantifier after the capture group should be respected in these cases, I think.

**Comment by Canop** [comment]
The version at master should now support this use case. Please confirm.

Please also note that
- the syntax is very simple and it is expected to be somehow limited compared to full regex replacements
- I'm not 100% sure that this change can't bring regressions elsewhere so it's tagged experimental

**Comment by Ryujinra** [comment]
Seems to work perfectly for me so far with a few fairly complex verb definitions; thanks.
