### ISSUE TITLE
Skin doesn't work when in tmux session.

### ISSUE THREAD

**Issue by tru2dagame** [Canop/broot#214]
**Describe the bug**
Skin doesn't work when in tmux session.
All the background is back, can't see the selected line.

**To Reproduce**
```
tmux new -s broot
br
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1673006/77259309-90aa8580-6cbb-11ea-939c-db55e9b331ae.png)

**Configuration (please complete the following information):**
 - OS: macOS
 - Version 10.15.3
 - App: iTerm2

**Comment by Canop** [comment]
There are many problems with crossterm in tmux, not just the skin, unfortunately. I'll ping timon on this but unless there's a champion to try work on this this will probably stall for a while

**Comment by tru2dagame** [comment]
@Canop I tried changing skin to [Solarized Dark](https://dystroy.org/broot/skins/) in broot toml file. It's just always black when using tmux.

![image](https://user-images.githubusercontent.com/1673006/77259612-8ee1c180-6cbd-11ea-9ac9-8524020316ea.png)

**Comment by Canop** [comment]
Related: https://github.com/crossterm-rs/crossterm/issues/401
(this new issue is just a stub and is quite empty because we should try to define what exactly doesn't work at the tmux level)

**Comment by nicm** [comment]
Are you sure you have told tmux the outside terminal supports RGB colour (assuming it does)? See https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour. RGB colour has been supported since tmux 2.2.

If that doesn't help - how old is your tmux? Possibly this application assumes the terminal supports BCE - tmux did not support BCE until version 2.4.

**Comment by danieltrautmann** [comment]
@tru2dagame I'm also using tmux and iTerm2 and have the following two lines in my tmux config that might help you here.

```
set-option -g default-terminal      "screen-256color"     # Use 256 color terminal
set-option -g terminal-overrides    ",xterm-256color:RGB" # Suggested by nvim health check
```

In iTerm2 you can set the reported terminal type. This setting can be found under Preferences > Profiles > Your Profile > Terminal > Reported terminal type

I've set it to `xterm-256color`.

**Comment by tru2dagame** [comment]
@danieltrautmann Thank you for your suggestions. It solves the problem.
