### ISSUE TITLE
Question: Ignore diacritics when searching

### ISSUE THREAD

**Issue by fsmiamoto** [Canop/broot#215]
Is it currently possible to ignore diacritics in word when searching in anyway?

For instance, when looking for a directory called `Comunicações`
![IssueBroot2](https://user-images.githubusercontent.com/20388082/78075713-6de33580-737b-11ea-951f-d5610ac1004b.png)

I would like to use `comunicacoes` in the search
![IssueBroot3](https://user-images.githubusercontent.com/20388082/78075721-70de2600-737b-11ea-810d-bffbe1477bdf.png)

**Comment by Canop** [comment]
It's not currently possible. You can abstain from typing the whole letter and it would match in this case but there's currently nothing in broot to ignore diacritics.

If you think there's a need, change your "question" into a "feature request". I don't really foresee any problem apart the performance cost.

**Comment by fsmiamoto** [comment]
Fair enough!
I'll be closing this then and opening a feature request for future discussions.
