### ISSUE TITLE
Ignore diacritics when searching

### ISSUE THREAD

**Issue by fsmiamoto** [Canop/broot#216]
When searching for directories with names that have diacritics, it would be convenient to search ignoring those
 
For example, when looking for a directory called `Comunicações`
![IssueBroot2](https://user-images.githubusercontent.com/20388082/78075713-6de33580-737b-11ea-951f-d5610ac1004b.png)

I would like to use `comunicacoes` in the search
![IssueBroot3](https://user-images.githubusercontent.com/20388082/78075721-70de2600-737b-11ea-810d-bffbe1477bdf.png)

**Comment by Canop** [comment]
Working on it.

**Comment by Canop** [comment]
One of the problems here is when the filesystem doesn't normalize the file name (ie when "comunicações" can be 14 chars instead of 12 chars, depending on how you got the file).

Normalizing all names would be costly.

**Comment by fsmiamoto** [comment]
I see, guess it isn't worth it then.

Since these names with diacritics are a large minority, I would rather type the characters than lose performance for all the rest.

Or maybe I should just probably avoid naming things with diacritics haha

**Comment by Canop** [comment]
I think I'll experiment and maybe hide the feature behind a flag. Performance issues are very dependent on your configuration and usage and some people (like me) almost never see any slowness while some other ones (who search from the root of a slow disk) frequently experience it.

It's also possible normalization isn't usually needed, as it depends how files are created. Could you check whether your file names with diacritics are normalized ? Do you know how to do this ?

**Comment by fsmiamoto** [comment]
Not quite sure actually, could you give some directions?

**Comment by Canop** [comment]
I decided to postpone this feature. For future reference it would involve:

1) [normalizing](http://www.unicode.org/reports/tr15/) the searched strings (filenames) while keeping links from the resulting chars to their positions in the original strings (normalization can merge chars). Keeping track of the merges is necessary to show the match position and isn't provided by any library I know. This is probably the biggest problem.

2) lowering the chars

3) remove diacritics

The problem can be made easier by not supporting *all* chars (assuming we do nothing wrong on the other ones). Only a small subset of the BMP need change.

I've made [a small experimental library](https://github.com/Canop/secular/blob/master/src/lib.rs#L16) to deal with 2 and 3 (in the scope of broot) but the hardest problem is 1.

I might also write a quite simpler solution not doing the normalization or doing a DIY one but this middle ground would have non optimal matches.

I'm not sure there are a lot of potential users for any of the two possible versions.

**Comment by Canop** [comment]
I just pushed a new "remove_diacritics" branch which doesn't do normalization but solves most cases anyway.

![image](https://user-images.githubusercontent.com/617006/78500702-55e32b80-7758-11ea-99b9-3fb4b54d4f3d.png)

The main reason it's still in a separate way is the performance concern. I had to remove a few optimizations and I'm looking at where I can improve the scoring speed.

**Comment by Canop** [comment]
Mostly solved by https://github.com/Canop/broot/commit/4379039a665bbc4d80ab5b65b184a673c0515549

**Comment by Canop** [comment]
![image](https://user-images.githubusercontent.com/617006/78670286-ce272980-78dd-11ea-819e-4eb0a3eea847.png)

**Comment by Canop** [comment]
@fsmiamoto feel free to reopen and/or comment if you find problems

**Comment by fsmiamoto** [comment]
@Canop 
Looks awesome, I'll definitely test it and give feedback if I find any issue.
Took the opportunity to learn more about Unicode and now I think I understand how this is not as trivial as it may look.
Thanks for the awesome work!
