### ISSUE TITLE
Version 0.13.5 doesn't work on Windows 10

### ISSUE THREAD

**Issue by sesameguy** [Canop/broot#217]
OS: Windows 10
Version: 1909

1. the below error message is shown when terminal is not **Administrator**
``
IO Error :  (os error 1314)
``
but it is ok when opened with **Administrator**

2. cannot open broot, the below message keep showing
``
Broot should be launched using a shell function (see https://github.com/Canop/broot for explanations).
Can I install it now? [Y n] Y
Writing br shell function in ~\AppData\Roaming\dystroy\broot\data\launcher\bash\1.
Creating link from ~\AppData\Roaming\dystroy\broot\config\launcher\bash\br to ~\AppData\Roaming\dystroy\broot\data\launcher\bash\1.
I found no sourcing file for the bash/zsh family.
If you're using bash or zsh, then installation isn't complete:
the br function initialization script won't be sourced unless you source it yourself.
``

**Comment by Canop** [comment]
I don't have any Windows machine to check but I think broot needs administrator rights at first launch to create its preference file.
