### ISSUE TITLE
Release linked against libmusl

### ISSUE THREAD

**Issue by juanfcocontreras** [Canop/broot#218]
It would be really great if there was a linux-libmusl release to use in older distributions (common in scientific clusters, such as Centos 7 with glibc 2.17) or alpine containers.

**Comment by Canop** [comment]
No objection. If somebody's willing to prepare this it would be easier for me.

**Comment by juanfcocontreras** [comment]
Thanks @Canop.Thank you very much. In fact, my knowledge of Rust is at the user level, not at the development level, so I'm sorry I'm not much help. I use other tools developed with Rust that have incorporated this kind of releases.

I have found this official documentation about it and it doesn't seem particularly complicated to follow:

[MUSL support for fully static binaries](https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html)

Thank you very much in advance!

**Comment by FallenWarrior2k** [comment]
So, I just tried building the latest master against musl, and it compiled without a hitch and seemed to work as expected from a quick check as well. The product is a fully statically linked binary that's roughly 200 kB larger than the GNU build (5.1 vs 5.3 MiB).
However, after a pass with `strip --strip-unneeded`, the musl binary is actually smaller at 3.5 MiB, with the GNU version being 3.6 MiB.

As for how I did it, if anybody's wondering or wants to do it themselves, I did `rustup target add x86_64-unknown-linux-musl` to install the necessary tooling on the Rust side, installed my distro's musl package (`community/musl` on Arch), and then did a `cargo build --release --target x86_64-unknown-linux-musl`.

**Comment by juanfcocontreras** [comment]
> So, I just tried building the latest master against musl, and it compiled without a hitch and seemed to work as expected from a quick check as well. The product is a fully statically linked binary that's roughly 200 kB larger than the GNU build (5.1 vs 5.3 MiB).
> However, after a pass with `strip --strip-unneeded`, the musl binary is actually smaller at 3.5 MiB, with the GNU version being 3.6 MiB.
> 
> As for how I did it, if anybody's wondering or wants to do it themselves, I did `rustup target add x86_64-unknown-linux-musl` to install the necessary tooling on the Rust side, installed my distro's musl package (`community/musl` on Arch), and then did a `cargo build --release --target x86_64-unknown-linux-musl`.

Could you share the binary release? I don't develop in Rust and I don't know how to compile it by myself.

**Comment by FallenWarrior2k** [comment]
Here you go. You can verify the signature against the key [0x9C301DF4E151C69E](http://keys.gnupg.net/pks/lookup?search=0x9C301DF4E151C69E&fingerprint=on&exact=on&op=get). And here's a link to a recent [commit](https://github.com/FallenWarrior2k/eslint-config/commit/e7595bde8fd13aa5b9196c907925a0e328de7673) I signed with that key, to show that I'm actually using it.

[broot-musl.zip](https://github.com/Canop/broot/files/4530463/broot-musl.zip)

**Comment by Canop** [comment]
Note: the reason I didn't include libmusl in my official build process is that I lamentably failed in my attempt to install the musl env in a reasonable time.

**Comment by juanfcocontreras** [comment]
> Here you go, @juanfcocontreras. You can verify the signature against the key [0x9C301DF4E151C69E](http://keys.gnupg.net/pks/lookup?search=0x9C301DF4E151C69E&fingerprint=on&exact=on&op=get). And here's a link to a recent [commit](https://github.com/FallenWarrior2k/eslint-config/commit/e7595bde8fd13aa5b9196c907925a0e328de7673) I signed with that key, to show that I'm actually using it.
> 
> [broot-musl.zip](https://github.com/Canop/broot/files/4530463/broot-musl.zip)

Thank you so much!

**Comment by juanfcocontreras** [comment]
> Note: the reason I didn't include libmusl in my official build process is that I lamentably failed in my attempt to install the musl env in a reasonable time.

I hope you can get it without wasting too much time in the future. Thanks a lot anyway.

**Comment by Canop** [comment]
Done, thanks to cross. The next release will include this.
