### ISSUE TITLE
No 'touch' command?

### ISSUE THREAD

**Issue by thorlucas** [Canop/broot#219]
There appears to be no way to `touch` a file within Broot. Only to create and immediately launch this in the editor. This is problematic because

1. Sometimes I need to just create a file, not edit it

2. I don't want to launch the file by itself in the editor — I want to have the whole project folder open.

Thanks,

Thor

**Comment by Canop** [comment]
You can add your own commands to broot.

Add this in the conf.toml file:

```
[[verbs]]
name = "touch"
invocation = "touch {new_file}"
execution = "touch {directory}/{new_file}"
leave_broot = false
```
