### ISSUE TITLE
Fuzzy match does not work on alphanumeric input

### ISSUE THREAD

**Issue by fkjogu** [Canop/broot#22]
Given a file `abcdefg.123`, typing `ab3` does not match anything.

Steps to reproduce:
```
# mkdir /tmp/test
# cd /tmp/test
# touch abcdefg.123
# broot
ab3
```

**Comment by Canop** [comment]
I confirm the bug.
This is weird.

**Comment by Canop** [comment]
In fact it's related to the length of the match compared to the size of the pattern.

I'll change this part of the pattern matcher and ensure there's a match (with a low score).

**Comment by fkjogu** [comment]
On a different tangent, it might be interesting to use something similar to [quickcheck](https://github.com/BurntSushi/quickcheck) to fuzz the matcher a bit. Generate random strings and use a random subset of it as a pattern to match against.

Just an idea. :smiley:
