### ISSUE TITLE
Consecutive verb execution with a single command is no longer possible

### ISSUE THREAD

**Issue by Ryujinra** [Canop/broot#221]
In the past, I used to be able to define an alias to `broot` like so: `br {query} :focus {optional_verbs}`, and broot would focus the first selected directory and then execute the optional verbs afterwards. This was useful in a number of different scenarios when using `--cmd` to string together verb executions, but this doesn't work currently.

Now, only the first verb is executed. In the example above, `broot` will complain that `:focus does not take arguments` if you follow it with any other verb.

This allowed a lot of flexibility when calling `br` with `--cmd`, but I imagine it could do interesting things in verb definitions as well if we could, for instance, put multiple previously defined verbs in the `execution` section of a new verb, so that `broot` would execute them sequentially when the composite verb was called.

**Comment by Canop** [comment]
I'm not sure I understand your whole question.

You might have missed that commands given to `--cmd` are now semicolon separated (see https://github.com/Canop/broot/blob/master/CHANGELOG.md#v0120---2020-01-19).

![image](https://user-images.githubusercontent.com/617006/78978523-35312200-7b1a-11ea-8163-555d1a81e15a.png)

Does that answer ?

**Comment by Ryujinra** [comment]
Indeed it does. That's what I get for not using broot more frequently lately! Thanks for the tip.

**Comment by Canop** [comment]
Broot is a big program and it's not easy to make everything obvious. Any idea for the documentation, separate blog posts, tweets, or other pieces of documentation would be welcome.

**Comment by Ryujinra** [comment]
I didn't mean any offense by that comment by the way! It is, of course, on me and anyone else to read and keep up with the documentation for the use of evolving software; I should have checked there first, in fact, before posting this particular issue.

I think the documentation is more than sufficient, as is; maybe a built-in message on first-run after an update which makes any major changes to syntax could be useful at some point to bring attention to such changes, but I'm not sure anything else would really catch enough attention to warrant the effort, probably.
