### ISSUE TITLE
[skin] selected_line foreground does not override other styles

### ISSUE THREAD

**Issue by YohananDiamond** [Canop/broot#222]
The `selected_line` style in the `[skin]` section of the broot config file doesn't override styles it was supposed to override, like `default`, `file` and `directory`.

**To reproduce**, replace the contents of conf.toml with:
```
[skin]
default = "white black"
selected_line = "black yellow"
```

What is seen is this:
![image](https://user-images.githubusercontent.com/23298480/79256302-26ba7180-7e5e-11ea-9e8a-4f2f9f310397.png)
In the image, the highlighted line (with yellow background) was supposed to have a black foreground (as specified in `selected_line`), but it doesn't, for some reason.

Here's a comparison of what happens and what should happen:
![image](https://user-images.githubusercontent.com/23298480/79257739-7306b100-7e60-11ea-9521-7a83e837274d.png)

**Configuration:**
 - OS: Arch Linux
 - Kernel: Linux 5.5.11-arch1-1
 - Architeture: x86-64

**Comment by Canop** [comment]
The problem here is that if I don't ignore the selection foreground then there's no difference between different types of lines (directories, aliases, simple files).

I guess more skin entries should be defined.
