### ISSUE TITLE
Broot breaks on exotic file names (newline and tab verified, possibly more)

### ISSUE THREAD

**Issue by FallenWarrior2k** [Canop/broot#223]
**Describe the bug**
When using broot to view directories that contain files with exotic names, various issues occur, such as wrong colours and screen positions not getting cleared properly.

**To Reproduce**

1. Create a file with a tab or newline character in the file name using e.g. `touch ba$'\n'r`.
2. Open broot. You will notice how the background after the place where the newline character should've been has the wrong color, presumably the terminal's default background color.
3. Create a file that comes before the previously created file in your preferred sorting order, e.g. `touch asdf`.
4. Open broot again, but this time search for (part of) the exotic name. You will notice how part of the name of the file from the line above will "bleed" into the line of the file with the exotic name.

**Expected behavior**
The screen should not be "corrupted" under any circumstances. How to handle such problematic characters is not my decision to make, but I think they should be handled in _some_ way.

**Screenshots**
Not a screenshot, but an Asciicast: https://asciinema.org/a/8nrRk0MhEVkt2O5O8kjgKctRX

**Configuration:**
 - OS: Arch Linux (last `pacman -Syu` at 2020-04-23T01:10:00Z)
 - Broot version: 0.13.5
 - Relevant configuration items: `default_flags = ghI` is the only change I've made to the default config

**Comment by Canop** [comment]
Problem confirmed.

**Comment by Canop** [comment]
Drawing is more robust now, and exotic file names shouldn't break more than their line (and only in their panel).
It's probably not enough but I've also added a filter to remove \n from display.
