### ISSUE TITLE
<F2> operates differently on symlinked files from <Enter> when configured to $EDITOR

### ISSUE THREAD

**Issue by max-sixty** [Canop/broot#226]
**Describe the bug**
Hitting an alias to `edit` on a symlinked file does not open the file in an editor, whereas hitting the alias on a normal file, or hitting `F2` does open the file in an editor.

I have checked this a couple of times but it's not impossible I made a mistake / there's an error with my configs.

**To Reproduce**
- Add the following config entry:
```
[[verbs]]
invocation = "edit"
key = "enter"
execution = "$EDITOR {file}"
```
- Create a symlink to a file
- Find the symlink with broot
- Hit `Enter`
- Nowt
- Hit `F2`
- You get an editor

Now retry on a non-symlinked file. It should open with `Enter`

**Expected behavior**
Operate the same on any alias

**Screenshots**

<img width="643" alt="image" src="https://user-images.githubusercontent.com/5635139/81724551-68c4dc00-9439-11ea-8141-0455b44d1ffe.png">
<img width="552" alt="image" src="https://user-images.githubusercontent.com/5635139/81725102-35368180-943a-11ea-9712-b7e4d1992090.png">

**Configuration (please complete the following information):**
- OS: MacOS
- Version 0.13.6
- Relevant configuration items:
```
[[verbs]]
invocation = "edit"
key = "enter"
execution = "$EDITOR {file}"
```

**Additional context**
Thank you for such an awesome library!

**Comment by Canop** [comment]
Thanks for the report.
I postpone the resolution of this problem because I'm working on the big "panels" branch but I'll definitely look at it.

**Comment by Canop** [comment]
I could reproduce the problem with 0.13.4 but not with the current master (which follows a rewrite of half broot). So I think it's fixed. Please reopen if you manage to reproduce on master.
