### ISSUE TITLE
Version 0.13.6 doesn't work on Windows 10

### ISSUE THREAD

**Issue by GregWoods** [Canop/broot#227]
* Using the binary for windows
* Using an Elevated Command Prompt
* Windows 10 1909

```shell
Broot should be launched using a shell function (see https://github.com/Canop/broot for explanations).
Can I install it now? [Y n]
y
Removing C:\Users\gregw\AppData\Roaming\dystroy\broot\data\launcher\bash\1.
Writing br shell function in C:\Users\gregw\AppData\Roaming\dystroy\broot\data\launcher\bash\1.
Removing C:\Users\gregw\AppData\Roaming\dystroy\broot\config\launcher\bash\br.
Creating link from C:\Users\gregw\AppData\Roaming\dystroy\broot\config\launcher\bash\br to C:\Users\gregw\AppData\Roaming\dystroy\broot\data\launcher\bash\1.

I found no sourcing file for the bash/zsh family.
If you're using bash or zsh, then installation isn't complete:
the br function initialization script won't be sourced unless you source it yourself.
```

* I have also tried installing from the crate, but it is unclear whether this is supported in Windows
* I have also tried the Linux installation on Ubuntu from Windows Subsystem for Linux (WSL)

If there is anything else I can add, just ask.

**Comment by Canop** [comment]
This output looks normal for the first run. Does it do the same every time ?

**Comment by GregWoods** [comment]
yes.
I'm also slightly confused about the reference to bash. I have bash in WSL, but not in Windows itself

**Comment by Canop** [comment]
The best in your case, as you don't use bash, zsh, or fish, is probably to try tell broot that you don't want the installation. This is normally done using

    broot --set-install-state refused

Please tell me if it works.

**Comment by muellerto** [comment]
Seems to work in my case but leaves broot in a mode where for instance cd doesn't work. (Why??? What's the problem with this simple directory change?)

**Comment by Canop** [comment]
broot alone can't do a `cd`. For this you need the `br` shell function (and launch it).

(not sure if I answered you)

**Comment by GilRtr** [comment]
Even when run inside WSL with the bash function added manually it doesn't work since the output is a windows path and bash can't work with that (I'm assuming that's the issue).
`C:\Program Files (x86)\` in cmd
would be `/mnt/c/Program\ Files\ \(x86\)/` in wsl

**Comment by GilRtr** [comment]
Actually, the error must be somewhere else since it originates from the code.
`IO Error : "The system cannot find the path specified. (os error 3)"`
This doesn't happen when I run with the powershell function but I can't use that one inside WSL.
I think WSL needs to use some sort of Frankenstein function
