### ISSUE TITLE
Make date/time format configurable

### ISSUE THREAD

**Issue by sschwarzer** [Canop/broot#229]
Thank you for broot! :-)

**Did a discussion occur before?**

I haven't found anything on this feature on https://dystroy.org/broot/, in the configuration file or in the issue tracker.

**Is your feature request related to a problem? Please describe.**

I wouldn't say it's a problem, but it would improve the user experience for me and probably for others.

**Describe the solution you'd like**

I'd like to be able to configure the date and time format that's used for `:d` inside broot. The format seems to be hardcoded to `YYYY/MM/DD HH:MM`, but I'd like to use ISO 8601 date/time format (i. e. `YYYY-MM-DD HH:MM`, which I have set almost everywhere in my system (where it's possible).

For example, the current display is like this:
```
2020/05/17 14:54 bin
```
and I'd like to have
```
2020-05-17 14:54 bin
```

Other users may have other preferences.

Here are a few ideas how the date/time format could be set:
- environment variable `LC_TIME` (in my experience, this may be unreliable for ISO 8601 formats)
- custom environment variable for broot
- setting in configuration file (would make most sense from my point of view)
- command line option

The format could be:
- percent format-based, as in `man 3 strftime`
- locale string, as used for `LC_TIME` (again, often unreliable for ISO 8601 formats)

I suppose setting the formats in the configuration file in percent-based formats would make most sense, but of course I'm open for other suggestions that I may have overlooked.

**Describe alternatives you've considered**

I haven't found a workaround to set the date/time format. The current format is kind of acceptable for me because at least the order YYYY, MM, DD that broot uses is the same as in ISO 8601. So it's not *too* confusing.

**Additional context**

- If you do *not* want to make the formats configurable for whatever reason, I'd suggest using the ISO 8601 formats, for example `2020-05-17 15:10`. However, this *may* be a problem for backward compatibility if someone uses `broot` in scripts and relies on the format.

- Although the current format has the same year/month/day order as the ISO format and is thus "close", using the ISO format is probably less confusing because the supposed target audience of broot would be more familiar with the ISO format. For example, with the current date format, I had to look at a few dates to be sure that the order was month/day, not day/month. Theoretically, some users may also check this order if you used hyphens instead of slashes, but intuitively I'd assume it's ISO format.

- Regardless of ISO format or not, hyphens instead of slashes in my opinion make it a bit easier to "parse" the date visually.

Please let me know what you think.

Do you have any questions?

**Comment by Canop** [comment]
Format follows https://docs.rs/chrono/0.4.11/chrono/format/strftime/index.html

Example:

    date_time_format = "%Y-%m-%d %R "

Please let me know if it's OK for you.

**Comment by Canop** [comment]
I'm still open to opinions, votes, etc. regarding the default choice of "/" or "-" (I understood the opinion of @sschwarzer )

**Comment by sschwarzer** [comment]
> Format follows https://docs.rs/chrono/0.4.11/chrono/format/strftime/index.html
> 
> Example:
> 
> ```
> date_time_format = "%Y-%m-%d %R "
> ```

This would go into the `conf.toml`, right?

> Please let me know if it's OK for you.

Yes, at least I can't think of anything better. :-)

**Comment by Ckln** [comment]
> 
> 
> I'm still open to opinions, votes, etc. regarding the default choice of "/" or "-" (I understood the opinion of @sschwarzer )
The default being ISO make more sense to me.

**Comment by Canop** [comment]
@sschwarzer Yes, this goes in the conf.toml file but it only works on the current master, it hasn't been released yet.
