### ISSUE TITLE
Allow verbs to use the 'fuzzy' text

### ISSUE THREAD

**Issue by fkarg** [Canop/broot#231]
My main use case for broot is actually within a short shell script navigating to my 'general reference file system', where I put notes about all kind of stuff, like books to read and whatnot. Effectively it is a repository with five folders and about 70 text files distributed among them.

So anyway, the fuzzy search is a real quality of life improvement for navigation there.

**Problem**:
I sometimes don't know in which file something is. In this case I need to manually navigate to my general reference system and grep (more specifically, `rg`) for what I am looking for. It's only txt files.

**Solution**:
It would be awesome to allow a verb execution not using '{file}', since 1) I do not know which file it is in yet, 2) a file with the one keyword I want to search for does most likely not exist.

I'm not sure how exactly `mkdir` and others use it (where it seems possible to 'input' something yourself), maybe a similar way would work here - though based on my understanding of the documentation this is currently not possible. Please correct me if I jumped to conclusions here.

My ideal verb definition would then look something like this:
```
[[verbs]]
invocation = "grep"
shortcut = "rg"
execution = "rg {fuzzy}"
```

**Fancy Solution**:
Even more awesome would be a 'search' mode, showing matches within files more or less like files in directories are shown, with a line number and the `grep`/`rg` match, showing only these files where matches are still present, and allowing easy selection of  file in this way (instead of the filename fuzzy search itself).

**Comment by Canop** [comment]
I don't understand this issue. Can you come to the chat and explain me ?

https://miaou.dystroy.org/3490

**Comment by fkarg** [comment]
Thanks for the Help!

Turns out that it already is possible, or rather, the missing link was that it is possible to define parameters in the invocation. This works:

```
[[verbs]]
invocation = "grep {searchargs}"
shortcut = "rg"
execution = "rg -ie {searchargs} {directory}"
```

**Comment by runiq** [comment]
> ```toml
> [[verbs]]
> invocation = "grep {searchargs}"
> shortcut = "rg"
> execution = "rg -ie {searchargs} {directory}"
> ```

This one should definitely go in the [cookbook](https://github.com/Canop/broot/issues/152) IMHO :)
