### ISSUE TITLE
Documentation about editing config is wrong

### ISSUE THREAD

**Issue by eproxus** [Canop/broot#232]
**Describe the bug**
The documentation [here](https://dystroy.org/broot/documentation/configuration/#opening-the-configuration-file) states:
> The easiest way to read and edit broot's configuration file is to go the help screen (using ?) then to type :os (shorcut for :open_stay).

When doing that on macOS 10.15.4 with iTerm nothing happens.

**To Reproduce**
Open help and type `:os`

**Expected behavior**
The config should be open in an editor. I would also expect the file location to be explicitly documented. It was only through searching of the GitHub issues I found out that the config file is located in `~/Library/Preferences/org.dystroy.broot/config.toml`.

**Configuration (please complete the following information):**
 - OS: macOS
 - Version 10.15.4

**Comment by Canop** [comment]
The fact nothing happens is probably related to a misconfiguration of MacOs' `open` on your system. I'm not sure how to handle that.

The config location is system dependent and is displayed in the help, towards the end:

![image](https://user-images.githubusercontent.com/617006/82793932-fd83fc80-9e71-11ea-9add-a6d3e58a418c.png)

**Comment by eproxus** [comment]
I'm using broot 0.13.6 installed via Hombrew. Running `open` manually shows me this:

```
$ open ~/Library/Preferences/org.dystroy.broot/conf.toml
No application knows how to open ~/Library/Preferences/org.dystroy.broot/conf.toml.
```

At the very minimum I would expect the documentation to list this file path explicitly so I can open it myself. I now notice that the path is actually printed in the inline help output, perhaps at least this should be documented. Although I would prefer if the actual file location is documented in the online docs.

I would also expect broot to notify me of the error since the command exits with code `1`.
