### ISSUE TITLE
[0.14.1] "Open files without a windowing system" custom enter verb now behaves differently compared with 0.13.6

### ISSUE THREAD

**Issue by bluz71** [Canop/broot#237]
Hello,

Just upgraded to 0.14.1 and there does appear to be a change in behaviour when defining a custom enter verb.

The [documentation for defining a custom enter verb](https://dystroy.org/broot/tricks/#open-files-without-a-windowing-system) whilst avoiding `xdg-open` lists:

```
[[verbs]]
invocation = "edit"
key = "enter"
execution = "$EDITOR {file}"
```

With 0.13.6 hitting enter on a directory navigates/focuses into that directory (remaining in broot) whilst hitting enter on a file will result in the `execution` statement listed above. Good.

With 0.14.1 hitting enter on a directory will spawn the `execution` statement. Not good.

The behaviour in 0.13.6 is much preferred since navigating directories is the core of `broot`. Launching `$EDITOR` on a directory is not desired.

In 0.14.1 hitting enter will always spawn the `$EDITOR`.

Many thanks.

**Comment by Canop** [comment]
It's a consequence of increased configuration capabilities: less behaviors are hardcoded.
And of course it's a problem here.
It looks like I'll have to fast add conditions to verbs, something like

```
apply_to = "file"
apply_to = "directory"
apply_to = "verb-edition"
```

**Comment by bluz71** [comment]
Yes, understandable. 0.14.X is a big release and there will be some behaviour changes to iron out.

Whichever way you go, please update the [Open files without a windowing system](https://dystroy.org/broot/tricks/#open-files-without-a-windowing-system) notes accordingly.

Some back-story: basically in my case `xdg-open` on a file launches GUI Gvim which is desired when double clicking a file in a GUI file manager. But in the command line when running `broot` I want to launch terminal `neovim` when entering a file. The `enter` verb Tip was very useful.

We just need a small tweak to make it be `enter-only-on-a-file`.

Many thanks for a great utility.

**Comment by bluz71** [comment]
@Canop,

Excellent.

Thank you very much for a speedy resolution to this issue.
I am looking forward to 0.14.2 landing in Homebrew.

Best regards.

**Comment by bluz71** [comment]
@Canop,

Just upgraded, and the new feature works very well. Thank you.
