### ISSUE TITLE
Make it possible to disable mouse interaction

### ISSUE THREAD

**Issue by jeberger** [Canop/broot#238]
I never use the mouse to interact with console applications, but I quite often use it to copy-paste text to/from consoles. In broot this doesn't work: attempting to select text with the mouse results in the corresponding line being activated, which opens the folder or the file pointed.

It would be nice if there was a config option to disable mouse interaction so that standard console interactions will work.

**Comment by Canop** [comment]
You can now add this to conf.toml:

```toml
capture_mouse = false
```

**Comment by jeberger** [comment]
Great, thanks!

**Comment by pixelblender** [comment]
In my case this still broken. In my `~/.config/broot/conf.hjson` I've put `capture_mouse: false` and I can't select filename as text. For what it's worth I'm using broot 1.9.4 in xfce4-terminal on Ubuntu 22.04

**Comment by Canop** [comment]
@pixelblender For a reason I doesn't remember, `capture_mouse = false` is currently the wrong syntax. The working one is `disable_mouse_capture = true`.

**Comment by Canop** [comment]
@pixelblender `capture_mouse=false` works in broot 1.10.0
