### ISSUE TITLE
Support emacs-style key binding

### ISSUE THREAD

**Issue by wookayin** [Canop/broot#24]
It would be great to make the app more CLI-friendly. For example,

* <kbd>C-W</kbd>: delete a word
* <kbd>C-U</kbd>: delete a line completely

Reference: https://caiorss.github.io/Emacs-Elisp-Programming/Keybindings.html

Note that many CLI programs that works on a bash/zsh shell are compatible with these keybindings.

**Comment by Canop** [comment]
Yes, I should work on including those, maybe through readline modes, for both vi and emacs styles.

**Comment by dgrisham** [comment]
+1 for vi keybindings. Would also be nice to just be able to set custom keys in general :)

**Comment by derrickcope** [comment]
+1 for "hjkl" keybinds for navigation

**Comment by Canop** [comment]
> +1 for "hjkl" keybinds for navigation

and how would you deal with search ? Right now those keys would filter the tree.

**Comment by derrickcope** [comment]
I would just use "/" to search or filter like in vim or vifm. 
I would love to replace vifm with broot. Seems like this is more light weight.

**Comment by lifranc** [comment]
make sure you dont hard-set those bindings, as not everyone is using qwerty.

**Comment by anuvyklack** [comment]
> > +1 for "hjkl" keybinds for navigation
> 
> and how would you deal with search ? Right now those keys would filter the tree.

Good option to use Ctrl + hjkl like in fzf.  When Ctrl is bind to Caps Lock key it's super convenient.

**Comment by Canop** [comment]
@anuvyklack you can already bind ctrl + hjkl to navigation functions in broot. See  https://dystroy.org/broot/documentation/configuration/#keyboard-key

**Comment by anuvyklack** [comment]
@Canop I've tried but it doesn't work. It seems like a bug. `alt + hjkl' works perfect. But it's not convenient everywhere use ctrl and in broot use alt. 

Is it really a bug? Need I open an issue?

**Comment by Canop** [comment]
I just tried and noticed that ctrl-j seems to be one of those key combinations that my terminals intercepts.

That's the biggest problem usually: when the terminal already handles the chars, it's hard to do anything.

You can open an issue, with the exact configuration you tested which didn't work.

**Comment by fnune** [comment]
```
[[verbs]]
name = "line_down"
key = "ctrl-n"
execution = ":line_down"

[[verbs]]
name = "line_up"
key = "ctrl-p"
execution = ":line_up"
```

I added my own `ctrl-p` and `ctrl-n` by adding custom verbs that just call built-in verbs.

**Comment by Canop** [comment]
@fnune just to be clear: does this configuration works for you ?

**Comment by fnune** [comment]
Indeed it does! I could add keybindings for everything this way, I think.

**Comment by Canop** [comment]
This might help other users. Maybe we'll include it in the [documentation](https://dystroy.org/broot/documentation/configuration/).

**Comment by fnune** [comment]
I think my "name" attribute is superfluous there and key + execution should suffice. But you probably know better :)

**Comment by fnune** [comment]
IMO it is still a workaround. I think a "planned" way of adding keybindings would be more elegant. But this works!

**Comment by Canop** [comment]
What could be a "planned" way ? A part of the config to uncomment maybe ? I don't want to have users opt-in for some key bindings in a whole and not being able to change them.

**Comment by fnune** [comment]
I deleted the previous comment because I thought a bit more about it: I think the current options are totally fine.

**Comment by dhovart** [comment]
You could maybe use https://github.com/kkawakam/rustyline ?
Thanks for your work, it's a really useful tool.

**Comment by gubikmic** [comment]
Hmm, @fnune adding your config, broot complains:

    Invalid [[verbs]] entry in configuration
    Missing invocation
    Invalid [[verbs]] entry in configuration
    Missing invocation

**Comment by jwr** [comment]
Just wanted to mention that I tried broot, and really liked it, but the first thing I wanted to do as a long-time Emacs user was use Control-N and Control-P to move down/up.

The next thing I expected (I do not know why?) was being able to compose a command line by pressing Command/Control/Alt-Enter and having the currently selected file/directory name copied to the end of a command line. I guess that's because I am old enough to have Norton Commander in my finger memory.

**Comment by Canop** [comment]
@jwr It's not clear if you noticed, but ctrl-n / ctrl-p is easy (see up if necessary).

Regarding the second part, I'm not sure I follow you (I don't remember Norton Commander well enough, I guess it's Alzheimer). Are you after the :print_path verb and mapping it to the desired key shortcut (https://dystroy.org/broot/documentation/configuration/#verbs-shortcuts-and-keys) ?

**Comment by jwr** [comment]
@Canop I thought the setup above didn't work based on the comments. Now I wanted to try it, but I am ashamed to admit I can't figure out where the configuration file is supposed to live (Mac OS). I looked at https://dystroy.org/broot/documentation/configuration/#opening-the-configuration-file but it only mentions "conf.toml" and says the location is OS-dependent. The method with typing :os from help doesn't seem to work for me (verb not found "os" and when trying :open_stay nothing happens — am I supposed to enter the name of the file now?).

As for :print_path, no, this is not quite what I meant. In Norton Commander you could start typing a command line (say type "mv", and use Ctrl-ENTER to append selected file or directory names one by one, so you would build up "mv file1.txt file2.txt some_dir" and then execute it with ENTER once you were ready). I realize broot has a different UI concept, but this could be something to think about.

**Comment by Canop** [comment]
@jwr when you type ?, you're normally shown the help screen, which displays the path to the config file.  

Regarding the other shortcuts, like the ones to navigate into the input, I have no objections against adding a few other verbs even if rarely used but please make sure you've read the documentation on https://dystroy.org/broot/documentation/usage/ and https://dystroy.org/broot/documentation/configuration/ )

Last point understood, thanks.

**Comment by jwr** [comment]
@Canop Thanks, now I can see the config file path, my terminal colors made it difficult to see. I also feel silly for not seeing it earlier.

I will do my best to configure the Emacs keybindings and come back with suggestions of things that might be added.

**Comment by fnune** [comment]
> Hmm, @fnune adding your config, broot complains:
> 
> ```
> Invalid [[verbs]] entry in configuration
> Missing invocation
> Invalid [[verbs]] entry in configuration
> Missing invocation
> ```

@gubikmic It worked for me. Maybe it's referring to a missing `invocation` attribute like it appears on other verbs:

```
[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"
```

Maybe you can try adding that?

**Comment by Canop** [comment]
invocation was needed previously but isn't in recent versions of broot.

**Comment by partiallyordered** [comment]
@Canop it's taken a few brushes but I'm starting to find myself incorporating broot into my workflow. It's a pleasure to use when I have the impetus to do so, thank you for developing it.

I came across this issue looking for the exact same keybindings as the original poster: `c-w` and `c-u`. I was able to map `ctrl-w` to `:input_del_word_left`. The documentation doesn't seem to indicate any input verb to clear the input. I tried to map `ctrl-u` to `:back`, noticing only that `Esc` was default mapped to `:back`, but having used that and it having not done as I expected, it seems as though `Esc` performs `:back` and the additional function of clearing the line. I'm a total amateur broot user so I might be misunderstanding something. Just wondering if there's a way to get the `ctrl-u` functionality so I can bring my muscle memory :grin:

**Comment by Canop** [comment]
There's currently no internal you could use to clear the input. I'll add one.

**Comment by partiallyordered** [comment]
That would be great, I'd really appreciate that. No rush, no pressure, take it easy. Thank you again!

**Comment by Canop** [comment]
I've added the `:input_clear` internal which may be mapped this way:

		{
			key: ctrl-u
			internal: ":input_clear"
		}

It will be officially available in 1.5.0 which should be released in a few hours

**Comment by Canop** [comment]
Broot 1.5.0 just released

**Comment by partiallyordered** [comment]
That's amazing, thank you for your super-quick response. Now to get it in my env.. :grin:. Thanks again.
