### ISSUE TITLE
Broot install files fail to load in ubuntu 20.04

### ISSUE THREAD

**Issue by StewAlexanderACC** [Canop/broot#243]
Cannot seem to get broot to install on 20.04

The files I see don't work @Canop

**Comment by Canop** [comment]
I'll need more details. Please come to the chat and tell me exactly what you tried.
https://miaou.dystroy.org/3490

**Comment by StewAlexanderACC** [comment]
Posted to chat channel details on what I did

**Comment by Canop** [comment]
Sorry but "something wasn't available" isn't precise enough. What wasn't available ? And did you chmod +x the file you downloaded on windows before copying it to your linux VM ?

**Comment by StewAlexanderACC** [comment]
Ok, I understand that, I'll attempt to get the output of the failed cargo install.

Anyway, using your advice I changed the broot file copied over to an executable, and it using ./broot it installed (that's on me, sorry for not converting the thing to an executable),  but now how I do use it?

Typing ```br``` gives me an error, apparently it expanded br to "broot" but it says its not found, see the screen grab:

![image](https://user-images.githubusercontent.com/48565067/86635651-58486200-bfa1-11ea-9628-ddb8ea99294a.png)

**Comment by StewAlexanderACC** [comment]
Looking under /bin or /sbin I don't see anything there, so do you have a log I can pull something from?

**Comment by Canop** [comment]
The first time you launch broot, it asks your authorization to install the `br` shell function (which makes the :cd command possible). If you refused the installation, you may
* ask for it to be installed by launching `broot --install`
* launch `broot` instead of `br`

**Comment by StewAlexanderACC** [comment]
Ok, so I got it to work by using ./broot from the install directory:

![image](https://user-images.githubusercontent.com/48565067/86636918-dd804680-bfa2-11ea-9e7b-a90d177ce7ab.png)

**Comment by Canop** [comment]
You can move the executable to a more suitable location, for example /usr/local/bin or ~/.local/bin

**Comment by StewAlexanderACC** [comment]
![image](https://user-images.githubusercontent.com/48565067/86637288-4a93dc00-bfa3-11ea-9c66-b702d8184935.png)

Now it works, the onus is on me, I apologize -- but your assistance is appreciated.
