### ISSUE TITLE
directoriy not expanded

### ISSUE THREAD

**Issue by nkh** [Canop/broot#245]
**Describe the bug**
/home/nadim/no_backup/pbs_tests
 ├──generated_pbs_project
 └──short
    └──_out_nadim
       ├──1.o.trigger_dependencies.pbs_log
       ├──2.o.trigger_dependencies.pbs_log
       ├──3.o.trigger_dependencies.pbs_log

 Hit enter to focus, alt-enter to cd, or a space then a verb
gen                                                          

**To Reproduce**

**Expected behavior**
gen selects a directory, the directory has files in it but is not exxpanded although there is plenty room.

I can send a script to reproduce the file structure is needed.

**Screenshots**
see above

- Relevant configuration items

**Additional context**

**Comment by Canop** [comment]
The script, broot version, and maybe a [log](https://dystroy.org/broot/community/#log) would be welcome. I don't really see what happens here.

If necessary come to the chat: https://miaou.dystroy.org/3490

**Comment by Canop** [comment]
Closing as the problem (a misunderstanding about how broot filtering works) has been solved in the chat.
