### ISSUE TITLE
tmux - search letters are not highlighter in the same manner

### ISSUE THREAD

**Issue by nkh** [Canop/broot#248]
**Describe the bug**

see attached snapshot

matching lines are displayed differently, some have the search letters highlighted other have the letter and the background highlighted.

it can be a single line in the page or multiple lines showing this behavior

**To Reproduce**
search with p/search

**Expected behavior**
all lines should look the same

**Screenshots**
![Screenshot_20200707_092601](https://user-images.githubusercontent.com/45409/86803744-8e0b4a80-c076-11ea-8410-df3317bc0863.png)

![Screenshot_20200707_173214](https://user-images.githubusercontent.com/45409/86805313-10e0d500-c078-11ea-8e2c-16b7f3fe89f8.png)

**Configuration (please complete the following information):**
 - OS: linux-kde-konsole-tmux

**Comment by Canop** [comment]
This is very probably related to tmux. I'll have a look.

**Comment by Canop** [comment]
I also reproduce weird patches of grey background when using broot inside tmux. They're not on the same spots and I have no idea where they come from.

**Comment by Canop** [comment]
@nkh A workaround which works for me is to define a skin (you can uncomment the example one which is in your conf.toml file) and remove the Italic. I suspect that for some people removing the "bold" too could be necessary.

Can you please confirm that removing Italic (and bold ?) is a valid workaround for you ?

**Comment by nkh** [comment]
I will test later and let you know if it works

Honestly this is the least problem I have with broot (I am new at it, please be patient)  but I though you'd want to present a consistent UI. 

indeed ANSI colors are difficult to get right everywhere

**Comment by Canop** [comment]
@nkh Did you check this ? I'd like to be clear on what works or not on tmux
