### ISSUE TITLE
not repeating paths

### ISSUE THREAD

**Issue by nkh** [Canop/broot#249]
**Did a discussion occur before?**
no

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
less repetition, or an option 

want:
path
    sub path
       sub path

got:

path
   path/sub path
       path/sub path/sub path

**Additional context**
![Screenshot_20200707_174452](https://user-images.githubusercontent.com/45409/86807072-cc563900-c079-11ea-9b17-2914da97c068.png)

**Comment by Canop** [comment]
This is only present when you search on subpath instead of names, for example with the `p/` prefix (I guess your search was `p/no_pbs2`).

The reason for this presentation is to show you the matching character in every found subpath.

**Comment by nkh** [comment]
the matching characters can be highlighted in the path components and it would make more sense, even if it is more difficult to implement

the example above was still ok to read but when multiple long paths match you get a large blob of unreadable text.

**Comment by Canop** [comment]
> the matching characters can be highlighted in the path components

The matching characters in a path element aren't the same for all the children.

If you search `p/aaa`, you'll have

**a**/**aa**/rkjrekjre
and
a/ezzee/rerer/**aaa**

**Comment by nkh** [comment]
And how the highlighting information from different from?

**a**
  **aa**
     rkjrekjre

and

a
   ezzee
     rerer
        **aaa**

**Comment by nkh** [comment]
the example you give is for a single match when multiple files match under a directory the full path for each entry is bloated imo.

it may be preferable as you wrote above when it is a single entry as it take 1 line instead for 3

github, IE, displays a single line if there is a single match but will display the directories if multiple matches are found below

**Comment by Arcadio-Buendia** [comment]
Is there a way to not display the entire path?
After the last update, I get the whole path for each file, and it has become a problem. The behaviour was absent earlier.

**Comment by Canop** [comment]
@Arcadio-Buendia This change is related to the change of default search mode.

To revert to the previous behaviour, modify your configuration file, find the `search_modes` section and change it to

```
        search_modes: {
            <empty>: "fuzzy name"
	    "/" : "regex name"
        }
```

More info:
* https://dystroy.org/broot/input/#the-filtering-pattern
* https://dystroy.org/broot/conf_file/#search-modes
* https://github.com/Canop/broot/blob/master/CHANGELOG.md#v140---2021-05-11

*I miss an efficient way to tell people about those changes...*

**Comment by Arcadio-Buendia** [comment]
Thank you.
"I miss an efficient way to tell people about those changes..."
If this is any help:
I did look at the release notes, but didn't think the first point was causing my problems. I must have forgotten all about it by the time I saw this thread or skimmed over the documentation. I didn't know where to look in the documentation,
