### ISSUE TITLE
Use LS_COLOR not own colors for elements

### ISSUE THREAD

**Issue by nkh** [Canop/broot#250]
If I am not wrong there's already a library in rust for that
![Screenshot_20200708_092214](https://user-images.githubusercontent.com/45409/86889746-8c846580-c0fc-11ea-8fc9-47fdc46024ec.png)

**Comment by Canop** [comment]
The problem isn't reading LS_COLORS. It's that broot needs a lot of colors and nuances, for example to show the difference between a focused and unfocused tree and LS_COLORS was build for `ls`, not for complex TUI.

**Comment by nkh** [comment]
That's one difference for the TUI but a large difference for the user who now has to guess what the files are. Some of us spend time tweaking their  LS_COLORS to get the most of the terminal. Windows users are probably happy to get colors altogether (given the subpar explorer they us) but I'd be surprised if not all linux users are not rising a brow.

if there is a possibility to hook some script (and I mean a shell script) to do the coloring I'll be happy to make my own.

**Comment by Canop** [comment]
There are at least two parts here:

1) trying to build a whole skin from the few colors defined in LS_COLORS along with the default foreground and background colors, hoping they're not too random

2) giving extension/type based colors to file entries

For the 1, I could probably do it but I'm not sure of how to ensure there aren't too many users ending with something unreadable. I'm not sure asking at launch would be efficient enough. 

For the 2, I could probably just have a setting in conf (and I could ask at first launch what value to set in the conf file broot writes).

**Comment by nkh** [comment]
both sound like viable workaround to using LS_COLORS

I could have a look at the skin format, maybe it's possible to generate it from my LS_COLORS if the format is simple enough

**Comment by Canop** [comment]
I'd be interested in such a script, either as a solution for other people or as a prototype for an optional skin initialization on install.

**Comment by nkh** [comment]
there need to be a way to match file extension in the skin on top of these

file = "gray(18) None / gray(15) None"
directory = "ansi(208) None Bold / ansi(172) None bold"
exe = "Cyan None"
link = "Magenta None"

**Comment by Canop** [comment]
There's now a [ext-colors] section in the conf.toml file.
