### ISSUE TITLE
Very slow with network shares.

### ISSUE THREAD

**Issue by Mo0dy** [Canop/broot#251]
Broot is unusably slow (> 10s to fuzzymatch one character) when a network share (sambashare) is mounted.

**Comment by Canop** [comment]
Broot is slow when it searches a slow volumes like a mounted one.

The best solution is usually to prevent automatic enter of this volume: https://dystroy.org/broot/conf_file/#special-paths

This doesn't prevent entering it: you may still select it and focus it, but it won't automatically be searched

**Comment by Mo0dy** [comment]
Thanks. I wonder if caching the folder structure for slow volumes
(optionally) would be a nice addition.

**Comment by Canop** [comment]
caching is dangerous when you have no way to be notified of changes, and it can be resources consuming, especially if it must look in advance.

**Comment by Canop** [comment]
It should be enough to configure special paths, eg
```
special_paths: {
    "/media" : {
        list: "never"
        sum: "never"
    }
}
```
