### ISSUE TITLE
"ctrl→" does not open new panel if directory or file  is selected

### ISSUE THREAD

**Issue by v217** [Canop/broot#256]
Thank you for this great software!
I am on ubuntu 20.04 (fishshell) and have downloaded the latest binary.
I installed `br` with `broot --install`
`ctrl→` does not open a new panel if a directory or file  is selected.
Thanks!

**Comment by Canop** [comment]
Can you please confirm you're using broot v0.19.0 or later ? You can check this with `br --help` or in the help screen.

Once it's confirmed, try to use another binding by adding this in the conf.toml file:

```
[[verbs]]
key = "ctrl-r"
execution = ":panel_right"
```

**Comment by v217** [comment]
```
br --help
broot 0.11.8

```
and I added
```
[[verbs]]
key = "ctrl-r"
execution = ":panel_right"
```
to conf.toml file still the same.
I finished installing it, so there are no other customizations, Thanks.

**Comment by Canop** [comment]
[broot 0.11.8](https://github.com/Canop/broot/blob/master/CHANGELOG.md#v0118---2020-01-12) is a very old version.

Half the features of broot were added later.

Please install a recent version: https://dystroy.org/broot/install/

**Comment by v217** [comment]
Oh sorry! I did forget that I installed an old version. I deleted the old version, now everything works as expected.

**Comment by Canop** [comment]
Cool. Thanks for update.
