### ISSUE TITLE
PageUp, PageDown not working

### ISSUE THREAD

**Issue by asdf8dfafjk** [Canop/broot#257]
Re: https://github.com/Canop/broot/issues/182, I noticed a potential bug if you don't mind me mentioning.

**Is everything clear?**
https://miaou.dystroy.org/3490?broot#

**Describe the bug**
`:page_down` and `:page_up` don't do what one would expect, I would expect my screen to move to show me other items, but nothing actually happens. 

**To Reproduce**
1) Got to a path from with a lot of Children items such that the screen is full and you know some sub-directories re not being listed.
2) Type `:page_down`.

**Expected behavior**
Expect to see other sub-directories

**Screenshots**

**Configuration (please complete the following information):**
 - OS: LInux
 - Version: (2020-07-2020) 9eb2f84 and 0.18.1 
- Relevant configuration items

**Comment by Canop** [comment]
Can you confirm a scrollbar is displayed ?
If not you may have to disable root trimming, which can be done with :toggle_trim_root

Note that not trimming the root is the default in 0.19.1.

**Comment by asdf8dfafjk** [comment]
Doing `:toggle_trim_root` does nothing for me. Tried it multiple times and then issued the `page_down` command each time. (I'd like to clarify something in my report, I can only verify that `page_down` isn't working, I have'nt been in a position to test `page_up`). 

Tried both on (2020-07-2020) 9eb2f84 and 0.18.1

**Comment by asdf8dfafjk** [comment]
Incorrect report, the latest git version has no problem with this feature, nor 0.19.1.
