### ISSUE TITLE
Allow full directory listing

### ISSUE THREAD

**Issue by outfrost** [Canop/broot#26]
The "unlisted" bit where `broot` truncates the contents of a directory sure is useful, but could we also have an option to display and browse (with paging?) the entire contents of a directory? Some directories just have a lot of subdirectories and files, and just now I found myself wanting to go through the listing manually instead of searching, because I didn't know what I was looking for. For now it's back to `ls -a` for me, but I was hoping I could use `broot`'s interactive tree view :)

**Comment by Canop** [comment]
This is *possible* in the sense that's what you get if you do `:s`.

I could add a verb (a toggle) to activate full directory listing when sizes aren't displayed.

**Comment by outfrost** [comment]
Oh. I guess I didn't try sizes x) Thanks for the quick reply!
Either way I'd say it could be helpful to have the documentation/readme/built-in help say that showing sizes also provides full listing.

**Comment by 0xpr03** [comment]
This should be documented in the FAQ, installed it just now an ran into this issue
