### ISSUE TITLE
md install request message - extra new line - weird [Y n]

### ISSUE THREAD

**Issue by Stargateur** [Canop/broot#262]
https://github.com/Canop/broot/blob/bc36c9354540b3feb2331e8794590c5f81468d82/src/shell_install/mod.rs#L15-L16

This add a new line at the start of the message, it so print:
```none
> broot | cat -e
$
text$
```
I expect no extra new line, this issue is present on most string in the file.

sometime there is extra new line at the end, https://github.com/Canop/broot/blob/bc36c9354540b3feb2331e8794590c5f81468d82/src/shell_install/mod.rs#L29-L31

---

https://github.com/Canop/broot/blob/bc36c9354540b3feb2331e8794590c5f81468d82/src/shell_install/mod.rs#L20

I think generally most linux tool write `[Y/n]`.

**Comment by Canop** [comment]
I've added the `/` in `[Y/n]`.

But I like the spacing for readability.

If other people want to chime in and give their opinion regarding the empty line, here's what it looks like today:

![image](https://user-images.githubusercontent.com/617006/88645887-ea391b80-d0c4-11ea-81c5-988c6868c276.png)
