### ISSUE TITLE
Move shell scripts to standalone files in repo, `include_str!()` them in the source

### ISSUE THREAD

**Issue by lilyball** [Canop/broot#265]
**Is your feature request related to a problem? Please describe.**
Broot installs shell files on first launch, which not only means it's mucking with my user config, but if I then uninstall broot later, it leaves the files behind. For bash/zsh it looks like this modifies my rc/profile files, and for fish it adds an extra file to my `~/.config/fish/functions` dir.

My package manager should be able to manage at least some of this for me. In particular, my package manager should be able to manage the fish script such that uninstalling broot removes it. bash/zsh support are a bit harder but possibly doable if my package manager writes out an rc file.

What's more, allowing the package manager to deal with this means the script can be written in a single place for systemwide installations, instead of separate per user.

**Describe the solution you'd like**
This could be handled by making two changes:

1. Move the bash/fish script contents to separate files in the repo in a predictable location, use `include_str!()` to pull them back into the source. This means no functional change to `broot` except my package manager can now find the files.
2. Add a feature flag that disables broot's built-in shell integration. This way broot doesn't have to try to figure out whether my package manager has installed the files, it will simply use the feature. Ideally we'd actually have two features, one for bash/zsh and one for fish, because it's much easier for a package manager to deal with the fish script than the bash/zsh script.

**Additional context**
I personally only care about Fish support, which is relatively easy to do with the proposed changes. If these changes are made, I can pretty easily update the Nix package to manage the Fish script directly.

**Comment by Canop** [comment]
@lilyball Isn't what you ask for covered by https://dystroy.org/broot/install-br/#manual-shell-function-installation ?
Those launch arguments have been designed for automated or manual installations 
(a clearer doc might be needed)

**Comment by lilyball** [comment]
I didn't know about the `--print-shell-function` commands. That helps. But `--set-install-state` doesn't because I can't run that as part of the Nix build. Nix builds can't touch anything outside of the Nix store (the results are made available to `PATH` via a symlink), and broot stores its install state in `~/.config/broot/launcher/installed-v1` which Nix can't set.

In order to use this from Nix, I'd have to replace `broot` with a shell script that does something like

```bash
path/to/real/broot --set-install-state installed
exec path/to/real/broot "$@"
```

Given the existence of `--print-shell-function`, all I need at this point is a way to statically declare that it should never auto-install (preferably with separate flags for bash and fish)

**Comment by Canop** [comment]
What kind of flag are you suggesting ? A launch argument ? An environment variable ?

**Comment by lilyball** [comment]
A cargo feature flag would be ideal. If not that, then an env var would be my next choice. Having to always pass a flag to `broot` just feels like the most awkward solution.

**Comment by Canop** [comment]
You don't call broot directly anyway but through a `br` function which could also give the flag.
A feature flag is easy but only for the rare people who can compile Rust.
In any case, if you confirm you'd like the feature flag, I can do it, that's not much of a problem. It could be a "shell-install" feature which would be a default feature.

**Comment by lilyball** [comment]
After giving this even more thought, it occurs to me if I only take over fish and not bash, broot doesn't know what shell it was invoked from so it will prompt to install the bash function anyway. It also occurs to me that installing broot with `Nix` but fish with a separate package manager means Nix can't provide functions to fish, so maybe I don't want a compile-time flag.

Does broot know not to do this if given the `--outcmd` flag, since that implies it's being called from the `br` function?

Given all this, I think the setup that works best for me is:

* If `--outcmd` is provided, disable shell installation checking since it's presumably already being invoked from `br`.
* Use either an env var or a flag that disables shell installation checking. I like env var so that way `ps` isn't showing extra flags, but maybe a flag would be better so that way it's not inherited by subprocesses, because either way, I'm going to need to wrap `broot` myself to set the env var or flag.

With this, I can then vend `broot` to everyone, include the fish function in cases where Nix installed fish itself, and also provide a fish function that wraps `broot` in order to set the env var / flag that disables shell checking, in case the user runs `broot` instead of `br`. This way if they then run `broot` from bash, they'll get prompted.

The downside here is installation from a run from bash will still reinstall the fish function and there's not much I can do about that given that I can't assume that Nix will provide the fish function.

**Comment by Canop** [comment]
> Does broot know not to do this if given the --outcmd flag, since that implies it's being called from the br function?

I guess it can learn this trick.
