### ISSUE TITLE
selecting and operating on multiple files

### ISSUE THREAD

**Issue by asokmath** [Canop/broot#266]
**Did a discussion occur before?**
No
**Is your feature request related to a problem? Please describe.**
A basic feature in file management is to select multiple files and operate move, copy etc on them.  This is missing in this otherwise exceptionally brilliant tool.

**Describe the solution you'd like**
First there must be a mechanism to select (and deselect) multiple files (better if possible across multiple directories as in nnn), show the selected files by something like a + sign  and the cp ,mv,cpp, mvp , rm commands should work on them. 

**Describe alternatives you've considered**

**Additional context**

**Comment by BogdanLysenko** [comment]
Hi, I'd bee happy to see this such neccessary feature as much as you.
Here is kind of my amateur reasonings about how to implement this.

At the first look, selection may be done by pressing, for example, SPACE (in Ranger way), then chosen ones (actually the list of strings containing their paths) should be placed in some kind of buffer or variable (or you can call it a register in vim way). Then (or before that) you can type a verb like cp and put that register name (some of what can not to be a filename like ^:*"@#$) after this, for example: `* cp DEST` or `* rm` or `* cpp`, then press ENTER... PROFIT!!!
In shell it will be interpreted like `<cmd> {path1,path2,path3,...} [DEST]`.
It also supposed that some kind of highlighting will present. You can see selection on current level. When you are moving between levels of tree, some of those can go out of view, but it's naturally that they apears again when you return to initial level (because all of them are stored in a buffer).
Obviously, "unselect" function should present (preferably at the same key as selecting, suppose SPACE).
Also there should present "free buffer" command on some key.

For simplicity you may consider automaticaly puting buffer as argument of command (implicity as registry name after command or no) because it's obvious from context that one aims to manipulate exactly selected files. And I think such way is more preferable.
If someone can propose more optimal way to implement this such necessary feature I'd be glad if you suggest such a way.

P.S. If I was a rust user I'd be happy to implement that myself, but unfortunately, I'm not.

**Comment by Canop** [comment]
Note: this request isn't ignored. It's rather high in my todo list, but the list is big and there are a few ergonomics problems here.

**Comment by asokmath** [comment]
Thanks for keeping the request in mind

**Comment by asokmath** [comment]
From the user end an interface similar to nnn might work for broot as well

In nnn we select multiple files using space bar (here since space bar precedes verbs some other key might be used). selected files are shown with a trailing +. On these selcstion one can perform cp, rm, mv , cpp, mvp etc. This way selections from multiple directories would also be possible.

**Comment by Canop** [comment]
I'm working on this. The name/metaphor is **staging area**.

It can already be tested in the *multiselect* branch and testers would be very welcome (feedbacks and guidelines in [chat](https://miaou.dystroy.org/3490)).

There's still a lot of work to do and I don't know what shortcuts and keys I'll defined as defaults (experimentation from several users would be useful).

Verbs:

* `:stage`  (key in modal mode: <kbd>+</kbd>)
* `:unstage` (key in modal mode: <kbd>-</kbd>)
* `:toggle_stage`
* `:show_staging_area`
* `:close_staging_area`
* `:toggle_staging_area` (shortcut "tsa")

When the staging area is focused, verbs apply to all its paths

**Comment by Canop** [comment]
What remains to be done, mainly:

* better execution preview in status (i.e. display group values when they're the same for all staged paths) 
* prettier and more informative staging area
* keyboard shortcut for non modal mode (it's the trickiest one...)
* selecting and unstaging from the staging area (and probably a syntax allowing a verb to access the selection in the SA)
* scrolling, count display in staging area
* a few details related to refreshing, autoclosing, etc.
* allowing globs (or similar) as argument to `:stage` (ie `:stage **` or `:stage *.xml`)
* `:undo_stage`
* maybe a syntax (or other solution) to help deal with relative paths when not all paths have the same parent
* update skins in confs & various examples and docs
* documentation

**Comment by Canop** [comment]
Please note that it will be easier for me to be confident I didn't overlook something important if I get tester reports.

**Comment by Canop** [comment]
The staging area is now in master.

**Comment by ryptyc** [comment]
I'm trying to make a vi mode shortcut for pasting all staged files in current directory using

```
{
	key: p
	external: "cp -r {other-panel-file} {directory}"
	leave_broot: false
}
```

But on staging some files and pressing 'p' it says 'this verb needs another panel'.

**Comment by Canop** [comment]
If I understand correctly, you want all staged files to be copied to the directory selected in the other panel ?

Then this should probably be `external: "cp -r {file} {other-panel-directory}"`.

From the message you get, it looks like it will fail too. I'll have a look at that.

**Comment by ryptyc** [comment]
> If I understand correctly, you want all staged files to be copied to the directory selected in the other panel ?

I want to copy all the staged files in the current directory without switching to the staged files panel.

**Comment by Canop** [comment]
> I want to copy all the staged files into the current directory without switching to the staged files panel.

There's no syntax for this right now. This is an interesting idea but it looks dangerous.

Today, the only way to execute a command on the staged files is to focus the staging area.

**Comment by Canop** [comment]
Staging area's documentation can be viewed here: https://dystroy.org/broot-master/staging-area/

**Comment by asokmath** [comment]
Thank you for implementing a long-waited feature

**Comment by Canop** [comment]
Staging Area is released with broot 1.3.

I'm closing this issue. Discussions are still possible, here, in chat, or in new issues.

**Comment by oshmoz** [comment]
Hello and thank you for this great feature.
I just installed broot 1.3.0 and '+' and '-' don't seem to work (broot treats them like typing "regular" characters - filtering for file name). The rest of the stage commands are working fine (:stage, :unstage, tsa, ctrl-g for example).
I''m not a programmer, let me know what more information you need.
Thank you.

**Comment by Canop** [comment]
@oshmoz The '+' and '-' keyboard shortcuts only work when you're in "modal" mode, which allows the input to not be focused.
See  https://dystroy.org/broot/modal/
If you're not a vi user, this mode might feel a little alien, though and I'd recommend to stick to ctrl-G or define your own shortcuts (depending on your OS and terminal)

**Comment by oshmoz** [comment]
https://dystroy.org/broot/staging-area/#stage-and-unstage-files
Second and third line on the table - "only in command mode".
But if it's only in modal mode, can you please recommend a shortcut? (space for toggling seems like a good option, but it's taken. Can I define '+' and '-' as shortcuts in command mode?)

**Comment by Canop** [comment]
They're already defined in command mode (which only exists when the modal mode of broot is enabled... I should make the terminology clearer).
I can hardly recommend shortcuts, it's so dependent on the terminal and os which reserve a lot of them.
But in practice having the `:toggle_stage` shortcut is enough.

**Comment by yingzhu146** [comment]
@Canop is it possible to add all files that match the current search term? would be great, e.g for quick`mv *.js ./src/` type reorgs. I don't think I've read anything about this in the docs

**Comment by Canop** [comment]
There's currently no way to do this. It's in my TODO list.

**Comment by asokmath** [comment]
Waiting to see this implemented in broot. May be the key combination cntrl-a will add all files that match the current search term to the staging area

**Comment by runiq** [comment]
I'd like to open all files in the staging area with my editor, while leaving broot – is that somehow possible with `--outcmd`? The docs are a little too sparse for me to figure it out, I'm afraid…

As in: I have `~/a`, `~/b` and `~/c` in my staging area, and I want to do `vim ~/a ~/b ~/c` somehow, and not return to broot afterwards, but to the (original) shell. Is that possible?

**Comment by Canop** [comment]
@runiq This isn't possible today. It would be easy to implement but I didn't think about it. I've added a specific issue.
