### ISSUE TITLE
Feature request: add key for "select previous"

### ISSUE THREAD

**Issue by magnetophon** [Canop/broot#27]
With tab you can go to the next match.
I expected shift-tab to go to the previous one.

**Comment by Canop** [comment]
Sounds logical. Will do.

**Comment by dgrisham** [comment]
@Canop Hm, doesn't seem like you can -- see https://github.com/redox-os/termion/blob/master/src/event.rs#L54. Might require a feature request/PR.

**Comment by dgrisham** [comment]
Asked about it here https://gitlab.redox-os.org/redox-os/termion/issues/16#note_15760
