### ISSUE TITLE
Trigger change of pane name in tmux to broot/br 

### ISSUE THREAD

**Issue by teynav** [Canop/broot#270]
I have my person keybind "ctrl+right key" to break pane in tmux and it won't work with broot
I want broot to trigger pane name change so i can write tmux hook to change the keybinding once pane name is changed.
I hope this feature is considered since it will help in making custom shortcut integration possible 

```
set-hook -g window-renamed 'if -F "#{==:#{window_name},broot}" "unbind C-right" "bind -n C-right break-pane"'

set-hook -g after-select-window 'if -F "#{==:#{window_name},broot}" "unbind C-right" "bind -n C-right break-pane"'

```

**Comment by Canop** [comment]
I'm sorry but I don't understand the problem. Can you please come to the chat and explain me ?
https://miaou.dystroy.org/3490

**Comment by Canop** [comment]
OK, I understand better.

I'll have a look.

In the meantime, you might consider changing the shortcut in broot, that is bind :panel_left and :panel_right to other keys.

**Comment by Canop** [comment]
If the name must be set on broot start, why not do it in the shell function outside of broot ? Or in a script launching it ?
https://stackoverflow.com/questions/40234553/how-to-rename-a-pane-in-tmux

**Comment by teynav** [comment]
> If the name must be set on broot start, why not do it in the shell function outside of broot ? Or in a script launching it ?
> https://stackoverflow.com/questions/40234553/how-to-rename-a-pane-in-tmux

Yeah this is what the issue is, if i do
set -g pane-border-status top
set -g pane-border-format "#P: #{pane_current_command}"

As what your link describe it to be I don't get name change, If you remember the screenshots i sent you were showing nothing but name of panes of "Current Command".
That's why I said it doesn't trigger name change I hope you are able to recreate the issue as it's very easy to do.

**Comment by Canop** [comment]
OK, I reproduce the issue, not in the case of broot directly, but in the case of broot being launched by the shell function.

**Comment by teynav** [comment]
> OK, I reproduce the issue, not in the case of broot directly, but in the case of broot being launched by the shell function.
Yeah sorry i was ambiguous before when I said broot i meant the "br" shell function not broot, using broot directly works well and it does change pane name.

**Comment by teynav** [comment]
I would like to mention How I solved this 
`function br {
sh=$(echo $SHELL | sed "s/^.*\///g" )
if command -v tmux >/dev/null
then
    tmux renamew -t $TMUX_PANE broot
fi
    f=$(mktemp)
    (
	set +e
	broot --outcmd "$f" "$@"
	code=$?
	if [ "$code" != 0 ]; then
	    rm -f "$f"
	    exit "$code"
	fi
    )
    code=$?
    if [ "$code" != 0 ]; then
	return "$code"
    fi
    d=$(<"$f")
    rm -f "$f"
    eval "$d"
if command -v tmux >/dev/null
then
  tmux renamew -t $TMUX_PANE $sh
fi
}`
This was my br function , also I made sure you don't have issue when tmux ain't installed
Now I edited my .tmux.conf file
`set-hook -g window-renamed[1] 'if -F "#{==:#{window_name},broot}" "unbind -n C-right" "bind -n C-right break-pane"'
set-hook -g after-select-window[1] 'if -F "#{==:#{window_name},broot}" "unbind -n C-right" "bind -n C-right break-pane"'`

Works like a charm!!!

**Comment by Canop** [comment]
Cool.
I won't change the general br function but I'll add an entry in the documentation, maybe in the "common problems" page.

**Comment by Canop** [comment]
updated doc: https://dystroy.org/broot/common-problems/#i-have-trouble-with-tmux
