### ISSUE TITLE
broot locks up / freezes

### ISSUE THREAD

**Issue by croyleje** [Canop/broot#282]
I f I try to select a file by pressing enter on it nothing happens and terminal session freezes not allowing any input the window has to be closed by killing the terminal.  Editing a file works fine if I select a file then use the <space> <e> option to edit.

terminal = alacritty
editor = vim
wm   = bspwm
dist = arch

Was unable to find any information about this issue online I know that these issue tickets are not really meant for this sort of thing but didn't know any other place to try any information or suggestions would be greatly appreciated.
Thank you,
Jason

**Comment by Canop** [comment]
> I know that these issue tickets are not really meant for this sort of thing but didn't know any other place to try any information or suggestions would be greatly appreciated.

I was answering you on Miaou. But an issue on GitHub is OK too, don't worry.

Can you tell me what happens when you open the file directly with xdg-open ?
If there's no problem this way, then I'd like to [see the log](https://dystroy.org/broot/community/#log).

**Comment by croyleje** [comment]
Hey sorry about that didn't relieve anyone was in there I checked xdg-open appears to be working no issues.

**Comment by Canop** [comment]
@croyleje Can you send me the debug log of when there's a freeze ?

**Comment by croyleje** [comment]
I tracked it down to a long standing bug in xdg-open but there does appear to be some recent discussion about fast tracking a patch if the logs would be useful to you please let me know I can still send them.

[original bug report]
https://bugs.freedesktop.org/show_bug.cgi?id=92514

[submitted patch >5 years old]
https://gitlab.freedesktop.org/xdg/xdg-utils/-/issues/84

**Comment by asdf8dfafjk** [comment]
I know i am commenting without context but I saw mention of xdg-open in the last comment so I will say this- I've spent at least 10 hours with xdg-open and the ecosystem around it, even based on Arch wiki promoted tools is an absolute mess with nobody following the standard.

**Comment by croyleje** [comment]
Going to close this issue but if you would still like copies of the logs just let me know I can supply them.  Thank you

**Comment by Canop** [comment]
Yes I'd like to see the logs to see what happens.

**Comment by croyleje** [comment]
[dev.log](https://github.com/Canop/broot/files/5258255/dev.log)
Here is the log you requested.  The suggested patch and work around discussed on the xdg-utils issues page does work but comes with its own issues as discussed in that thread.  If you interested in working on this from your side I would be happy to help anyway I can.  I have only recently started coding in rust but would be happy to help where I can.

**Comment by oblitum** [comment]
Same issue here, makes broot unusable for pick & edit of files.

**Comment by Canop** [comment]
@oblitum can you come to the chat to confirm precisely what problem you have ? https://miaou.dystroy.org/3490

**Comment by Canop** [comment]
> 
> [[verbs]]
> key = "enter"
> execution = "$EDITOR {file}"
> 
> in my conf.toml file that will work also but then you have no way to move up in the directory structure.

Just notice this. I may be too late but just in case, do you know about [apply_to](https://dystroy.org/broot/conf_verbs/) ?

**Comment by oblitum** [comment]
> @oblitum can you come to the chat to confirm precisely what problem you have ? https://miaou.dystroy.org/3490

@Canop I confirm it's precisely the same issue. I'm using almost the same env as OP, the only difference is the window manager, I'm using i3. broot completely freezes/locks-up when hitting <kbd>enter</kbd>, `edit` verb works, and I think it's due to how `xdg-open` as OP has found already.

**Comment by Canop** [comment]
There's no obvious course of actions from here to me.

**Comment by oblitum** [comment]
Agreed... I'm mostly thinking up whether the problem can be circumvented or something, given how fixing upstream (if it's actually xdg-open to blame) may be slow or not productive (5y issue, etc).

**Comment by oblitum** [comment]
For what is worth, `xdg-open sample.cpp` does work from terminal and open `nvim` fine for the file.

**Comment by Canop** [comment]
Ok, I'll try to reproduce the problem and see if I can circumvent it
