### ISSUE TITLE
display precise images in terminal supporting them

### ISSUE THREAD

**Issue by Canop** [Canop/broot#287]
Some terminals like kitty support image inserts.

We could probably increase the rendering precision of images in those terminals.

**Comment by Dieterbe** [comment]
I think this would be great. For context, I'm wondering if I can use broot as an "image manager", which i suppose is just about the same thing as a file manager, except with live previews of images. I suppose one limitation would be that you can only preview 1 image at once. There's graphical applications such as [gqview](http://gqview.sourceforge.net/view-shot.html) which can show multiple previews at once, but then of course you don't have the same navigation and keybinds as broot offers...
(if anyone can recommend graphical image managers that are perhaps more similar to broot in terms of navigation, i would be happy to hear about them!)

**Comment by Canop** [comment]
> one limitation would be that you can only preview 1 image at once

Not necessarily. If precise image inserts appear good enough, I see no obstacle to a directory preview (including filtering).

If somebody wants to have a look at how image kittens work and can be inserted at precise positions on the terminal, I'd welcome that help.

**Comment by kovidgoyal** [comment]
You can display images with either cell or pixel precision using the kitty graphics protocol. It's on my TODO list to write an image display/browse kitten for kitty using the protocol, to replace https://github.com/kovidgoyal/iv  but I would be glad to delegate to broot instead :)

See https://sw.kovidgoyal.net/kitty/graphics-protocol.html#display-images-on-screen  for how to control image placement.

**Comment by Canop** [comment]
> but I would be glad to delegate to broot instead

or you could write it yourself into broot :)

the current viewer: https://github.com/Canop/broot/blob/master/src/image/image_view.rs

**Comment by kovidgoyal** [comment]
Thanks, but it would be a *lot* less work for me to write a kitten for it. If you do decide to implement it and have questions, feel free to ping me.

**Comment by HybridDog** [comment]
I hope this is still on-topic:
It should be possible to make the current image displaying a bit more precise without kittens.

Image shown in broot:
![br](https://user-images.githubusercontent.com/3192173/95249718-682e4700-0819-11eb-8c31-23dc65f6f109.png)

Image shown with tiv (https://github.com/stefanhaustein/TerminalImageViewer):
![tiv](https://user-images.githubusercontent.com/3192173/95250000-d07d2880-0819-11eb-94f1-7c1d903ddbeb.png)

Image downscaled with SSIM-based perceptual downscaling (https://graphics.ethz.ch/~cengizo/Files/Sig15PerceptualDownscaling.pdf):
![ssim_based](https://user-images.githubusercontent.com/3192173/95250146-fa364f80-0819-11eb-9ca0-f033a2c781e0.png)

Original image: [030022](https://user-images.githubusercontent.com/3192173/95250412-5dc07d00-081a-11eb-937c-82c16e9043b3.jpg)

**Comment by Canop** [comment]
Yes it's possible to have a better precision. There are two quite simple solutions:

* changing the downscaling function (see https://github.com/Canop/broot/blob/master/src/image/image_view.rs#L74), using another of the ones available at https://crates.io/crates/image
* using other characters than just half height squares

But both of those solutions are very time expensive. I might try testing using better interpolation in background but I'm not sure having 2 renderings would be an ideal experience.

I'd be interested in other attempts or explorations. It's possible the image crate I use isn't really the best one but I didn't found anything else in Rust.

**Comment by AndydeCleyre** [comment]
It may be worth looking at what [ueberzug](https://github.com/seebye/ueberzug) does with X11.

[fzfimg.sh](https://github.com/seebye/ueberzug/blob/master/examples/fzfimg.sh)

![image](https://user-images.githubusercontent.com/1787385/97068573-b9b72f80-1596-11eb-8841-dddb0985247f.png)

**Comment by Canop** [comment]
I know it and mentioned it, but its licence isn't really compatible with broot unless I change how broot itself is licenced.

**Comment by wavexx** [comment]
I discovered broot could preview images by chance, so I plunged here. Ascii preview is nice, but next to useless in most cases.

There are at least 2 popular inline protocols I'm aware of, plus some hacks like w3m-img which are simpler to implement than processing the final ascii data.

sixel has the widest terminal support, and you could rely on sixel-bin's utilities (img2sixel) to directly encode the image without bundling any image decoding in broot itself.

Then there's OSC1337 (supported by mlterm and iterm2 afaik). This works by streaming the source image base64-encoded directly to the terminal plus some positioning data. It relies on the terminal to decode the image, so not all image types are supported depending on the terminal. Again, very simple to implement, and with both png and jpg images the b64 encoded data size is actually competitive with sixel most of the time. You might still want to process the image to shrink it for the current terminal size prior to streaming though if the image is large.

Kitty supports inline images. I'm not sure if this is identical to OSC1337, but in principle the image data is streamed inline b64-encoded. I'm not sure why they decided to implement another protocol when OSC1337 was already there, almost identical in behavior.

**Comment by kovidgoyal** [comment]
kitty's graphical protocol is nothing like OSC 1337 which is a poorly thought out bandaid. Go read https://sw.kovidgoyal.net/kitty/graphics-protocol.html and https://github.com/kovidgoyal/kitty/issues/33

**Comment by Canop** [comment]
Follow-up.

This isn't dropped, at all. I just didn't have time recently to work on broot.

Right now the two approaches that seem to make sense to me are:

* implementing the kitty protocol
* use a X11 based hack to display a borderless window

Both ones would have the big drawback of being usable by only a small number of users.

**Comment by wavexx** [comment]
@kovidgoyal I remember reading at it while I implemented some crude support for OSC1337 in ranger. I like the persistence options which are lacking, but the raw stream modes are perceptibly slower than sixel even when using a local terminal, and I don't see much difference when the png data is streamed, which is what you'd probably want in all but the simplest cases. Am I wrong?

**Comment by kovidgoyal** [comment]
Sixel has 256 colors *only* (though using hacks it can be got up to
15bit color), which means for fair comparison you have to
transmit indexed images, which in kitty's case would be using PNG. Where
you will find no performance difference. 

And that's for the *streaming* case, which is needed only over ssh. Run
kitty's protocol on a local machine and you will get several orders of
magnitude better performance. 

All this has been discussed at length during the design of kitty's
protocol, spend some time reading, the issue I linked to above.

**Comment by wavexx** [comment]
Yeah, I'm pretty aware of sixel's limit in general (not a fan of the encoding personally), but I'm not advocating on merits here. It's old encoding with wider/existing terminal support. I'm mostly familiar with OSC1337 as I was working with mlterm which supports one of these two and OSC1337 was dead-simple to implement.

I wasn't aware of kitty's support for shared memory until this point. OSC1337 has also support for a path to avoid streaming. My point was that they're *very* close when it boils down to png. You can easily have shared code to support both.

**Comment by Canop** [comment]
All those protocols will probably be opt-in (with an added availability check when possible).

I propose I start with the kitty one, then adding the OSC1337 will probably be simple and light.

**Comment by kovidgoyal** [comment]
You can query support for the kitty graphics protocol, and whether a shared filesystem/memory is available, like this: https://sw.kovidgoyal.net/kitty/graphics-protocol.html#querying-support-and-available-transmission-mediums

**Comment by Canop** [comment]
Started the work on the kitty part.

![image](https://user-images.githubusercontent.com/617006/100235861-34c08c80-2f2d-11eb-92f4-8b03e6f7037f.png)

It's far from finished but it looks doable.

**Comment by Canop** [comment]
Kitty support is mostly done, I've only a few details to change (centering, testing shared buffers).

![image](https://user-images.githubusercontent.com/617006/100389623-2c9c4600-302e-11eb-9423-f27c21976bcb.png)

Tests (and code reviews for people knowing kitty well enough) would be welcome. The branch to use is the "kitty" one.

**Comment by kovidgoyal** [comment]
Since I dont know Rust, cant comment on your code, some general observations:

1) With the temporary file transmission, there are no races, provided you send the escape code after finishing writing the file. Not sure why there is a comment about raciness in the code.

2) You might want to use the compression when using chunked transfer, for better performance: https://sw.kovidgoyal.net/kitty/graphics-protocol.html#compression

3) You use STDOUT_FILENO for TIOCGWINSZ and other places. I dont know if broot usage mode guarantess that stdout is never redirected, but the correct way to do this on Unix is to open the result of ctermid() and use that file descrtor to communicate with the controlling terminal, so this always works, even if stdout is redirected.

4) You will likely get best performance via shared memory. I didnt see any code to test availability of shared filesystem/memory, but I may have missed that.

5) Detecting support. I think you currently use the value of TERM, this is fairly fragile. Instead I suggest you implement (4) where you can simultaneously query for presence of shared filesystem/emmory and detect support for the image protocol as well. See https://sw.kovidgoyal.net/kitty/graphics-protocol.html#querying-support-and-available-transmission-mediums

**Comment by kovidgoyal** [comment]
Oh and 

6. You are transmitting RGBA (32-bit) data, this is only needed if the image has transparency, which most images dont, you shoul dconsider transmitting 24bit RGB data instead, for better performance in the common case.

**Comment by AndydeCleyre** [comment]
> I know it and mentioned it, but its licence isn't really compatible with broot unless I change how broot itself is licenced.

Sorry, I don't know where that mention is, so maybe this is already addressed, but: does the license matter if you're not actually including that project with yours? Can't it just use the binary interface if available on the system, without legal entanglements?

**Comment by Canop** [comment]
>  Can't it just use the binary interface if available on the system

Probably. As I don't really have the time at the moment I'd appreciate experiments and/or PR.

**Comment by teacher144123** [comment]
Hello, I was searching a album-like command line tool and I found this repo.
I am not familiar with Rust enough.
Was it easy to add iTerm2 support like viu or viuer package?
Ref:
https://github.com/atanunq/viu
https://github.com/atanunq/viuer
https://github.com/atanunq/viuer/blob/master/src/printer/iterm.rs

**Comment by Canop** [comment]
@teacher144123  The problem with iTerm2 is you need a mac to test and develop...

**Comment by wavexx** [comment]
@canop iTerm2 uses OSC1337, which is supported by mlterm.

**Comment by teacher144123** [comment]
@Canop that is a good reason I never thought.
I will try to develop this feature.

**Comment by Kabouik** [comment]
For some reason, even when I use `broot` in `Kitty`, the image is downscaled/pixelated as if I were using `viu`. Is there something I need to do to make it use `kitty`'s `icat` or at least `ueberzug` (which I think is significantly faster, at least on my computer) by default?

**Comment by Canop** [comment]
No idea. You might create a specific issue on broot+kitty not displaying high resolution images

**Comment by AndydeCleyre** [comment]
If sixel support isn't there, I hope it will be, as tmux and zellij will never support the kitty protocol, but there's a tmux fork for sixel support and zellij plans to support sixel as well.

**Comment by AndydeCleyre** [comment]
I just learned that official tmux can now be built with sixel support!

https://www.arewesixelyet.com/#tmux
