### ISSUE TITLE
Problems with 'cd' into paths with spaces in them

### ISSUE THREAD

**Issue by DependentChemical** [Canop/broot#29]
I noticed issues when using this to cd into a directory which is under folders or hard drive names having spaces in them as the command being executed splits up the directory into two parameters and the cd says that the cd has too many arguments.

I fixed my issue with the following changes into the bash launder script (under ~/.config/broot/launcher/bash/br) with the following disclaimer: I just didn't know anything about bash scripting before hand so I just have to use answers I found on google and try to patch whatever I can and it now apparently works which shows in how inelegant it looks, and I really don't know if this was really an issue, I just found it doesn't cd properly with a path having spaces in them, sorry if this was already fixed and I was just using it wrong (also first time trying to use a terminal file manager)
```
# This script was automatically generated by the broot function
# More information can be found in https://github.com/Canop/broot/blob/master/documentation.md

# This function starts broot and executes the command
# it produces, if any.
# It's needed because some shell commands, like `cd`,
# have no useful effect if executed in a subshell.
function br {
	f=$(mktemp)
	(
		set +e
		broot --outcmd "$f" "$@"
		code=$?
		if [ "$code" != 0 ]; then
			rm -f "$f"
			exit "$code"
		fi
	)
	code=$?
	if [ "$code" != 0 ]; then
		return "$code"
	fi
	d=$(cat "$f")
	#hacky fix
	OIFS=$IFS
	IFS=' '
	read -a sPlit <<< "${d}"
	IFS="$OIFS"
	if [ ${#sPlit[@]} > 2 ]; then
		d="${sPlit[0]} "
		d+='"'
		d+="${sPlit[@]:1}"
		d+='"'
	else
		d='${sPlit[@]}'
	fi
	#end of hacky fix
	rm -f "$f"
	eval "$d"
}
```

other than that, I love the program! and I'm hoping I can learn to further customize it more! Likewise I wan't to ask if we can access the path name other than the directory name when creating new verbs like {file} uses?

Thank you :)

**Comment by Canop** [comment]
> I wan't to ask if we can access the path name other than the directory name when creating new verbs like {file} uses?

I'd rather not have a lengthy off-topic discussion here on that question. Care to come explain what you mean in [the chat](https://miaou.dystroy.org/3490)?

**Comment by DependentChemical** [comment]
I'm sorry :), I just looked at the source code and what I wanted was already there, it was not just in the documentation of the conf.toml file. :)
Anyways, the earlier fix I wrote was quite wrong, here I tried to fix it
```
#apparently broken with paths containing spaces (windows)
#hacky fix
OIFS=$IFS
IFS=' '
read -a sPlit <<< "${d}"
IFS="$OIFS"
if [ ${#sPlit[@]} > 2 ] && [ "${sPlit[0]}" == 'cd' ]; then
     d="${sPlit[0]} \"${sPlit[@]:1}\""
else
     d="${sPlit[@]}"
fi
```

**Comment by Canop** [comment]
I fixed it by escaping in broot.

![1](https://i.imgur.com/rYc8zJ2.png)

![2](https://i.imgur.com/967RzzF.png)

![3](https://i.imgur.com/Kcctbxx.png)
