### ISSUE TITLE
NetBSD package

### ISSUE THREAD

**Issue by voidpin** [Canop/broot#298]
FYI,
I've just packaged and merged `broot` to pkgsrc, so it's now available on NetBSD.

https://mail-index.netbsd.org/pkgsrc-changes/2020/11/04/msg223463.html

**Comment by Canop** [comment]
@voidpin Why did you close it ? I intended to mention this in the install documentation of broot. Is there a problem ?

**Comment by voidpin** [comment]
@Canop No, there's no problem, it works perfectly, https://www.unitedbsd.com/d/305-broot :)

To install on NetBSD just run
`pkgin install broot` or build from source

```
cd /usr/pkgsrc/sysutils/broot
make install
```

I closed the issue because, there's no issue :)

**Comment by Canop** [comment]
I'll close the issue myself on deploying the update to the install documentation :)

**Comment by voidpin** [comment]
Sure, np.
I'm really liking this.
Thanks for creating `broot`.
