### ISSUE TITLE
Preserve the filter in the tree view input area after passing it as an argument to broot

### ISSUE THREAD

**Issue by Ryujinra** [Canop/broot#30]
Right now, the filter is not preserved in the resultant tree view's input area if you pass a filter directly to br as an argument, like so: 

`br -c "miaou :g" ~`

This means if you need to to alter the filter query in any way (like turning on exact matching by terminating with a '/'), you need to retype the entire filter from scratch.

The filter works as expected, but I think it would be useful to preserve the filter in the input area for subsequent modification. 

Thanks for your consideration.

**Comment by Canop** [comment]
This sounds reasonnable
