### ISSUE TITLE
Issues with light mode skin

### ISSUE THREAD

**Issue by max-sixty** [Canop/broot#302]
**Describe the bug**

I'm using the light mode (aka "White Background skin") from https://dystroy.org/broot/skins/ in iTerm2, and I'm getting an unexpected result:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/5635139/99020529-aa7f2e00-2513-11eb-8e40-b0277162554a.png">

The colors are at least having some impact, because if I comment them out, I get normal dark mode:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/5635139/99020593-cb478380-2513-11eb-90eb-c056b22b80f3.png">

After quitting `br`, I get the message:

```
grey level must be between 0 and 23 (got 24)
```

**Configuration (please complete the following information):**
 - OS: MacOS
 - Version: broot 1.0.5
- Relevant configuration items: None

And a big thanks for such an impressive tool — I find it really helpful.

**Comment by Canop** [comment]
@max-sixty this skin doesn't have a white background but a transparent one, it is designed to be used when your terminal is configured with a dark foreground color and a light background color.

**Comment by Canop** [comment]
There are two parts here:

* the `grey level must be between 0 and 23 (got 24)`. It's an error in the skin. I'll fix it (and probably check how it renders with new features).
* the background. I think you misunderstood the purpose of this skin. It doesn't have a white background, but a transparent one. It's designed for when you already have a terminal with a dark foreground and a light background. I'll fix the documentation to try make this clearer.

Here's how the "white skin" renders for me in a terminal having a light grey background:

![image](https://user-images.githubusercontent.com/617006/99036661-65deab80-2582-11eb-9a67-15e1ff32a686.png)

**Comment by max-sixty** [comment]
Hi @Canop — thanks for the quick response. Your description is what I expected, and my terminal has a light background already. 

That said, maybe it's only iTerm / something idiosyncratic. Let me know if there's any debugging information that would be helpful.

**Comment by Canop** [comment]
Your terminal has a white background ? Then it's strange. Are you sure there's no other skin line in your config ?

**Comment by max-sixty** [comment]
Thanks @Canop  

It's a light background:

<img width="548" alt="image" src="https://user-images.githubusercontent.com/5635139/99097797-fae6a200-258c-11eb-8f13-81cb7570a4da.png">

I also tried changing `24` to `23` to confirm that wasn't it.

Anything else I could try for debugging?

**Comment by Canop** [comment]
Can you try with 

    default = "grey(1) none"

(ie replacing "white" with "none" on first line) ?

**Comment by max-sixty** [comment]
That works!!

**Comment by Canop** [comment]
"white" and "black" often behave very strangely: terminals often remap them to "foreground" and "background".

**Comment by max-sixty** [comment]
Thanks a lot @Canop , both for your help here and broot generally!
