### ISSUE TITLE
Search performance goes down as search string get's longer.

### ISSUE THREAD

**Issue by najamelan** [Canop/broot#303]
First of all, thanks for this awesome software. cli search without needing to read 3km of man page every time I use it, I love it.

**Describe the bug**
I thought I give the search a try on a rather big directory (my code directory). Admittedly even counting the number of files in there takes a long time. I am on a fast machine (ssd at 3GB/s, Amd ryzen 9 3900x, 32GB ram, ...). I tried searching for `thespis` which is one of my coding projects. I thought broot just hung. Then I backspaced and on shorter strings it's actually reasonably fast. As I add letters one at a time, it gradually get's slower. By the last `s`, it takes more than a minute.

This surprised me, as I would imagine that once you have the results for `thespi`, adding the `s` only requires eliminating existing search results that don't contain an `s` rather than searching everything again. By the feel of it, it runs the search again from scratch. 

**Expected behavior**
Search to be as fast as possible ;).

**Configuration (please complete the following information):**
 - OS: Arch linux
 - Version 1.0.5

By now nemo is still counting my directory (1.9 million files in 10GB and counting) although that includes all the `.git/objects` which I imagine broot would ignore anyways.

**Comment by Canop** [comment]
The main reason shorter searches are much faster is that they're not complete: broot doesn't search in the deepest directories if it found already enough matches at low depths.

The optimization you mention is rarely possible. It would need the previous optimization to have been complete, that is neither interrupted by the current search's key nor good enough with a partial (low deep) search. It would also need to be recent enough to not ignore changes in the file system.

Depending on the machine, `c/` and `cr/` have various speed profiles, you may try the one you don't use as they give the same result for all simple patterns.

**Comment by Canop** [comment]
> By now nemo is still counting my directory (1.9 million files in 10GB and counting) although that includes all the `.git/objects` which I imagine broot would ignore anyways.

You should try `:toggle_counts` in broot. It counts **all** files and does it with a quite optimized multi-thread algorithm.

**Comment by najamelan** [comment]
Yeah, I realized the search algorithm is quite involved. I didn't search for file content, only names, so I can't imagine how slow `c` or `cr` would be, I think I'm not going to try.

`toggle_counts` is fast indeed. Much faster than nemo but it get's to 3.5m. I imagine the rest is in `.git/objects` directories which I suppose ignored. But it was really fast, a couple of seconds only. It might also be much of the inodes are in memory cache by now after searching in this directory for a while.

As there doesn't seem to be a path for action here, I'll close the issue. Thanks again, great UX.
