### ISSUE TITLE
[opinion needed] Replace TOML for config with another format ?

### ISSUE THREAD

**Issue by Canop** [Canop/broot#304]
TOML still feels alien to many users. The structure doesn't clearly appear to everybody and configuration changes are sometimes tricky.

Its traps, like the need to have values before arrays, make people giving up on some trivial configuration changes.

A format like HJSON would probably be easier for users.

So, do you think the default format (still allowing TOML) should be a different one, or that we should stick to TOML and better explain how it works in documentation ?

**Comment by asdf8dfafjk** [comment]
I agree. 

I would wager  that the biggest audience of your work is programmers, and most of them would be familiar with JSON family of config languages.

**Comment by savchenko** [comment]
No strong feelings. JSON or YAML maybe?

**Comment by Canop** [comment]
@savchenko  YAML brings its own class of spacing errors and JSON isn't suitable for configuration due to its lack of comments (and many minor grippes like forbidding tailing commas and quoted keys).

If I change the default configuration format, it will certainly be for HJSON.

The main drawback of HJSON is that everything is between { and }, which isn't really pretty, but otherwise it's nice. I'll try before making it definitive anyway.

**Comment by savchenko** [comment]
I (carefully) doubt if community is more familiar with HJSON compared to the TOML. You are right about trailing commas - highly annoying.

Perhaps leave TOML where it is and invest time elsewhere? Your call obviously.

**Comment by AndydeCleyre** [comment]
I'm not a big fan of TOML, but I do prefer it to hand-writing JSON or HJSON. My first choice is (strict)YAML, then about even preference for "INI-like" and TOML.

![image](https://user-images.githubusercontent.com/1787385/100425041-7ef45b80-305c-11eb-9732-f5ede6e3c37f.png)

**Comment by Canop** [comment]
JSON is out of question anyway.

HJSON looks rather clear and is probably less tricky:
![image](https://user-images.githubusercontent.com/617006/100429120-2c836100-3095-11eb-8068-c335ea15f6b7.png)

I translated a whole config file:

```hjson
###############################################################
# This configuration file lets you
# - define new commands
# - change the shortcut or triggering keys of built-in verbs
# - change the colors
# - set default values for flags
# - set special behaviors on specific paths
#
# Configuration documentation is available at
#     https://dystroy.org/broot
###############################################################
{
    # the theme used for syntactic coloring in previews
    syntax_theme: base16-ocean.light

    ###############################################################
    # Default flags
    # You can set up flags you want broot to start with by
    # default, for example `default_flags="ihp"` if you usually want
    # to see hidden and gitignored files and the permissions (then
    # if you don't want the hidden files you can launch `br -H`)
    # A popular flag is the `g` one which displays git related info.
    #
    default_flags: 

    # whether to set a triangle left to the selection
    show_selection_mark: true

    ###############################################################
    # Special paths
    # If some paths must be handled specially, uncomment (and change
    # this section as per the examples
    #
    special-paths: {
        "/media/slow-backup-disk": no-enter
        "/home/dys/useless": hide
        "/home/dys/my-link-I-want-to-explore": enter
    }

    ###############################################################
    # Date/Time format
    # If you want to change the format for date/time, uncomment the
    # following line and change it according to
    # https://docs.rs/chrono/0.4.11/chrono/format/strftime/index.html
    #
    date_time_format: %Y/%m/%d %R

    ###############################################################
    # Column order
    # cols_order, if specified, must be a permutation of "gbpdscn"
    # where every char denotes a column:
    #  g : Git file info
    #  b : branch (shows the depth and parent in the tree)
    #  p : permissions (mode, user, group)
    #  d : last modification date
    #  s : size (with size bar when sorting)
    #  c : count, number of files in directories
    #  n : file name
    #
    cols_order: [
        mark
        git
        branch
        permission
        date
        size
        count
        name
    ]

    ###############################################################
    # Verbs and shortcuts
    # You can define your own commands which would be applied to
    # the selection.
    # 
    verbs: [
        {
            invocation: edit
            key: F2
            shortcut: e
            execution: $EDITOR +{line} {file}
            leave_broot: false
        }
        {
            invocation: root
            key: F9
            internal: ":focus /"
        }
        {
            name: "backup"
            invocation: "bu {name}"
            cmd: ":cp {file}-back_{name};:!focus {file}-back_{name}"
            apply_to: directory
        }
        # go up 4 lines. Uncomment if you need it
        # {
        #     key: "ctrl-u"
        #     invocation: "u4"
        #     execution: ":line_up 4"
        #     leave_broot: false
        # }
        {
            invocation: "create {subpath}"
            external: "$EDITOR {directory}/{subpath}"
            leave_broot: false
        }
        # This one launches a terminal (on exit you'll be back in broot)
        {
            key: "ctrl-t"
            external: "$SHELL"
            leave_broot: false
            set_working_dir: true
        }
        {
            invocation: "git_diff"
            shortcut: "gd"
            leave_broot: false
            external: "git difftool -y {file}"
        }
    ]

    ###############################################################
    # Skin
    # If you want to change the colors of broot,
    # uncomment the following bloc and start messing
    # with the various values.

    skin: {
        default: gray(23) none / gray(20) none
        tree: ansi(94) None / gray(3) None
        file: black None / gray(15) None
        directory: ansi(208) None Bold / ansi(172) None bold
        exe: Cyan None
        link: Magenta None
        pruning: gray(12) None Italic
        perm__: gray(5) None
        perm_r: ansi(94) None
        perm_w: ansi(132) None
        perm_x: ansi(65) None
        owner: ansi(138) None
        group: ansi(131) None
        count: ansi(136) gray(3)
        dates: ansi(66) None
        sparse: ansi(214) None
        content_extract: ansi(29) None
        content_match: ansi(34) None
        git_branch: ansi(229) None
        git_insertions: ansi(28) None
        git_deletions: ansi(160) None
        git_status_current: gray(5) None
        git_status_modified: ansi(28) None
        git_status_new: ansi(94) None Bold
        git_status_ignored: gray(17) None
        git_status_conflicted: ansi(88) None
        git_status_other: ansi(88) None
        selected_line: None gray(5) / None gray(4)
        char_match: Yellow None
        file_error: Red None
        flag_label: gray(15) None
        flag_value: ansi(208) None Bold
        input: White None / gray(15) gray(2)
        status_error: gray(22) ansi(124)
        status_job: ansi(220) gray(5)
        status_normal: gray(20) gray(3) / gray(2) gray(2)
        status_italic: ansi(208) gray(3) / gray(2) gray(2)
        status_bold: ansi(208) gray(3) Bold / gray(2) gray(2)
        status_code: ansi(229) gray(3) / gray(2) gray(2)
        status_ellipsis: gray(19) gray(1) / gray(2) gray(2)
        purpose_normal: gray(20) gray(2)
        purpose_italic: ansi(178) gray(2)
        purpose_bold: ansi(178) gray(2) Bold
        purpose_ellipsis: gray(20) gray(2)
        scrollbar_track: gray(7) None / gray(4) None
        scrollbar_thumb: gray(22) None / gray(14) None
        help_paragraph: gray(20) None
        help_bold: ansi(208) None Bold
        help_italic: ansi(166) None
        help_code: gray(21) gray(3)
        help_headers: ansi(208) None
        help_table_border: ansi(239) None
        preview: gray(20) gray(1) / gray(18) gray(2)
        preview_line_number: gray(12) gray(3)
        preview_match: None ansi(29) Underlined
        hex_null: gray(10) None
        hex_ascii_graphic: gray(18) None
        hex_ascii_whitespace: ansi(143) None
        hex_ascii_other: ansi(215) None
        hex_non_ascii: ansi(167) None
    }


    ###############################################################
    # File Extension Colors
    #
    # uncomment and modify the next section if you want to color
    # file name depending on their extension
    #
    ext-colors: {
        png: rgb(255, 128, 75)
        rs: yellow
    }
}
```
There's still one trick: you can be told that some string should be quoted but it can be precisely pointed on parsing contrary to the missing properties of TOML.

**Comment by AndydeCleyre** [comment]
Oh yeah, that does look good!

Can you elaborate on the trick you mention, or show an example?

**Comment by Canop** [comment]
My main problem with TOML, besides the [[array]] thing puzzling people, is this one:

```TOML
[[chars]]
name = "A"
value = 10 

[[chars]]
name = "B"
value = 11 

prop = 3
```

The only way to have "prop" not a part of the second element of the "chars" array is to put it before the array.

And so there are people adding a line at the end of the conf, because it's usual with other conf files, a line that they found in my doc or elsewhere, and not understanding why it doesn't work.

**Comment by hiqua** [comment]
Rust developers (so possible contributors) will be more familiar with TOML though. And you have premium support of this format by the Rust community. But maybe that's the case with HJSON as well.

I think that if you want to make the configuration more user-friendly, you could instead add some command line switches to change the configuration, à la `git config`. This way users who just need to change a few things could resort to the command line switches that would sanitize the input before putting it in the config, and more advanced users could still edit the TOML config directly.

Examples:
```
  git config --global diff.tool 'vimdiff'
  git config --global pull.ff only
  git config --global alias.a      "add"
```

There's probably a way to generate this kind CLI automatically from the configuration struct.

**Comment by Canop** [comment]
> But maybe that's the case with HJSON as well

HJSON has clearly not the same traction among Rust developers. All of them have to know TOML, that's clear. And even in the larger broot community, HJSON is less known today.

> I think that if you want to make the configuration more user-friendly, you could instead add some command line switches to change the configuration, à la git config. 

This is an excellent idea. It's related but isn't really an answer to the current issuer so I'll create a different issue if you don't do it.

**Comment by Canop** [comment]
The last commit introduces Hjson in broot:

* both Hjson and TOML files are read
* when there's both a config.toml and a config.hjson file in the config directory, Hjson is prefered
* when there's none, broot creates a hjson file

I'd really appreciate some tests before I release a new version.

**Comment by Canop** [comment]
I had to write a Hjson deserializer myself this week-end so a bug at this point would **not** be surprising

**Comment by Canop** [comment]
The new 1.1.10 version uses Hjson as the default configuration format.

**Comment by Stargateur** [comment]
> when there's both a config.toml and a config.hjson file in the config directory, Hjson is prefered

This will just create confusion, I think issue an error will avoid unnecessary debug from user side.

**Comment by Canop** [comment]
> > when there's both a config.toml and a config.hjson file in the config directory, Hjson is prefered
> 
> This will just create confusion, I think issue an error will avoid unnecessary debug from user side.

Maybe. I'm not sure anybody but the tester may encounter this situation, though.

**Comment by AndydeCleyre** [comment]
I know this discussion is old and done, and I'm happy with the hjson choice, but I recently found [NestedText](https://nestedtext.org/) and think it's pretty perfect and just wanted to mention it here. That said, I don't think there is a rust implementation yet.

**Comment by Canop** [comment]
@AndydeCleyre Interesting but if you want to use that format to read some configuration, don't you need some additional convention to decide how booleans or numbers are represented ? Those conventions are kind of simple but I find it strange to pretend you don't need them at some point when deserializing.

(with those conventions, making a serde derive based deserializer would probably be easy)

**Comment by AndydeCleyre** [comment]
The idea from the project is that any fancy non string types should only be the concern of the application code, not specified in the config file itself.

**Comment by dominiwe** [comment]
Nothing against Hjson but as someone more familiar with TOML, is there a way to convert my config directory to TOML or at least to generate a default config in TOML?

Asking because Hjson is obscure enough that I also didn't quickly find and tooling to do this... which lockes me into using Hjson.

**Comment by Canop** [comment]
Obscure ? Any JSON document is valid HJson. If you know JSON, you can edit a Hjson file.

(so a TOML to JSON converter can be used but the point of using Hjson is to have proper comments and a readable config organization)

**Comment by dominiwe** [comment]
Thanks for the instructions @AndydeCleyre.

Perhaps my use of the word obscure wasn't accurate. It wasn't in reference to the format itself but to the ecosystem around it. And by that I roughly meant me being unable to quickly find the right tooling.
