### ISSUE TITLE
Package question

### ISSUE THREAD

**Issue by voidpin** [Canop/broot#305]
Hi,
I was the one packaging `broot` for NetBSD.
Today I was at crates.io looking at some other stuff when I saw `broot-1.0.6`.
Looking at the tags here at github, there's no 1.0.6 release.
Are you planning to release only on crates.io? On NetBSD we pull the sources from github to create Rust packages, without a git tag will be much harder to maintain the package. I would have to pull from a specific commit and build from there.

Just wondering.
Thanks for any information on this.

**Comment by Canop** [comment]
@voidpin I just forgot to distribute on GitHub (and wouldn't have noticed until the next release without your issue). I'll fix that ASAP.

**Comment by voidpin** [comment]
Merci!

**Comment by Canop** [comment]
Done. I'll let you close the issue if it's good.

**Comment by voidpin** [comment]
Built and merged, thanks!
