### ISSUE TITLE
Show directories folded

### ISSUE THREAD

**Issue by savchenko** [Canop/broot#306]
## Is your feature request related to a problem? Please describe.

`broot` behaves like a `tree` by default.

## Describe the solution you'd like

Act like a file-manager. `ranger`, `mc`, you call it.

## Describe alternatives you've considered

Either accepting `broot` as it is or continuing using `ranger`.

## Additional context

Normally, I would expect file-manager to show directories first and folded. Some examples below.

### mc
![image](https://user-images.githubusercontent.com/300146/99957398-8b886380-2d7f-11eb-8926-59dc50e9a92b.png)

### ranger
![image](https://user-images.githubusercontent.com/300146/99957667-fa65bc80-2d7f-11eb-9876-7183b6105506.png)

### total-commander (Windows application)
![image](https://user-images.githubusercontent.com/300146/99957791-2c771e80-2d80-11eb-9144-c7628e93f442.png)

### far
![image](https://user-images.githubusercontent.com/300146/99958238-ed959880-2d80-11eb-9182-67116a89e35d.png)

**Comment by Canop** [comment]
It's possible (it was an option at the very beginning).
But *why?*
It wouldn't allow displaying more information, so what would be exactly the benefit ?

**Comment by savchenko** [comment]
> But why?

1. To show the most important data first: overview of what's inside of the folder
2. To follow the established convention and avoid surprising users at the first launch

**Comment by Canop** [comment]
broot provides the ability to see beyond the first level. That's the whole point.

I'm not interested in making broot show less, as this feature is already covered by all tools of the previous generations.

**Comment by vtopc** [comment]
Would be great to have some config option for this.

**Comment by quantonganh** [comment]
> Would be great to have some config option for this.

https://github.com/Canop/broot/issues/467
