### ISSUE TITLE
Add :next_same_depth and :previous_same_depth internals

### ISSUE THREAD

**Issue by onnyyonn** [Canop/broot#308]
This is not really a bug report, but rather proposal to change a current behaviour.

At a particular directory, both arrow keys and tab can be used to move the selection. I propose changing behaviour of the tab key to limit it to files/directories directly under the current directory only. This will be similar to how arrow keys and tab behaves differently for search results.

**Comment by Canop** [comment]
The purpose of tab cycling, the reason why it exists when there's also arrow keys, is it lets you cycle between *matches*.

Look at this screen:

![image](https://user-images.githubusercontent.com/617006/100131517-6af60180-2e84-11eb-80b3-806696e545d2.png)

The tab key lets you cycle between the 7 lines having a green part.

**Comment by onnyyonn** [comment]
The main idea behind this suggestion was to have a way to quickly move selection. Arrow keys take a lot of time because they go through subdirectories etc. too. Although I suggested tab, I am not particularly fixated on that. If you think tab shouldn't have this behaviour, what do you think about some additional shortcuts, like Alt+arrow?

**Comment by Canop** [comment]
There are two separate things:

* the internal, which defines the action
* the key binding, which can be changed

When using tab, you use the binding to the `:next_match` internal. I can add an internal, which could be something like `:next_same_level` and let you (or other users) define a key binding (which can be the `tab` key if you like).

So the discussion doesn't really need to be on the "tab" key, but on the available internals.

**Comment by onnyyonn** [comment]
Yes, you are right. I was too caught up in finding the right shortcut and couldn't articulate the actual issue very well.

> I can add an internal, which could be something like `:next_same_level` and let you (or other users) define a key binding (which can be the tab key if you like)

Yes, making `:next_same_level` (maybe `:previous_same_level` as well?) available will definitely make it possible what I was trying to achieve.

**Comment by Canop** [comment]
This can be tested with

```
[[verbs]]
invocation = "psd"
key = "ctrl-up"
internal = ":previous_same_depth"

[[verbs]]
invocation = "nsd"
key = "ctrl-down"
internal = ":next_same_depth"
```

I'm not sure it's really useful but it's costless and allows
experimentations.
