### ISSUE TITLE
launcher for fish shell

### ISSUE THREAD

**Issue by thorink** [Canop/broot#31]
It seems, that currently only bash and zsh are supported. I usually use the fish shell.

I looked a bit into it and ported the bash script to fish:

```fish
function br
    set f (mktemp)
    broot --outcmd $f $argv
    if test $status -ne 0
        rm -f "$f"
        return "$code"
    end
    set d (cat "$f")
    rm -f "$f"
    eval "$d"
end
```

I saved it to `~/.config/broot/launcher/fish/br` and also added this into my `~/.config/fish/fish.config`:

```fish
source /home/<username>/.config/broot/launcher/fish/br
```

The integration to the `broot --install` command is missing.

Currently I'm not able to integrate it into the broot code base, but I wanted to leave it here as a starting point for someone else. Maybe I also find some time to work on it myself, but we'll see.

**Comment by Canop** [comment]
> Currently I'm not able to integrate it into the broot code base, but I wanted to leave it here as a starting point for someone else.

I can take it from there. I'll probably create a dedicated branch and request some tests when I have a ready code.

**Comment by thorink** [comment]
Great, thanks! Send me a message when I can test something!

**Comment by Canop** [comment]
I guess you meant `config.fish` and not `fish.config` as you wrote.

I just pushed the "fish" branch, with the relevant installer.

Can you test installing with `broot --install` (after having removed what you previously manually added) ?

**Comment by Canop** [comment]
No tester available for fish ?
@thorink  ?

**Comment by thorink** [comment]
Sorry, I currently struggle with totally unrelated Linux booting problems. I my machine in up again, I will test it.
