### ISSUE TITLE
failed to parse command: Text ended before matching quote was found for "

### ISSUE THREAD

**Issue by oliverpool** [Canop/broot#316]
I am trying to force broot to open a new terminal on a verb:
```
[[verbs]]
invocation = "edit"
key = "enter"
shortcut = "e"
execution = "xterm -e \"kak {file}\""
```

However it fails wih 
```
failed to parse command: Text ended before matching quote was found for "
```

The log indicates

```
11:21:56 [ INFO] Executing not leaving, launchable Program { exe: "termite", args: ["-e", "\"kak", "/home/path/to/file\""], working_dir: None }
```

**Configuration:**
 - OS: Arch Linux
 - broot 1.0.7

**Comment by Canop** [comment]
It's a tokenization bug in broot. I'll fix it ASAP. Thanks for the report.

**Comment by oliverpool** [comment]
In the meantime, I have created a `open-kak.sh` script
```
#!/bin/bash
$(termite -e "kak \"$1"\") &
```
and ajusted the verb:
```
[[verbs]]
invocation = "edit"
key = "enter"
shortcut = "e"
execution = "/home/olivier/.config/broot/open-kak.sh {file}"
leave_broot = false
```

Inspired by this video: https://youtu.be/Wo1G6rW_W5k?t=516

**Comment by oliverpool** [comment]
Apparently you need an array of arguments, you could let the user configure it in toml:
```
[[verbs]]
invocation = "edit"
key = "enter"
shortcut = "e"
execution = "xterm"
execution_args = ["-e", "kak {file}"]
```
With a fallback to the current behavior if `execution_args` is not set.

**Comment by Canop** [comment]
> Apparently you need an array of arguments, you could let the user configure it in toml:

Maybe. That's what I did in more recent applications like bacon: https://github.com/Canop/bacon#define-your-own-jobs

I should probably handle the obvious quote case AND provide an alternate explicit syntax as an array.

**Comment by Canop** [comment]
This should solve the problem. I've still made an issue for the suggestion you made: https://github.com/Canop/broot/issues/319

**Comment by oliverpool** [comment]
I just compiled the master branch and it works fine!

Merci beaucoup :smile:
