### ISSUE TITLE
CC not found when doing cargo install

### ISSUE THREAD

**Issue by athaa** [Canop/broot#324]
**Describe the bug**
CC not found when doing cargo install

**To Reproduce**
fresh linux install (without build-essential packages(gcc, cc, make etc)) : 
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
cargo install broot
**Expected behavior**
build/install sucessful
**Screenshots**

![Capture d’écran (2)](https://user-images.githubusercontent.com/3407800/103661914-908c2580-4f6f-11eb-8522-9d1115579ed9.png)

**Configuration (please complete the following information):**
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
 uname -a
Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Canop** [comment]
For your case this would probably be fixed with

    sudo apt install build-essential

(please confirm)

but I'll keep the issue open because I need to either fix the build process (maybe removing a dependency) or fix the broot install documentation.

**Comment by athaa** [comment]
I confirm that installing build-essential package fix the bug.
Thank you for the help.
