### ISSUE TITLE
Mouse can't be used to select in nano if broot wasn't quitted

### ISSUE THREAD

**Issue by Canop** [Canop/broot#325]
When launching nano from broot, the mouse isn't usable for selection if `leave_broot` is set to `false`.

**Comment by Canop** [comment]
This has been observed by @ovizii (https://miaou.dystroy.org/3490?broot#14554456)

**Comment by ovizii** [comment]
Thanks. This is what it looks like if you set leave_broot: false - as soon as you click the mouse or select text the strange symbols appear on top (see red marking)

![image](https://user-images.githubusercontent.com/837902/104492830-7d630080-55d4-11eb-86ef-46a0977d74a2.png)
