### ISSUE TITLE
Use same scoring function as `fzf` for fuzzy searches

### ISSUE THREAD

**Issue by sgraf812** [Canop/broot#327]
I'm using broot as a file selector (in fuzzy path search mode, e.g. `p/`) in a pretty big directory tree and it works marvellous. The only repeated gripes I'm having with it are due to its scoring function for fuzzy matches, which is sometimes very off compared to `fzf`.

Here's an example: If I type in `p/IdIn`, the (to me) relevant file is `compiler/GHC/Types/Id/Info.hs`. But what broot selects is `compiler/GHC/Iface/UpdateIdInfo.hs`. In fact, my preferred result isn't even among the matches!

By constrast, if I use `fzf` then `compiler/GHC/Types/Id/Info.hs` is the first hit for `IdIn`.

I don't know what `fzf` does, but it's great! I'd like the same in `broot`. And there even is [`skim`](https://github.com/lotabout/skim), a Rust clone which offers a library. But trying it on my code base similarly brings up `compiler/GHC/Iface/UpdatedIdInfo.hs`, so from my position switching to that would win nothing. So maybe there is no way other than copying from https://github.com/junegunn/fzf/blob/32c493e994288f63c2ceec1dbeaadc5de7399552/src/algo/algo.go?

That's a lot to ask, of course. But currently I find `fzf` to yield much more relevant results.

**Comment by Canop** [comment]
> In fact, my preferred result isn't even among the matches

The problem may thus be not even related to the scoring. It's possible there are too many matches and broot thinks it doesn't have to go so deep. But It's hard to tell there for me.

**Comment by Canop** [comment]
If you want to try tune the settings of the fuzzy search, you may change the values [here](https://github.com/Canop/broot/blob/master/src/pattern/fuzzy_pattern.rs#L10) and see if you can have something more like your expectations.
If you want to venture there I'd suggest you come and chat on [miaou](https://miaou.dystroy.org/3490).

**Comment by sgraf812** [comment]
Ah, that makes sense. Maybe we might have to keep searching then, but I'm not sure if that's against `broot`'s philosophy.

Maybe I'll try hacking on it a bit this weekend :)

**Comment by Canop** [comment]
Can you try doing `:total_search` so that you see if the result list is more relevant when asking broot to look at all files ?

**Comment by sgraf812** [comment]
Basically the same as without `:total_search`:

![Screenshot 2021-01-21 180359](https://user-images.githubusercontent.com/1151264/105384918-0ef4f280-5c13-11eb-9095-84b1ec805010.png)

I think the important part is rating the initial `I` as matching the `Id/` component of the path.

**Comment by Canop** [comment]
Hum. Your desired file is one tab away. I don't find the result ridiculous.

Part of the scoring here is the depth: broot [prefers](https://github.com/Canop/broot/blob/master/src/tree_build/builder.rs#L123) to select files that are close to your current position.
Another reason of the choice is the fact there's no cut in the pattern.

**Comment by sgraf812** [comment]
Yes, I think weighing capital letters as "begin of a path component" might be the key to my example. I'll try to note down a few other examples as I come across them.
