### ISSUE TITLE
Changing directory does not work if name contains space

### ISSUE THREAD

**Issue by FallenWarrior2k** [Canop/broot#329]
**Describe the bug**
Trying to use Alt-Enter or the `cd` verb to switch to a directory that has a space in its name fails.
Logs: [broot.log](https://github.com/Canop/broot/files/5875314/broot.log)

**To Reproduce**

1. Create a directory that has a space in its name, e.g. `mkdir 'bar baz'`.
2. Open Broot.
3. Select the newly created directory.
4. Hit Alt-Enter or type `cd` to attempt to change into it.

[![asciicast](https://asciinema.org/a/hqp01j8eUMm8kLtX9x6Lnydwx.svg)](https://asciinema.org/a/hqp01j8eUMm8kLtX9x6Lnydwx)

**Expected behavior**
Changing directories should work normally, independent of the names of 

**Configuration (please complete the following information):**
- broot version: 1.2.0
- OS: Arch Linux
- Version: rolling
- Relevant configuration items: none

**Additional context**
As visible in the Asciicast, I'm using Zsh. I'm mentioning this because Zsh has in the past caused issues that I initially misattributed to other tools.

**Comment by Canop** [comment]
I confirm the problem in bash. It should be recent enough as it's sometimes which was tested before.
