### ISSUE TITLE
When -o is set, create the output file if it does not exist

### ISSUE THREAD

**Issue by Ryujinra** [Canop/broot#33]
I think that the expected behavior should be that the destination file is created if it does not already exist when "-o {FILENAME}" argument is passed. 

Instead, if you supply a file that does not exist yet, you get an IO Error:

> \# br -o result.txt
> IO Error : "No such file or directory (os error 2)"

**Comment by Canop** [comment]
I didn't expect that people would want to have a file dynamically created this way, but I see no harm in creating the file if it doesn't exist.

**Comment by Ryujinra** [comment]
My use case is I occasionally will use `br -o /tmp/tmpfile` or `br -c "somefile :print_path" -o /tmp/tmpfiile` to get the path into a file that I can pipe into some arbitrary program, since there is no way to capture the output of broot directly. This was brought up in #25 and this was my best solution to obtaining the path of the selected file.

The reason I sometimes use a different tmpfile is that `-o` always appends to the target file (although I suppose I could just ensure my function deletes the file after each use, but I also sometimes use the path multiple times).
