### ISSUE TITLE
[whale-spotting regressions] v1.0.8 and v1.0.9 do not have 'special-paths' hide as well as v1.0.7

### ISSUE THREAD

**Issue by bluz71** [Canop/broot#330]
Hello,

I use `br --whale-spotting` quite often. However I have been a little lazy with Homebrew and I haven't updated broot in quite a while.

I just upgraded from 1.0.7 to 1.2.0 and notice a couple regressions, both related to special-paths hidding (aka paths that should be ignored).

I use `[special-paths]` to hide certain directories because either they are not useful or they are housed on slow network drives, my setting:

```
[special-paths]
"/home/dennis/encrypted" = "hide"
"/home/dennis/.Private" = "hide"
```

With broot v1.0.7, all good, no issue as seen in this screenshot (works perfect, and fast):

![1_0_7](https://user-images.githubusercontent.com/11382509/105938787-06d20280-60ac-11eb-8597-17a01af830c1.png)

With v1.0.8 there is now a size indicator in the top left corner. That compution however is **not ignoring hidden paths**, hence in my case it is calculating the size including my large and slow network drive as seen in this screenshot:

![1_0_8](https://user-images.githubusercontent.com/11382509/105938929-4e588e80-60ac-11eb-8f16-f83e079d88ed.png)

Notice the 682GB value, this includes my network drive which I explicitly hide in the special-paths stanza. Also the graphic size indicator is all out of proportion for each directory because the hidden directory is being including in the overall size. Whale spotting is now about 50 times slower than with release v1.0.7, this is the main issue.

The second regression is that v1.0.9 appears to be ignoring the special-paths stanza altogether as seen in this screenshot:

![1_0_9](https://user-images.githubusercontent.com/11382509/105939096-98da0b00-60ac-11eb-8da2-d8dc12796484.png)

Looking at the v1.0.9 I don't see any mention of syntax change. I assume there could well be a regression. The circled directories are the two I explicitly want to hide.

Hopefully these issues are easily fixable.

I will stick with version v1.0.7 in the meantime.

**Comment by Canop** [comment]
OK, the (main) bug is that `special-paths` (with a dash) was accepted before but in the current version only `special_paths` (with an underscore) works.

I'll fix that.

**Comment by Canop** [comment]
I've added another issue for the request of not including the sizes of hidden directories as it's not so easy to deal with (even deciding whether it's the right choice), so it will make triage easier.
