### ISSUE TITLE
Changing panels on macOS

### ISSUE THREAD

**Issue by basbebe** [Canop/broot#334]
The Shortcuts `CTRL-Left` and `CTRL-Right` on macOS are being used to switch between 'spaces'.

This does not seem to work in my `conf.hjson` (does nothing):
```
                # switch panels on macOS
		{
			key: alt-[
			execution: ":panel_left"
		}
		{
			key: alt-]
			execution: ":panel_right"
		}

```

**Comment by basbebe** [comment]
this seems to work now:

```
                # switch panels on macOS
		{
			key: alt-Left
			execution: ":panel_left"
		}
		{
			key: alt-Right
			execution: ":panel_right"
		}
```

It doesn/t "overwrite" the original command, though.
What would be the right way to do that?

**Comment by Canop** [comment]
> It doesn/t "overwrite" the original command, though.

What do you mean ? Is the problem that the old shortcut is still displayed in the help ?

**Comment by basbebe** [comment]
yes.
And I *know* that this isn't a *problem* 😛– I'm just curious wether this is possible / desired.

I now came up with this, which should be more in line with the current syntax of the config.
There ist no "description" field though, is there?

```json
                # switch panels on macOS
		{
                        invocation: panel_left
			key: alt-Left
			internal: ":panel_left"
		}
		{
                        invocation: panel_right
			key: alt-Right
			internal: ":panel_right"
		}
```

**Comment by Canop** [comment]
Removing a shortcut should be possible some day. There's an issue for it: https://github.com/Canop/broot/issues/328

No, there's no description.

**Comment by basbebe** [comment]
any idea why `alt-]` and `alt-[` don't work at all?

**Comment by Canop** [comment]
Those work on my computer (not easy to do on AZERTY, though) but shortcuts not working are very very dependent on the OS and terminal: both intercept many key combinations for their own use.

**Comment by basbebe** [comment]
macOS 11.2, kitty terminal, US ANSI layout

🤷‍♂️
