### ISSUE TITLE
Fish shell function: use `--wraps`

### ISSUE THREAD

**Issue by basbebe** [Canop/broot#337]
This way, `br` can use the shell completions installed for `broot`.

```fish
[…]

function br --wraps=broot
    […]
```

https://fishshell.com/docs/current/cmds/function.html
> `-w WRAPPED_COMMAND` or `--wraps=WRAPPED_COMMAND` causes the function to inherit completions from the given wrapped command.

**Comment by Canop** [comment]
Can you test the whole and make a PR ?
