### ISSUE TITLE
Filters/verbs in a command passed to broot with `--cmd` are only parsed correctly when separated by spaces

### ISSUE THREAD

**Issue by Ryujinra** [Canop/broot#34]
In broot interactive mode, you can type a query like "test:s" and it will display results for "test" and toggle sizes. However, neither the "test" filter or the size toggle will register in broot if you start broot like so:

`br -c "test:s"`

However, this command works as expected:

`br -c "test :s"`

Thanks.

**Comment by Canop** [comment]
I don't think that's exact.

In my tests, according to what I expect from the code, the `:s` command is executed if you do `br -c test:s`.

What users can legitimately find surprising is that `test` is ignored in `test:s`.

What happens is a little like if you start a search with "test" and then instantly executes a command: the search is canceled and the command is executed on the non filtered version of the tree.

This isn't ideal but I'm not sure there's really an urgent need to change that as you can separate the two parts.
