### ISSUE TITLE
Feature request: allow include in config

### ISSUE THREAD

**Issue by basbebe** [Canop/broot#340]
It would be great if something like `include: filename.hjson` in the config  would be allowed.

Two usecases:

- `broot.local.hjson`, with settings that should not be distributed to different machines (like system-specific shortcuts or bookmarked folders)
- `themes/sometheme.hjson` (have a folder with different available skins)

**Comment by Canop** [comment]
Some use cases should already been covered with broot's ability to use several config files at launch with `--conf` (you can change your launch alias/function/shortcut to have this setting).

**Comment by Stargateur** [comment]
this is very difficult to do, add a lot of complexity, I don't think it's worth it for a simple config file

**Comment by Canop** [comment]
Conditional imports incoming.
