### ISSUE TITLE
broot should limit height when printing the tree

### ISSUE THREAD

**Issue by schemar** [Canop/broot#341]
**Describe the bug**
When passing the `--height` flag to broot,
Then the printed tree should be limited to that height
But instead the output is much longer.

It appears the printed tree is not pruned at all.

I get from https://dystroy.org/broot/export/ that it should behave according to my description.
I hope I don't misunderstand the documentation.

**To Reproduce**
Steps to reproduce the behavior: run `br --height=20 --cmd ":pt"`
Alternatively, run `br --height=20` and execute ` pt` from within.

Make sure there is more to show than your set limit so that you see that the output is actually longer than the specified height.

**Expected behavior**
I expect the output to be max 20 lines long.
But instead the output is much longer (much longer than `tput lines` even)

**Configuration:**
- broot version: 1.2.1
- OS: Linux
- Version: Fedora 33

Thank you for your time! :blush:

**Comment by Canop** [comment]
Hum. Curiously it does work for me. Can you try with `broot` instead of `br` ? What's your shell?

![image](https://user-images.githubusercontent.com/617006/106957800-c708bc00-6738-11eb-9e0d-749f273f449b.png)

**Comment by schemar** [comment]
I am on ZSH. The interface of broot is actually limited. Just the printed tree isn't.

`broot` instead of `br` has the same behavior.

It seems it works when it is able to prune inside sub-directories, but not when the very directory I am in has more files than the limit. Is that actually expected?

Smaller, constructed example:
![image](https://user-images.githubusercontent.com/1196244/106958289-6fb71b80-6739-11eb-82a9-921dc593a886.png)

Here it does work if many files are inside a sub-directory:
![image](https://user-images.githubusercontent.com/1196244/106958437-a55c0480-6739-11eb-8f37-14128a8ad250.png)

**Comment by Canop** [comment]
> It seems it works when it is able to prune inside sub-directories, but not when the very directory I am in has more files than the limit.

Ok, with this now I reproduce the bug.

> Is that actually expected?

No, it's a bug. I'll fix it.

**Comment by schemar** [comment]
Thanks! And thank you for `broot` :blush:
