### ISSUE TITLE
Release 1.2.2 has an outdated lockfile

### ISSUE THREAD

**Issue by svenstaro** [Canop/broot#342]
Trying to build 1.2.2 with `--locked` results in:

```
error: the lock file /build/broot/src/broot-1.2.2/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, use the --offline flag.
```

Could you push a fixed release?

**Comment by Canop** [comment]
How did you get the release ? With cargo or GitHub ?

**Comment by svenstaro** [comment]
I'm the maintainer of the official broot package in Arch Linux and we always fetch Rust stuff using the GitHub release archive like [here](https://github.com/archlinux/svntogit-community/blob/packages/broot/trunk/PKGBUILD).

**Comment by Canop** [comment]
The problem is the tag points to the wrong commit. I don't see any good solution here. Forcing the tag to a different commit looks risky. So I probably need another tag, with a different semantic.

**Comment by Canop** [comment]
At this point I should probably just jump to 1.2.3

**Comment by svenstaro** [comment]
FWIW for my own Rust software, I like using [cargo-release](https://github.com/sunng87/cargo-release) to make sure this kind of thing doesn't happen.

**Comment by Canop** [comment]
I'll have a look but I do other things with my current script like updating the changelog with date and version, building half a dozen versions and building an archive from them (including complete scripts and version marker file), deploying it on my server, updating the web site, etc. so it may not be trivial to change

**Comment by svenstaro** [comment]
Thanks for the swift fix.
