### ISSUE TITLE
Feature request: Configuration option for setting cycling from last to first result on or off

### ISSUE THREAD

**Issue by E3D3** [Canop/broot#344]
**Did a discussion occur before?**
Yes, we spoke about this in the Broot chat room.

**Is your feature request related to a problem? Please describe.**
When scrolling down with arrow-down key I'm sometimes confused about the current location because I didn't notice that the results cycled from the end back to the beginning.

**Describe the solution you'd like**
I like to have a configuration option to set cycling on or off.

**Describe alternatives you've considered**
The only alternative I know to prevent 'loss of location awareness' is to avoid the arrow-down key as much as possible, and use the page-down key for scrolling instead.

**Additional context**
...

My request is for a configuration option to set cycling from the last result back to the first result off or on.

**Comment by Canop** [comment]
I've added the `:line_up_no_cycle` and `:line_down_no_cyle` internals

They may be mapped instead of :line_up and :line_down when you
don't want to cycle (ie arrive on top when you go down past
the end of the tree/list)

**Comment by E3D3** [comment]
It works here exactly as I wished for. Thank you very much.
