### ISSUE TITLE
Opinion needed: Yes or No for limiting to 2 the number of panels

### ISSUE THREAD

**Issue by Canop** [Canop/broot#345]
In retrospect, I'm not sure it's useful to have more than 2 panels. I never use this ability.

Limiting the number of panels to 2 allow easier navigation & open/close shortcuts.

But before I remove a broot feature, I'd like to be sure I won't break any useful workflow. So please tell me if you sometimes use more than 2 panels and why.

**Comment by jahoyne** [comment]
You asked, @Canop, if people used more than two panels, and while I don't use more than two I hope you'll forgive this comment. 
At first, I found the multiplication of panels confusing, but learned to avoid spawning extra panels erroneously when my intention was to navigate between two panels. I'd like to see the behaviour where the shortcut to move to the next panel, e.g. <kbd>Ctrl+right arrow</kbd>, would simply cycle between two existing panels.
I wonder if you find many folk use in excess of two panels for their workflows, would the possibility of adding a configuration for the max number of panels: _Limit Panels to n_

Thanks, for a great utility

**Comment by Canop** [comment]
> I wonder if you find many folk use in excess of two panels for their workflows, would the possibility of adding a configuration for the max number of panels: Limit Panels to n

If nobody seems to think spawning panels easily should be encouraged, I'll probably  have a limit in conf, with a default to 2.

**Comment by vanhtuan0409** [comment]
I think you can add a configuration to limit how many panels can be spawned. For me, only 1 is needed so I might want to disable the function of creating new panel
