### ISSUE TITLE
Request: Implement multiple file selection.

### ISSUE THREAD

**Issue by BogdanLysenko** [Canop/broot#354]
This request was made before, but was ignored: https://github.com/Canop/broot/issues/266

This is only my opinion, but missing multiple file selection for using cp,mv,rm,etc makes file manager completely useless in practice. I know broot is not exactly such one but it can be even bigger than that if several additional features will be added.

I'm just ordinar user, so there is not much of I can advise) 
But at the first look, selection may be done by pressing, for example, SPACE (in Ranger way), then chosen ones (actually the list of strings containing their paths) should be placed in some kind of buffer or variable (or you can call it a register in vim way). Then (or before that) you can type a verb like cp and put that register name (some of what can not to be a filename like ^:*"@#$) after this, for example: `cp * DEST` or `rm *` or `cpp *`, then press ENTER... PROFIT!!! 
In shell it will be interpreted like `<cmd> {path1,path2,path3,...} [DEST]`.
It also supposed that some kind of highlighting will present. You can see selection on current level. When you are moving between levels of tree, some of those can go out of view, but it's naturally that they apears again when you return to initial level (because all of them are stored in a buffer).
Obviously, "unselect" function should present (preferably at the same key as selecting, suppose SPACE).
Also there should present "free buffer" command on some key.

For simplicity you may consider automaticaly puting buffer as argument of command (implicity as registry name after command or no) because it's obvious from context that one aims to manipulate exactly selected files.

About alternatives, If someone can propose more optimal way to implement this such necessary feature I'd be glad if you suggest such a way below.

In addition I want to say that I much appreciate your work on this project. I like its simplicity and aesthetics. I belive it will spread widely.

**Comment by Canop** [comment]
Please don't duplicate requests for changes just because the previous one wasn't implemented.

I'll close this request as duplicate but I'd appreciate if you'd repeat your interesting comment on the previous request.

**Comment by BogdanLysenko** [comment]
@Canop, Ok, I'm sorry for misunderstanding.
