### ISSUE TITLE
empty help and interface bug

### ISSUE THREAD

**Issue by Fatpandac** [Canop/broot#357]
**Expected behavior**
open broot in PowerShell it's not over the window.
type "?", I got an empty space.

**Screenshots**
![image](https://user-images.githubusercontent.com/30423976/110058442-466fc680-7d9d-11eb-8ebf-2a6e9de2a9c2.png)

**Configuration (please complete the following information):**
- broot version: [broot 1.2.7]
- OS: [Windows10]
- Version: [1909]

**Comment by Canop** [comment]
It looks like there's a crash.

Can you please retry with `BROOT_LOG=debug broot` and show me the `broot.log` file ?

**Comment by Fatpandac** [comment]
I can't find broot.log in broot's file.
