### ISSUE TITLE
Allow multiple keys per verb

### ISSUE THREAD

**Issue by runiq** [Canop/broot#358]
**Did a discussion occur before?**

[Yes](https://miaou.dystroy.org/3?Code_Croissants#14766148)

**Is your feature request related to a problem? Please describe.**

I would like to assign multiple keybindings to a single verb, so that they show up like the multiple keybindings for builtin commands. I know I can define a verb multiple times instead, with different keys, but that results in multiple entries in the help table too.

**Describe the solution you'd like**

The best would probably be a `keys` attribute for verbs, which takes a list, and conflicts with the (singular) `key` attribute.

**Describe alternatives you've considered**

- Keep the current workaround: Defining verbs multiple times in my config, with a single keybinding per definition (clutters verb table in help screen)
- Keep the `key` attribute, separate keys with spaces (`"ctrl-c ctrl-d"`) or commas (`"ctrl-c,ctrl-d"`)

**Comment by Canop** [comment]
Example:

		{
			keys: [
				f2
				ctrl-b
			]
			external: xdg-open https://dystroy.org/broot
			leave_broot: false
		}

**Comment by Canop** [comment]
If you don't want to compile yourself, wait for 1.2.8, probably by end of week or start of next one

**Comment by runiq** [comment]
Works fine, thank you so much! :)
