### ISSUE TITLE
Feature request: Pass any text following a custom verb to the execution command

### ISSUE THREAD

**Issue by Ryujinra** [Canop/broot#36]
broot integrates nicely with fzf-marks for bookmarking using a custom verb as follows:

```
[[verbs]]
name = "mark"
invocation = "mark"
execution = "cd {directory} && mark"
from_shell = true
```

However, 'mark' can take an argument which is then used as the name of the bookmark. If you try typing `:mark {mybookmark_name}`, broot does not recognize that a verb has been typed.

In other words, being able to pass on the text that follows a custom verb would be a useful feature.

In fact, the ability to capture the text after a verb would more generally enable the ability to execute an on-the-fly command with the current directory or file as the trailing argument. E.g. a 'multipurpose' verb with the execution syntax something like: `execution = "{command} {file}"` (where {command} is the trailing text after the verb) would enable things like: `:custom mpv --loop`

I think this is a way of greatly enhancing the flexibility of broot without needing to be able to capture paths from stdout.

Thanks for your work and for your consideration.

**Comment by Canop** [comment]
This is something that I was already trying to design, for other commands (rm, mkdir, rename, etc.)

I was more thinking on a pattern matching design, which would then not be limited to space separated tokens (I have an example in another project of mine: https://github.com/Canop/resc#simple-regex-based-task-generation).

This is definitely something I'll be working on.

**Comment by Canop** [comment]
I've made progress.

Examples of verbs which can be configured now

```
[[verbs]]
invocation = "mkdir {subpath}"
execution = "/bin/mkdir -p {directory}/{subpath}"
leave_broot = false

[[verbs]]
invocation = "create {subpath}"
execution = "/usr/bin/nvim {directory}/{subpath}"

[[verbs]]
invocation = "rm"
execution = "/bin/rm -rf {file}"
confirm = true
leave_broot = false

[[verbs]]
invocation = "mv {subpath}"
execution = "/bin/mv {file} {parent}/{subpath}"
leave_broot = false


[[verbs]]
invocation = "blop {name}\\.{type}"
execution = "/bin/mkdir {parent}/{type} && /usr/bin/nvim {parent}/{type}/{name}.{type}"
from_shell = true
```

Notice the `\\.` ? That's because the invocation pattern is interpreted as a regular expression
(with just a shortcut for the easy case, enablinrg `{name}`.
The whole regular expression syntax may be useful for more complex rules.
Let's say we don't want the type to contain dots, then we do this:

```
[[verbs]]
invocation = "blop {name}\\.(?P<type>[^.]+)"
execution = "/bin/mkdir {parent}/{type} && /usr/bin/nvim {parent}/{type}/{name}.{type}"
from_shell = true
```

![selection_999 203](https://user-images.githubusercontent.com/617006/53654065-168d0600-3c4d-11e9-94a0-aa1cea60d286.png)

![selection_999 204](https://user-images.githubusercontent.com/617006/53654130-3fad9680-3c4d-11e9-95ae-df72faf32604.png)

**Comment by Ryujinra** [comment]
This looks great. `leave_broot = false` looks especially useful; perhaps even [ueberzug] (https://www.github.com/seebye/ueberzug) can be used inside broot for previewing images now.

Regular expressions do seem powerful in this context as well. We can use it to sanitize input or to prevent matching input that is not syntactically valid as well. I would stick something in my `rm` verb to prevent removing certain top-level dirs accidentally, for instance.

**Comment by Canop** [comment]
This is fully testable in the verb_arguments branch (some confirmations would help me merge it faster into master).

Two remarks:

* configuration changes, it's better to just drop your conf.toml file before launching broot
* leave_broot=false doesn't play well with terminal application. I don't think I'll be able to fix that soon (I'm more and more considering dropping termion for crossterm, btw)

**Comment by Ryujinra** [comment]
Did some testing; all of the verbs I've written at the bottom of this post work as expected IF you actually input some printable text to be captured by the regular expression. For instance, if you decide not to add any additional mpv arguments, it will pass this command literally: `mpv {args} somefile.mp4`  (i.e. the literal characters `{args}` are passed to mpv). It looks like `.*` is not being interpreted correctly as "zero or more" instances.

It behaves the same way if you type a syntactically invalid command (no regex match); `mpv {args} somefile.mp4` will be passed literally. It would be nice if it still displayed the invocation syntax (as it does now) when there is no match, but refused to execute it.


As expected, terminal apps don't do anything from within broot with `leave_broot = false`. A `No such file or directory (os error 2)` is thrown (gracefully at least), much like if you try piping or capturing broot's standard output from the terminal (#25). I tested [urbainvaes/fzf-marks](https://www.github.com/urbainvaes/fzf-marks) (fzm and mark functions) and [seebye/ueberzug](https://www.github.com/seebye/ueberzug).

I think it might be the right move switching to crossterm, expecially if it helps deal with this issue, and might even be a fix for #11 now that crossterm is very close to being able to handle mouse events (TimonPost/crossterm#93 #TimonPost/crossterm#81)


```
[[verbs]]
name = "mark"
invocation = "mark (?P<bookmark_name>.*)"
execution = "cd {directory} && mark {bookmark_name}"
from_shell = true

[[verbs]]
name = "bookmarks"
invocation = "fzm (?P<filter>.*)"
execution = "fzm {filter}"
from_shell = true

[[verbs]]
name = "mpv"
invocation = "mpv (?P<args>-.*)"
execution = "mpv {args} {file}"
from_shell = true

[[verbs]]
name = "arbitrary file operation"
invocation = "!f (?P<arbitrary_operation>.+)"
execution = "{arbitrary_operation} {file}"
from_shell = true

[[verbs]]
name = "arbitrary dir operation"
invocation = "!d (?P<arbitrary_operation>.+)"
execution = "{arbitrary_operation} {directory}"
from_shell = true
```

**Comment by Canop** [comment]
In case you missed it, I pushed yesterday a stricter control of invocation matching. My initial idea was that displaying the unfilled group in the command in the status line was clear enough but you changed my mind. It's obviously better to prevent the incomplete command from being ran.

I'll have to rewrite the documentation before I merge into master.

**Comment by Ryujinra** [comment]
I did checkout and test the latest commit. I've been using the verb_argument branch for a couple days now and have not noticed any other issues than the ones I've mentioned.

I also wrote a few more much larger regular expressions surveying most regex operators and have not run into any unexpected behavior.

**Comment by Canop** [comment]
The new verb arguments have been merged into master.
A new version, 0.7.0 has been released.
A new documentation site explains everything (I hope): https://dystroy.org/broot/

I consider this issue as complete. New ideas or problem should go in a new one.

Thans @Ryujinra for this feature request ;)
