### ISSUE TITLE
Command `input_del_word_left` causes process to crash

### ISSUE THREAD

**Issue by wfxr** [Canop/broot#361]
**Is everything clear?**

I think so.

**Describe the bug**

`input_del_word_left` command causes the process to panic.

<details><summary>broot.log</summary>
<p>
19:15:31.680 [INFO] cli_log::init: Starting broot v1.2.9-dev with log level DEBUG
19:15:31.688 [DEBUG] broot::cli: Conf::from_default_location() took 7.259661ms
19:15:31.688 [DEBUG] broot::cli: config: Conf {
    files: [
        "/home/wenxuan/.config/broot/conf.hjson",
    ],
    default_flags: None,
    date_time_format: None,
    verbs: [
        VerbConf {
            invocation: Some(
                "edit",
            ),
            internal: None,
            external: None,
            execution: Some(
                String(
                    "$EDITOR +{line} {file}",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: None,
            keys: [],
            shortcut: Some(
                "e",
            ),
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
        VerbConf {
            invocation: Some(
                "edit",
            ),
            internal: None,
            external: Some(
                String(
                    "$EDITOR {file}",
                ),
            ),
            execution: None,
            cmd: None,
            cmd_separator: None,
            key: Some(
                "ctrl-enter",
            ),
            keys: [],
            shortcut: None,
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: Some(
                "file",
            ),
            set_working_dir: None,
            description: None,
        },
        VerbConf {
            invocation: Some(
                "create {subpath}",
            ),
            internal: None,
            external: None,
            execution: Some(
                String(
                    "$EDITOR {directory}/{subpath}",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: None,
            keys: [],
            shortcut: None,
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
        VerbConf {
            invocation: Some(
                "git_diff",
            ),
            internal: None,
            external: None,
            execution: Some(
                String(
                    "git difftool -y {file}",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: None,
            keys: [],
            shortcut: Some(
                "gd",
            ),
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
        VerbConf {
            invocation: Some(
                "terminal",
            ),
            internal: None,
            external: None,
            execution: Some(
                String(
                    "$SHELL",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: Some(
                "ctrl-t",
            ),
            keys: [],
            shortcut: None,
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: Some(
                true,
            ),
            description: None,
        },
        VerbConf {
            invocation: None,
            internal: None,
            external: None,
            execution: Some(
                String(
                    ":line_up",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: Some(
                "ctrl-p",
            ),
            keys: [],
            shortcut: None,
            leave_broot: None,
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
        VerbConf {
            invocation: None,
            internal: None,
            external: None,
            execution: Some(
                String(
                    ":line_down",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: Some(
                "ctrl-n",
            ),
            keys: [],
            shortcut: None,
            leave_broot: None,
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
        VerbConf {
            invocation: None,
            internal: None,
            external: None,
            execution: Some(
                String(
                    ":page_up",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: Some(
                "ctrl-u",
            ),
            keys: [],
            shortcut: None,
            leave_broot: None,
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
        VerbConf {
            invocation: None,
            internal: None,
            external: None,
            execution: Some(
                String(
                    ":page_down",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: Some(
                "ctrl-d",
            ),
            keys: [],
            shortcut: None,
            leave_broot: None,
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
        VerbConf {
            invocation: None,
            internal: None,
            external: None,
            execution: Some(
                String(
                    ":input_del_word_left",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: Some(
                "ctrl-w",
            ),
            keys: [],
            shortcut: None,
            leave_broot: None,
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            description: None,
        },
    ],
    skin: Some(
        {
            "link": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 104,
                                g: 157,
                                b: 106,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "default": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 235,
                                g: 219,
                                b: 178,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: Some(
                                Rgb {
                                    r: 189,
                                    g: 174,
                                    b: 147,
                                },
                            ),
                            background_color: Some(
                                Rgb {
                                    r: 40,
                                    g: 40,
                                    b: 40,
                                },
                            ),
                            attributes: Attributes(
                                0,
                            ),
                        },
                    },
                ),
            },
            "perm_x": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 152,
                                g: 151,
                                b: 26,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "content_match": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 189,
                                g: 174,
                                b: 147,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            4,
                        ),
                    },
                },
                unfocused: None,
            },
            "status_italic": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 211,
                                g: 134,
                                b: 155,
                            },
                        ),
                        background_color: Some(
                            Rgb {
                                r: 50,
                                g: 48,
                                b: 47,
                            },
                        ),
                        attributes: Attributes(
                            16,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: None,
                            background_color: None,
                            attributes: Attributes(
                                0,
                            ),
                        },
                    },
                ),
            },
            "help_paragraph": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: None,
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "preview": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 235,
                                g: 219,
                                b: 178,
                            },
                        ),
                        background_color: Some(
                            Rgb {
                                r: 40,
                                g: 40,
                                b: 40,
                            },
                        ),
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: Some(
                                Rgb {
                                    r: 235,
                                    g: 219,
                                    b: 178,
                                },
                            ),
                            background_color: Some(
                                Rgb {
                                    r: 40,
                                    g: 40,
                                    b: 40,
                                },
                            ),
                            attributes: Attributes(
                                0,
                            ),
                        },
                    },
                ),
            },
            "selected_line": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: None,
                        background_color: Some(
                            Rgb {
                                r: 60,
                                g: 56,
                                b: 54,
                            },
                        ),
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: None,
                            background_color: Some(
                                Rgb {
                                    r: 50,
                                    g: 48,
                                    b: 47,
                                },
                            ),
                            attributes: Attributes(
                                0,
                            ),
                        },
                    },
                ),
            },
            "purpose_ellipsis": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: None,
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "char_match": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 250,
                                g: 189,
                                b: 47,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "file": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: None,
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: None,
                            background_color: None,
                            attributes: Attributes(
                                16,
                            ),
                        },
                    },
                ),
            },
            "pruning": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 124,
                                g: 111,
                                b: 100,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            16,
                        ),
                    },
                },
                unfocused: None,
            },
            "perm_r": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 215,
                                g: 153,
                                b: 33,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "owner": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 215,
                                g: 153,
                                b: 33,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            4,
                        ),
                    },
                },
                unfocused: None,
            },
            "git_branch": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 251,
                                g: 241,
                                b: 199,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "git_status_modified": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 152,
                                g: 151,
                                b: 26,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "directory": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 69,
                                g: 133,
                                b: 136,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            4,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: Some(
                                Rgb {
                                    r: 131,
                                    g: 165,
                                    b: 152,
                                },
                            ),
                            background_color: None,
                            attributes: Attributes(
                                0,
                            ),
                        },
                    },
                ),
            },
            "git_status_ignored": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 213,
                                g: 196,
                                b: 161,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "count": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 69,
                                g: 133,
                                b: 136,
                            },
                        ),
                        background_color: Some(
                            Rgb {
                                r: 50,
                                g: 48,
                                b: 47,
                            },
                        ),
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "help_bold": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 214,
                                g: 93,
                                b: 14,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            4,
                        ),
                    },
                },
                unfocused: None,
            },
            "flag_value": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 211,
                                g: 134,
                                b: 155,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            4,
                        ),
                    },
                },
                unfocused: None,
            },
            "input": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 251,
                                g: 241,
                                b: 199,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: Some(
                                Rgb {
                                    r: 189,
                                    g: 174,
                                    b: 147,
                                },
                            ),
                            background_color: None,
                            attributes: Attributes(
                                16,
                            ),
                        },
                    },
                ),
            },
            "git_status_conflicted": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 204,
                                g: 36,
                                b: 29,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "status_bold": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 211,
                                g: 134,
                                b: 155,
                            },
                        ),
                        background_color: Some(
                            Rgb {
                                r: 50,
                                g: 48,
                                b: 47,
                            },
                        ),
                        attributes: Attributes(
                            4,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: None,
                            background_color: None,
                            attributes: Attributes(
                                0,
                            ),
                        },
                    },
                ),
            },
            "git_status_current": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 60,
                                g: 56,
                                b: 54,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "status_normal": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: None,
                        background_color: Some(
                            Rgb {
                                r: 50,
                                g: 48,
                                b: 47,
                            },
                        ),
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: None,
                            background_color: None,
                            attributes: Attributes(
                                0,
                            ),
                        },
                    },
                ),
            },
            "hex_ascii_other": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 254,
                                g: 128,
                                b: 25,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "status_error": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 213,
                                g: 196,
                                b: 161,
                            },
                        ),
                        background_color: Some(
                            Rgb {
                                r: 204,
                                g: 36,
                                b: 29,
                            },
                        ),
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "help_headers": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 254,
                                g: 128,
                                b: 25,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            4,
                        ),
                    },
                },
                unfocused: None,
            },
            "hex_null": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 189,
                                g: 174,
                                b: 147,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "hex_ascii_graphic": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 213,
                                g: 196,
                                b: 161,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "purpose_italic": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 177,
                                g: 98,
                                b: 134,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            16,
                        ),
                    },
                },
                unfocused: None,
            },
            "flag_label": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 189,
                                g: 174,
                                b: 147,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "help_italic": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 211,
                                g: 134,
                                b: 155,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            16,
                        ),
                    },
                },
                unfocused: None,
            },
            "perm__": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: None,
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "status_ellipsis": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 251,
                                g: 241,
                                b: 199,
                            },
                        ),
                        background_color: Some(
                            Rgb {
                                r: 50,
                                g: 48,
                                b: 47,
                            },
                        ),
                        attributes: Attributes(
                            4,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: None,
                            background_color: None,
                            attributes: Attributes(
                                0,
                            ),
                        },
                    },
                ),
            },
            "preview_match": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: None,
                        background_color: Some(
                            Rgb {
                                r: 80,
                                g: 73,
                                b: 69,
                            },
                        ),
                        attributes: Attributes(
                            4,
                        ),
                    },
                },
                unfocused: None,
            },
            "content_extract": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 168,
                                g: 153,
                                b: 132,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            16,
                        ),
                    },
                },
                unfocused: None,
            },
            "help_code": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 142,
                                g: 192,
                                b: 124,
                            },
                        ),
                        background_color: Some(
                            Rgb {
                                r: 50,
                                g: 48,
                                b: 47,
                            },
                        ),
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "purpose_normal": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: None,
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "hex_ascii_whitespace": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 152,
                                g: 151,
                                b: 26,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "purpose_bold": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 177,
                                g: 98,
                                b: 134,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            4,
                        ),
                    },
                },
                unfocused: None,
            },
            "tree": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 168,
                                g: 153,
                                b: 132,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: Some(
                                Rgb {
                                    r: 102,
                                    g: 92,
                                    b: 84,
                                },
                            ),
                            background_color: None,
                            attributes: Attributes(
                                0,
                            ),
                        },
                    },
                ),
            },
            "perm_w": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 204,
                                g: 36,
                                b: 29,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "help_table_border": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 80,
                                g: 73,
                                b: 69,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "git_deletions": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 190,
                                g: 15,
                                b: 23,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "file_error": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 251,
                                g: 73,
                                b: 52,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "git_status_new": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 104,
                                g: 187,
                                b: 38,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            4,
                        ),
                    },
                },
                unfocused: None,
            },
            "git_insertions": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 152,
                                g: 151,
                                b: 26,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "sparse": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 250,
                                g: 189,
                                b: 47,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "hex_non_ascii": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 214,
                                g: 93,
                                b: 14,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "exe": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 184,
                                g: 187,
                                b: 38,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "group": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 215,
                                g: 153,
                                b: 33,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "git_status_other": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 204,
                                g: 36,
                                b: 29,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "status_code": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 251,
                                g: 241,
                                b: 199,
                            },
                        ),
                        background_color: Some(
                            Rgb {
                                r: 50,
                                g: 48,
                                b: 47,
                            },
                        ),
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: None,
                            background_color: None,
                            attributes: Attributes(
                                0,
                            ),
                        },
                    },
                ),
            },
            "status_job": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 250,
                                g: 189,
                                b: 47,
                            },
                        ),
                        background_color: Some(
                            Rgb {
                                r: 60,
                                g: 56,
                                b: 54,
                            },
                        ),
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "preview_line_number": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 124,
                                g: 111,
                                b: 100,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: Some(
                                Rgb {
                                    r: 124,
                                    g: 111,
                                    b: 100,
                                },
                            ),
                            background_color: Some(
                                Rgb {
                                    r: 40,
                                    g: 40,
                                    b: 40,
                                },
                            ),
                            attributes: Attributes(
                                0,
                            ),
                        },
                    },
                ),
            },
            "scrollbar_thumb": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 213,
                                g: 196,
                                b: 161,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: Some(
                                Rgb {
                                    r: 102,
                                    g: 92,
                                    b: 84,
                                },
                            ),
                            background_color: None,
                            attributes: Attributes(
                                0,
                            ),
                        },
                    },
                ),
            },
            "dates": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 168,
                                g: 153,
                                b: 132,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: None,
            },
            "scrollbar_track": SkinEntry {
                focused: CompoundStyle {
                    object_style: ContentStyle {
                        foreground_color: Some(
                            Rgb {
                                r: 80,
                                g: 73,
                                b: 69,
                            },
                        ),
                        background_color: None,
                        attributes: Attributes(
                            0,
                        ),
                    },
                },
                unfocused: Some(
                    CompoundStyle {
                        object_style: ContentStyle {
                            foreground_color: Some(
                                Rgb {
                                    r: 50,
                                    g: 48,
                                    b: 47,
                                },
                            ),
                            background_color: None,
                            attributes: Attributes(
                                0,
                            ),
                        },
                    },
                ),
            },
        },
    ),
    special_paths: {},
    search_modes: None,
    disable_mouse_capture: None,
    cols_order: None,
    show_selection_mark: None,
    ext_colors: {},
    syntax_theme: None,
    true_colors: None,
    icon_theme: Some(
        "vscode",
    ),
    modal: None,
    max_panels_count: None,
}
19:15:31.723 [DEBUG] broot::app::context: COLORTERM env variable = "truecolor"
19:15:31.724 [DEBUG] broot::app::context: true colors are available
19:15:31.724 [DEBUG] broot::tree_build::builder: GitIgnorer::default() took 45ns
19:15:31.737 [DEBUG] broot::app::app: display panel took 4.077469ms
19:15:31.738 [DEBUG] broot::app::app: pending_tasks took 1.126µs
19:15:32.788 [INFO] broot::app::app: event: Key(KeyEvent { code: Char('a'), modifiers: NONE })
19:15:32.788 [DEBUG] broot::app::app: command after add_event: PatternEdit { raw: "a", expr: BeTree { atoms: [PatternParts { parts: ["a"] }], nodes: [Node { operator: None, parent: None, left: Atom(0), right: None, unary: false }], head: 0, tail: 0, last_pushed: Atom, op_count: 0, openess: 0 } }
19:15:32.789 [DEBUG] broot::app::panel: result in panel PanelId(0): Ok(Keep)
19:15:32.789 [DEBUG] broot::app::app: display panel took 201.137µs
19:15:32.789 [DEBUG] broot::tree_build::builder: GitIgnorer::default() took 76ns
19:15:32.800 [INFO] broot::browser::browser_state: tree filtering on "a" took 11.016073ms
19:15:32.801 [DEBUG] broot::app::app: display panel took 818.77µs
19:15:32.802 [DEBUG] broot::app::app: pending_tasks took 12.835304ms
19:15:33.690 [INFO] broot::app::app: event: Key(KeyEvent { code: Char('w'), modifiers: CONTROL })
</p>
</details>

**To Reproduce**

- start broot
- type `a`, then hit `ctrl-w` which binds to `input_del_word_left` command.
- broot panics and messes up the terminal:
```
thread 'main' panicked at 'removal index (is 1) should be < len (is 1)', library/alloc/src/vec/mod.rs:1347:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**

`input_del_word_left` should delete the word before the cursor and no error occurs.

**Configuration (please complete the following information):**
- broot version:  broot 1.2.8 / broot 1.2.9-dev
- OS: Arch Linux
- Version: 5.11.6-arch1-1
- Relevant configuration items

```hjson
{
    key: ctrl-w
    execution: ":input_del_word_left"
}
```

**Additional context**

This error seems to be caused by the `termimad` crate:
https://github.com/Canop/termimad/blob/aa0bab819e56d55501943a452a2affd86763a50b/src/views/input_field.rs#L173

For some reasons the value of `cursor_pos` is not less than `self.content.len()`. So the `remove` method paniced.

Note that this error sometimes doesn't appears when running in debug mode.

**Comment by Canop** [comment]
I reproduce the bug

**Comment by Canop** [comment]
It's fixed in master and I should release a new version soon enough.

Thanks for the clean bug report.

**Comment by wfxr** [comment]
@Canop Thanks for the quick fix!
