### ISSUE TITLE
Nushell setup has changed

### ISSUE THREAD

**Issue by mvolkmann** [Canop/broot#368]
The docs say:
As a shortcut for Nushell, define the following alias:
`alias br [] { broot | trim | cd $it }`

The first word "alias" should now be changed to "def".

**Comment by Canop** [comment]
Can you point to a reference so that I don't have to try search the doc myself (not a nushell user) ?

**Comment by mvolkmann** [comment]
Here are the current docs on Nushell aliases:
https://www.nushell.sh/book/aliases.html
They can no longer have a parameter list ('[]') like in the current broot docs.

Here are the current Nushell docs on "custom commands" that are defined with `def`:
https://www.nushell.sh/book/custom_commands.html
These can have a parameter list.

**Comment by Canop** [comment]
Thanks
