### ISSUE TITLE
shell command to cd/broot back to before last broot move 

### ISSUE THREAD

**Issue by Canop** [Canop/broot#37]
Those abilities would be useful, at least to me:

* get back in the shell to where I was before last navigation done with broot
* open broot on the last opened path (before last navigation which might have been done with alt-enter)
* open broot on the last state (including filtering)

Those would be easily achieved with broot just storing the last opening path in `.config/broot`. It's possible one of those commands would be enough (I don't want to add dozens of commands to the shell).

**Comment by Canop** [comment]
As nobody seems interested, I'll probably close this issue.

**Comment by webmastak** [comment]
This is a very useful feature.

For example, how here [dua-cli)](https://github.com/Byron/dua-cli) does not exit the program when opening a file!

At least it could have been done if the editor is opened independent of the terminal, for example Gedit.

**Comment by Canop** [comment]
@webmastak noted. I'll work on that. Thanks for your feedbak.

**Comment by webmastak** [comment]
I'm trying to pick Rust and still have a bad understanding of it. Tell me where to make an edit so as not to exit the program by pressing Enter when opening a file in my case in Gedit.

**Comment by Canop** [comment]
Regarding the feature you seem to ask for, I've already the code ready. The question is whether I make this change which seems to make sense but could break usages.

Here's today's behavior:

- in case of enter or double-click
   - on a directory: open that directory, staying in broot
   - on a file: open the file, quitting broot
- in case of alt-enter
   - on a directory: cd to that directory, quitting broot
   - on a file: cd to that file's parent directory, quitting broot

The behavior I'm thinking about:

- in case of enter or double-click
   - on a directory: open that directory, staying in broot
   - on a file: open that file in default editor, leaving broot open
- in case of alt-enter
   - on a directory: cd to that directory, quitting broot
   - on a file: open that file in default editor, quitting broot

**Comment by webmastak** [comment]
It is very good! If you are afraid that something will break, just make a branch from which you can simply install exsample: `cargo install --git https://github.com/Canop/broot --brach dev`

**Comment by Canop** [comment]
I just pushed and published broot 0.9

Note that this doesn't solve all problems of the present issue
