### ISSUE TITLE
Compile error on FreeBSD host

### ISSUE THREAD

**Issue by aleksuss** [Canop/broot#371]
I've tried to compile broot 1.2.10 on FreeBSD 12.2 host and stuck with compile error:

```
error[E0308]: mismatched types
  --> /home/work/.cargo/registry/src/github.com-1ecc6299db9ec823/broot-1.2.10/src/display/cell_size.rs:32:43
   |
32 |     let r = unsafe { ioctl(STDOUT_FILENO, TIOCGWINSZ, &w) };
   |                                           ^^^^^^^^^^
   |                                           |
   |                                           expected `u64`, found `u32`
   |                                           help: you can convert a `u32` to a `u64`: `TIOCGWINSZ.into()`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `broot`
```

The reason is that on freebsd host a size of type `TIOCGWINSZ` constant is 4 bytes, rather than 8 bytes.
```rust
use std::mem::{size_of, size_of_val};
use libc::{c_ulong, TIOCGWINSZ};

fn main() {
    assert_eq!(size_of_val(&TIOCGWINSZ), 4);
    assert_eq!(size_of::<c_ulong>(), 8); // TIOCGWINSZ has type c_ulong
}
```
But on linux host it's [8 bytes](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4694fe5f44c2513d3aecdcf106dc2f87).

I've investigated a little and found out that the binary linking with `/lib/libc.so.7`:
```shell
$ ldd playground/target/debug/playground
playground/target/debug/playground:
	libthr.so.3 => /lib/libthr.so.3 (0x8010b2000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x8010df000)
	libc.so.7 => /lib/libc.so.7 (0x8010f9000)
```
And it seems that used `libc.so.7` had been compiled for `amd64` arch.
```shell
$ objdump -f /lib/libc.so.7

/lib/libc.so.7:     file format elf64-x86-64-freebsd
architecture: i386:x86-64, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x000000000007fc90
```

And at last:
```c
#include <stdio.h>
#include <sys/ioctl.h>

int main() {
    printf("%lu\n", sizeof(TIOCGWINSZ));
    return 0;
}
```
outputs 8 !!!

**Comment by jyoung15** [comment]
A similar issue was reported for Zellij.  See that pull request for the resolution (https://github.com/zellij-org/zellij/pull/547), which is to apply the compiler suggestion (`TIOCGWINSZ.into()`).  This works for me on FreeBSD 13.0 amd64.

**Comment by Canop** [comment]
@jyoung15 Do you want to make a PR ?

**Comment by Canop** [comment]
@aleksuss I'll let you close the issue once you've checked the repushed version does compile fine on FreeBSD

**Comment by aleksuss** [comment]
@Canop I've checked it out from the master. Everything is OK 👍🏻
