### ISSUE TITLE
Modal: Be back in command mode after executing a command

### ISSUE THREAD

**Issue by alexherbo2** [Canop/broot#372]
After entering a command, for example typing `:rm<ret>`, Broot does not back in normal mode.

**Comment by Canop** [comment]
I changed the title to make it clearer that:

* it only concerns the [modal mode](https://dystroy.org/broot/vim_mode/) which isn't the default mode of broot
* the "normal" mode is the mode in which you type commands

**Comment by Canop** [comment]
My tests weren't really complete enough and I don't commonly use the modal mode so I'd like you to confirm it's OK.
