### ISSUE TITLE
Need a br shell function for nushell

### ISSUE THREAD

**Issue by Canop** [Canop/broot#375]
An alias was previously proposed:

    alias br [] { broot | trim | cd $it }

but it doesn't seem to work now, either because of changes in nushell or because of changes in broot.

Help appreciated.

**Comment by Canop** [comment]
This one partially works: it doesn't allow flags

```
def br [...rest] {
  let path = $(broot --color yes --out /dev/stdout $rest | str trim)
  let is_empty = $(= $path | empty?)
  if $is_empty {} {
    cd $path
  }
}
```

**Comment by IndianaRoy** [comment]
Hey, noob question. Where do I write the def?

**Comment by sorenrade** [comment]
> Hey, noob question. Where do I write the def?

See my comment in #373

**Comment by IndianaRoy** [comment]
> > Hey, noob question. Where do I write the def?
> 
> See my comment in #373

Thanks, that did it

**Comment by davor-skontra-ng** [comment]
Ok, I found a way to do it with python:

**Comment by davor-skontra** [comment]
Ok, I found a way to do it with Python: 

```
import sys
import tempfile

temp_file = tempfile.NamedTemporaryFile()
args = " ".join(sys.argv[1:])
start_cmd = "broot --color yes --outcmd {} {}".format(temp_file.name, args)

exit_status = os.system(start_cmd)
if (exit_status != 0):
    temp_file.close()
    print(exit_status)
    exit()

then_cmd = temp_file.read().decode('utf-8')
temp_file.close()

if (then_cmd[:3] == 'cd '):
    target = then_cmd[3:-1].replace('\\', "/")
    os.chdir(target)
    os.system('nu')
else:
    print('running: ' + then_cmd)
    os.system(then_cmd)
```

Stash that into a file and then add an alias to call up that file to config. Eg.

`alias br = python c:/path/to/your/file.py`

Obviously you need to have Python installed, but it works (and so do flags!)

**Comment by Canop** [comment]
I'll try. I'd appreciate opinions from other nushell users

**Comment by davor-skontra** [comment]
This solution should in theory work for any shell aon os combo that can run Python, just changing the os.system('nu') call to whatever shell the user is using. maybe by passing a param to the python script. I can try to help if needed.

**Comment by davor-skontra** [comment]
Btw you might have tried it already, but wouldn't this same approach also work from Rust instead of Python? What I'm doing is setting the current directory and resetting shell after that to apply the directory change. You could set the dir with [std::env::set_current_dir](https://doc.rust-lang.org/std/env/fn.set_current_dir.html) and then reset the shell using [std::process::Command](https://doc.rust-lang.org/std/process/struct.Command.html) no?

**Comment by davor-skontra** [comment]
This might work for most shells I think. But I'm not sure. I'm also not a Rust programmer so I might be wrong about the above also.

**Comment by Canop** [comment]
> You could set the dir with std::env::set_current_dir and then reset the shell using std::process::Command no?

No you can't because `std::env::set_current_dir` changes the current dir for the current process, not for the parent shell. As soon as you leave the Rust application, you're back to the old current dir.

**Comment by davor-skontra** [comment]
Ahh I always assumed that the old shell is killed when you start a new one, but you are right. When you start a new one and exit it you drop back into the old one, so they are nesting. I found something of a way around it, or at least it seems to work on windows. 

```
import os
import sys
import signal
import tempfile

temp_file = tempfile.NamedTemporaryFile()
args = " ".join(sys.argv[1:])
start_cmd = "broot --color yes --outcmd {} {}".format(temp_file.name, args)

exit_status = os.system(start_cmd)
if (exit_status != 0):
    temp_file.close()
    print(exit_status)
    exit()

then_cmd = temp_file.read().decode('utf-8')
temp_file.close()

if (then_cmd[:3] == 'cd '):
    pid = os.getppid()
    target = then_cmd[3:-1].replace('\\', '/').replace('"', '')
    os.chdir(target)
    os.system('nu')
    os.kill(pid, signal.SIGTERM)
else:
    os.system(then_cmd)
```

This kills the parent shell after starting the new one so it doesn't linger. Its not perfect but its better than not having this functionality. Note that this new version also fixes an issue that the previous one had where paths with spaces would not load.

**Comment by Canop** [comment]
I may propose that one way or another but this is kind of annoying: killing the previous shell and starting with a new one may be surprising or slow, as the init scripts are executed again.

We should try to discuss this with the nushell authors. I'll try to visit them when I find the time.

**Comment by Stargateur** [comment]
> Ahh I always assumed that the old shell is killed when you start a new one, but you are right. When you start a new one and exit it you drop back into the old one, so they are nesting. I found something of a way around it, or at least it seems to work on windows.
> 
> ```
> import os
> import sys
> import signal
> import tempfile
> 
> temp_file = tempfile.NamedTemporaryFile()
> args = " ".join(sys.argv[1:])
> start_cmd = "broot --color yes --outcmd {} {}".format(temp_file.name, args)
> 
> exit_status = os.system(start_cmd)
> if (exit_status != 0):
>     temp_file.close()
>     print(exit_status)
>     exit()
> 
> then_cmd = temp_file.read().decode('utf-8')
> temp_file.close()
> 
> if (then_cmd[:3] == 'cd '):
>     pid = os.getppid()
>     target = then_cmd[3:-1].replace('\\', '/').replace('"', '')
>     os.chdir(target)
>     os.system('nu')
>     os.kill(pid, signal.SIGTERM)
> else:
>     os.system(then_cmd)
> ```
> 
> This kills the parent shell after starting the new one so it doesn't linger. Its not perfect but its better than not having this functionality. Note that this new version also fixes an issue that the previous one had where paths with spaces would not load.

to be frank, a program that kill my shell would go to `/dev/null` faster than light.

**Comment by Hipfox** [comment]
After adapted from https://github.com/Canop/broot/issues/373 I try this works.

add definitions, aliases to the global [config.nu](https://www.nushell.sh/book/configuration.html#nushell-configuration-with-env-nu-and-config-nu) then start an new nushell

```
def-env br_cmd [] {
  let cmd_file = (^mktemp | str trim);
  ^broot --outcmd $cmd_file;
  let-env cmd = ((open $cmd_file) | str trim);
  ^rm $cmd_file;
}
alias br = (br_cmd | cd ($env.cmd | str replace "cd" "" | str trim))
```

![WindowsTerminal_rROYSZPE0U](https://user-images.githubusercontent.com/125309/163905327-4b8e0698-730d-4ef2-a586-628555d123e6.gif)

**Comment by Hipfox** [comment]
update my br command for nushell, use parameters with some restrictions.
```
Usage:
  > br {flags}

Flags:
  -h, --help
      Display this help message
  -a, --args <String>
```
For example

launched in the c:\ directory
`br -a c:\`

Show the size of files and directories
`br -a -s`

combine show the size and show the last modified date of files and directories
`br -a -ds`

```
def-env br [
  --args (-a): string
] {
  let cmd_file = (^mktemp | str trim)
  if ($args | empty?) {
    ^broot --outcmd $cmd_file
  } else {
    ^broot $args --outcmd $cmd_file
  }
  let-env cmd = ((open $cmd_file) | str trim)
  ^rm $cmd_file
  cd ($env.cmd | str replace "cd" "" | str trim)
}
```

**Comment by nightscape** [comment]
@Hipfox that might be a nice contribution to https://github.com/nushell/nu_scripts 👍

**Comment by luccahuguet** [comment]
Can we give some love to the shell written in rust? Nushell could make great use of official "br" support! 

Is there a pr already in works?

**Comment by Canop** [comment]
@luccahuguet There's no registered PR, and I don't have time now to dive into nushell, so your help would be welcome here.

**Comment by azzamsa** [comment]
@luccahuguet this works for me.

```Nu
def-env br_cmd [] {
  let cmd_file = (^mktemp | str trim);
  ^broot --outcmd $cmd_file;
  let-env cmd = ((open $cmd_file) | str trim);
  ^rm $cmd_file;
}
# Broot file manager
alias br = (br_cmd | cd ($env.cmd | str replace "cd" "" | str trim))
```

**Comment by Canop** [comment]
Ideal would be a tested PR (I mean the shell initialization process tested) with other nushell users confirming it works for them too and it seems consistent with good nushell practices.

**Comment by luccahuguet** [comment]
Thank you so much @azzamsa! I can confirm this works in a linux environment, namely Fedora 36 in WSL2

it does not work in windows though, it does not recognize mktemp (but wsl2 was my main worry)

Thanks for the fast answer @Canop, I hope someone is able to tackle this problem

**Comment by mediumrarez** [comment]
New version, based on @azzamsa's code.

Changes:
  - Added cross-platform support
  - Cleanup (no more environment variable, use nu pipelines instead of bash-isms)
  - Bug fix: if "cd" is a substring of target path, `cd` will fail

```nushell
def _br_cmd [] {
  let cmd_file = ([ $nu.temp-path, $"broot-(random chars).tmp" ] | path join)
  touch $cmd_file
  ^broot --outcmd $cmd_file
  let target_dir = (open $cmd_file | to text | str replace "^cd\\s+(.+)\\s*" "$1")
  rm --permanent --force $cmd_file
  
  $target_dir
}
alias br = cd (_br_cmd)
```

**Comment by FrancescElies** [comment]
I can confirm @mediumrarez br command works fine in windows too

**Comment by Canop** [comment]
> Use: run config nu and paste snippet in the file opened

Now, what would be the clean way for nushell to have the script installed by broot at first run like for other shells ?

**Comment by mediumrarez** [comment]
@Canop I don't think there's any way to load it modularly (i.e. like `/etc/profile.d` on Linux). The best we can do is to insert the `br` snippet into `config.nu` programmatically and add comments to mark the start and end.

```nushell
# BROOT_BEGIN
# THIS SNIPPET IS AUTOMATICALLY GENERATED. DO NOT EDIT. ALL CHANGES WILL BE UNDONE.
def _br_cmd [] {
  let cmd_file = ([ $nu.temp-path, $"broot-(random chars).tmp" ] | path join)
  touch $cmd_file
  ^broot --outcmd $cmd_file
  let target_dir = (open $cmd_file | to text | str replace "^cd\\s+" "" | str trim)
  rm -p -f $cmd_file
  
  $target_dir
}
alias br = cd (_br_cmd)
# BROOT_END
```

We can get `config.nu` filepath by running `nu -c $nu.config-path`. It should be enough to just tack it on to the end of the file.

---

Alternatively, we could write `br.nu` into the config dir and `source` it inside the main config.

**Comment by Canop** [comment]
The br.nu file with a sourcing line is what's done by broot for zsh, bash, fish, etc.

**Comment by mediumrarez** [comment]
That'd work as well. You could make the sourcing a one-liner too.

```nushell
source ([($nu.config-path | path dirname), "br.nu"] | path join)  # BROOT_SOURCE
```

**Comment by mediumrarez** [comment]
That'd work as well. You could make the sourcing a one-liner too.

```nushell
source ([($nu.config-path | path dirname), "br.nu"] | path join)  # BROOT (automatically generated. do not edit.)
```

The nushell language still changes from time to time though. Even the sourcing line might need to be updated in the future.

**Comment by Canop** [comment]
I'd like to have testers for the nushell branch.
PR: https://github.com/Canop/broot/pull/647

**Comment by Canop** [comment]
I will do a release ASAP

**Comment by Canop** [comment]
Version 1.19.0 comes with this.

BTW, major releases are now published on my Mastodon account: https://mastodon.dystroy.org/@dystroy/109626772709150819
