### ISSUE TITLE
Non-interactive mode

### ISSUE THREAD

**Issue by muellerj** [Canop/broot#382]
Maybe I'm missing a hacky way to do this already, but I sometimes just want the (very nicely filtered and compacted) view that `broot` provides and then continue in my shell without loosing view of the output. As such, it would be nice to have a non-interactive mode, which just prints the current view for root and then exits with 0, thus imitating what `tree` does.

**Comment by Canop** [comment]
Would that be what you want ?
https://dystroy.org/broot/tricks/#replace-tree

**Comment by muellerj** [comment]
It would! Thanks for the pointer 😊
