### ISSUE TITLE
color of root_fs disk usage not reset properly

### ISSUE THREAD

**Issue by plgruener** [Canop/broot#386]
The red color used to indicate a (nearly) full disk in the top line (with `:toggle_root_fs`) is not reset properly and leaks into the next lines, until an item that sets a new color.
To see this, you need a "transparent" skin like this:

```
skin: {
default: none none
file: none none
directory: none none
tree: none none
…
}
```
(and either disable git info or move it down/to the right in `cols_order`), see screenshot

![broot_screenshot](https://user-images.githubusercontent.com/5796100/118693970-db665580-b80b-11eb-94c8-05e75946006e.png)

Configuration:
- broot version: 1.4.0
- OS: Arch Linux

**Comment by Canop** [comment]
TBH it looks like you'd better not miss the urgency here!

(I reproduce it, never occurred to me to test this with a default foreground color, I'll fix that ASAP)
