### ISSUE TITLE
Request: internal verb: toggle_panel

### ISSUE THREAD

**Issue by AndydeCleyre** [Canop/broot#388]
**Did a discussion occur before?**
[A little](https://miaou.dystroy.org/3490?broot#15060877)

**Is your feature request related to a problem? Please describe.**
I'd like to make my usage of broot's panel (at least for a files view) and KDE's Dolphin panes more similar.

I'm going to use the term "pane" hereafter to mean either a broot panel showing a files tree or a Dolphin pane showing files.

Dolphin only offers up to two panes, so I can use a single shortcut (default `F3`) to:

```python
if count(panes) == 1:
    focus_new_pane()
else:
    close_inactive_pane()
```

I wish to achieve the same with broot.

**Describe the solution you'd like**

An internal verb that does something like:

```python
if count(panes) == 1:
    focus_new_pane()
elif count(panes) == 2:
    close_inactive_pane()
else:
    # Broot's support for more panes must be considered, too.
    # I don't know or care too much what happens in this case. Maybe:
    close_least_recent_pane()
```

**Describe alternatives you've considered**
I can add this
```hjson
{ internal: ":focus!", key: "f3" }
```
but I can't use the same key to close an inactive pane.

**Additional context**
To be clear, I would not count a preview panel as a "pane" in this context.

**Comment by Canop** [comment]
Given that a preview panel doesn't count as a panel, and that this is dedicated to the 2 panels case, I think I'll name this verb `:toggle_second_tree`.

**Comment by Canop** [comment]
This can be tested with the last commit and this config:

		{
			invocation: tst
			key: F3
			internal: ":toggle_second_tree"
		}

**Comment by AndydeCleyre** [comment]
And here "second" means the inactive one (or least-recently-active), not the one on the right (necessarily), and not the most recently spawned one (necessarily), correct?

**Comment by Canop** [comment]
Right now it's the one on the right but I'm not against tuning this feature

**Comment by AndydeCleyre** [comment]
IMO just handling the one on the right doesn't offer very much advantage over the existing `ctrl`+`left`/`right`; this request was intended to be about handling an *inactive* pane.

**Comment by AndydeCleyre** [comment]
It's working beautifully!

Here's what I'm noticing with preview interactions:
 
- With one tree and one preview, triggering *replaces* the preview with an active tree (?)
- With two trees and one preview, one of the trees focused, triggering closes the inactive tree (👍🏼)
- With two trees and one preview, preview focused, triggering closes the least-recently-active tree (👍🏼)

I did not test with more trees than that.

I don't know what's best for the first scenario.

I think `:toggle_inactive_tree` or `:toggle_other_tree` may be clearer.

**Comment by w-jablonski** [comment]
> I suspect there's still room for tuning in non tree cases (eg when the focused panel is a preview one).

Please can we add this? Details: I use `→` to open preview of file, then `←` (bound to `panel_left` ) successfully closes it. But then I would like to hit `←` again to go up the directory. But this opens a new panel instead (becaude it's still bound to `panel_left` ). So ideally, there would be a function to close the preview IF it exists ELSE it's transpartent i.e. allows some other action to be bound to this key. Context `panels = [multiple]` comes to mind.

BTW, as I see you are very open to suggestions, don't you view this navigation as most intuitive: 
`⇅` select directories
`←` go up the directory
`→` enter the directory or file

Big Thanks for the project.
