### ISSUE TITLE
Request: ability to use :go as an alias for :focus

### ISSUE THREAD

**Issue by AndydeCleyre** [Canop/broot#389]
**Did a discussion occur before?**
[A bit](https://miaou.dystroy.org/3490?broot#15060866)

**Is your feature request related to a problem? Please describe.**
I would like to be able to use `:go` to trigger the internal `:focus` verb.

e.g.: 

- `:go ~`
- `:go!`
- `:go`

**Describe the solution you'd like**
I don't know what would be best. Some alternatives that come to mind:

1. Add a way to define an "alias" for an internal verb, that will handle arguments identically to calling the internal verb directly.
2. Add a way to specify optional arguments to user-defined verbs.
3. If no one wants (1) or (2), and a bunch do want to use the specific term `:go` for this action, it could be implemented internally as a shortcut for `:focus`.

**Describe alternatives you've considered**
I can define this:
```hjson
{ internal: ":focus", shortcut: go }
```
but that won't accept arguments.

I can similarly define a new verb that takes an argument, but that won't work when trying with no arguments.

**Comment by Canop** [comment]
Examples of verbs which are now possible:

```
        {
            invocation: "gos"
            execution: ":focus"
        }
        {
            invocation: "go {path}"
            execution: ":focus {path}"
        }
        {
            invocation: "goroot"
            key: "ctrl-r"
            execution: ":focus /"
        }
        {
            invocation: "gotar {path}"
            execution: ":focus {path}/target"
        }

```

**Comment by Canop** [comment]
> But it's a little misleading in that typing :go reports in the status bar that "go doesn't take arguments" 

Do you have version 1.14.2 ?

![image](https://user-images.githubusercontent.com/617006/178786243-5c186c16-185a-4cd8-aea9-cd48ef7c1209.png)

**Comment by Canop** [comment]
oh, I see, you defined go twice. I'll see what I can do for that case.
