### ISSUE TITLE
broot --install doesn't work when fish uses conf.d

### ISSUE THREAD

**Issue by pzmarzly** [Canop/broot#39]
I have installed fish from Manjaro repository. In `~/.config/fish/`. I have no `config.fish` file, instead I place configuration in `.fish` files in `~/.config/fish/conf.d/`. `broot --install` fails as it is looking for `config.fish` file.

After copying [FISH_FUNC](https://github.com/Canop/broot/blob/8bd5f6fca462d191bf2c8fabca197a3fd0bd4f53/src/shell_fish.rs#L10) into new file (e.g. `~/.config/fish/conf.d/br.fish`) and restarting fish, it works.

I think fish supports `conf.d` out-of-the-box, so `broot --install` should:

1. create `conf.d` if it doesn't exist
2. check if `broot.fish` exists
2.1. if not, create it and put `FISH_FUNC` there
2.2. otherwise, check if the content equals `FISH_FUNC`, if not, report error to user

related #31

**Comment by Canop** [comment]
Please check it's OK for you.
(it will be in release 0.11 of broot which should come soon)

**Comment by offbyone** [comment]
This looks like it'll sort out my usage for sure... when can we expect to see 0.11 released (to homebrew, for me, for what it's worth)

**Comment by Canop** [comment]
@offbyone I'm not sure. I'm not the maintainer of the brew formula, I dont really know how it works (I have no mac) and there are strange problems: https://github.com/Canop/broot/issues/77#issue-541402729

**Comment by Lucretiel** [comment]
Fish specifies that functions live in ~/.config/fish/functions, from where they are lazily loaded as needed, to keep start time fast. This is documented at https://fishshell.com/docs/current/tutorial.html#tut_autoload.

#128 fixes this.

**Comment by Canop** [comment]
Fish users, please come and check PR #128 and tell us whether you think it's good.
