### ISSUE TITLE
Request: Verb: Toggle entering of selected symlink (interactive counterpart to config: special_paths: {...: enter })

### ISSUE THREAD

**Issue by AndydeCleyre** [Canop/broot#391]
**Did a discussion occur before?**
[A bit.](https://miaou.dystroy.org/3490?broot#15075667)

**Is your feature request related to a problem? Please describe.**
Sometimes I enter a directory that I wish to deeply search, and it contains a symlink to another large directory with files I wish to be included in the same search pool.

**Describe the solution you'd like**
- I'd like to select the symlink entry, perform a verb, and now have that link get followed, as if it's a regular folder, when searching from above, and showing some children. This is not a persistent change, just until the process exits. 
- I'd like to be able to focus on the link and perform the same verb to reverse this change.

Another way of thinking of this: "folding" and "unfolding" symlinked folders.

**Describe alternatives you've considered**
- hard-code known linked folders for auto-enter in the config; but:
  - I don't always want to enable that
  - I won't always predict my needs before launching broot
  - I may not want to include those paths in my configs, if the configs are public and the paths are private

**Comment by Canop** [comment]
> I see no one else has subscribed to this issue in the years it's been here

Sometimes, I forget some issues, even when they're good: there are so many issues and so many projects and my head is so small.

There's absolutely no problem in pinging me after some time, here or in Miaou, just to know whether I forgot.
