### ISSUE TITLE
find a solution to easily set a specific parent path as context for when executing a verb

### ISSUE THREAD

**Issue by Canop** [Canop/broot#392]
The discussion started [here](https://github.com/Canop/broot/issues/179#issuecomment-854840428) with @runiq and was deepened [here](https://miaou.dystroy.org/3490?broot#15081397).

The goal is to have vi (or another editor) run with a specific directory as context when opening a file from broot. This directory is always a parent of the opened file but it can't be automatically determined.

Several ideas have been found. Listing here only the core of the ideas without the many small technical details.

**Idea 1:**

- have a new internal moving the current tree root one step down in the direction of the selection
- ensure the working directory on launch of the external is the current tree root (using #395 and #396)

**idea 2:**

use a verb like
```
{
   invocation: ed {context:parent}
   key: ctrl-e
   auto_exec: false
   external: "cd {context}; vi {file}"
}
```
and, if necessary, between the ctrl-e and the enter, remove a few words at the end of the input

**Comment by runiq** [comment]
Actually, I realized that simply exposing the tree root to verbs would be enough – I can just determine the rest in a subshell.

**Comment by Canop** [comment]
With #395, #396, and #399 done, I think we have everything.

Waiting for confirmation.

**Comment by runiq** [comment]
Absolutely perfect! Thank you so much <3
