### ISSUE TITLE
Need --color=yes when writing result into file

### ISSUE THREAD

**Issue by sgraf812** [Canop/broot#397]
When invoking broot like 

```
$ broot --conf=$HOME/.config/broot/select.toml > /tmp/broot-result
```

for editor integration, I also need to supply --color=yes since https://github.com/Canop/broot/commit/8d5ae36e67a60af6a752ca56880ff9c2e7cf1e92, otherwise I end up in a monochrome screen where I can't see which line is selected.

I'd expected it to figure out that I want colors or at least be able to see what is selected, like it did before.

It would help if it detected colors for that use case again or if there was a useful visual selection marker in monochrome mode.

**Comment by Canop** [comment]
Not disregarding your issue, note that there's already a setting for a selection mark and you can add it in your select.toml file: https://dystroy.org/broot/conf_file/#selection-mark

**Comment by sgraf812** [comment]
Nice, that's a useful workaround. I'm mostly opening this issue because maybe someone else noticed it while upgrading. I feared that I somehow scrambled my $TERM environment with the last Nix upgrade.

**Comment by Canop** [comment]
You did good. The current behavior doesn't seem optimal.
