### ISSUE TITLE
Musl binary no longer available in 1.6.0

### ISSUE THREAD

**Issue by elkarouh** [Canop/broot#400]
The musl binary was provided in 1.5.1
I use a somewhat old machine and the musl binary is the only workable option.
Thanks

**Comment by Canop** [comment]
I may have messed something but I see the musl binary in the [install page](https://dystroy.org/broot/install/) and in the global archive in [download/](https://dystroy.org/broot/download/).

Do you refer to something else ?

**Comment by elkarouh** [comment]
The musl binary is present in the broot_1.6.0.zip file

**Comment by elkarouh** [comment]
typo: is NOT present in the zip file !

**Comment by Canop** [comment]
I just tried dezipping it. I get this:
![image](https://user-images.githubusercontent.com/617006/122584629-db4fb480-d05a-11eb-8c3d-c259e6899c57.png)

**Comment by elkarouh** [comment]
Sorry, my mistake.
I look at the wrong dir !

**Comment by Canop** [comment]
Good !

I'll let you close the issue if you confirm it's OK.

**Comment by elkarouh** [comment]
Yes, please do!
