### ISSUE TITLE
search is executed on cursor movement when query hasn't changed

### ISSUE THREAD

**Issue by balta2ar** [Canop/broot#402]
**Describe the bug**
When you move your cursor (left and right arrows) broot performs a new search, which is pointless because query hasn't changed.

**To Reproduce**
Type some query and move cursor around using left or right arrow keys.

**Expected behavior**
broot should not perform a new search if the query hasn't changed.

**Comment by Canop** [comment]
Good observation. I'll have a look and check the problem isn't even deeper (like new states, etc.)
