### ISSUE TITLE
Control broot's searching behavior

### ISSUE THREAD

**Issue by amosbird** [Canop/broot#404]
**Did a discussion occur before?**

I cannot find relate discussions in both issue list and in Broot chat room.

**Is your feature request related to a problem? Please describe.**

I'd like to configure broot to limit the dir searching with max depth 2, and it should only show me directories or symlinks to directories.

**Describe the solution you'd like**

Make the searching behavior configurable.

**Describe alternatives you've considered**

I don't know what would be the alternative way.

**Additional context**

Btw, is it possible to configure the `enter` key to act as `alt-enter`?

**Comment by balta2ar** [comment]
> Btw, is it possible to configure the enter key to act as alt-enter?

@amosbird  Try this:
```
        ###############################################################
        # Verbs and shortcuts
        # You can define your own commands which would be applied to
        # the selection.
        # You'll also find below verbs that you can customize or enable.
        verbs: [
                {
                        key: left
                        execution: ":parent"
                }
                {
                        key: right
                        execution: ":focus"
                }
                {
                        key: enter
                        execution: ":open_leave"
                }
                {
                        key: alt-enter
                        execution: ":open_stay"
                }
```

**Comment by stephane-klein** [comment]
> I'd like to configure broot to limit the dir searching with max depth 2, and it should only show me directories or symlinks to directories.

Small up to this feature request.

**Comment by 1andro1** [comment]
Would it not be better if there is an search option which to limit the search in different depth of the subfolders. As example 0/ for no search in subfolders, 1/  for search in only one level of subfolders, 2/ for search in subfolder and sub-subfolders and so on?

**Comment by Canop** [comment]
Closing as not specific enough, but #843 would probably answer part of the concern.
