### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Raytle** [Canop/broot#408]
Please see a copy/paste of my terminal... https://pastebin.com/v5DVkVzf

### In case it matters...

1. I just installed Rust using `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
2. I'm running Lubuntu 20.04 LTS.
3. I had never installed Rust before.
3. I am not an engineer.

**Comment by Canop** [comment]
Can you please give me the output of

    rustup --version

and

    rustc --version

?

**Comment by Raytle** [comment]
Thanks for taking the time to respond to me.

```
y@y-peppy:~$ rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.53.0 (53cb7b09b 2021-06-17)`
y@y-peppy:~$ rustc --version
rustc 1.53.0 (53cb7b09b 2021-06-17)
```

**Comment by Canop** [comment]
You may be missing the `build-essential` package. Try

    sudo apt install build-essential

then the installation again

**Comment by Raytle** [comment]
Thanks again for responding quickly to me.

Please see... https://pastebin.com/M1eT9gZ0

I have received that `E: Unable to correct problems, you have held broken packages.` several times over the last few months when I have attempted to install various applications. I think I'm going to wipe my local drive and then install Lubuntu 20.04 LTS again.

In the meantime, I'll try installing Broot on one of my other machines. My hunch is that it will work on one of my other machines. I will let you know if I had tried to install Broot on one of my other machines.

**Comment by Canop** [comment]
@Raytle Rather than wiping your disk, you may also install the precompiled broot

**Comment by Yekutiel** [comment]
>  Rather than wiping your disk, you may also install the precompiled broot

Thanks for your thoughtful suggestion.

On a different machine of mine, let's call it "machine 2", I did the following...

1. I downloaded  [Linux | x86_64-linux](https://dystroy.org/broot/install/) to `/usr/local/bin/broot`.
2. I ran `chmod +x broot`
3. I verified the permissions https://i.imgur.com/NQY9AMK.png
4. I ran `br -s` in a terminal.
5. Here are the results...
```
y@y-peppy:/usr/local/bin$ br -s

Command 'br' not found, but can be installed with:

sudo apt install bottlerocket
```

**Comment by Canop** [comment]
You must first launch broot, which installs br on first run. See https://dystroy.org/broot/install-br/

**Comment by Raytle** [comment]
That worked! Thank you. Broot looks very nice to me.

I suggest you update the documentation so other people can install broot more easily.

**Comment by Canop** [comment]
The point about build-essential was already in the install page, but in the "Install from source" section. I've just changed the "common problems" page to repeat it: https://dystroy.org/broot/common-problems/#compilation-fails-during-installation

I'm open to suggestions for other improvements.

**Comment by Raytle** [comment]
> I'm open to suggestions for other improvements.

Feel free to edit my suggestions below as you like. I tend to prefer extremely verbose documentation because, well, I'm essentially a business guy/salesman who is not very technically saavy.

## Installation instructions or users who already have the Rust development environment installed on their machine
1. Blah, blah, blah.

## Installation instructions for users who don't need to have the Rust development environment installed on their machine

If you are neither a Rust developer nor an aspiring Rust developer, although we love Rust (it's really, really great), we actually recommend **against** installing the Rust development environment merely to use Broot. The Rust development environment is around 200 megabytes and very probably unnecessary in your case. Instead,  we recommend you install the precompiled Broot (which is small, less than 10 megabytes as of 25 June 2021).

1. Download [Linux | x86_64-linux](https://dystroy.org/broot/install/) to `/usr/local/bin/`. (You will need root access for this).
2. Run `chmod +x broot` in a terminal. ([kitty](https://github.com/kovidgoyal/kitty) is a terminal that we recommend which is very popular for very good reasons).
3. See https://i.imgur.com/nOWB22J.png. Notice that "Owner", "Group", and "Other" can all execute. That's what you need.
4. In your terminal you must launch `broot` to install `br` on first run. See https://dystroy.org/broot/install-br/ for more information.
5. Now try to run `br -s` in a terminal to launch Broot.
6. If it didn't work copy your terminal to, for example, [Pastebin](https://pastebin.com/) and the post an issue at https://github.com/Canop/broot/issues to receive technical support.
7. If you need to send us any screenshots and don't already, for example, have, for example, a nifty `scrot` or `maim` solution that you find works well for you, we recommend  [Flameshot](https://github.com/flameshot-org/flameshot#preview) which, like kitty, is also very popular for very good reasons.
