### ISSUE TITLE
Use the os-specific file opener instead of hardcoding xdg-open

### ISSUE THREAD

**Issue by lovasoa** [Canop/broot#41]
MacOS does not have an `xdg-open` script by default.
I would suggest using the [opener crate](https://crates.io/crates/opener) to open files with their default editor in a platform-agnostic manner.

**Comment by Canop** [comment]
No opinion yet about that (and thus no fundamental objection), but I found nobody to test on Mac. Would you be able to validate it works on Mac ?

**Comment by lovasoa** [comment]
Yes, I am currently working under MacOS.

**Comment by Canop** [comment]
OK, I'm making a branch with the opener crate. If I see no problem I'll ask you to test.

**Comment by Canop** [comment]
I've pushed a new branch, [opener](https://github.com/Canop/broot/tree/opener). I'll wait for your tests

**Comment by lovasoa** [comment]
I just tested it. It works :)

**Comment by Canop** [comment]
No reason to keep this one open: it's done.
