### ISSUE TITLE
broot + kitty does not display images in high resolution

### ISSUE THREAD

**Issue by Kabouik** [Canop/broot#410]
**Describe the bug**
My `kitty` terminal is correctly set up and capable of showing high resolution images with its `icat` native protocol, but somehow `broot` only shows low resolution images:

![Screenshot_20210626_001](https://user-images.githubusercontent.com/7107523/123506878-bbc21880-d666-11eb-94b4-9a934d628182.png)

I cannot run `BROOT_LOG=debug br` on my Debian machine; can't try on my other machine running Solus right now:

```
user@debian-sid:/$ BROOT_LOG=debug br
thread 'main' panicked at 'Log file can't be created: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cli-log-2.0.0/src/init.rs:30:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
- Open `kitty` and run `broot` (tested with 1.2.2, 1.2.8 and 1.6.1 installed with `cargo` on Solus as well as Debian). 
- <kbd>Ctrl</kbd><kbd>→</kbd> on an image.

**Expected behavior**
The image should be shown in high resolution since `kitty` supports that and `broot` too. See example in `nnn`:

![Screenshot_20210626_003](https://user-images.githubusercontent.com/7107523/123507108-02fcd900-d668-11eb-95d6-600099ef7d3d.png)

**Configuration (please complete the following information):**
- `broot` version: 1.2.2, 1.2.8, 1.6.1
- OS: Solus OS, Debian Sid (as an LXC container within Sailfish OS; screenshots above)
- Version: both Solus and Debian Sid are rolling

**Comment by Canop** [comment]
Can you retry logging by starting broot in your home directory (i.e. where it can write a log file) ?

**Comment by Kabouik** [comment]
Oh, my bad, that was the issue for `broot.log` indeed. Here are the logs:

<details>
<summary>Expand</summary>
11:31:26.643 [INFO] cli_log::init: Starting broot v1.6.1 with log level DEBUG
11:31:26.652 [DEBUG] broot::cli: Conf::from_default_location() took 708.852µs
11:31:26.652 [DEBUG] broot::cli: config: Conf {
    files: [
        "/home/user/.config/broot/conf.hjson",
    ],
    default_flags: None,
    date_time_format: None,
    verbs: [
        VerbConf {
            invocation: Some(
                "edit",
            ),
            internal: None,
            external: None,
            execution: Some(
                String(
                    "$EDITOR +{line} {file}",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: Some(
                "F2",
            ),
            keys: [],
            shortcut: Some(
                "e",
            ),
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            working_dir: None,
            description: None,
            auto_exec: None,
        },
        VerbConf {
            invocation: Some(
                "create {subpath}",
            ),
            internal: None,
            external: None,
            execution: Some(
                String(
                    "$EDITOR {directory}/{subpath}",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: None,
            keys: [],
            shortcut: None,
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            working_dir: None,
            description: None,
            auto_exec: None,
        },
        VerbConf {
            invocation: Some(
                "git_diff",
            ),
            internal: None,
            external: None,
            execution: Some(
                String(
                    "git difftool -y {file}",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: None,
            keys: [],
            shortcut: Some(
                "gd",
            ),
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: None,
            working_dir: None,
            description: None,
            auto_exec: None,
        },
        VerbConf {
            invocation: Some(
                "terminal",
            ),
            internal: None,
            external: None,
            execution: Some(
                String(
                    "$SHELL",
                ),
            ),
            cmd: None,
            cmd_separator: None,
            key: Some(
                "ctrl-t",
            ),
            keys: [],
            shortcut: None,
            leave_broot: Some(
                false,
            ),
            from_shell: None,
            apply_to: None,
            set_working_dir: Some(
                true,
            ),
            working_dir: None,
            description: None,
            auto_exec: None,
        },
    ],
    skin: None,
    special_paths: {},
    search_modes: None,
    disable_mouse_capture: None,
    cols_order: None,
    show_selection_mark: None,
    ext_colors: {},
    syntax_theme: None,
    true_colors: None,
    icon_theme: None,
    modal: None,
    max_panels_count: None,
    quit_on_last_cancel: None,
    file_sum_threads_count: None,
}
11:31:26.678 [DEBUG] broot::app::app_context: COLORTERM env variable = "24bit"
11:31:26.679 [DEBUG] broot::app::app_context: true colors are available
11:31:26.679 [DEBUG] broot::tree_build::builder: GitIgnorer::default() took 1.406µs
11:31:26.683 [DEBUG] broot::tree_build::builder: trimming prematurely interrupted
11:31:26.695 [DEBUG] broot::app::app: display panel took 1.861245ms
11:31:26.695 [INFO] broot::app::app: pending_tasks took 2.76µs
11:31:29.756 [INFO] broot::app::app: event: Key(KeyEvent { code: Up, modifiers: NONE })
11:31:29.760 [DEBUG] broot::app::app: command after add_event: VerbTrigger { index: 34, input_invocation: None }
11:31:29.761 [DEBUG] broot::app::app: display panel took 645.884µs
11:31:29.761 [INFO] broot::app::app: pending_tasks took 1.302µs
11:31:31.563 [INFO] broot::app::app: event: Key(KeyEvent { code: Right, modifiers: CONTROL })
11:31:31.563 [DEBUG] broot::app::app: command after add_event: VerbTrigger { index: 50, input_invocation: None }
11:31:31.631 [DEBUG] broot::image::image_view: decode image on "/home/host-user/Pictures/MMS/mms-20210625.jpg" took 66.329165ms
11:31:31.632 [DEBUG] broot::app::app: display panel took 486.77µs
11:31:31.701 [DEBUG] broot::image::image_view: resize image took 68.756346ms
11:31:31.701 [DEBUG] broot::image::image_view: resized image dimensions: 88,66
11:31:31.705 [DEBUG] broot::app::app: display panel took 72.047745ms
11:31:31.705 [INFO] broot::app::app: pending_tasks took 3.177µs
11:31:36.229 [INFO] broot::app::app: event: Key(KeyEvent { code: Char('c'), modifiers: CONTROL })
11:31:36.237 [DEBUG] broot::app::app: command after add_event: VerbTrigger { index: 54, input_invocation: None }
11:31:36.238 [DEBUG] broot::task_sync: dead dam
11:31:36.241 [INFO] cli_log::mem: Physical mem usage: current=3.9M, peak=850M
11:31:36.241 [INFO] broot: bye
</details>

**Comment by Canop** [comment]
Can you tell me what's the content of the TERM env var in your kitty ?

**Comment by Kabouik** [comment]
It's `xterm-256color` on the Debian machine.

**Comment by Canop** [comment]
Ok, that's why. Broot recognizes kitty by the TERM env var it sets. Can you fix this value to contain `kitty` ?

**Comment by Kabouik** [comment]
Is that a standard method to recognize the terminal emulator in use?

To be frank `infocomp` is sorcery to me, but as far as I remember, terminals are based on different norms that all share some common ground but there are limits to customizing `TERM`. Some terminals are designed to use `xterm` or variants, and changing that is a hack that may not immediately show but can break things like colors, ncurses support, *etc.* The same kind of compatibility mixups may happen when using `tmux` for instance, as `tmux` also needs a different `TERM` value for 24-bit colours, and changing `TERM` to enable high resolution in `broot` would therefore mean that either resolution or colours would break in `kitty` + `tmux`.

**Comment by Canop** [comment]
This is the fast and safe way. Kitty itself is setting this TERM value, which is meant to identify the terminal.

The other way, that I didn't implement, involves querying the terminal in a non standard way with potential side effects on other terminals. I'd rather use another env variable (that you'd have to set on kitty launch) than doing this hack.

The TTY protocol didn't really define anything clean there...

**Comment by Kabouik** [comment]
`kitty` does not define any `TERM` value by itself on my end, on the two machines and distributions I tested. Maybe @kovidgoyal can tell if this is expected?

Also, while manually setting `TERM` to include "kitty" fixes HR images in `broot`, it prevents running `tmux` or will conflict with the value it needs for 24-bit colours.

`nnn`'s plugin for image previews uses `TERMINAL` instead do detect if the default terminal emulator is `kitty`. That would be fine for me because my `.bashrc` does set this variable, but I imagine not all users define it, and even if they did, that doesn't detect if the actual terminal where the program runs is indeed the one defined in `TERMINAL`.

**Comment by Canop** [comment]
Reading both TERM and TERMINAL would be OK for broot.

**Comment by Kabouik** [comment]
`TERMINAL` is set to "kitty" here but I suspect `broot` gives priority to `TERM`?

**Comment by Canop** [comment]
Right now broot only reads `TERM`. I'll have to modify it (which is easy).

**Comment by Kabouik** [comment]
Oh, got it. Thanks for considering it!

**Comment by Canop** [comment]
Please reopen if it doesn't work.

**Comment by Kabouik** [comment]
Yup, that fixes it for me using TERMINAL and leaving TERM untouched, thanks a lot @canop. Image previews don't work in kitty + tmux though (not even in low resolution, while low resolution do show up if I unset TERMINAL). Not sure how important this issue is, so not reopening.

**Comment by kovidgoyal** [comment]
kitty definitely does set TERM, to xterm-kitty. And the tmux maintainer refused to add
support for images, so those are not going to work. One more reason I
always recommend people ditch terminal multiplexers.

**Comment by Kabouik** [comment]
Thanks for your comment. That's really weird. I triple checked my rc files and TERM is not manually set anywhere, yet its value is "xterm-256color" when I check it in kitty. I'll check the other computer when I am home.

**Comment by kovidgoyal** [comment]
Check kitty.conf as well, you can override the term there.

**Comment by melMass** [comment]
I believe a note about this could be added to broot's doc, I also had `xterm` set in my kitty.conf, removing it properly set it to `xterm-kitty`

**Comment by Canop** [comment]
@melMass I'll add an entry in https://dystroy.org/broot/common-problems/

**Comment by Canop** [comment]
Please @melMass review this entry: https://dystroy.org/broot/common-problems/#high-resolution-images-in-kitty

**Comment by melMass** [comment]
> Please @melMass review this entry: https://dystroy.org/broot/common-problems/#high-resolution-images-in-kitty

Nice! Small note, but it might not be needed to add, `xterm-kitty` is the default if not set at all in config as well.

Thanks!!
