### ISSUE TITLE
To help non-technical users why not include a link to an online color picker?

### ISSUE THREAD

**Issue by Raytle** [Canop/broot#413]
Why not include a link to, for example, https://pinetools.com/image-color-picker at the following point in the Broot documentation https://i.imgur.com/hFZPn62.png

To help technical users (like you) avoid wasting their time, you could include a colored icon with a label such as "For non-technical users" such as the labels shown at [For Dummies](https://www.dummies.com/home-garden/car-repair/auto-body-work/how-to-remove-small-dents-and-dings-from-your-automobile/?keyword=automo&index=2) which I have pointed out with arrows here https://i.imgur.com/gsvzhb0.png.

Developers (like you) often fail to realize how many things that are utterly obvious to you are completely unknown to, I would guesstimate, around 99.99% of the people who live on this planet.

**Comment by Canop** [comment]
I modified the broot site to link to the list of ansi colors from here: https://dystroy.org/broot/skins/#color
