### ISSUE TITLE
How can I apply BTreeMap<base16-ocean.light> to broot?

### ISSUE THREAD

**Issue by Raytle** [Canop/broot#414]
Please see... https://i.imgur.com/Z7p7neE.png

Based on `BTreeMap<String, Theme>` I guessed that maybe I should append… `BTreeMap<base16-ocean.light>` to… `conf.hjson` but based on my testing that failed.

How can I apply `BTreeMap<base16-ocean.light>` to broot?

**Comment by Raytle** [comment]
Please see...https://i.imgur.com/84Xb7oq.png

When I added the skin below (which is listed at https://dystroy.org/broot/skins/#color) to `conf.hjson` I received the following error…

```
y@y-peppy:~$ br -s
Bad configuration file "/home/y/.config/broot/conf.hjson" : unable to parse Hjson: TrailingCharacters at 363:1 at "skin: {\n    def"


```

**Comment by Canop** [comment]
The theme configuration needs a theme name, for example:

    syntax_theme: base16-ocean.light
    
 You can't paste a piece of Rust code in a configuration file.

**Comment by Raytle** [comment]
I don't understand your directions. Am I supposed to create file named, such as, `base16-ocean.light`?

I found the following links by [searching on Google...](https://www.google.com/search?q=rust+how+to+create+a+theme+configuration&client=ubuntu&hs=f2q&channel=fs&sxsrf=ALeKk00uHiu38pgnyZgUGLK65T49ylSFLw%3A1624871704747&ei=GJPZYKH-LJLv-gS356vICw&oq=rust+how+to+create+a+theme+configuration&gs_lcp=Cgdnd3Mtd2l6EAM6BwgjELADECc6BwgAEEcQsANKBAhBGABQqyhY5F5gr2JoAXACeAGAAYYDiAGpFpIBCDAuMTQuMi4xmAEAoAEBqgEHZ3dzLXdpesgBCcABAQ&sclient=gws-wiz&ved=0ahUKEwih6pDm_rnxAhWSt54KHbfzCrkQ4dUDCBA&uact=5)

1. https://docs.rs/cursive/0.8.1/cursive/theme/index.html#colors
2. https://github.com/rust-lang/mdBook/issues/605

> You can't paste a piece of Rust code in a configuration file.

Thanks for letting me know. I appreciate that. This might surprise you, but I had no idea that `syntax_theme: base16-ocean.light` was Rust code.

**Comment by Canop** [comment]
You can't add new syntactic themes to broot. You can only select one of the included themes.

When you add 

     syntax_theme: base16-ocean.light

in conf.hjson, you just tell broot to select the "base16-ocean.light" theme.

**Comment by Raytle** [comment]
I added ` syntax_theme: base16-ocean.light` to `conf.hjson` as shown here –>  https://i.imgur.com/Tha1gZe.png.

Then I ran `br -s` in a terminal. Here is what I saw in my terminal...

`y@y-peppy:~$ br -sBad configuration file "/home/y/.config/broot/conf.hjson" : unable to parse Hjson: TrailingCharacters at 363:1 at "syntax_theme: b"`

**Comment by Canop** [comment]
You seem to have put it after the last `}`, instead of just before.

But I can't be sure without the whole file (as text, not as image)

**Comment by Raytle** [comment]
That worked! Thanks for taking the time to help me with this.

Please see..

https://i.imgur.com/oTPW7d6.png which, of course, I created by taking a screenshot of https://github.com/Canop/broot/issues/412#issue-930987714

Also please see, https://i.imgur.com/9xaUL37.png. 

I have tried being subtle and polite with you but, well, there's a time for being blunt and harsh. This is that time. None of the following is meant to be kind; rather it's meant to be like a splash of cold water in your face.

If you would like to squander countless hours of your time answering unnecessary broot support questions then be sure to edit the following text down to something terse and vague (instead of verbose and clear). That is, of course, sarcasm. You are an engineer who, like every engineer I have ever worked with , is bad at writing documentation for non-technical users.

If you want non-technical users to use broot the—I suppose from your vantage point—the documentation needs to be verbose. On the other hand, if you want technical users to use broot then I suppose the current broot documentation is fine because terse and unclear documentation is an excellent way to repel (alienate) non-technical users.

No, of course, documentation is not UI (user interface). But they are related because they both help users who are unfamiliar with how to use an application to use that application. Please read the following. It clearly applies to you. À toi? Oui Monsieur. À toi.

`"Deep down inside every software developer, there's a budding graphic designer waiting to get out. And if you let that happen, you're in trouble. Or at least your users will be, anyway..." `[This Is What Happens When You Let Developers Create UI](https://blog.codinghorror.com/this-is-what-happens-when-you-let-developers-create-ui/).

I suggest you resist the temptation to apply—what might seem to you to be your deft engineer's editing scalpel—to the text at the bottom of this comment. Instead I encourage you to risk infecting—what is essentially a form of documentation for broot—your beloved creation with something that would actually make sense to non-technical users. 

Furthermore, for a denizen of L'hexagone your English is remarkably good. But, well, the French are not renowned for their mastery of the English language. Therefore, unsurprisingly, much of the broot documentation is "a little bit off" (uses non-standard English) which, in and off itself would not be very problematic (in other words, would not be very problematic per se) but when combined with the typical inane, myopic, obsession that virtually all engineers have with terseness instead of clarity, results in unnecessarily vexing and bewildering documentation.

Put simply: please copy and paste the following into `conf.hjson` **as it is**...

```
   ###############################################################
    # Themes
    #
	# Themes change things such as the colors in broot. You can choose one of the themes below. To add a theme uncomment one of the following by removing the "#" in front of the theme you would like to use and then saving this file. Pleas do not uncomment more than one of the following:
	#
        # syntax_theme: base16-ocean.light
        # syntax_theme: base16-ocean.dark
        # syntax_theme: base16-eighties.dark
        # syntax_theme: base16-mocha.dark
        # syntax_theme: base16-ocean.light
    #
    # After you have chosen a theme above (by uncommenting it) run... br -s ... in a terminal.
    # You should notice that the appearance of broot has changed.
    # For more information about themes please see...
    #
    #https://dystroy.org/broot/conf_file/#syntax-theme
    #https://dystroy.org/broot/conf_file/#colors-by-file-extension

```
