### ISSUE TITLE
Have you considered using docs.rs or readthedocs.org as the wiki for broot?

### ISSUE THREAD

**Issue by Raytle** [Canop/broot#416]
Both of the following seem better to me than the Github wiki...

1. https://docs.rs/about like https://docs.rs/syntect/4.5.0/syntect/highlighting/struct.ThemeSet.html#impl-1? 
2. If you don't like that then have you considered the extremely popular https://readthedocs.org/?

**Comment by Canop** [comment]
broot is already on docs.rs, like all crates published on crates.io
