### ISSUE TITLE
Git worktree: Status not working

### ISSUE THREAD

**Issue by href** [Canop/broot#429]
When running `br -ghc :gs` in a git worktree directory, the status is not shown correctly.

**To Reproduce**
```bash
# Prepare the repository
cd $(mktemp -d)
mkdir foo bar

# Add a commit to the first branch
cd foo
git init
echo foo > foo
git add foo
git commit -m "Initial commit"

# Create a worktree of branch "bar"
git branch bar
git worktree add ../bar bar

# Make  a change to bar
cd ../bar
echo bar > foo
touch bar
```

At this point, `git status` will report a change in `foo` and an untracked `bar`. `br -ghc :gs` will only report line changes, but not show any files.

**Expected behavior**
The output of `br -ghc :gs` should include the same files as `git status`.

**Screenshots**

**Git Status**
![Screenshot of iTerm2 (08-08-21, 15-26-50)](https://user-images.githubusercontent.com/273163/128633561-defdc84d-71e7-44b7-b31e-36ff62bc519c.png)

**Broot**
![Screenshot of iTerm2 (08-08-21, 15-27-02)](https://user-images.githubusercontent.com/273163/128633563-4ac33194-8cd3-4929-9888-aa2a4f065429.png)

**Configuration (please complete the following information):**
- broot version: 1.6.1
- OS: macOS
- Version: 10.15.7

**Comment by Canop** [comment]
Is this issue different than the one just before ?

**Comment by href** [comment]
No, definitely a duplicate of #428. My bad, I noticed the bug a week ago, at the time there was no issue. I remembered to create an issue today, but did not check existing ones again. Sorry for the noise.

**Comment by Canop** [comment]
> Sorry for the noise.

No worry.

Remember to register for notifications on the other issue. I'll try to address it soon.
