### ISSUE TITLE
When a command fails to launch, display its name

### ISSUE THREAD

**Issue by lovasoa** [Canop/broot#43]
Currently, when broot tries to launch an external executable and fails (because the executable is not present), it displays :

```
Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

This message is not very user-friendly, and it would be more helpful if t contained the name of the missing executable. Something like:

```
Unable to launch /usr/bin/nvim: No such file or directory (os error 2)
```

**Comment by ovizii** [comment]
Is this really closed? Sorry to post into such an old thread but its the same question (apparently).

I am using broot 1.1.11 and when navigating to a file i.e.  /root/.config/broot/conf.hjson and hitting enter I get:

`Os { code: 2, kind: NotFound, message: "No such file or directory" }`

if I manually edit it: /root/.config/broot/conf.hjson and replace $EDITOR with "nano" it still does not work except if I press F2 for editing.

```
{
                        invocation: edit
                        key: F2
                        shortcut: e
                        #execution: "$EDITOR +{line} {file}"
                        execution: "nano +{line} {file}"
                        leave_broot: false
                }
```

Am I doing something wrong?

**Comment by Canop** [comment]
@ovizii I'm not sure I understand everything. Could you come to the chat, maybe ? https://miaou.dystroy.org/3490

**Comment by Canop** [comment]
When you hit enter on a file, unless the configuration is changed, `xdg-open` is called.

You may:
1. configure xdg-open
2. call an editor of your choice on open
3. call a system opener of your choice on open

I don't really recommend 2 in the general case as it means you won't have something useful on some files.
1 and 3 are done like this: https://dystroy.org/broot/tricks/#change-standard-file-opening
