### ISSUE TITLE
Automatic skin selection for "light" or "dark" mode

### ISSUE THREAD

**Issue by Canop** [Canop/broot#431]
Some users use several terminals, some light, some dark. There's also the case of unconfigured broot.

For both cases, having in the conf 2 skins for "dark" and "light" terminals (or 3 with a "medium" one) and an automatic switch seems useful. 

The main blocking point was detecting whether the terminal was light or dark but I'm building a crate for that: https://github.com/Canop/terminal-light

Related issue: #430

**Comment by snieda** [comment]
would be nice, if the user could change the dark/light mode with a shortcut/command.
