### ISSUE TITLE
[FEATURE] git pull/push when inside a git repo

### ISSUE THREAD

**Issue by daniejstriata** [Canop/broot#450]
Won't it be possible to add a git verb when inside a git repo to do a "git pull/push/status" without having to exit broot? I see there is already  `git diff`

**Comment by Canop** [comment]
`git diff` in broot is for one specific (selected) file. What would you do with a pull or push ?

**Comment by daniejstriata** [comment]
I would like to go into a directory and update the whole repo from within broot without exiting the TUI. Further, if it could show me the git status of each file dynamically, that would be awesome!

Almost like what Tortiose Git does on Windows.
![image](https://user-images.githubusercontent.com/13314239/135278598-a1037ec2-696e-4927-812a-8301a7024d47.png)

**Comment by Canop** [comment]
There are two approaches, at least, today:

The first one is to se the <kbd>ctrl</kbd><kbd>t</kbd> shortcut which opens a terminal in which you can execute `git pull origin` or whatever then `exit` which brings you back to broot (I personally have a shortcut for all those exit in my .bashrc). This has the advantage of letting you see the operation's progress and result.

The second one is to define specific verbs like this in the configuration:

```hjson
		# git pull
		{
			invocation: "gpl"
			execution: "git pull origin"
			set_working_dir: true
			leave_broot: false
		}

		# git push
		{
			invocation: "gps"
			execution: "git push origin"
			set_working_dir: true
			leave_broot: false
		}
```

**Comment by daniejstriata** [comment]
wow! Nice! Thank you! I'll give it a spin.
