### ISSUE TITLE
Building against source produces compile time errors

### ISSUE THREAD

**Issue by shankargopal** [Canop/broot#451]
**Describe the bug**
When compiling from source to test fix for #448, I get this error:
<pre>
error[E0658]: or-patterns syntax is experimental
  --> src/preview/preview.rs:94:17
   |
94 |             Err(ProgramError::ZeroLenFile | ProgramError::UnmappableFile) => {
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error[E0658]: use of unstable library feature 'clamp'
   --> src/app/app_context.rs:112:14
    |
112 |             .clamp(2, 100);
    |              ^^^^^
    |
    = note: see issue #44095 <https://github.com/rust-lang/rust/issues/44095> for more information

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `broot`.
</pre>

**To Reproduce**

Follow instructions from https://dystroy.org/broot/install/ for installation from source.  

**Expected behavior**

Successful build of broot.

**Configuration (please complete the following information):**
- broot version: Compiling
- OS: Debian Linux
- Version: Testing

`uname -a` output: `Linux debian 5.9.0-3-amd64 #1 SMP Debian 5.9.9-1 (2020-11-19) x86_64 GNU/Linux`

Thank you so much again for a wonderful piece of software, and for the really quick fix for #448!

**Comment by Canop** [comment]
Can you please update your rust compiler (normally with `rustup update`) and tell me whether you still have the error ?

**Comment by shankargopal** [comment]
Sure, if it's buliding for you.   I simply haven't had time to try again
:-(, if I do and it still doesn't work I'll add a note here?  

On Fri, 08 Oct 2021 13:04:54 -0700
Canop ***@***.***> wrote:

> Can I close this ?
> 



-- 
‎

**Comment by Canop** [comment]
I wondered if you had just forgotten the issue. I'll wait more for you to try updating rustup then compiling.

**Comment by Canop** [comment]
I'll close the issue
