### ISSUE TITLE
Alt+enter to cd not working in Win10

### ISSUE THREAD

**Issue by Trid-collab** [Canop/broot#459]
First thank for this excellent file manager. It was just the thing I need for my WIN10 machine. 
I have been using it for the past few days with my Windows Terminal 1.12 
The search is bit slow but workable 

The issue I am facing is with the alt+enter option to cd into the selected directory 
Do I need add any config for me to do this. Presently I am using the default settings - which I presuming is basically nothing

**Comment by RealKelsar** [comment]
> Once it's checked in the log, OP can either change terminal, look into the settings of the terminal, or opt for a different shortcut in broot.

Sorry, I can not find how to change the shortcut, I would like to change it? alt-enter is a global Windows Shortcut to switch between Windowed and Fullscreen Mode, just as explanation.

**Comment by Canop** [comment]
It's documented here: https://dystroy.org/broot/conf_verbs/

You may try this to add this to the verbs section:

		{
			key: alt-c
			execution: ":cd"
		}
