### ISSUE TITLE
--conf Flag Question

### ISSUE THREAD

**Issue by is0n** [Canop/broot#462]
How can I use the following config...
```
verbs: [
	{
		key: enter
		execution: ":print_path"
		apply_to: file
	}
]
```
from `conf.hjson` with `$ broot --conf`?

**Comment by Canop** [comment]
Add the external braces:

```hjson
{
	verbs: [
		{
			key: enter
			execution: ":print_path"
			apply_to: file
		}
	]
}
```

Then, supposing the file is called `pp-conf.hjson`, you can execute `br --conf pp-conf.hjson`

**Comment by is0n** [comment]
Can I use these settings without a config file though?

Something like...
```
$ broot --conf { verbs: [ { key: enter execution: ":print_path" apply_to: file } ] }
```

**Comment by Canop** [comment]
No you can't. You could create the file automatically before launching broot.

What's your use case ?

**Comment by is0n** [comment]
> What's your use case ?

I'm trying to bring broot into neovim with my plugin [fm-nvim](https://github.com/is0n/fm-nvim), however, I need broot to write the selected file's path to `/tmp/fm-nvim`. 

I can do this by using `$ broot --out /tmp/fm-nvim` but I need to write out `:print_path` whenever I want to open a file within neovim. Mapping `enter` to do this is what I'm trying to accomplish but I want to include this mapping in the `$ broot` command as to not use a separate config file.

**Comment by Canop** [comment]
It's a good practice IMO to have separate config files. The standard one is still used but verbs are added or overloaded.

**Comment by is0n** [comment]
So it is not possible to map something to a command with the `$ broot --conf` command right?

**Comment by is0n** [comment]
Is it instead possible to create mappings while inside of broot?

**Comment by Canop** [comment]
No, but I don't understand your problem with creating a file, temporary or not. Creating a file with a few line is fast, and can be done in a script if necessary.

**Comment by is0n** [comment]
My goal with mapping `Enter` to `:print_path` is so that when a user in using broot within neovim, they can just press enter to print the file's path instead of have to input `:print_path`. Once the file's path is written, neovim will the read the file path in the temporary file and then open that file.

This is a bit more tedious since the user has to input `:print_path` whenever they want to open a file within neovim.

**Comment by Canop** [comment]
It's OK and common to remap enter in broot for special uses, but it's normally done with a specific config file.

Have a look at this blog post in which I explain how I use a special config where enter is remapped too: https://dystroy.org/blog/gg/

**Comment by is0n** [comment]
By following your advice, I managed to add support for `broot` in `neovim` so I'll be closing the issue as I got the answer to my question. Thanks for the quick and helpful responses :)
