### ISSUE TITLE
mkdir (:md) not working in powershell

### ISSUE THREAD

**Issue by Shcak** [Canop/broot#466]
Hello,

I’m trying to use Broot on Windows, but I can’t make new directories.

On a fresh install of Broot via Cargo in Powershell, if I use the _:md_ verb it correctly tries to execute _mkdir -p path_. 

A command that works fine in Powershell outside of Broot. 

But it fails and displays "Unable to launch mkdir: Le fichier spécifié est introuvable. (os error 2)"

Thanks

**Comment by Canop** [comment]
It's possible broot needs the whole path to the mkdir executable.

Can you try to add a verb like this ?

```Hjson
{
    invocation: "md {subpath}"
    external: "path/to/mkdir -p {directory}/{subpath}"
}
```

**Comment by Shcak** [comment]
That works !
Mkdir and others commands are not files so I invoke PowerShell with the appropriate commands.
Thanks

**Comment by Canop** [comment]
@Shcak Can you tell me what exact config you put so that I could help other Windows users ?

**Comment by Shcak** [comment]
I used :
```
	{
		invocation: md {subpath}
		leave_broot: false
		external: "powershell -command \"mkdir -path {directory}\\{subpath}\""
	}
```

**Comment by Canop** [comment]
This should probably find its way into the FAQ, I'm just surprised that nobody told me about this problem before so we might be missing something

**Comment by Canop** [comment]
@Shcak to ease typing commands and remove some of the pain with escaping, you may use arrays:

```Hjson
    {
		invocation: md {subpath}
		leave_broot: false
		external: [
                       powershell
                       -command
                       mkdir -path {directory}\\{subpath}
                ]
    }
```
