### ISSUE TITLE
Sort files first

### ISSUE THREAD

**Issue by dermetfan** [Canop/broot#467]
**Did a discussion occur before?**

Yes: https://miaou.dystroy.org/3490?broot#15519690

**Is your feature request related to a problem? Please describe.**

To get an overview of the direct contents of a single folder my eyes have to skip over the sub folders and pick out single files.

**Describe the solution you'd like**

`sort_by_mime`: `inode/directory` would be automatically grouped.

The sort order would list them first.

*Extra:*

It does not matter much whether files or directories are listed first as long as they are grouped.

Ideally we could toggle the sort order, allowing to put files first or last, but always grouped.
It would be nice be able to toggle order for the other sorts as well (`sort_by_count`, `sort_by_date`, `sort_by_size`).
A new verb could be introduced: `toggle_sort_order` / `tso` that applies to all current sorts.

**Describe alternatives you've considered**

Add a setting that just lists files before folders (direct implementation that is not a generalized mime sort).

**Additional context**

Like `ls --group-directories-first`.

**Comment by Canop** [comment]
With `:st`, you can sort by type, with directories either first or last.

I might add a `:toggle_sort_order` another time.
