### ISSUE TITLE
Support alternative keyboard escape sequences

### ISSUE THREAD

**Issue by stevenxxiu** [Canop/broot#475]
I'm using [Fix Terminals - Please](http://www.leonerd.org.uk/hacks/fixterms/) for my keyboard escape sequences.

A lot of the default keys don't appear work in my terminal, such as:

- `Home`: `:input_go_to_start`
- `End`: `:input_go_to_end`
- `Alt + C`: `:copy_path`
- `Ctrl + Home`: `:focus ~`

Could this be supported? It would be enough to support assigning any escape sequence to any verb. The escape sequences in [Fix Terminals - Please](http://www.leonerd.org.uk/hacks/fixterms/) could also be hard-coded and supported directly using some library, but that's optional.

Many other software support this, such as *Kitty* (with slightly modified escape sequences), *WezTerm*, *Tmux*.

**Comment by Canop** [comment]
I'm not sure I understand what you ask.

I checked this configuration works:

```Hjson
		{
			key: home
			internal: input_go_to_start
		}
```

**Comment by stevenxxiu** [comment]
Ah that works indeed. I thought those key bindings were included by default from what I saw in https://dystroy.org/broot/conf_verbs/#input-related-verbs, but I have to specify them manually. Sorry about that.

**Comment by Canop** [comment]
Oh, I understand your issue now.

You're perfectly right, they should be bound by default (to conform the doc).

I'll fix that.
