### ISSUE TITLE
Python syntax highlighting in preview stops at the first comment

### ISSUE THREAD

**Issue by shaypal5** [Canop/broot#477]
broot 1.8.1 on macOS 11.6.1.
broot is opened in a bash shell, in a `byobu` (`tmux`) window inside an iTerm2 3.4.14 window.

As can be seen, syntax highlighting of Python files stops at the first comment, making it a bit unusable, as `# noqa: ...` comments that disable PEP8 warnings can be quite common in the first line of a Python file, as are general start-of-file comments.

It doesn't matter if the comment is inline or not.

![image](https://user-images.githubusercontent.com/917954/148198684-556f7cb3-5f5e-4434-968e-7ad7968176ce.png)

![image](https://user-images.githubusercontent.com/917954/148198767-4bd12b47-c7a7-4bc5-b626-2737a1237010.png)

**Comment by Canop** [comment]
I can reproduce the problem. Thanks for the report.

**Comment by shaypal5** [comment]
Thank you for the prompt response and this great open source project. :)
