### ISSUE TITLE
stage file and move to next file

### ISSUE THREAD

**Issue by jack99999** [Canop/broot#479]
i searched the docs but couldn't find this mentioned... when i stage a file i often want to stage another. my preference is to stage the current file and then have the cursor move to the next file in the list. sometimes i want to stage several files together, which means ^G <Down> repeatedly. 

i was able to implement this easily using Autokey, but that is an external application. would be neater as an option in the broot configuration file.

jack

**Comment by Canop** [comment]
You can define a shortcut like this:


		{
			key: ctrl-k
			cmd: ":stage;:line_down"
		}

**Comment by jack99999** [comment]
Ah, that's excellent. I didn't realise i could string commands together.

Many thanks

⁣Jack​

**Comment by jack99999** [comment]
can i possibly plead for the equivalent .toml definition? is there any particular reason why i should use one format rather than the other... i chose .toml because it looked a bit simpler but it's no big deal.

**Comment by Canop** [comment]
In TOML, this would be

```TOML
[[verbs]]
key = "ctrl-k"
cmd = ":stage;:line_down"
leave_broot = false
```

**Comment by jack99999** [comment]
that's excellent. fwiw, i changed that to :toggle_stage which suits me better.

many thanks for the quick help
