### ISSUE TITLE
homebrew package for Mac

### ISSUE THREAD

**Issue by Canop** [Canop/broot#48]
That's something I've been asked for a few times.

I'd need somebody with a mac to look at it and propose a solution for package generation and maintenance, I have no idea how macs work those days...

@lovasoa maybe?

**Comment by kevinastone** [comment]
I added a home-brew formula in Homebrew/homebrew-core#42907.  It could use a better test (I just verify the `--version` runs correctly).  Is there a good simple test to run on the command to ensure it's built and installed correctly?

**Comment by Canop** [comment]
I'm far from computers in august so I can't really devise anything complex but a test could be to check the output of a command given with --cmd, for example outputting the tree (see https://dystroy.org/broot/documentation/usage/#export-a-tree)

**Comment by kevinastone** [comment]
Added a print-tree test: https://github.com/Homebrew/homebrew-core/pull/42907/commits/56a77558a302a14acf01fbed91cd2569ca58512d

**Comment by Canop** [comment]
I have no mac and absolutely no knowledge of homebrew. I'd need some mac user inputs to go further.

**Comment by dbast** [comment]
broot is now available on win/osx/linux via conda: `conda install -c conda-forge broot` :)

**Comment by Canop** [comment]
Thanks for that.
But I don't know Conda. How, as the broot developper, am I supposed to guarantee it's kept up to date and that it's what it's supposed to be ?

**Comment by dbast** [comment]
Packaging is done via so called feedstocks and the build recipe can be found in the recipe folder here https://github.com/conda-forge/broot-feedstock

You can also contribute updates to the feedstock via PR and become maintainer.

There is a bot in place, who is triggered by new upstream releases and automatically proposes updates via PR to the feedstock, that just can be reviewed and merged in most cases.

**Comment by Canop** [comment]
I think we can close this.

If there's a problem with the current homebrew package, we'll create a new issue.
