### ISSUE TITLE
Question: How make `panel_right` work with `ctrl+right` on iTerm2?

### ISSUE THREAD

**Issue by shaypal5** [Canop/broot#480]
Hey,

I apologize for the silly question, but I've been through the documentation and all listed issues (open and closed), and searched through both with several relevant keywords (preview, focus, etc,), but I can't for the life of me figure out what verb or command can get me to focus on the preview panel.

I've managed to bind the `open_preview` command to `ctrl-p`, and if I click anywhere on the preview panel with the mouse cursor it becomes focused -  and I can then browse and search it to my heart's content - but I can figure out a way to do it without using my mouse. And I'd like to. :)

Thank you!

**Comment by Canop** [comment]
Here's how I usually go to the preview panel:
- when it's already open: with <kbd>ctrl</kbd><kbd>right</kbd>, which is bound to `:panel_right`
- when it's not open: by selecting a file then open the preview with <kbd>ctrl</kbd><kbd>right</kbd>, because `:panel_right` opens the preview when a file is selected and there's no panel to the right

Is that OK or do you need more ?

**Comment by shaypal5** [comment]
I think that should be ok, and it's not working for me because Karabiner Elements hijacks this sequence to make it a way to jump to next/previous word in a terminal line while you're editing it. I'll have to see what I can do about that.

**Comment by shaypal5** [comment]
Makes a lot of sense. Can I bind command on mac? This doesn't seem to work:
```
{
    invocation: panel_right
    key: cmd-right
    apply_to: file
    external: "vim {file}"
    leave_broot: false
}
```

**Comment by shaypal5** [comment]
I think like I'm very close to solving this, based on the kind of solution I've opted for in the `alt-enter` issue.

But here iTerm2 has a default mapping in play:
![image](https://user-images.githubusercontent.com/917954/148995545-b413ed6d-300e-4c1b-9534-0a808f777197.png)

It doesn't map `ctrl-right-arrow` to a series of hex codes, but rather to an escape sequence. 

This can be seen in the resulting `broot` log file. I press the down arrow twice, then `ctrl-right-arrow` and finally `ctrl-c`:

```python
19:53:33.778 [INFO] broot::app::app: event: TimedEvent { time: Instant { t: 551060033159976 }, event: Key(KeyEvent { code: Down, modifiers: NONE }), double_click: false }
19:53:33.778 [DEBUG] broot::app::app: command after add_event: VerbTrigger { index: 76, input_invocation: None }
19:53:33.783 [DEBUG] broot::app::app: display panel took 4.420964ms
19:53:33.784 [INFO] broot::app::app: pending_tasks took 1.065µs
19:53:34.125 [INFO] broot::app::app: event: TimedEvent { time: Instant { t: 551060381168289 }, event: Key(KeyEvent { code: Down, modifiers: NONE }), double_click: false }
19:53:34.126 [DEBUG] broot::app::app: command after add_event: VerbTrigger { index: 76, input_invocation: None }
19:53:34.131 [DEBUG] broot::app::app: display panel took 4.657495ms
19:53:34.132 [INFO] broot::app::app: pending_tasks took 835ns
19:53:36.927 [INFO] broot::app::app: event: TimedEvent { time: Instant { t: 551063182421712 }, event: Key(KeyEvent { code: Esc, modifiers: NONE }), double_click: false }
19:53:36.927 [DEBUG] broot::app::app: command after add_event: Internal { internal: back, input_invocation: None }
19:53:36.934 [DEBUG] broot::app::app: display panel took 6.293004ms
19:53:36.935 [INFO] broot::app::app: pending_tasks took 1.058µs
19:53:36.935 [INFO] broot::app::app: event: TimedEvent { time: Instant { t: 551063190914573 }, event: Key(KeyEvent { code: Char('f'), modifiers: NONE }), double_click: false }
19:53:36.936 [DEBUG] broot::app::app: command after add_event: PatternEdit { raw: "f", expr: BeTree { atoms: [PatternParts { parts: ["f"] }], nodes: [Node { operator: None, parent: None, left: Atom(0), right: None, unary: false }], head: 0, tail: 0, last_pushed: Atom, op_count: 0, openess: 0 } }
19:53:36.939 [DEBUG] broot::app::app: display panel took 3.268597ms
19:53:36.941 [DEBUG] broot::tree_build::builder: GitIgnorer::default() took 52ns
19:53:36.941 [DEBUG] broot::git::ignore: pushing GIF GitIgnoreFile {
    rules: [
        GitIgnoreRule {
            ok: false,
            directory: false,
            filename: true,
            pattern: "*.swp",
        },
    ],
}
19:53:37.149 [DEBUG] broot::tree_build::builder: blines before trimming: 1281
19:53:37.162 [INFO] broot::browser::browser_state: tree filtering on "f" took 220.846785ms
19:53:37.167 [DEBUG] broot::app::app: display panel took 4.697533ms
19:53:37.168 [INFO] broot::app::app: pending_tasks took 227.189589ms
19:53:38.557 [INFO] broot::app::app: event: TimedEvent { time: Instant { t: 551064812631067 }, event: Key(KeyEvent { code: Char('c'), modifiers: CONTROL }), double_click: false }
19:53:38.557 [DEBUG] broot::app::app: command after add_event: VerbTrigger { index: 38, input_invocation: None }
19:53:38.557 [DEBUG] broot::task_sync: dead dam
19:53:38.558 [INFO] broot: bye
```

**Comment by shaypal5** [comment]
I'm not sure `panel_right` will solve my problem. I've rebound it with the following definition, and while it opens a preview panel, the focus does not shift:

```
{
    invocation: my_panel_right
    key: ctrl-v
    internal: panel_right
}
```

**Comment by shaypal5** [comment]
Ok, but it does seem that a second invocation of `ctrl-v`, when the panel is already open, will shift focus to it. That's a bit better!

**Comment by Canop** [comment]
If you want to do both with just one key, you may either

* replace `internal: panel_right` with `cmd: ":panel_right;:panel_right"`
* ask me to add a `:open_focused_preview` internal but it may take some time as I currently lack time for open-source

**Comment by shaypal5** [comment]
The first option sounds like enough. I don't think this is a priority for a feature.

I would love to know if the mac ⌘ key is supported for key combinations. I think `⌘+right` would be a great solution for me.

**Comment by shaypal5** [comment]
I'm closing this as this is not a `broot` issue, but rather a combination of my current `byobu`-related use of `alt-right` and `alt-left` which I didn't want to give up, and some special Mac+iTerm2 shenanigans.

For the protocol, I ended up binding `alt-p` to `cmd: ":panel_right;:panel_right"`, which enables me to jump immediately into a previewed file, and I use `ctrl-p` to just toggle the preview panel. I re-mapped the `my_panel_right` internal to just `right`, which works ok for me now. Together with the working `enter` and `alt-enter` binds (see #481) for editing selected files with `vim` (with/without leaving `broot`), I feel like I'm getting a lot out of `broot` for the moment. :)

Note: To make `alt-p` work on iTerm2 (on macOS Big Sur 11.6.1) I added a mapping of `alt-p` to `Send ^[ p` in my iTerm2 profile. You can do this by selecting `Send Escape Sequence` from the dropdown menu, and add **just** the letter `p` in the text box:

![image](https://user-images.githubusercontent.com/917954/149099499-32829aab-e4b9-4567-a751-13b25964e8ff.png)
