### ISSUE TITLE
Buffer to Stderr

### ISSUE THREAD

**Issue by elferherrera** [Canop/broot#482]
I just wanted to say thank you because your crate help us reduce flickering in Reedline. 

My only question is, why this type
```
pub type W = std::io::BufWriter<std::io::Stderr>;
```
is a buffer to Stderr and not to Stdout?

I tried changing it to Stdout and the flickering is back. I hope you can help me understand this.

Thanks in advance

**Comment by Stargateur** [comment]
I don't know if this is the case here, but on unix system, stderr is often used on interact with terminal application, this allow to not "pollute" the stdout and so using standard pipe redirection like `broot > result`. It's also sometime possible to write on `stdin` for the same reason but it's less used and less recommended (as far as I remember)

**Comment by elferherrera** [comment]
I see. So the crossterm actions are still implemented into the terminal but we are sending the characters to Stderr. I would have never thought about that one. Thanks for the explanation

**Comment by Canop** [comment]
Sorry I wasn't here. @Stargateur is totally right.

Imaging you're doing `cd $(broot)` in your shell and you expect broot to return a path. This can only works if stdout hasn't been polluted by the TUI display. Hence the use of stderr.

**Comment by elferherrera** [comment]
Thanks a lot for the explanation. It makes sense now why it works so well in reedline as well.
