### ISSUE TITLE
error: Found argument '-¨' which wasn't expected

### ISSUE THREAD

**Issue by Robert-Schmid** [Canop/broot#483]
Trying to use `br` or `broot` in my terminal I get the following error:

```
error: Found argument '-¨' which wasn't expected, or isn't valid in this context

USAGE:
    broot [FLAGS] [OPTIONS] [ROOT]

For more information try --help
```

Note, the `¨` is not the ususal `"` but `\u{A8}`.

Any sugguestions on where this argument might come from are welcome.
I don't have any issues with any other cl tools.

I'm on Manjaro and installed broot from the official repository, but I have the same issue if I install broot from the unstable channel with nix.
Versions in my terminal are:

broot --version
broot 1.8.0  (pacman)
broot 1.7.4  (nix)

kitty --version
kitty 0.23.1 created by Kovid Goyal

zsh --version
zsh 5.8 (x86_64-pc-linux-gnu)

**Comment by Canop** [comment]
> Any sugguestions on where this argument might come from are welcome.

I have no idea here. We might have to use a special version dumping the args in the log. Can you try with another shell ?

**Comment by Robert-Schmid** [comment]
It persists in the gnome terminal 
`GNOME Terminal 3.42.2 using VTE 0.66.2 +BIDI +GNUTLS +ICU +SYSTEMD`

and in /bin/bash
`GNU bash, version 5.1.12(1)-release`

**Comment by Canop** [comment]
I've added a little additional log.
If you can run the current master with [debug log enabled](https://dystroy.org/broot/community/#log) it might help understand what happens.
If you can't fetch and compile broot, no problem: I should create a release in a few days.

**Comment by Robert-Schmid** [comment]
Thanks, let me know about the new release.

Or I will compile it once pacman updates their rust from 1.57.
I just want to avoid non-pkg-managed stuff that I rarely use.

**Comment by Canop** [comment]
@Robert-Schmid I just released broot v1.9.2 with the aforementioned log.

**Comment by Robert-Schmid** [comment]
Thank you. Seems to be an issue with the default flag in my conf.hjson.
So probably my fault, I don't remember what I did exactly when I last had a look at the config.
You can see it at https://github.com/Robert-Schmid/configuration/blob/manjaro/config/broot/conf.hjson

No idea how the wierd characters got in there and it seems that I don't need quotes in hjson at all compared to the old conf.toml

It works for me now. Thank you for the help. Here's the log in case you are interested:
[broot.log](https://github.com/Canop/broot/files/7920759/broot.log)

**Comment by Canop** [comment]
Thanks for the explanation.
Reopening: There should have been a better error message.

**Comment by Canop** [comment]
Will be clearer, I think:

![image](https://user-images.githubusercontent.com/617006/150688058-175ac2bc-3093-4dc8-8413-bd5583bc4d7f.png)
