### ISSUE TITLE
preview of pictures and pdf ?

### ISSUE THREAD

**Issue by evanescente-ondine** [Canop/broot#489]
Hi.
I'm not sure if it's not a feature or I can't find how to do it.
Can we preview pictures, like in ranger for instance ?
I need to renames lots of pictures, and seeing them at the same time would be useful...
Thanks

**Comment by Canop** [comment]
Yes you can review pictures. Hit ctrl-rightarrow

See https://dystroy.org/broot/#preview-files

**Comment by evanescente-ondine** [comment]
so, a bug it was... I'll purge the profile and reinstall.

**Comment by Canop** [comment]
Hum. Your report isn't really clear nor actionnable, now.

**Comment by Canop** [comment]
Closing as unclear. Reopen if you can provide a clear description of the problem.
