### ISSUE TITLE
Regex capture groups in custom verbs are not parsed when using `--cmd`

### ISSUE THREAD

**Issue by Ryujinra** [Canop/broot#49]
Regex capture groups in the invocation in custom verbs are not parsed at all when using `--cmd`.

For instance, this custom verb:

```
[[verbs]]
name = "mpv"
invocation = "mpv (?P<args>.*)"
execution = "mpv {args} {file}"
from_shell = true
```

With this this cli command:

`br --cmd "somefile.mp4 :mpv --loop"`

Will pass the literal string `{args}` to mpv, instead of the expected behavior of matching and substituting `--loop`.

Thanks for your work.

**Comment by Canop** [comment]
Damn... I didn't even think about this... A new syntax might be necessary...

**Comment by Canop** [comment]
@Ryujinra Please confirm it's OK for you (or reopen if it's not).

**Comment by Ryujinra** [comment]
Yep, works fine for me.
