### ISSUE TITLE
show only search results without tree structure, and sort results

### ISSUE THREAD

**Issue by evanescente-ondine** [Canop/broot#490]
I wish to emulate fzf selector behavior by showing only results, if possible only their basename, without the tree, sorting these results.
It would make researching much more comfortbale, for those with complex trees and looong directory names !

Thanks for your work, it's the single best and best written piece of software I've come across, and God knows my exigences are sky high.

**Comment by Canop** [comment]
It depends on the search mode. The current default is a search on path. If you switch to a search on filename, the path isn't repeated. See https://dystroy.org/broot/conf_file/#search-modes

Try for example with

```Hjson
"search-modes": {
    <empty>: fuzzy name
    /: regex name
    z/: regex path
}
```

**Comment by evanescente-ondine** [comment]
I see, thanks.
It would be great to toggle that behavior, regardless of the search mode. I do need to search on the path too, but that doesn't mean I want it to show.

**Comment by Canop** [comment]
The reason it's shown is so that the matching chars are displayed.

**Comment by Canop** [comment]
> But it would be useful to let the user decide anyway.

This can be made configurable.
