### ISSUE TITLE
Use mutool draw for previewing PDFs

### ISSUE THREAD

**Issue by mizlan** [Canop/broot#494]
MuPDF's `mutool draw` command produces a decently high-resolution image form of a PDF. It can be specified to only produce an image of the first page, which would be nice for previewing PDFs.

Quick demo (after installing MuPDF):

```bash
$ mutool draw -o pdf-preview.png julia-1.5.0.pdf 1 # can add 2>/dev/null
page julia-1.5.0.pdf 1
$ kitty +kitten icat pdf-preview.png
```

Or directly through stdout:

```bash
mutool draw -o - julia-1.5.0.pdf 1 2>/dev/null | kitty +kitten icat
```

**Comment by xxyxxyxyx1** [comment]
PDF previews would allow me to use broot as my main file browser, I hope it can be added! In addition to mutool, the [Kitty icat](https://sw.kovidgoyal.net/kitty/kittens/icat/) method may be of interest. It uses ImageMagick to open both images and pdfs. (For a pdf, one generally needs a white background.)
`kitty +kitten icat --background white stuff.pdf`

**Comment by andrej1919** [comment]
> PDF previews would allow me to use broot as my main file browser, I hope it can be added! In addition to mutool, the [Kitty icat](https://sw.kovidgoyal.net/kitty/kittens/icat/) method may be of interest. It uses ImageMagick to open both images and pdfs. (For a pdf, one generally needs a white background.) `kitty +kitten icat --background white stuff.pdf`

Just discovered Broot. Amazing application. PDF previews are literately the only missing feature.

**Comment by Canop** [comment]
@xxyxxyxyx1 @mizlan @andrej1919 Feedback on https://github.com/Canop/broot/pull/898 would be welcome
