### ISSUE TITLE
Navigating down, then back up says "Hit <enter> to quit", which doesn't work

### ISSUE THREAD

**Issue by jonas-schievink** [Canop/broot#5]
Steps to reproduce:

* Run broot. The status line correctly says `Hit <esc> to quit`
* Hit `<down>` to select the first file. The status line says `Hit <enter> to open the file`.
* Hit `<up>` to select the current folder again. The status line now incorrectly says `Hit <enter> to quit`, which doesn't do anything.

**Comment by Canop** [comment]
Confirmed.
