### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by Canop** [Canop/broot#50]
In the next few days|weeks|centuries, I'll be attempting this.

This will involve replacing termion with crossterm or pancurses... and do many changes.

**Comment by Canop** [comment]
The rewritten version (in the crossterm branch) now runs both on Windows 10+ and Linux.

There's still a lot of work to do and **I need testers**.

Please come [here](https://miaou.dystroy.org/3490?broot#10739988) if you're willing to test and to see the living matrix of features.

Current state:

# State of the crossterm branch
Feature|Linux|Windows 10+|
:-|:-:|:-:|
run in launching teminal | ok | seems ok
screen view | ok | ok
searches | ok | ok
navigation | ok | ok
markdown in help | no | no
file/dir size | ok | no
read prefs | ok | ?
hidden files | ok | no
gitignore | ok | ?
--cmd | ok | ?
open on specific path | ok | ?
external program launching | ok | ?
open in external viewer | ok | ?
open in external editor | ok | ?
user permissions | ok | no
configured skin | no | no
br shell function | ok | no
alt-enter to cd | ok with br | ?

**Comment by Canop** [comment]
The crossterm branch has been merged into master.

Broot can now be compiled and launched on windows, and a broot.exe can be downloaded from the site.

**I won't be able to up the quality and feature level of the windows version without help from windows developers, though.**

**Comment by harrysarson** [comment]
Hi! I tried to build current master (f1ec96bcf72f8cff71bf1caca55f960c84ca4996) from source on windows (using `stable-x86_64-pc-windows-msvc (default) rustc 1.35.0 (3c235d560 2019-05-20)`).

Broot built fine but then when I tried to run the executable I got an error:

```
PS C:\Users\harry\rust\broot> cargo run --release -- .\.git\
    Finished release [optimized] target(s) in 0.14s
     Running `target\release\broot.exe .\.git\`
IO Error : "A required privilege is not held by the client. (os error 1314)"
```

Setting `$env:BROOT_LOG="trace"` resulted in:

```
15:02:52 [ INFO] Starting Broot v0.9.3 with log level TRACE
15:02:52 [ INFO] creating link from "C:\\Users\\harry\\AppData\\Roaming\\dystroy\\broot\\config\\launcher\\bash\\br" to "C:\\Users\\harry\\AppData\\Roaming\\dystroy\\broot\\config\\launcher\\bash\\1"
15:02:52 [ WARN] Error: IO Error : "A required privilege is not held by the client. (os error 1314)"
```

Is there anything I can do to help debug this more?

**Comment by harrysarson** [comment]
I should add that I am using power shell.

**Comment by Canop** [comment]
(I have absolutely no idea of how to solve this Windows related problem)

**Comment by FrancescElies** [comment]
I get the same `(os error 1314)`  on windows.

ℹ If you run it in a prompt with admin rights the problem goes away, why broot requires admin rights is not clear to me though.

If I set `set BROOT_LOG=debug` I don't see any extra information (probably I am doing something wrong here)

**Comment by Canop** [comment]
Just to be sure @FrancescElies @harrysarson do you also have the problem when downloading the executable from GH ?
(I promise there aren't many trojan inside)

**Comment by FrancescElies** [comment]
Update:

Broot requires admin rights the first time you run it, because it tries to create `%home%/AppData/Roaming/dystroy/broot/config/conf.toml`.
After the first time you run broot with admin rights, you no longer get `os error 1314`

**Comment by Canop** [comment]
Oh... thanks!

Is there a way on windows to change the config without admin rights and still use a proper location ?

If not I should mainly add a proper error message explaining why admin rights are needed and that it's only for the first use.

**Comment by FrancescElies** [comment]
> Is there a way on windows to change the config without admin rights and still use a proper location ?

Not sure, I'm not a windows dev but if I discover something I'll report back.

**Comment by Canop** [comment]
I've added a mention in installation doc for the needed rights: https://dystroy.org/broot/documentation/installation/

Right now I'll close the present issue but I might accept new issues or PR related to this right problem or other Windows problems.

**Comment by 71** [comment]
I'm trying to use this on Windows (through PowerShell Core) now and made a PowerShell script to mimic `br`. The problem I now hit is that Broot [calls](https://github.com/Canop/broot/blob/d327ae6cb0fd00b66f4ca33664b904684269e9e0/src/cli.rs#L151) [`std::fs::canonicalize`](https://doc.rust-lang.org/std/fs/fn.canonicalize.html), which returns a path like `\\?\C:\Users\71`, instead of `C:\Users\71`. Therefore using `:cd` inside Broot will write a command `cd '\\?\A:\foo'`, which will confuse PowerShell (and I'm guessing a bunch of other commands). Right now my workaround is to execute `$Command.Replace('\\?\', '')` instead of `$Command`, but this is ugly.

For reference, the script is:
```pwsh
function br
{
    $TempFile = New-TemporaryFile
    broot.exe --outcmd $TempFile $Args

    if (!$?)
    {
        Remove-Item -Force $TempFile
        return $LASTEXITCODE
    }

    $CommandToExecute = Get-Content $TempFile
    Remove-Item -Force $TempFile
    Invoke-Expression $CommandToExecute.Replace('\\?\', '')
}
```

**Comment by Canop** [comment]
@71 Thanks for this. I'd prefer to have it in a dedicated issue so that we can discuss it in a detailed way. Can you create it ?

Related: I think I'll close the present issue which is too wide (there are probably many independent problems on windows).

**Comment by mqudsi** [comment]
fwiw, alt-enter is the shortcut to full-screen the terminal, it can't be disabled within cmd.exe

**Comment by Canop** [comment]
Is cmd.exe still relevant on Windows ? What about powershell ? An alternative natural key combination ?

Note that I'd need dedicated testers able to both test and try changing code for the windows version as I lack both competences and computer when it comes to this OS. If you volunteer, please come to the Miaou chat : https://miaou.dystroy.org/3

**Comment by mqudsi** [comment]
I was being imprecise. cmd is the old shell, powershell the newer one, and pwsh the newest. The shortcut is a feature of conhost, the Windows terminal (and the only terminal available oob or officially endorsed, though there is a new one in preview).

**Comment by carlinmack** [comment]
I'm using windows terminal and facing the same issue with alt-enter. 

(on a side note is $EDITOR set in .bashrc or in the config file?)

**Comment by SMUsamaShah** [comment]
I keep getting os 1314. Tried both cmd, powershell with administrator privileges.

Keep seeing this

```
Can I install it now? [Y/n]

Removing C:\Users\usama\AppData\Roaming\dystroy\broot\data\launcher\bash\1.
Writing br shell function in C:\Users\usama\AppData\Roaming\dystroy\broot\data\launcher\bash\1.
Creating link from C:\Users\usama\AppData\Roaming\dystroy\broot\config\launcher\bash\br to C:\Users\usama\AppData\Roaming\dystroy\broot\data\launcher\bash\1.
IO Error : "A required privilege is not held by the client. (os error 1314)"
```

**Comment by rgwood** [comment]
A few people in this thread were running into issues with Windows Terminal using `alt+enter` as the default keybinding for fullscreen. The keybinding can be disabled like so in settings.json:

```
{ "command": null, "keys": "alt+enter" }
```

**Comment by Canop** [comment]
@rgwood This is interesting. Could you make a PR for [this page](https://dystroy.org/broot/common-problems/) or give me a little more details (exact name of the involved terminal, maybe a link to its online help) ?

**Comment by rgwood** [comment]
Sure, I'll try to submit a PR to the docs today. 

For posterity, this is an issue in [Windows Terminal](https://en.wikipedia.org/wiki/Windows_Terminal) (the new/modern first-party terminal on Windows). Windows Terminal is mostly configured via a `settings.json` file. Actions and keybindings are configured in the `actions` array in `settings.json` ([docs](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions)).
