### ISSUE TITLE
Alt + Up/Down to move around Folders

### ISSUE THREAD

**Issue by aalakhan19** [Canop/broot#502]
I would like to have a way to move around folder to folder with maybe Alt+Up/Down

**Comment by Canop** [comment]
You mean like up/down/next but skipping simple files ?

**Comment by aalakhan19** [comment]
yeah exactly, normal up/down goes file by file, and for example Alt + Up/down skips simple files and goes from folder to folder

**Comment by Canop** [comment]
I'll probably add internals for that it's possible to define verbs with keyboard shortcuts.

**Comment by aalakhan19** [comment]
that would be great!

**Comment by Canop** [comment]
This will be in the next release.

Here's an example configuration:

```Hjson
		{
			key: ctrl-up
			internal: previous_dir
		}

		{
			key: ctrl-down
			internal: next_dir
		}
```

**Comment by Canop** [comment]
broot 1.9.3 has been released

**Comment by aalakhan19** [comment]
thank you very much
