### ISSUE TITLE
Feature request: allow user to override verbs

### ISSUE THREAD

**Issue by magnetophon** [Canop/broot#51]
Since I'm using NixOS, none of the binaries are where broot expects them.
It would be nice if I could put:
```
[[verbs]]
name = "mkdir"
invocation = "md"
execution = "/run/current-system/sw/bin/mkdir -p {directory}/{subpath}"
```
in my config and have it override the default.

**Comment by Canop** [comment]
@magnetophon you can now override the default.

Your verb definition would be like this:

    [[verbs]]
    name = "mkdir"
    shortcut = "md"
    invocation = "mkdir {subpath}"
    execution = "/run/current-system/sw/bin/mkdir -p {directory}/{subpath}"

This is available in master on the repository. Tell me if you'd like a new release soon and I'll try to do one tonight.

**Comment by magnetophon** [comment]
Great, thanks!
Make a release when you feel it's needed, they are frequent enough as it is.
