### ISSUE TITLE
Confusing documentation on how to select staging area

### ISSUE THREAD

**Issue by izidormatusov** [Canop/broot#510]
First of all, I love broot! It's such an amazing tool.

I was using the staging area to find large folders to empty enough disk space. I was able to select the folders without issues using `ctrl+g`.

However, I got stuck on how to focus staging area to execute `rm` command on all selected files. From [the documentation](https://dystroy.org/broot/staging-area/#execute-a-command):

> Focus the staging area (usually with ctrl→) then type the verb in the input.

I'm on Mac and ctrl→ is mapped to OS-level switch to next workspace. When I disabled it, still nothing happened. (I do not have any custom broot config).

[Another part of the documentation](https://dystroy.org/broot/conf_verbs/#focus) says:

> for example :!focus is equivalent to ctrl→

However `:!focus` opens a new panel instead of focusing the staging area:

<img width="969" alt="Screen Shot 2022-02-20 at 07 35 20" src="https://user-images.githubusercontent.com/98588/154831881-9a8b3ab2-4cea-41d3-b9a5-0b55afe3f71c.png">

I eventually resolved the issue by mouse clicking the on the staging area.

Another way that I found to do this was to use `:panel_left` or `:panel_right`. I have discovered those commands via command autocomplete. As far as I can tell, those commands are not documented anywhere.

**Comment by Canop** [comment]
@izidormatusov The most important part of your issue is this: https://github.com/Canop/broot/issues/497
I need to write a clear entry in the FAQ for all the mac users who have this problem

And I'll have a look at the list of internals for the missing `:panel_left` and `:panel_right`

**Comment by Canop** [comment]
I've improved the documentation, especially here: https://dystroy.org/broot/panels/#keyboard-shortcuts
