### ISSUE TITLE
menubar doesn't scroll = hidden items

### ISSUE THREAD

**Issue by CouldBeThis** [Canop/broot#514]
Hi, 

On the broot website, because the navigation bar doesn't scroll, the bottom gets cut off on a small screen. Especially with larger text as might be required by someone with poor vision. By reducing the text size I can see there are 4 items missing. 

Not sure how to solve it.

![Screenshot 2022-03-12 at 09-36-13 Broot](https://user-images.githubusercontent.com/53547181/158012777-1769dcca-ea12-4573-8eec-484d1687c871.png)

**Comment by Canop** [comment]
Just changed it to have a scrollbar if it doesn't fit.
Does that look fine to you ?

**Comment by CouldBeThis** [comment]
cool it does! thanks
