### ISSUE TITLE
Only x86_64 binary changed in v1.9.4 release?

### ISSUE THREAD

**Issue by eggbean** [Canop/broot#515]
I don't know if this is am error or not, but I just upgraded to v1.9.4 and only the x86-64 binary changed. The aarch64 and arm binaries are the same as v1.9.3.

**Comment by Canop** [comment]
It must be an error my side. How did you upgrade ?

**Comment by eggbean** [comment]
I unzipped the file under Releases. I put all three version in a dotfiles/binaries repository that get stow symlinked depending on host architecture.

**Comment by Canop** [comment]
The build is failing...

     error: failed to run custom build command for `libz-sys v1.1.3`

I'll have a look as soon as possible, hopefully today

**Comment by Canop** [comment]
I'll start by removing the release.

**Comment by Canop** [comment]
One of the dependencies of git2 doesn't compile on cargo-cross anymore...

**Comment by Canop** [comment]
I released the 1.9.4 by downgrading rust to 1.58. I'll create a different issue

**Comment by Canop** [comment]
https://github.com/Canop/broot/issues/516
