### ISSUE TITLE
cargo cross compilation fails on rust 1.59

### ISSUE THREAD

**Issue by Canop** [Canop/broot#516]
The commands I use in for cross compilation are in compile-all-targets.sh.

An example:

    cross build --target armv7-unknown-linux-gnueabihf --release

Such command works with rsut 1.58 but fails with the 1.59 toolchain with

```
   Compiling libz-sys v1.1.5
error: failed to run custom build command for `libz-sys v1.1.5`

Caused by:
  process didn't exit successfully: `/target/release/build/libz-sys-c9f1cfab8a32c91b/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/libz-sys-c9f1cfab8a32c91b/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /target/release/build/libz-sys-c9f1cfab8a32c91b/build-script-build)
  /target/release/build/libz-sys-c9f1cfab8a32c91b/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /target/release/build/libz-sys-c9f1cfab8a32c91b/build-script-build)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

libz-sys is a dependency of git2. A solution could be to search a pure rust alternative to git2.

I don't know if compilation failing is more related to cargo cross or to the targets.

**Comment by eggbean** [comment]
Aren't there any aarch64 builds anymore? This architecture is getting more popular on cloud instances and with the Raspberry Pi 4.

If cross-compiling is an issue, you can build on real aarch64 runners at [BuildJet](https://buildjet.com/for-github-actions). It costs practically nothing for builds like this.
