### ISSUE TITLE
Opening broot lowers monitor brightness

### ISSUE THREAD

**Issue by lordgrenville** [Canop/broot#523]
On calling `br`, brightness fades on external monitor. Using 2020 Macbook Air, Monterey 12.3, iTerm 3.4.12. Monitor is Samsung of some type. On closing br brightness goes back to normal. What is going on here?

**Comment by Canop** [comment]
Is that perceived brightness ? Do you measure it ? Can you show what happens in some way ?

**Comment by lordgrenville** [comment]
Wow, I really appreciate the very quick response! Upon more testing, I've found it happens in a few edge cases with other programs, not just broot, so it's not a broot issue. Very sorry for wasting your time :(

**Comment by Canop** [comment]
@lordgrenville I'd really appreciate more news on this interesting issue if you can understand what happens, it may help other users in the future.

**Comment by lordgrenville** [comment]
I'm not 100% sure about the cause, but I think it was some kind of auto-dimming function on my monitor. It was similar to the issue described [here](https://forums.tomshardware.com/threads/monitor-auto-adjusting-brightness.2927865/). I eas able to fix it by doing a factory reset of the monitor settings.
