### ISSUE TITLE
Name the icon font something other than `Untitled1`

### ISSUE THREAD

**Issue by stevenxxiu** [Canop/broot#524]
I followed [Icons - Broot](https://dystroy.org/broot/icons/) to display icons.

The font is however named `Untitled1`, resulting in my awkward *WezTerm* config:

```lua
font = wezterm.font_with_fallback({
  ...
  'Untitled1', -- Required by *Broot* icons
}),
```

Can this be named something more sensible? This is also mentioned in [Support Nerdfont Icons · Issue #333 · Canop/broot](https://github.com/Canop/broot/issues/333).

**Comment by Canop** [comment]
PR welcome

**Comment by stevenxxiu** [comment]
Sure what name would be appropriate here? Would `Broot Icons` work?

**Comment by stevenxxiu** [comment]
Fixed by https://github.com/Canop/broot/pull/526.
