### ISSUE TITLE
Windows Path Unable to launch

### ISSUE THREAD

**Issue by pixelblender** [Canop/broot#527]
Hi,

Thank you for your awesome work on broot. I'm trying to launch external program but somehow it breaks if the path contains space, ie: C:\Program Files\Vim\vim82\gvim.exe. Broot says "Unable to launch C:Program: the system cannot find the specified. (os error 2)

I put it as external command in my conf: `external: "C:\\Program Files\\Vim\\vim82\\gvim.exe {file}"`

Tested on cmd, powershell and windows terminal.

Thank you

**Comment by Canop** [comment]
Can you try with 

    external: ["C:\\Program Files\\Vim\\vim82\\gvim.exe", "{file}"]

?

**Comment by pixelblender** [comment]
awesome it works! but now i have another issue, the broot shell is gone after that even though i have `leave_broot: false`? my conf:

```
key: ctrl-t
apply_to: file
external: ["C:\\Program Files\\Vim\\vim82\\gvim.exe", "{file}"]
leave_broot: false
```

**Comment by Canop** [comment]
No idea there and I don't have any windows computer to try.
