### ISSUE TITLE
Correct usage of XDG-Directory standard

### ISSUE THREAD

**Issue by weilbith** [Canop/broot#53]
Hey! :upside_down_face: 
You have implemented a nice tool. It is a great and light alternative for solutions where fzf is not enough and ranger too much.

I'm just about to configure it and this includes for me adding its configuration to my dotfiles repository. I happily assert that you support the XDG-Directory standard. But this `$XDG_CONFIG_HOME` does contain not only user configuration. Also the `launcher` directory with the shell script for the `br` functions is included. For me this is not part of the user configuration and more a shared source. At least I will overwrite this and export to another location. But this is cumbersome and I must handle this specifically in my dotfile manager. I would suggest to use `$XDG_DATA_HOME` for example. Or even share it between all user in `/usr/share/` like many other tools are doing as well.

**Comment by Canop** [comment]
This makes sense.

I won't do it immediately as there's a non zero probability the crossterm experiment will make the script useless but I keep the issue around for later.

**Comment by Canop** [comment]
A problem with using `/usr/share`: you typically need to be super user to write there.

As the goal is just to have a piece of configuration, a 10 lines shell function which could have been directly in the `.bashrc` (or equivalent) file, this looks overly constraining for the user.

**Comment by Canop** [comment]
When broot detects the script isn't here, it proposes to install it.

It could propose another option: to relaunch with appropriate rights and with an argument giving the path in which to install the launcher.

Such an option could be used by installers too.

**Comment by weilbith** [comment]
If I got this correctly, your problem right now is that you want to use `/usr/share/` which is protected. So if this is the case, why don't simply use the next list entry in `$XDG_DATA_DIRS`? Usually this should be then `$XDG_DATA_HOME` of the user? If you still want to make it precise, ask the user in a dialog if he is fine with that, or if he wants to rerun it with root permissions. What do you think?
