### ISSUE TITLE
background job

### ISSUE THREAD

**Issue by evanescente-ondine** [Canop/broot#537]
I don't understand why opening things or starting tasks (like big files copying) in the backgroiund in complicated. If I can do it in a shell, broot should be able to as well.
It's frankly annoying, given that I use broot AS a shell, increasingly so.
Can't it be fixed ?

**Comment by Canop** [comment]
Everything is more complex when you manage a dozen FOSS projects after work, and you get issues every day, and some of them look just like vague rants.

**Comment by Stargateur** [comment]
fix what ? If you ask something be clear. You need to provide clear description of the problem. So far "spawn task in background is complicated", okay but what is complicated for you ?

**Comment by evanescente-ondine** [comment]
Ahah, sorry it is a bit of a rant indeed. But I'm genuinely surprised.
Whether I use "open" or "handlr open" in a terminal, stuff opens and I can close the terminal without the file closing as well.
With broot, while it uses the same resource opener, things always close with it.
Why ?

**Comment by Canop** [comment]
When you launch a program from a program, you're making a sub-process. And this sub-process is killed with you.
If you want the sub-process to go on after you, there are two solutions:
- make it replace you, for example with excv (which isn't very clean)
- ask the shell to launch it for you after you quit, which is done with the br script

**Comment by Stargateur** [comment]
> When you launch a program from a program, you're making a sub-process. And this sub-process is killed with you.

That not necessary true, you can kill the parent without kill the child with `kill (2)`, and if the parent exit without wait for the child; process 0 inherit of them. (AFAIK).

> I'm really curious how things are implemented as I can't think of anything simpler than launching a process in the background, but perhaps it is more complicated?

Implement such feature require a lot of code, it's would be hard for broot to do it without heavy work. It's require handle backgound job, have option to detach them etc.

**Comment by jakubkaczor** [comment]
@evanescente-ondine, I suspect the surprise comes from the wording in broot's configuration. The verb definition attribute is named “external”, thus one could infer it is independent. Have you tried using `setsid -f` instead? It seems to work for me.

Either way, not having to use additional commands, but changing the way of execution by specifying an attribute would be very comfortable and explicit. @Stargateur, does it really require a lot of code? Isn't this as simple, as using https://docs.rs/fork/latest/fork/fn.daemon.html? If the process is meant to be detached, I don't think it is necessary to handle it after detaching, unless you meant something different. If it is a lot more complex, excuse me my ignorance. I know next to nothing about programming in Rust and the codebase. 😅

**Comment by evanescente-ondine** [comment]
> @evanescente-ondine, I suspect the surprise comes from the wording in broot's configuration. The verb definition attribute is named “external”, thus one could infer it is independent. Have you tried using `setsid -f` instead? It seems to work for me.

**Great**.
