### ISSUE TITLE
Cannot use verb cd with ZSH

### ISSUE THREAD

**Issue by Yuchen971** [Canop/broot#539]
**Describe the bug**
I typed `broot --install` and then use the verb `cd` with Iterm2, this message still came out:
**This verb needs broot to be launched as br, try broot --install if necessary.**
However, when I use mac's default terminal, the verb `cd` works just fine.

**To Reproduce**
Install broot in a mac, use iterm2 as terminal
type `broot --install` -> `br` -> ` cd`

**Other Info**
OS: mac
Broot Version: V 1.11.1
Terminal: Iterm2

**Comment by Canop** [comment]
After installation, you must use `br` (the script you installed) and not `broot`.

**Comment by Yuchen971** [comment]
Thank you so much.
I ended up writing that br function directly into my zshrc, instead of sourcing it, and then it runs perfectly.
