### ISSUE TITLE
Move staged files

### ISSUE THREAD

**Issue by Yuchen971** [Canop/broot#540]
**Describe the bug**
I'm trying to use the verb `mv` in the staging panel with multiple files,
but when I want to use a new panel to fill the args of the `mv`, `ctrl-p` doesn't do anything.

**To Reproduce**
stage multiple files -> in the staging area type ` mv` -> type `ctrl-p`, nothing happens

**Other Info**
OS: MacOS
Broot Version: V1.11.1

**Comment by Canop** [comment]
The current version limits the number of panels you can open to 2. This might change.

The current solution to moving staged files is to type `mv path/to/dest` in the staging area.

Open discussions on what should be the best solution are welcome (in the "Discussions" thing of GH for example)

**Comment by Yuchen971** [comment]
I think the most convenient way to move multiple files in the current version is: 
1. stage the files to be moved, 
2. locate the current panel to the target folder, 
3. use verb `mvp` in the staging area to move the files.
