### ISSUE TITLE
I can't delete mistyped commands

### ISSUE THREAD

**Issue by oscaretu** [Canop/broot#541]
I installed broot yesterday, and it doesn't let me delete characters to correct misspelled commands. Instead of being able to delete the characters I typed wrong, I have to press the Esc key and retype everything again. This happens to me on an Ubuntu 16.04 LTS (native). And it doesn't happen to me on an Ubuntu 18.04 LTS under WSL2 on Windows 10.

**Comment by Canop** [comment]
I guess the backspace key is intercepted by your terminal (which one is it ?). Maybe look at its settings.

You can rebind the `:input_del_char_left` internal to another key but it sounds inconvenient to not have the usual key.

**Comment by oscaretu** [comment]
> I guess the backspace key is intercepted by your terminal (which one is it ?). Maybe look at its settings.
> 

The terminal I use is MobaXTerm v21.0 Build 4592 https://mobaxterm.mobatek.net/download-home-edition.html%%
 
> You can rebind the `:input_del_char_left` internal to another key but it sounds inconvenient to not have the usual key.

I've solved the problem adding this to the config file, in the verbs section:

`{ key: "ctrl-h", internal: ":input_del_char_left" }`

Denys, thanks a lot for your help!
