### ISSUE TITLE
Ability to interact with a file's xattr values  (view/filter/edit)

### ISSUE THREAD

**Issue by bhougland18** [Canop/broot#555]
MacOS uses a files extra attributes to allow users to organize their files using tags, and linux has the same ability.  Both operating systems can do this using the tool xattr.  I think it would be great if Broot had the ability to view (and filter) the values of an attribute key (user could define the key in the config).  In addition, it would be great if a user could quickly edit the files "tags".

Here is an article related to using these attributes in MacOS:

https://brettterpstra.com/2017/08/22/tagging-files-from-the-command-line/

**Comment by Canop** [comment]
The same feature (looks like it's the same) exists on linux: https://man7.org/linux/man-pages/man7/xattr.7.html
So it should be possible to handle Mac & linux in the same way (and probably the same code).

What's unclear to me at the moment is how those tags would be best rendered on screen.
