### ISSUE TITLE
$EDITOR environment variable and explicitly set editor not respected

### ISSUE THREAD

**Issue by 0xphk** [Canop/broot#557]
I'm running ```broot``` (using the shell function) on 2 different Manjaro systems (both i3-wm) and I really like the fuzzy style navigation.

But both systems behave unexpected and different when opening, for example ```.sh``` files, using ```Enter```.

```$EDITOR``` env is set to ```nano``` and I already tested to set ```nano``` explicitly in broot's ```config.hjson```, but behavior doesn't change.

On one system it always opens ```.sh``` files in an awful looking vim (white background, highlighted and hard to read contents) using a complete different color scheme that the terminal normally runs.

The other system opens ```.sh``` files always in ```Mousepad```, which in my case it means on a different and unfocused workspace.

Also it behaves different for different file extensions, for example ```.json``` always opens in ```VSCodium``` instead of the expected ```nano```.

Additionally, there is a small error in the config file documentation for the ```Default flags``` section,
which reads ```for example 'default_flags="ihp"'``` but expected is a colon instead of the equal sign.

**Comment by Canop** [comment]
The `enter` key, unless you override it, isn't mapped to `$EDITOR` but to `xdg-open`.

You may either:

- [change the mapping](https://dystroy.org/broot/tricks/#change-standard-file-opening) in broot (either for all files or depending on their extensions)
- change the configuration of xdg-open

**Comment by 0xphk** [comment]
Thanks, remapping works. 

For the strange color scheme, is this defined by xdg-open somehow? I could not find any color reference.

**Comment by 0xphk** [comment]
Was some weird xdg issue, setting the defaults with xdg-mime again solved it.
