### ISSUE TITLE
Feature request: Feature gate jemallocator

### ISSUE THREAD

**Issue by hellow554** [Canop/broot#56]
I try to install broot on a windows machine. Therefore I'm using the crossterm branch right now. 
The only thing that prevents me from installing it is that I don't have a C-compiler installed. Because of the dependency of jemallocator it is required to have one sadly. 

I would like to see an optional feature, where you can tell to not use jemallocator.

The alternative would be to install a C-compiler, I don't want that :)

This one should be  very easy. 
Just add a feature in https://github.com/Canop/broot/blob/master/Cargo.toml, make it a default feature and put 

https://github.com/Canop/broot/blob/e77e6568db0785135cd8bbf887170d9117be4618/src/main.rs#L1-L2

behind that feature gate

**Comment by Canop** [comment]
I'll remove it for windows:

    [target.'cfg(unix)'.dependencies]
    jemallocator = "0.3"
