### ISSUE TITLE
1.13.2 doesn't respect default_flags in conf.toml

### ISSUE THREAD

**Issue by ATM-Jahid** [Canop/broot#566]
I have the following line in my [`conf.toml`](https://github.com/ATM-Jahid/afrodots/blob/main/fakehome/.config/broot/conf.toml).
`default_flags = "dghisT"`

In the latest version of broot, the flags defined in the config file are ignored. I downgraded broot to 1.13.1 to confirm that it used to work before.

**Comment by Canop** [comment]
Thanks for the report!

**Comment by Canop** [comment]
New version incoming

**Comment by Canop** [comment]
(not so fast, as compilation for all platforms takes more than half an hour...)

**Comment by Canop** [comment]
1.13.3 released
