### ISSUE TITLE
--cmd argument not accepted

### ISSUE THREAD

**Issue by tylerw** [Canop/broot#570]
Hello,

I'm not sure if `--cmd` has been deprecated or not, but broot no longer accepts the option:
```
$ pwd
/tmp/broot

$ broot --cmd "man:pp"
error: Found argument '--cmd' which wasn't expected, or isn't valid in this context

	If you tried to supply `--cmd` as a value rather than a flag, use `-- --cmd`

USAGE:
    broot [OPTIONS] [FILE]

For more information try --help

$ broot --commands "man:pp"
/tmp/broot/man

$ broot -c "man:pp"
/tmp/broot/man

$ broot --version
broot 1.13.3
```

The same behavior occurs with the `br` shell function.

There are several references to `--cmd` in the repo:
```
$ git grep -w -c -e --cmd
CHANGELOG.md:3
src/command/command.rs:1
src/verb/verb_execution.rs:1
website/docs/community.md:1
website/docs/conf_verbs.md:2
website/docs/export.md:2
website/docs/launch.md:4
website/docs/remote.md:1
website/docs/tricks.md:1
```

OS: macOS 11.6.7 (Big Sur)
(Broot installed via Homebrew; also reproduced the behavior building broot from the repo.)

P.S. – Thank you for broot!

**Comment by Canop** [comment]
I use `-c` all the time so I didn't notice...

`--cmd` wasn't deprecated, this is a bug.
