### ISSUE TITLE
Broot fails to compile with cargo install

### ISSUE THREAD

**Issue by westernwontons** [Canop/broot#573]
Broot fails to compile and this is the error message

```bash
error[E0432]: unresolved import `nix::sys::epoll`
  --> /Users/nagybotond/.cargo/registry/src/github.com-1ecc6299db9ec823/xterm-query-0.1.0/src/lib.rs:41:19
   |
41 |     use nix::sys::epoll::*;
   |                   ^^^^^ could not find `epoll` in `sys`

error[E0433]: failed to resolve: use of undeclared type `EpollCreateFlags`
  --> /Users/nagybotond/.cargo/registry/src/github.com-1ecc6299db9ec823/xterm-query-0.1.0/src/lib.rs:49:33
   |
49 |     let poll_fd = epoll_create1(EpollCreateFlags::empty())?;
   |                                 ^^^^^^^^^^^^^^^^ use of undeclared type `EpollCreateFlags`

error[E0433]: failed to resolve: use of undeclared type `EpollEvent`
  --> /Users/nagybotond/.cargo/registry/src/github.com-1ecc6299db9ec823/xterm-query-0.1.0/src/lib.rs:50:21
   |
50 |     let mut event = EpollEvent::new(EpollFlags::EPOLLIN, 0);
   |                     ^^^^^^^^^^ use of undeclared type `EpollEvent`

error[E0433]: failed to resolve: use of undeclared type `EpollFlags`
  --> /Users/nagybotond/.cargo/registry/src/github.com-1ecc6299db9ec823/xterm-query-0.1.0/src/lib.rs:50:37
   |
50 |     let mut event = EpollEvent::new(EpollFlags::EPOLLIN, 0);
   |                                     ^^^^^^^^^^ use of undeclared type `EpollFlags`

error[E0433]: failed to resolve: use of undeclared type `EpollOp`
  --> /Users/nagybotond/.cargo/registry/src/github.com-1ecc6299db9ec823/xterm-query-0.1.0/src/lib.rs:53:9
   |
53 |         EpollOp::EpollCtlAdd,
   |         ^^^^^^^ use of undeclared type `EpollOp`

   Compiling proc-status v0.1.1
error[E0433]: failed to resolve: use of undeclared type `EpollEvent`
  --> /Users/nagybotond/.cargo/registry/src/github.com-1ecc6299db9ec823/xterm-query-0.1.0/src/lib.rs:57:23
   |
57 |     let mut events = [EpollEvent::empty(); 1];
   |                       ^^^^^^^^^^ use of undeclared type `EpollEvent`

error[E0425]: cannot find function `epoll_create1` in this scope
  --> /Users/nagybotond/.cargo/registry/src/github.com-1ecc6299db9ec823/xterm-query-0.1.0/src/lib.rs:49:19
   |
49 |     let poll_fd = epoll_create1(EpollCreateFlags::empty())?;
   |                   ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `epoll_ctl` in this scope
  --> /Users/nagybotond/.cargo/registry/src/github.com-1ecc6299db9ec823/xterm-query-0.1.0/src/lib.rs:51:5
   |
51 |     epoll_ctl(
   |     ^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `epoll_wait` in this scope
  --> /Users/nagybotond/.cargo/registry/src/github.com-1ecc6299db9ec823/xterm-query-0.1.0/src/lib.rs:58:20
   |
58 |     let fd_count = epoll_wait(poll_fd, &mut events, timeout_ms)?;
   |                    ^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0425, E0432, E0433.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `xterm-query` due to 9 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `broot v1.14.0`, intermediate artifacts can be found at `/var/folders/18/br1lcr9s0js75bc8l464y8_m0000gn/T/cargo-installgrscap`
```

`uname -a`
Darwin computer.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

`cargo --version`
cargo 1.64.0-nightly (c0bbd42ce 2022-07-03)

**Comment by mjsteinbaugh** [comment]
@Canop I'm also seeing similar build issues with Rust 1.62.0 on macOS:

```
> rustc --print cfg
debug_assertions
panic="unwind"
target_arch="x86_64"
target_endian="little"
target_env=""
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_feature="sse3"
target_feature="ssse3"
target_has_atomic="128"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="macos"
target_pointer_width="64"
target_vendor="apple"
unix
```

**Comment by westernwontons** [comment]
> rustc --print cfg

debug_assertions
panic="unwind"
target_abi=""
target_arch="aarch64"
target_endian="little"
target_env=""
target_family="unix"
target_feature="aes"
target_feature="crc"
target_feature="dit"
target_feature="dotprod"
target_feature="dpb"
target_feature="dpb2"
target_feature="fcma"
target_feature="fhm"
target_feature="flagm"
target_feature="fp16"
target_feature="frintts"
target_feature="jsconv"
target_feature="llvm14-builtins-abi"
target_feature="lor"
target_feature="lse"
target_feature="neon"
target_feature="paca"
target_feature="pacg"
target_feature="pan"
target_feature="pmuv3"
target_feature="ras"
target_feature="rcpc"
target_feature="rcpc2"
target_feature="rdm"
target_feature="sb"
target_feature="sha2"
target_feature="sha3"
target_feature="ssbs"
target_feature="v8.1a"
target_feature="v8.2a"
target_feature="v8.3a"
target_feature="v8.4a"
target_feature="vh"
target_has_atomic="128"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_has_atomic_equal_alignment="128"
target_has_atomic_equal_alignment="16"
target_has_atomic_equal_alignment="32"
target_has_atomic_equal_alignment="64"
target_has_atomic_equal_alignment="8"
target_has_atomic_equal_alignment="ptr"
target_has_atomic_load_store="128"
target_has_atomic_load_store="16"
target_has_atomic_load_store="32"
target_has_atomic_load_store="64"
target_has_atomic_load_store="8"
target_has_atomic_load_store="ptr"
target_os="macos"
target_pointer_width="64"
target_thread_local
target_vendor="apple"
unix

**Comment by Stargateur** [comment]
macos doesn't support epoll, it have a thing call kqueue. I think mio could be used to replace the call of epoll in xterm-query

**Comment by Canop** [comment]
Could one of you test on mac if it's enough to replace` this line` with `Luma::Unknown` ?

If that's the case I'll just issue a new release with a conditional compilation thingie before looking for a more inclusive solution.

**Comment by westernwontons** [comment]
> Could one of you test on mac if it's enough to replace` this line` with `Luma::Unknown` ?
> 
> If that's the case I'll just issue a new release with a conditional compilation thingie before looking for a more inclusive solution (which would be in this crate: https://github.com/Canop/terminal-light).

Which line exactly?

**Comment by Canop** [comment]
sorry, updated

**Comment by westernwontons** [comment]
Still the same error

**Comment by westernwontons** [comment]
Okay so I commented out lines `18-35` in `luma.rs` and this: 

> you also need to remove
> 
> https://github.com/Canop/broot/blob/3454e1efa0c90b8680c130e6b98ee87cb85a4f8c/Cargo.toml#L62
> 
> and of course don't use the feature
> https://github.com/Canop/broot/blob/3454e1efa0c90b8680c130e6b98ee87cb85a4f8c/Cargo.toml#L20

and it compiles and works

**Comment by westernwontons** [comment]
Could I maybe help with a PR?

**Comment by Canop** [comment]
The best long term solution would be to fix the [xterm-query](https://github.com/Canop/xterm-query) repository to support Mac (maybe with mio as suggested by @stargateur). Any volunteer for that is welcome!

**Comment by 0323pin** [comment]
@Canop this is causing trouble on NetBSD also. It's not a MacOS thing, it's actually a Linux thing, `epoll` only exist on Linux. 

```
Compiling xterm-query v0.1.0
error[E0432]: unresolved import `nix::sys::epoll`
--> /scratch/sysutils/broot/work/vendor/xterm-query-0.1.0/src/[lib.rs:41](http://lib.rs:41/):19
|
41 | use nix::sys::epoll::*;
| ^^^^^ could not find `epoll` in `sys`

error[E0433]: failed to resolve: use of undeclared type `EpollCreateFlags`
--> /scratch/sysutils/broot/work/vendor/xterm-query-0.1.0/src/[lib.rs:49](http://lib.rs:49/):33
|
49 | let poll_fd = epoll_create1(EpollCreateFlags::empty())?;
| ^^^^^^^^^^^^^^^^ use of undeclared type `EpollCreateFlags`

error[E0433]: failed to resolve: use of undeclared type `EpollEvent`
--> /scratch/sysutils/broot/work/vendor/xterm-query-0.1.0/src/[lib.rs:50](http://lib.rs:50/):21
|
50 | let mut event = EpollEvent::new(EpollFlags::EPOLLIN, 0);
| ^^^^^^^^^^ use of undeclared type `EpollEvent`

error[E0433]: failed to resolve: use of undeclared type `EpollFlags`
--> /scratch/sysutils/broot/work/vendor/xterm-query-0.1.0/src/[lib.rs:50](http://lib.rs:50/):37
|
50 | let mut event = EpollEvent::new(EpollFlags::EPOLLIN, 0);
| ^^^^^^^^^^ use of undeclared type `EpollFlags`

error[E0433]: failed to resolve: use of undeclared type `EpollOp`
--> /scratch/sysutils/broot/work/vendor/xterm-query-0.1.0/src/[lib.rs:53](http://lib.rs:53/):9
|
53 | EpollOp::EpollCtlAdd,
| ^^^^^^^ use of undeclared type `EpollOp`

error[E0433]: failed to resolve: use of undeclared type `EpollEvent`
--> /scratch/sysutils/broot/work/vendor/xterm-query-0.1.0/src/[lib.rs:57](http://lib.rs:57/):23
|
57 | let mut events = [EpollEvent::empty(); 1];
| ^^^^^^^^^^ use of undeclared type `EpollEvent`

error[E0425]: cannot find function `epoll_create1` in this scope
--> /scratch/sysutils/broot/work/vendor/xterm-query-0.1.0/src/[lib.rs:49](http://lib.rs:49/):19
|
49 | let poll_fd = epoll_create1(EpollCreateFlags::empty())?;
| ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `epoll_ctl` in this scope
--> /scratch/sysutils/broot/work/vendor/xterm-query-0.1.0/src/[lib.rs:51](http://lib.rs:51/):5
|
51 | epoll_ctl(
| ^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `epoll_wait` in this scope
--> /scratch/sysutils/broot/work/vendor/xterm-query-0.1.0/src/[lib.rs:58](http://lib.rs:58/):20
|
58 | let fd_count = epoll_wait(poll_fd, &mut events, timeout_ms)?;
| ^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0425, E0432, E0433.
For more information about an error, try `rustc --explain E0425`.
Compiling proc-status v0.1.1
error: could not compile `xterm-query` due to 9 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Canop** [comment]
How many users at Apple do I need before they give me a mac to test my apps ? ^^

**Comment by Stargateur** [comment]
github action can allow you to run on linux windows and macos for free if your repo is public

**Comment by Canop** [comment]
on macos ? I should check for that (windows I do with cargo cross)

**Comment by Canop** [comment]
Could you people please test compilation and execution of the no-luma-on-non-linux branch ? If it's OK I'll make a 1.14.1 release tonight before looking for a better solution.

**Comment by Canop** [comment]
OK, let's release the 1.4.1

@westernwontons Sorry I didn't wait for you, this was kind of urgent

**Comment by Canop** [comment]
Could you please register for [the other issue](https://github.com/Canop/broot/issues/575) so that I can find mac testers when trying solutions for that color determination problem ?

**Comment by 0323pin** [comment]
@Canop Only MacOS or, are you interested in supporting this feature on NetBSD also?

**Comment by Canop** [comment]
@0323pin I'm interested by making it work on all platforms. I'm more focused in macos when looking for testers because it's where I have most unsuspected surprises, but please do register too.
