### ISSUE TITLE
No verb matches ":cd"

### ISSUE THREAD

**Issue by blueray453** [Canop/broot#574]
I am using broot 1.14.0

When i try
```
$ brcd() { br --only-folders --hidden --cmd "$1 :cd"  }
$ brcd
No verb matches ":cd"
```

**Comment by Canop** [comment]
The command separator in `--cmd`, unless specified otherwise, is the semicolon.

You can fix your function like this:

    brcd() { br --only-folders --hidden --cmd "$1;:cd"  }
    
[related](https://dystroy.org/broot/tricks/#dcd-deep-fuzzy-cd)

**Comment by blueray453** [comment]
The bellow command does not work

   brcd() { br --only-folders --hidden --cmd "$1;:cd"  }

However, if I use

    brcd() { broot --only-folders --hidden --cmd "$1;:cd"  }

it open broot. In the bottom I can see `:cd` but it does not do anything when I press enter. 

Screenshot:

![Screenshot-2022-07-07-12:23:00](https://user-images.githubusercontent.com/855297/177705672-c5090a7b-78cf-4ceb-8178-4db2df0f551e.png)

**Comment by blueray453** [comment]
I am using `zsh`.

**Comment by blueray453** [comment]
The command does nothing. Screenshot attached.

![Screenshot-2022-07-07-12:44:39](https://user-images.githubusercontent.com/855297/177709124-cc2b6840-08a0-44ad-846f-f8d6d128c0b9.png)

**Comment by Canop** [comment]
But you don't pass parameters ?

![image](https://user-images.githubusercontent.com/617006/177709468-28267682-cc86-4915-92fb-caa3cedfa5fc.png)

**Comment by blueray453** [comment]
I thought when I select a directory in broot, it becomes $1. I mean the directories path is send to cd command.

What I am trying to do is, open broot, select a folder, press enter to cd into it, and get back to terminal.

When I use:

```
function brcd() {
    cd $(broot --only-folders --hidden --cmd "$1;:pp")
}
```
or,
```
brcd() { br --only-folders --hidden --cmd "$1;:cd"  }
```
it does not even run broot when i run `brcd`.

**Comment by Canop** [comment]
Ok, this is a very different purpose.

You can use a specific config file defining a verb:

![image](https://user-images.githubusercontent.com/617006/177712972-07a17404-0a86-4346-9a17-fb61f4491456.png)

This opens broot, and goes to the chosen directory on enter.

But then you can hardly deeply navigate as any enter leaves broot.

That's why br exists: you navigate, and you do  alt-enter to cd to the chosen directory.

**Comment by blueray453** [comment]
Thank you very very much. This solves my problem.

Just curious, how is `brcd() { br --only-folders --hidden --cmd "$1;:cd"  }` supposed to be used? What argument shall I pass to `brcd`?

**Comment by Canop** [comment]
It's the same than my [dcd](https://dystroy.org/broot/tricks/#dcd-deep-fuzzy-cd) : you pass it a pattern and it jumps to the best match. This is useful when you already know where it will go because it's a location you often jump to.
