### ISSUE TITLE
terminal's background color determination doesn't work on non linux

### ISSUE THREAD

**Issue by Canop** [Canop/broot#575]
because of the use of epoll.

Related: https://github.com/Canop/broot/issues/573

The fix should be done in either the [terminal-light](https://github.com/Canop/terminal-light) repository or the one it uses, [xterm-query](https://github.com/Canop/xterm-query).

**Comment by Canop** [comment]
I just pushed the [terminal-light-mio](https://github.com/Canop/broot/tree/terminal-light-mio)  branch which should be compatible with more unix variants.

I'd like testers to check it compiles for them, and to check it correctly determines whether their terminal is light or dark.

To test the latter, fire broot in a light or in a dark terminal, with the relevant configuration (see [there](https://github.com/Canop/broot/blob/master/resources/default-conf/conf.hjson#L152)).

In a dark terminal, the status bar is dark:

![image](https://user-images.githubusercontent.com/617006/178097039-c5e00a0a-916b-4d9e-9ad8-d7c045d35ebc.png)

And it's light gray in a light terminal:

![image](https://user-images.githubusercontent.com/617006/178097010-4532b7bc-f486-45db-b4c6-1164db9f616a.png)

You can also read the luma in the debug log

**Comment by 0323pin** [comment]
@Canop Unfortunately, I had to re-build `rust` itself. It's still running but, as soon as it's done, I'll do a build of `broot` and test. Probably tonight.

**Comment by Canop** [comment]
BTW if somebody's willing to try porting that to windows (with WinAPI I suppose), he's welcome.

**Comment by 0323pin** [comment]
@Canop All good on NetBSD 😄 
It compiles and works fine.

**Comment by Canop** [comment]
Coool. Could I get some screenshots @0323pin ?

**Comment by 0323pin** [comment]
Bien sûr :)

![2022-07-09-174026_1366x768_scrot](https://user-images.githubusercontent.com/90570748/178112785-0515495b-df73-46d2-8184-ea343e8cbdae.png)

**Comment by Canop** [comment]
@0323pin  Superb. It does work :)

Now I'm waiting for some test on mac before merging.

**Comment by 0323pin** [comment]
Thank you for fixing it.

**Comment by Stargateur** [comment]
> BTW if somebody's willing to try porting that to windows (with WinAPI I suppose), he's welcome.

I see no reason since mio support windows https://github.com/tokio-rs/mio#platforms

**Comment by Canop** [comment]
@Stargateur If you find a way to make it work without block on Windows, a PR would be welcome

(thanks already for the suggestion to use mio which works for unix)

**Comment by cyann** [comment]
Looks like it's working on on macOS ARM64, but I couldn't find the debug log to validate.

**Comment by Canop** [comment]
> Looks like it's working on on macOS ARM64, but I couldn't find the debug log to validate.

Could I have screenshots to check the skins are really different ?

**Comment by cyann** [comment]
![image](https://user-images.githubusercontent.com/961115/178309113-a3cca767-dc33-4310-a1b5-1708bf846ac2.png)

**Comment by Canop** [comment]
With 1.14.2, this feature is available on most unixes. I'm closing the issue.

If somebody's feeling like working on the Windows version, a new issue would be created.
