### ISSUE TITLE
Replace "Alt + *" with "Opt + *" on macOS

### ISSUE THREAD

**Issue by Saafo** [Canop/broot#584]
I've already read all issues about "alt mac", many of them are talking about "alt + enter", and the suggestion is to set "ctrl+o" in verbs.hjson, or map "alt+enter" to other combination.

However, many shortcuts in broot are alike "alt + *", e.g.: "alt + h" / "alt + i", we can't map them one by one, which cause too much troubles.

The Option key (⌥) on macOS is always considered the replacement of the Alt key on Windows or Linux, why shouldn't we replace the default "alt + *" shortcuts with "opt + *" on macOS?

**Comment by Canop** [comment]
I have no mac. Can you please use [print_key ](https://github.com/Canop/print_key) and tell me what is printed when you type for example opt-i ?

**Comment by Saafo** [comment]
I got it. You have to set something in your terminal to make command line applications like print_key or broot from receiving "Opt + *" shortcuts.

For Example:

If you're using Terminal.app, set "Use Option as Meta Key" in the preferences.

![](https://user-images.githubusercontent.com/124501/72387214-d9502c00-36d7-11ea-9264-67c5c6bdf8b6.png)

If you're using iTerm.app, set "ESC+" to Left / Right Option key in Preferences - Profiles - Keys - General

![](https://user-images.githubusercontent.com/46736350/183635688-eb3c25bb-9695-42b9-8c67-527e753db677.png)

and you can using "Opt + *" as "Alt + *" without doing anything more.

It seems the problem is solved already, thanks alot~

**Comment by Saafo** [comment]
I got it. You have to set something in your terminal to make command line applications like print_key or broot from receiving "Opt + *" shortcuts.

For Example:

If you're using Terminal.app, set "Use Option as Meta Key" in the preferences.

![](https://user-images.githubusercontent.com/124501/72387214-d9502c00-36d7-11ea-9264-67c5c6bdf8b6.png)

If you're using iTerm.app, set "ESC+" to Left / Right Option key in Preferences - Profiles - Keys - General

![](https://user-images.githubusercontent.com/46736350/183635688-eb3c25bb-9695-42b9-8c67-527e753db677.png)

and you can using "Opt + *" as "Alt + *" without doing anything more.

It seems the problem is solved already, thanks alot~
