### ISSUE TITLE
Compilation with Rust 1.35 fails - no field `table_border` on type `termimad::skin::MadSkin

### ISSUE THREAD

**Issue by ksandvik** [Canop/broot#59]
Compiling broot v0.8.4
error[E0609]: no field `table_border` on type `termimad::skin::MadSkin`
Attempted to access a non-existent field in a struct.

Erroneous code example:

```
struct StructWithFields {
    x: u32,
}

let s = StructWithFields { x: 0 };
println!("{}", s.foo); // error: no field `foo` on type `StructWithFields`
```

**Comment by Canop** [comment]
I guess you used cargo to fetch broot ?
I had omitted to cargo-publish a version of broot modified for the very last version of termimad. I'll fix that now.

**Comment by Canop** [comment]
@ksandvik Can you please confirm it's OK now ?

**Comment by ksandvik** [comment]
Verified, works.
