### ISSUE TITLE
Allow jumping between directories

### ISSUE THREAD

**Issue by rexagod** [Canop/broot#591]
Hello! First off, amazing project!

I use the `modal_mode` generally, and I feel the need of including more vim-compatible shortcuts. One such shortcut is `{,}` that usually jumps over paragraphs, so I wanted to map a shortcut to it in order to jump between directories. However, on the website, it says there are `{previous,next}_dir` commands that will help me achieve that, but I don't see these in `broot` itself (see below).

<details>
<summary>Broot</summary>

![image](https://user-images.githubusercontent.com/33557095/187618904-723f0018-d190-4b22-a622-1aef56d8f4c2.png)

</details>

<details>
<summary>Website</summary>

![image](https://user-images.githubusercontent.com/33557095/187619023-ea2ec3df-0f99-4a31-bb04-d8a1f3953fa1.png)

</details>

Any clues?

**Comment by Canop** [comment]
There are two concepts:

* internals: behaviors defined by broot internally. One of those is called `:next_dir`
* verbs: commands defined as built-in or in configuration. A verb can call an internal

There's a built-in verb for most internals but not for all. There's no default verb for the :next_dir internal.

But you can define a verb for :next_dir, it will work.

**Comment by rexagod** [comment]
Oh, that makes sense. Thanks, @Canop!
