### ISSUE TITLE
MacOSX iterm2 Command-Enter is wired to fullscreen

### ISSUE THREAD

**Issue by ksandvik** [Canop/broot#60]
**Is everything clear?**
We prefer you come to the chat and speak about the problem first.
Broot chat room: https://miaou.dystroy.org/3490?broot 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
- Relevant configuration items

**Additional context**

**Comment by ksandvik** [comment]
I've been trying to find a way to turn off command (alt)-Enter in iTerm2 (Build 3.2.9) and  MacOSX 10.14.5 but so far have not been able to remap this. Is there a way to config broot to map the back to cd shell command alt-enter to let's say control-enter?

**Comment by Canop** [comment]
Hem... you're supposed to edit the issue's first comment...

**Comment by Canop** [comment]
> Is there a way to config broot to map the back to cd shell command alt-enter to let's say control-enter?

Not yet. And Not all keys are mappable because of terminal restrictions. I'll look at what can be done.

**Comment by Canop** [comment]
The only modifier I'm able to use with enter is alt.

Unless somebody finds a better solution I can only advise to use the :cd verb, which means typing a space, a `c`, then enter.
