### ISSUE TITLE
`--sort-by-type` flag

### ISSUE THREAD

**Issue by dimas-cyriaco** [Canop/broot#602]
It would be great if we could start broot with `--sort-by-type`.

**Comment by p7u** [comment]
+1, I also noticed that flag does not exist.

**Comment by Stargateur** [comment]
what do you mean by type of a file, the extension or file/directory/etc... ?

**Comment by Stargateur** [comment]
more `--sort-by-extension` or `--some-by-file-type` and broot try to guess file nature ?

It would be better if you extend clearly what you want.

**Comment by Canop** [comment]
@Stargateur  there's now a `:sort_by_type command`. So this flag would be the rough equivalent of `br -c :sort_by_type`
