### ISSUE TITLE
Mouse scroll up does not wrap around (mouse scroll down does)

### ISSUE THREAD

**Issue by shoffmeister** [Canop/broot#603]
In `broot` 1.14.3 on Fedora Linux 36, KDE konsole, scrolling through the list of entries with the mouse scroll wheel up does not wrap from the top-most entry to the bottom-most entry.

This is in contrast to using the mouse scroll wheel to go down, which does wrap from the bottom-most entry to the top-most entry.

Steps:

* Run `br`; top-most entry is highlighted
* mouse scroll up
//exp: bottom-most entry is highlighted ("wrap")
//act: nothing happens

* mouse scroll down all the way to the very end
* mouse scroll down
//exp: top-most entry is highlighted ("wrap")
//act: top-most entry is highlighted ("wrap")

FWIW, your mouse scroll up/down might be inverted - the wrap behaviour though should be the same.

**Comment by Canop** [comment]
The fact the mouse wheel wraps on bottom was a bug. I fixed it.

Then, because wrapping seems more convenient, I changed the behavior to wrap in both directions.
