### ISSUE TITLE
toggle_stage doesn't work on links to links (??) and ctrl-a (staging all files on sight) on no link at all

### ISSUE THREAD

**Issue by evanescente-ondine** [Canop/broot#606]
Hi,
it's pretty weird.
I did create those links on links unintentionally but still. toggle_stage can't target them. ctrl-a doesn't stage any link whatsoever.

broot 1.14.3

**Comment by doremiyeon** [comment]
this seems to be related to at least these two locations in the code:

https://github.com/Canop/broot/blob/71244dfb7170c1e3f4187bf7d7ef606af7291b1e/src/browser/browser_state.rs#L685

and

https://github.com/Canop/broot/blob/71244dfb7170c1e3f4187bf7d7ef606af7291b1e/src/tree_build/builder.rs#L180

**Comment by Canop** [comment]
Oh thanks. Both for the probable explanation and because I totally missed this issue!

**Comment by Canop** [comment]
Hum... I just tried (broot 1.26.0) and I can't reproduce the problem. I can stage links, and execute operations on staged links.

**Comment by doremiyeon** [comment]
hm. is this enough? won't this include all links that aren't matched by the active filter but weren't rejected because they're not regular files?
