### ISSUE TITLE
How to chain :internal commands?

### ISSUE THREAD

**Issue by Schweber** [Canop/broot#622]
If i define the following in `conf.hjson`

`{ key: "ctrl-r", internal: ":!focus ~ && :input_clear" }`

or 

`{ key: "ctrl-r", internal: ":!focus ~ :input_clear" }`

only the focus command is executed in the new tab, but the new tab keeps the input of the original tab. 

How can i have the input of the new tab cleared?

**Comment by Canop** [comment]
You use `cmd` with a semicolon separated sequence of verbs:

        {
            key: ctrl-r
            cmd: ":!focus ~;:input_clear"
        }

See https://dystroy.org/broot/conf_verbs/#verb-definition-attributes

**Comment by Schweber** [comment]
I see, thank you!
