### ISSUE TITLE
Allow override of default invocations

### ISSUE THREAD

**Issue by Schweber** [Canop/broot#623]
I would like to override the default invocation of `rm` to trash the files instead of deleting them.

In `verbs.hjson` i did the following:

```
    {
        invocation: = "rm"
        # key: ctrl-x
        external: "rmtrash -rf {file}"
        leave_broot: false
    }
```

However, if i type `rm` the default verb/invocation is still shown:

<img width="272" alt="image" src="https://user-images.githubusercontent.com/64630479/199024993-68d26f3d-39da-48ed-affb-620671d6eebd.png">

Am i doing something wrong or is it not possible to override the default verbs/invocations?

**Comment by Canop** [comment]
This is probably because of the typo: `invocation: = "rm"`. Remove the `=`.

**Comment by Schweber** [comment]
My bad, now it works. Thank you for your quick and friendly replies!

Would it be possible for broot to point out such errors in the configuration files? This would make it easier to spot a problem.

**Comment by Canop** [comment]
> Would it be possible for broot to point out such errors in the configuration files?

Not really. This wasn't a syntax error in Hjson. You were setting the invocation's value to `= "rm"` (with the quotes).
