### ISSUE TITLE
Cannot search the content of files over 10M

### ISSUE THREAD

**Issue by kliu** [Canop/broot#626]
The content search by "c/" will ignore the files over 10M and the files with some extensions, such as bak, dat, etc.

This seems to be because these files are treated as binaries https://github.com/Canop/broot/blob/7379b16eaf7dd060fa3729c3950117c884608a22/src/content_search/mod.rs. 

So is it possible to provide some way to override this judgment, such as by making it configurable? Thanks.

**Comment by Canop** [comment]
Making the 10MB limit configurable is probably easy.
The list of extensions to hide is currently a little more painful as the set is optimized at compilation for efficiency.

**Comment by kliu** [comment]
Thanks for your quick reply. Please make the file size limit configurable. Thank you.
