### ISSUE TITLE
Unbind built-in keybinds

### ISSUE THREAD

**Issue by ok-nick** [Canop/broot#632]
I find some of the built-in keybinds counterintuitive, like `<C-w>`, for example. I expect it to delete the previous word, but by default it closes panels and the program. There are a few other default keybinds that I don't like and there should probably be an option to disable them.

**Comment by Canop** [comment]
I forgot this issue, which is why it didn't progress.

I'll do something, probably a kind of no-op verb as you suggest.

The cleanest design would probably be to separate bindings from verb definition but this implies a lot of breaking changes.

**Comment by Canop** [comment]
@SamuelSwartzberg I did it. The code and logic is ugly, but it makes it possible to unbind a key.

https://github.com/Canop/broot/pull/883
