### ISSUE TITLE
Provides a minimal mode (just for selection)

### ISSUE THREAD

**Issue by lost22git** [Canop/broot#634]
In order to replace `fzf`, I am expecting `broot` to be able to provide  a minmal functional mode that just for `fuzzy find files`.

And I think this will be useful in some interactive shell scripts : )

**Comment by Canop** [comment]
Why exactly ?
Can't you simply use broot like this: https://dystroy.org/broot/tricks/#a-generic-fuzzy-finder ?

**Comment by lost22git** [comment]
@Canop Maybe it would be safer to block the built-in file management verbs,

and there is multi-selection in broot?

**Comment by Canop** [comment]
> and there is multi-selection in broot?

not today (or only using the staging area)
