### ISSUE TITLE
Computing sizes in /proc freezes the application

### ISSUE THREAD

**Issue by monkeyt00l** [Canop/broot#637]
When broot is run at  / it will stop listing directory sizes when it reached /proc and instead just freeze.

It would probably be reasonable to add /proc to the ignored files by default to avoid this issue

**Comment by Canop** [comment]
> It would probably be reasonable to add /proc to the ignored files by default to avoid this issue

Broot has been designed to be able to work in /proc:
![image](https://user-images.githubusercontent.com/617006/205834957-7ce3e432-572b-49f4-9488-0cd9915cc81c.png)

But I forgot to try size_computation. There are a few things which can go wrong there. I'll have a look at this specific problem.
