### ISSUE TITLE
Open in vscode support

### ISSUE THREAD

**Issue by mahdi739** [Canop/broot#645]
Hi. I was wondering if it would be possible to add support for opening with vscode. I already wrote a line that works, but I'm not sure if it's the best way. I just added this line:
`external("code", "code {directory}", FromParentShell).with_key(key!(alt-p)),` 
in `src\verb\builtin.rs` in the vector that's returned from builtin_verbs() function.
(In my case, I set alt+p as it's shortcut)

**Comment by Canop** [comment]
You're not supposed to change the application for that, just configure a verb: https://dystroy.org/broot/conf_verbs/

**Comment by rszyma** [comment]
I've solved this by adding following snippet to `~/.config/broot/verbs.hjson`

```hjson
    # opening directory in vscode without leaving broot
    {
        name: code
        shortcut: c
        invocation: code
        execution: "code {directory}"
        leave_broot: false
    }
```

And you can use it by typing `:code` in broot
