### ISSUE TITLE
Folders starting with "test-" not shown by default

### ISSUE THREAD

**Issue by jjansen72** [Canop/broot#646]
Folders like `test-data` or `test-output` are not shown by default but treated like hidden files (on linux).

Those folders can be seen by pressing i to show hidden items. But I cannot think of a reason why those folders should be hidden by default just because their name starts with `test-`. 

Renaming  e.g.  `test-data` to `test_data` (underscore instead of hyphen) works as expected.

**Comment by Canop** [comment]
> Those folders can be seen by pressing i to show hidden items.

There's very probably a gitignore file with patterns excluding those folders in your system, either in the local git repository (the nearest `.gitignore`) or in the global gitignore (you may find this file with `git config --global core.excludesFile`).

**Comment by jjansen72** [comment]
Thanks, that was exactly the cause! I read it in the docs but it somehow didn't sink in ...
