### ISSUE TITLE
Glitches in editor launched by br in nushell

### ISSUE THREAD

**Issue by FrancescElies** [Canop/broot#656]
I am having an issue when opening files directly from broot on windows, I tried different terminals like _Alacritty, Wezterm and Windows-Terminal_ all of them have the same issue, I also tried to edit code in _helix_ and _vim_ both suffer from the same problem

See below a gif showing the problem, here I also show a similar workflow with [gitui](https://github.com/extrawurst/gitui) where I also open the texteditor à la broot, over there everything works fine.

Wit broot I open files with enter.
<details>
  <summary>Relevant part of the verbs.hjson (click me)</summary>
  
    {
        invocation: edit
        shortcut: e
        name: open-code
        key: enter
        extensions: [
            c
            cs
            cpp
            h
            hpp
            hjson
            js
            md
            nu
            py
            pyi
            rs
            tex
            toml
            yaml
            yml
        ]
        # vim
        # execution: "$EDITOR +{line} {file}"
        # hx
        execution: "$EDITOR {file}:{line}"
        leave_broot: false
    }

</details>

<details>
  <summary>Video (click me)</summary>
  
   https://user-images.githubusercontent.com/6558089/213666250-3f80b524-0a10-42d4-b29a-3297714bb0d6.mp4

</details>

I can see _gitui_ uses [crossterm](https://github.com/extrawurst/gitui/blob/master/Cargo.toml#L32) `v0.25`, broot uses crossterm too but `v0.23.2`

These are the dependencies using it.
<details>
  <summary>(click me)</summary>
  
```
❯ cargo tree -i crossterm
crossterm v0.23.2
├── coolor v0.5.0
│   ├── termimad v0.20.6
│   │   ├── broot v1.19.0 (C:\Users\FrancescElies\src\broot)
│   │   └── glassbench v0.3.4
│   │       [dev-dependencies]
│   │       └── broot v1.19.0 (C:\Users\FrancescElies\src\broot)
│   └── terminal-light v1.0.1
│       └── broot v1.19.0 (C:\Users\FrancescElies\src\broot)
├── crokey v0.4.3
│   └── broot v1.19.0 (C:\Users\FrancescElies\src\broot)
├── csv2svg v0.1.8
│   └── glassbench v0.3.4 (*)
├── termimad v0.20.6 (*)
└── terminal-light v1.0.1 (*)
```

</details>

This makes me suspect that something is going on with broot or most probably one of it's dependencies on windows.

This is the only thing keeping me from using broot more than what I do now :), could you tell me what could I check

Suggestions, what could I look into to solve this problem? 
I'll try to upgrade dependencies first and see if that helps, recommendations?

Thanks for this great program

**Comment by Canop** [comment]
Can you tell me how you open the editors ? With what verb ?

**Comment by FrancescElies** [comment]
Enter, I updated the description with the relevant section of verbs.hjson

**Comment by Canop** [comment]
Standard opening isn't really good with opening editors in the same terminal while keeping the opening program (i.e. broot) alive.

There are 2 solutions:
* use the editor verb with eg `:e` shortcut for when you want to open a terminal editor and keep broot behind
* add [a new verb with extension filtering](https://dystroy.org/broot/conf_verbs/#file-extensions) if you want to use the enter key 

If you confirm the problem, I'll at the very least try to make that clear in the doc.

**Comment by Stargateur** [comment]
use a gif instead of a webp or mp4 should be illegal, fly away

**Comment by Canop** [comment]
@FrancescElies I think that @Stargateur  means that a GIF is *not* ideal. As a GIF comes without stop/play/advance controls in my browsers, I tend to agree with him

**Comment by FrancescElies** [comment]
Oh ok, now I got it, thanks.

`webp` was forbidden to upload to github but I didn't realize I could upload mp4, that's why I chose the gif format. 

I just updated the issue description with a mp4 video,

**Comment by FrancescElies** [comment]
> Standard opening isn't really good with opening editors in the same terminal while keeping the opening program (i.e. broot) alive.
> 
> There are 2 solutions:
> 
>     * use the editor verb with eg `:e` shortcut for when you want to open a terminal editor and keep broot behind
> 
>     * add [a new verb with extension filtering](https://dystroy.org/broot/conf_verbs/#file-extensions) if you want to use the enter key
> 
> 
> If you confirm the problem, I'll at the very least try to make that clear in the doc.

So in verbs.hjson I have
```
    {
        invocation: edit
        shortcut: e
        name: open-code
        key: F2
        execution: "$EDITOR {file}:{line}"
        leave_broot: false
    }

```

I tried `leave_broot: true` but had exactly the same problem and tried `key: F2` and `key: enter`

**Comment by FrancescElies** [comment]
Update, I just found the issue, when I call `broot` things work as expected no glitches found but as soon as I use the `br` shortcut problems occur

https://user-images.githubusercontent.com/6558089/213668774-3501edaf-1ded-4ba8-9d88-486bca182b33.mp4

So for editing code I should call `broot` instead of `br` (in my case under nushell)

**Comment by Canop** [comment]
@FrancescElies Is the problem only happening with nushell ?

**Comment by FrancescElies** [comment]
I just retested the same thing on powershell and works fine, thus it seems it's an issue with nushell itself or the nushell function.

If you are fine with it I'll close this issue, thanks for your help!

**Comment by Canop** [comment]
> If you are fine with it I'll close this issue, thanks for your help!

Well, no, it's not solved!

**Comment by Canop** [comment]
I reproduce the problem on linux: there are glitches in a terminal editor launched by br on nushell (but not broot).

I'll try to have a look.

ping @mediumrarez

**Comment by mediumrarez** [comment]
It's because broot is run inside a nushell pipe, which is trying to capture stdout so it can send it to the next step of the pipeline. vim is writing to stdout to draw its UI, and that's confusing nushell.

**Comment by Canop** [comment]
I'm sorry but I hadn't a good look at the nushell function before and there's another problem: it always does a `cd` instead of calling the function returned in the `outcmd` file.

Compare to the crust of the bash function:

        cmd=$(<"$cmd_file")
        eval "$cmd"

**Comment by mediumrarez** [comment]
Yes, now that it's not in a nushell function anymore we could just `source` the `outcmd` file.

But we need a guarantee that the path argument string will always be a [valid nushell string](http://www.nushell.sh/book/working_with_strings.html).

**Comment by Canop** [comment]
You can't `source`: it would only `cd` in a subshell, that's why the br function for bash does a `eval`.

Are there problems in the path exported by broot today ? There should already be relevant escaping.

**Comment by mediumrarez** [comment]
I'm not sure I understand what you're saying about the subshell. Sourcing the `outcmd` script `cd`s in the current shell, for both bash and nushell (tested both).

---

The problems with the `outcmd` file depend on whether it's being sourced or parsed.

If we `source "outcmd"` there are formatting issues. For example, nushell won't accept `cd "C:\Users\User\Desktop"` but broot will output this. For unquoted strings there are only certain characters allowed etc.

If we parse `outcmd` and `cd $broot_cd_path`, then we first have to remove all of the escapes that broot added, unquote everything, etc.

IMO it would be safest and most future-proof for broot to just dump the original unmodified, unescaped, unquoted absolute file path and let `broot_cd.nu` do everything else.

**Comment by FrancescElies** [comment]
Thanks for the help to you both.

I had to do some reading before I could comment but if I understood the problem correctly we can't pack broot in a `def` function definition because then the it runs [in a nushell pipeline](https://www.nushell.sh/book/custom_commands.html#pipeline-input) and this messes when running an editor.
Neither we can do things like in bash because there is no [eval function](https://www.nushell.sh/book/how_nushell_code_gets_run.html#eval-function)

Starting from today I'll be testing locally @mediumrarez's suggestion.

I slightly modified it to handle exiting broot with `ctrl-c` in that case parsing fails because file is empty.

```nu
# ~/broot_cd.nu
let _broot_cd_file = ([ $nu.temp-path, $"broot-(random chars).tmp" ] | path join)
let _broot_cd_target = null

touch $_broot_cd_file
^broot --outcmd $_broot_cd_file
if not (open $_broot_cd_file | lines | is-empty) {
  let _broot_cd_target = (open $_broot_cd_file | parse -r `^cd\s+(?<quote>"|'|)(?<path>.+)\k<quote>[\s\r\n]*$` | get path | to text)
  rm -p -f $_broot_cd_file 
  cd $_broot_cd_target
}

let _broot_cd_target = null
let _broot_cd_file = null

```
```nu
# ~\AppData\Roaming\dystroy\broot\config\launcher\nushell\br
alias br = source '~/broot_cd.nu'

```

**Comment by FrancescElies** [comment]
> I had to do some reading before I could comment but if I understood the problem correctly we can't pack broot in a def function definition because then the it runs [in a nushell pipeline](https://www.nushell.sh/book/custom_commands.html#pipeline-input) and this messes when running an editor.

I got that wrong, the problem is not packing broot in a `def` but the `alias cd = (_br_cmd)` instead

@Canop 
> * handling arguments (i.e. launching broot with arguments like `br -hi ..`)

I agree

> * using other commands than `cd` (but it looks like this is a hard limitation of nushell so we'll probably let it go)

I did some reading and I think I found what we need, [def-env](https://www.nushell.sh/book/commands/def-env.html) which _defines a custom command, which participates in the caller environment_ 

```nu
def-env br [] {
  let cmd_file = ([ $nu.temp-path, $"broot-(random chars).tmp" ] | path join)
  touch $cmd_file
  ^broot --outcmd $cmd_file
  let target_dir = (open $cmd_file | parse -r `^cd\s+(?<quote>"|'|)(?<path>.+)\k<quote>[\s\r\n]*$` | get path | to text)
  rm -p -f $cmd_file

  cd $target_dir
}
```

I will be testing this and if everything goes well (so far so good) I'll add the argument handling and create a pr, @mediumrarez could you give a try to the previous function too?

**Comment by Canop** [comment]
> I did some reading and I think I found what we need, [def-env](https://www.nushell.sh/book/commands/def-env.html) which _defines a custom command, which participates in the caller environment_

That's very interesting. I'm holding the next version of broot for a while, as I'd like to have nushell integration right.

BTW, guys, if you want to discuss all this in a more fluid ways, my chat is open: https://miaou.dystroy.org/3490

**Comment by FrancescElies** [comment]
ℹ️ Se below what I tried so far `br` `br2` and `br3`

In a nutshell:
- `br` can't forward/accept any arguments to broot. This is what I use locally at the moment.
- `br2` provides a nice autocompletion in nushell but couldn't figure out a nice way to forward parameters to broot, still WIP 👷‍♂️
- `br3` we could forward rest-args somehow to broot and we don't incur in parameter maintenance cost, but this is still WIP 👷‍♂️ I still don't know how to forward args to broot.
- TODO: I still need to ask in the nushel community maybe someone knows a better way, but I didn't have time to do that yet.

```nu
def-env br [
] {
  # NOTE: All blocks are scoped, including variable definition and environment variable changes.
  # What does this mean? See https://www.nushell.sh/book/commands/def-env.html
  # Takeaway: be carful when opening curly braces in a def-env { ... }
  let _broot_cmd_file = ([ $nu.temp-path, $"broot-(random chars).tmp" ] | path join)
  touch $_broot_cmd_file
  ^broot --outcmd $_broot_cmd_file

  # we can't cd inside the if statement see br function's NOTE, that's why we need this extra variable.
  let _broot_target_dir = if (open $_broot_cmd_file | lines | is-empty) {
    "."
  } else {
    (open $_broot_cmd_file | parse -r `^cd\s+(?<quote>"|'|)(?<path>.+)\k<quote>[\s\r\n]*$` | get path | to text)
  }
  rm -p -f $_broot_cmd_file 

  cd $_broot_target_dir
}

def-env br2 [
    --cmd(-c): string               # Semicolon separated commands to execute
    --color: string = "auto"        # Whether to have styles and colors (auto is default and usually OK) [possible values: auto, yes, no]
    --conf: string                  # Semicolon separated paths to specific config files"),
    --dates(-d)                     # Show the last modified date of files and directories"
    --no-dates(-D)                  # Don't show the last modified date"
    --only-folders(-f)              # Only show folders
    --no-only-folders(-F)           # Show folders and files alike
    --show-git-info(-g)             # Show git statuses on files and stats on repo
    --no-show-git-info(-G)          # Don't show git statuses on files and stats on repo
    --git-status                    # Only show files having an interesting git status, including hidden ones
    --hidden(-h)                    # Show hidden files
    --no-hidden(-H)                 # Don't show hidden files
    --height: int                   # Height (if you don't want to fill the screen or for file export)
    --help                          # Print help information
    --git-ignored(-i)               # Show git ignored files
    --no-git-ignored(-I)            # Don't show git ignored files
    --install                       # Install or reinstall the br shell function
    --no-sort                       # Don't sort
    --permissions(-p)               # Show permissions
    --no-permissions(-P)            # Don't show permissions
    --print-shell-function: string  # Print to stdout the br function for a given shell
    --sizes(-s)                     # Show the size of files and directories
    --no-sizes(-S)                  # Don't show sizes
    --set-install-state: string     # Where to write the produced cmd (if any) [possible values: undefined, refused, installed]
    --show-root-fs                  # Show filesystem info on top
    --sort-by-count                 # Sort by count (only show one level of the tree)
    --sort-by-date                  # Sort by date (only show one level of the tree)
    --sort-by-size                  # Sort by size (only show one level of the tree)
    --sort-by-type                  # Same as sort-by-type-dirs-first
    --sort-by-type-dirs-first       # Sort by type, directories first (only show one level of the tree)
    --sort-by-type-dirs-last        # Sort by type, directories last (only show one level of the tree)
    --trim-root(-t)                 # Trim the root too and don't show a scrollbar
    --no-trim-root(-T)              # Don't trim the root level, show a scrollbar
    --version(-V)                   # Print version information
    --whale-spotting(-w)            # Sort by size, show ignored and hidden files
    --write-default-conf: string    # Write default conf files in given directory
] {
  # if $cmd { $"--cmd $cmd"} else { "" }) 
  # broot (if $dates { "--dates"} else { "" }) + " " + (if $no_dates { "--no-dates"} else { "" })

  # TODO
  # Not sure what the best way is to forward those arguments to broot
  # CONS:
  # Added maintenance cost of keeping this arguments in sync with broot
  # PROS:
  # You get autocompletion in nushell

}

def-env br3 [...args] {
  # broot ($args | to text)

  # TODO
  # Not sure what the best way is to forward rest args to broot
  # CONS:
  # The opposite of br2
  # PROS:
  # The opposite of br2
}


```

**Comment by mediumrarez** [comment]
@FrancescElies Nice find about `def-env`. I tested and your `br` function is working just fine.

I tested and `def-env` doesn't leak variables into the global namespace. Maybe "environment" in `def-env` means "the current shell", and "all blocks are scoped" means "variable and environment variable namespace"? That would explain why `cd` in a `def-env` has a lasting effect and why I can't access `$_broot_target_dir` at the prompt after the script exits.

**Comment by FrancescElies** [comment]
@mediumrarez great, right this means we can remove the `_broot_` prefix from the variables in the function, the previous ones were more readable.

**Comment by FrancescElies** [comment]
Update `br3`: 
Examples `br3` or passing flags like so `br3 "-h" "-i"`, it's usage not very ergonomic once you want to pass flags, without quotes it won't work because the `def` doesn't have those parameters defined.

```nu
# Usage: br3 "-h" "-i"
# CONS:
# The opposite of br2
# cli usage not very ergonomic
# PROS:
# The opposite of br2
def-env br3 [...args] {
  # NOTE: All blocks are scoped, including variable definition and environment variable changes.
  # What does this mean? See https://www.nushell.sh/book/commands/def-env.html
  # Takeaway: be carful when opening curly braces in a def-env { ... }
  let cmd_file = ([ $nu.temp-path, $"broot-(random chars).tmp" ] | path join)
  touch $cmd_file
  ^broot --outcmd $cmd_file $args

  # we can't cd inside the if statement see br function's NOTE, that's why we need this extra variable.
  let target_dir = if (open $cmd_file | lines | is-empty) {
    "."
  } else {
    (open $cmd_file | parse -r `^cd\s+(?<quote>"|'|)(?<path>.+)\k<quote>[\s\r\n]*$` | get path | to text)
  }
}

```

**Comment by Canop** [comment]
And what if you also set the args in the definition ? Is that compatible ?

**Comment by mediumrarez** [comment]
We could also get of the mandatory `cd` as well. (Also, I moved deleting `$cmd_file` right after reading for paranoia about leaving file on disk if there's an error later.)

```nushell
# Usage: br3 "-h" "-i"
# CONS:
# The opposite of br2
# cli usage not very ergonomic
# PROS:
# The opposite of br2
def-env br3 [...args] {
  # NOTE: All blocks are scoped, including variable definition and environment variable changes.
  # What does this mean? See https://www.nushell.sh/book/commands/def-env.html
  # Takeaway: be carful when opening curly braces in a def-env { ... }
  let cmd_file = ([ $nu.temp-path, $"broot-(random chars).tmp" ] | path join)
  touch $cmd_file
  ^broot --outcmd $cmd_file $args
  let $cmd = (open $cmd_file)
  rm -p -f $cmd_file

  if (not ($cmd | lines | is-empty)) {
    cd ($cmd | parse -r `^cd\s+(?<quote>"|'|)(?<path>.+)\k<quote>[\s\r\n]*$` | get path | to text)
  }
}
```

**Comment by FrancescElies** [comment]
@mediumrarez that's interesting, I thought we couldn't do `cd` inside the if statement, but maybe I missunderstood [the docs](https://www.nushell.sh/book/commands/def-env.html#notes), I tried it and one can cd via `alt-enter`

**Comment by Canop** [comment]
@mediumrarez We now know why the cd works in the block. We got the explanation [on discord](https://discord.com/channels/601130461678272522/601130461678272524/1070250207830356019).
> we split blocks from closures some time ago

**Comment by Canop** [comment]
I see no progress in the discord, so I'll release a new version of broot with this:

```
# Launch broot
#
# Flags for broot must be between quotes:
#   > br "-hi" some/path
#   > br
#   > br "-sdp"
#
# See https://dystroy.org/broot/install-br/
def-env br [
    ...args
] {
  let cmd_file = ([ $nu.temp-path, $"broot-(random chars).tmp" ] | path join)
  touch $cmd_file
  ^broot --outcmd $cmd_file $args
  if (not ($cmd | lines | is-empty)) {
      let target_dir = (open $cmd_file | to text)
      rm -p -f $cmd_file
  } else {
      rm -p -f $cmd_file
      ^
  }
}
```

Does that look OK ?

**Comment by FrancescElies** [comment]
@Canop I see that as the best version we have so far, I can open a pr if you like but I am also fine if you do that

------

As a separate topic we could consider getting this into master too, learned from the discord discussion.

This would give nice autocomplete in nushell for broot but let's keep it separate.

```nu
export extern broot [
    --cmd(-c): string               # Semicolon separated commands to execute
    --color: string = "auto"        # Whether to have styles and colors (auto is default and usually OK) [possible values: auto, yes, no]
    --conf: string                  # Semicolon separated paths to specific config files"),
    --dates(-d)                     # Show the last modified date of files and directories"
    --no-dates(-D)                  # Don't show the last modified date"
    --only-folders(-f)              # Only show folders
    --no-only-folders(-F)           # Show folders and files alike
    --show-git-info(-g)             # Show git statuses on files and stats on repo
    --no-show-git-info(-G)          # Don't show git statuses on files and stats on repo
    --git-status                    # Only show files having an interesting git status, including hidden ones
    --hidden(-h)                    # Show hidden files
    --no-hidden(-H)                 # Don't show hidden files
    --height: int                   # Height (if you don't want to fill the screen or for file export)
    --help                          # Print help information
    --git-ignored(-i)               # Show git ignored files
    --no-git-ignored(-I)            # Don't show git ignored files
    --install                       # Install or reinstall the br shell function
    --no-sort                       # Don't sort
    --outcmd: path                  # Write cd command in given path
    --permissions(-p)               # Show permissions
    --no-permissions(-P)            # Don't show permissions
    --print-shell-function: string  # Print to stdout the br function for a given shell
    --sizes(-s)                     # Show the size of files and directories
    --no-sizes(-S)                  # Don't show sizes
    --set-install-state: path       # Where to write the produced cmd (if any) [possible values: undefined, refused, installed]
    --show-root-fs                  # Show filesystem info on top
    --sort-by-count                 # Sort by count (only show one level of the tree)
    --sort-by-date                  # Sort by date (only show one level of the tree)
    --sort-by-size                  # Sort by size (only show one level of the tree)
    --sort-by-type                  # Same as sort-by-type-dirs-first
    --sort-by-type-dirs-first       # Sort by type, directories first (only show one level of the tree)
    --sort-by-type-dirs-last        # Sort by type, directories last (only show one level of the tree)
    --trim-root(-t)                 # Trim the root too and don't show a scrollbar
    --no-trim-root(-T)              # Don't trim the root level, show a scrollbar
    --version(-V)                   # Print version information
    --whale-spotting(-w)            # Sort by size, show ignored and hidden files
    --write-default-conf: path      # Write default conf files in given directory
    ...args
]

```
In the video the autocomplete appears on `<tab>`
https://user-images.githubusercontent.com/6558089/216370447-f4e098d6-e2d2-4b67-945f-45ff4aba4be7.mp4

**Comment by Canop** [comment]
Waiting for your confirmation the PR looks OK
