### ISSUE TITLE
Opening a text file will freeze broot when xdg-open wants to open with vi in same terminal

### ISSUE THREAD

**Issue by fkarg** [Canop/broot#66]
## **Bug-Despriction**
Trying to open text-files will result in a 'blocking' freeze of broot, without the expected result. Meaning: broot does not need 100% CPU (rather 0%), but does not react to any actions (deleting letters, adding new ones) tried. The opening of the selected text-file does not happen either. Only solution found: killing the terminal.

## **To Reproduce**

- Set the default for opening text-files with xdg-open as 'vi' or 'vim'. Maybe with 'update-alternatives'.
- simply try to 'open' (not 'edit', this works fine) a (text-) file. Other files (opening with external programs) also work fine.

## **Expected behavior**
My preference:
- Open a new Terminal with this file in vim (as does happen when opening text-files from a graphical file explorer)

Also okay:
- Closing broot and opening vim with this file in this window (same as: editing)

## **Configuration (please complete the following information):**
 - OS: Linux (Ubuntu 18.04)
 - broot v0.9.3
 - vim: NVIM v0.3.8

## **Assumption**
My assumption as to why this is happening is because broot does not exit in this case, and xdg-open intends to open vim in this terminal. This might result in broot waiting for xdg-open to finish 'opening', and xdg-open waiting for broot to release the terminal, which does not happen.

**Comment by Canop** [comment]
I don't reproduce this problem.

I have the same exact version of Ubuntu and neovim, and the same configuration (I think); xdg-open is also configured to launch neovim (in a new terminal).

It seems to work ok both with enter and alt-enter.

I'm puzzled and I'd like some help for the reproduction or diagnosis.

**Comment by fkarg** [comment]
Please tell me what more information you want me to provide (if any), or how I can debug this.

**Comment by tavianator** [comment]
I get a crash when opening a text file with my default editor `emacs` when X is not available:

```
$ DISPLAY= broot
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/libcore/result.rs:999:5
```

**Comment by Canop** [comment]
When X is not available and you try to edit in a new terminal, a crash isn't totally unexpected.

@tavianator Does this work if you open your file with a shortcut like this one ?

```
[[verbs]]
invocation = "edit"
key = "F2"
shortcut = "e"
execution = "$EDITOR {file}"
```
(i.e. quitting broot)

**Comment by tavianator** [comment]
Ah, I was expecting `xdg-open` to just launch `emacs` in the current tty if X isn't there.  But indeed it fails.  Perhaps that should not crash broot though.

**Comment by Canop** [comment]
Crashing broot isn't really nice, yes.

As for make this work I don't see any other way than to use alt-open (which closes broot and thus frees the TTY) or configure a verb closing broot.

**Comment by webkadiz** [comment]
same problem broot just freeze

**Comment by webkadiz** [comment]
xdg-open index.js
it's work correctly

but in broot it fails

**Comment by Canop** [comment]
@webkadiz I'd need more info, at least the log. Can you come to [Miaou](https://github.com/Canop/broot/issues/66) to post it ?

**Comment by webkadiz** [comment]
such work for me

{
	invocation: open_stay 
	shortcut: os
        key: enter
	execution: "xdg-open {file}"
	leave_broot: false 
}

true, there was a problem with folders, when you press enter on them, the default application opens, and not the built-in functionality of broot, but the arrows still work correctly

**Comment by webkadiz** [comment]
"at least the log", how i can get log?
"Can you come to Miaou to post it", sorry for my stupid, i don't understand what that means

**Comment by webkadiz** [comment]
I don't use any DE, use i3, maybe my problem in that

**Comment by Canop** [comment]
@webkadiz Both miaou and the log are explained on this page: https://dystroy.org/broot/community/
