### ISSUE TITLE
Add verb or shortcut to clear prompt

### ISSUE THREAD

**Issue by n0bra1n3r** [Canop/broot#664]
Would be great to have a configurable way to clear the search prompt. At the moment, I have to repeatedly press backspace to clear it.

This would work very well with verbs that use `leave_broot = false`.

**Comment by Canop** [comment]
What would you bind it to ?

**Comment by n0bra1n3r** [comment]
Something like `<C-Enter>`. That mapping works in terminal mode in neovim for me.

**Comment by Canop** [comment]
In fact there's already an internal for that. Here's mapping ctrl-L to it:

```Hjson
    {
        key: ctrl-l
        internal: input_clear
    }
```

note: as it may be hard to find the available key shortcuts, you might find this useful: https://github.com/Canop/print_key

**Comment by n0bra1n3r** [comment]
Perfect! I somehow missed that internal, thanks for your help!
