### ISSUE TITLE
Dangerously Incorrect rm verb statusline

### ISSUE THREAD

**Issue by ThomasBrierley** [Canop/broot#665]
If the file or directory selection is changed _after_ typing the `rm` verb, the statusline changes to give the incorrect instruction "Hit enter to open file" or "Hit enter to focus", when in-fact hitting enter will delete the file or directory.

This does not appear to be unique to the rm verb, it's just particularly dangerous with the rm verb. I'm not sure if the better solution is to fix the statusline, or change the behaviour... I'm leaning towards the latter, it's slightly less convenient but safer.

**Comment by Canop** [comment]
Right now I don't think I'll change the behavior: the verb won't be removed from the input. I'm only fixing the status being out of sync in PR #666

**Comment by Canop** [comment]
The change is present in release 1.20.1
