### ISSUE TITLE
Does not see the lib directory

### ISSUE THREAD

**Issue by webmastak** [Canop/broot#67]
Does not see the lib directory in the project directory, but if you go up one level, it finds.
![scrinshot 1](https://i.imgur.com/C1JJJvd.png)
![scrinshot 2](https://i.imgur.com/TmNSrty.png)
![scrinshot 3](https://i.imgur.com/ehcMCqX.png)

ssory. lib directory is registered in gitignore ))

**Comment by Canop** [comment]
One can legitimately forget that gitignored files aren't shown and it can be disturbing.

If you have an idea regarding ergonomics in order to not fall into this again, I'd be interested.

**Comment by webmastak** [comment]
Everything is very good. It's my fault I did not read the documentation. Is it possible to make it possible to run broot with a flag that includes gitignore, for example `br --gi`

**Comment by Canop** [comment]
Yes it's possible. Try `br --help`

**Comment by webmastak** [comment]
Thank
