### ISSUE TITLE
env_color = Error message NoColorFgBgEnv issued in the terminal after entering a folder

### ISSUE THREAD

**Issue by slamp** [Canop/broot#672]
Hello,

Problem: When I enter into a folder (alt-enter), the message below is issued in the terminal:

[/build/.cargo/registry/src/github.com-1ecc6299db9ec823/terminal-light-1.1.0/src/lib.rs:109] &env_color = Err(
    NoColorFgBgEnv,
)
![broot](https://user-images.githubusercontent.com/714910/219961526-7986c5a6-3fae-486f-b643-a7e838ef7838.png)

Installation: sudo pacman -S broot
Environment:
- broot version: 1.20.1
- terminal: mobaXterm on windows 10. From here I ssh to a remote server:
  - OS: Manjaro-ARM 23.02 (Arch linux like)
  - shell: zsh
  
The problem doesn't happen when I'm using iterm2 from a Mac to do the ssh

**Comment by Canop** [comment]
Damn...

https://github.com/Canop/terminal-light/blob/main/src/lib.rs#L109

I'll fix that

**Comment by Canop** [comment]
Version 1.20.2 should fix that
