### ISSUE TITLE
Add [Home-Key] shortcut to jump into ~

### ISSUE THREAD

**Issue by dns2utf8** [Canop/broot#68]
**Did a discussion occur before?**
No

**Is your feature request related to a problem? Please describe.**
I am usually deeply in a nested structure and I can't find stuff on the disk.

**Describe the solution you'd like**
I was searching for a button eg. the Home-Key to jump into my users home directory to start the search there.

**Describe alternatives you've considered**
I read about shortcuts, but the docs are not good enough for a 5min fix.

**Additional context**
I like this project so far, please add more docs and explain better why the service is needed.

**Comment by Canop** [comment]
Problem is the Home key could be used for other things:

1) going top of the list, as in some other list based applications
2) going to the beginning of the input, which is always focused
3) going to ~

I've chosen 2.

I'm open to suggestions regarding a shortcut to go to ~.

**Comment by dns2utf8** [comment]
What if there was a shortcut on the `~`-key?
Or when one enters `:~` it could jump to to?

**Comment by dns2utf8** [comment]
Or `Alt + Home`?

**Comment by Canop** [comment]
OK, here's what I'll do (should be done by tomorrow):

1) define a few more internal verbs, among them `:focus_root` and `:focus_user_home`
2) allow configuration to map trigger keys to verbs

It means you'll be able to add this to config.toml:

```
[[verbs]]
invocation = "root"
key = "F9"
execution = ":focus_root"

[[verbs]]
invocation = "home"
key = "ctrl-H"
execution = ":focus_user_home"
```

In this example, ctrl-H sends to your home, and F9 sends to /.

I don't know if there will also be a default mapping for those actions as none seems obvious.
