### ISSUE TITLE
alt enter not Working on macOS

### ISSUE THREAD

**Issue by faxotherapy** [Canop/broot#682]
Hi, after installing Broot, managed to start it successfully. As a test, I wanted to quit Broot in order to make sure I'm well back again on the prompt. Unfortunately, not. Pressing `⎇` `Enter` only moves the cursor up to the tree.

**Comment by Canop** [comment]
Looks like a parent of https://github.com/Canop/broot/issues/588

**Comment by Canop** [comment]
BTW I'm open to suggestions and discussions related to the best key combination(s) to set up for each platform. There could be more than one.

**Comment by faxotherapy** [comment]
> A workaround is to find a key combination which isn't blocked and add a new verb entry like this:

Is it best to create a custom verb file or reuse existing verb config file currently present in `~/.config/broot` directory?

**Comment by Canop** [comment]
I don't see what existing verb you would reuse. Maybe come to [the chat](https://miaou.dystroy.org/3490) if it's easier to discuss with less noise ?

**Comment by faxotherapy** [comment]
Just found an even easier workaround. As I use [iTerm2](https://iterm2.com/) I had to set “Left Option key” to “Esc+” in: Preferences ➝ Profiles ➝ Keys ➝ General

**Comment by Canop** [comment]
@faxotherapy can you review [this](https://dystroy.org/broot/common-problems/#missing-shortcut) and maybe propose changes ?
