### ISSUE TITLE
Redefine special paths handling (discussion)

### ISSUE THREAD

**Issue by Canop** [Canop/broot#687]
This redesign is triggered by #669 which asks for a way to tell that some ignored folders should be summed (i.e. have their size computed)

Today, a special path can be given one of the following values:     `None`,    `Enter`,    `NoEnter`,    `Hide`,    `NoHide`.

Special paths are queried for the following operations:

* `show` the file/dir: we may want to hide it, or to show it even when it would otherwise be ignored or hidden
* `list` the children, when it's a dir: we sometimes don't want to list the children of a visible not selected dir because it's slow or garbage
* `sum`: we may want to avoid diving to count files or sum their sizes, or we may (as in #669) specially want to sum

For each of those operations, we would have 3 possible values: `default`, `always`, or `never`.

I propose a new, retro-compatible, syntax, which would be an explicit definition of those booleans, and the current values would be shortcuts.

Examples:

directive              |   show   |     list    |     sum    | 
------------------------|------------|------------|-------------|
some/path = none        | default | default | default   |
some/path = enter        | always | always | always   |
some/path = hide        | never | never | default   |
some/path = no-hide        | always | never | default   |
some/path = {show:"never", sum:"always"} | never | default | always |

Opinions welcome

**Comment by Schweber** [comment]
That would work for me in #669 and i don't have a better idea, so i'm all for it.

**Comment by 9999years** [comment]
I'd like to only be able to show the top level for my home directory with a `special-paths` entry.
