### ISSUE TITLE
Empty buffer opens when default editor is set to helix.

### ISSUE THREAD

**Issue by 2gn** [Canop/broot#689]
## My environment
OS: MacOS ventura 13.2.1
Terminal Emulator: [WezTerm](https://github.com/wez/wezterm)
Shell: zsh

## issue
I'm using [Helix Editor](https://github.com/helix-editor/helix) as my primary editor.
And when I try to edit a file from broot using `:e` command, helix opens an empty buffer and the file I want to edit, and the empty buffer comes first.
I can switch to the file I want by executing `:buffer-next` in helix.

**Comment by Canop** [comment]
I confirm the problem in gnome terminal on debian. No idea what helix does as other terminal editors have no problem.
I don't have the time to debug helix right now so help would be welcome.

**Comment by yudjinn** [comment]
I think its just the line-number argument. removing it in verbs.hjson works for me.

**Comment by Canop** [comment]
(feedback on the "fix" welcome)
