### ISSUE TITLE
Write newline after "source .../br" when writing to shell config files.

### ISSUE THREAD

**Issue by ghuls** [Canop/broot#69]
Write a newline after the `source .../br` line when writing to shell config files.

**src/shell_install.rs**
```rust
                shellrc.write_all(b"\n")?;
                shellrc.write_all(source_line.as_bytes())?;
                shellrc.write_all(b"\n")?;
```

**Comment by Canop** [comment]
This looks good. Do you make a PR or do you prefer that I do the change ?

**Comment by ghuls** [comment]
You can change it if you want. It is a very trivial change, not worth a PR.
