### ISSUE TITLE
The `--height` setting clears the screen and only shows in the top half of the screen

### ISSUE THREAD

**Issue by stevenxxiu** [Canop/broot#690]
I'm not sure if this is what the `--height` setting is meant to do. On my terminal it appears to clear the screen, and only show *Broot* in the top half of the screen:

![Screenshot_2023-03-26_23-33-53](https://user-images.githubusercontent.com/2058940/227776230-f3e73153-c26b-4ce7-8480-66188feb388f.png)

I expected it to not clear the screen and only show on the bottom half. This way I get some context for what I did before running *Broot*.

**Comment by Canop** [comment]
This isn't a bug. It tells broot what height of the screen to use. This is mostly useful when exiting immediately, for example in a command like `br -c :pt --height 20`.
