### ISSUE TITLE
Update crossterm dependencies

### ISSUE THREAD

**Issue by zrzka** [Canop/broot#70]
Take this as a friendly reminder, because you're already aware of what's going on. All the `crossterm_*` subcrates (except `crossterm_winapi`) will be deprecated and no longer maintained soon. There's no date yet, but there's some progress already.

For more information, check [this issue](https://github.com/crossterm-rs/crossterm/issues/265). Phase 1 & Phase 2 is finished. Phase 3 is in the progress and once finished, we will start merging.

But because there's no clear answer how the code will be organized (aka public API) yet, it doesn't make sense to migrate now. Once it will be clear, crates will be merged, ... I'll ping you here.

This doesn't mean that you must update these dependencies. It's totally up to you. I just wanted to inform you about what's going on and that you'll be potentially using no longer maintained crates.

**Comment by Canop** [comment]
I'm aware of this. I'm looking into using the new Command API in termimad and broot.
