### ISSUE TITLE
shorten long directories to show filenames

### ISSUE THREAD

**Issue by kakulukia** [Canop/broot#700]
Hi,

even on a maxed out terminal window im not able to see the full file names.

![SCR-20230427-fv0](https://user-images.githubusercontent.com/96352/234822564-95667d48-4faf-4034-96c6-468bacf965ef.png)

Sure this is a very insane folder structure, but sadly its a real world example and on smaler terminals this feature will make even more sense.
Here is how my shell is handling longer folder names:

![SCR-20230427-fzy](https://user-images.githubusercontent.com/96352/234821677-85ec3cf4-e0d0-4a61-95c0-ab8cfc28f93f.png)

For sure broot shall keep the matching parts, but this might be an idea to actually see something inside a horrible folder structure.

Just updated from 1.9 to the current version .. did i overlook an existing flag to already get this feature? If its already possible it should be a default, tho.

**Comment by Canop** [comment]
Is it better if you set this in the config ?

    show_matching_characters_on_path_searches: false

**Comment by kakulukia** [comment]
This sure looks better:

![SCR-20230427-gdd](https://user-images.githubusercontent.com/96352/234826057-459b3290-a3a9-4f2a-aeed-8e433f8f4e36.png)

**BUT** its missing the information of what broot found where. So all in all i find this presentation worse than before. ./

**Comment by Canop** [comment]
OK. This wasn't meant as a complete solution but as a quick workaround for your problem anyway.
Shortening directories looks like a good solution but it needs more work. I'll see when I have time.

**Comment by kakulukia** [comment]
Thanks!

**Comment by Canop** [comment]
I settled for left elision of the paths and nothing elided after the path (meaning the file name and decorations are just truncated):

![image](https://github.com/Canop/broot/assets/617006/04ec8fb4-a36b-4351-bcb3-a92daf8dd5a8)

![image](https://github.com/Canop/broot/assets/617006/c4994b49-4a77-4048-b760-da0da7ec67fb)

![image](https://github.com/Canop/broot/assets/617006/e94ef899-0412-4b6b-a0a2-e8617ea2b4cd)

This should be available soon.

**Comment by kakulukia** [comment]
looks good .. i will test asap :D

**Comment by Canop** [comment]
Here's the PR to test if you can compile Rust: https://github.com/Canop/broot/pull/706

**Comment by kakulukia** [comment]
i better wait for the release :)

**Comment by Canop** [comment]
It's released in 1.22.0

**Comment by kakulukia** [comment]
Works like a charm!
