### ISSUE TITLE
Allow dir size computation in /run/media 

### ISSUE THREAD

**Issue by jinliu** [Canop/broot#704]
Dir size computation is disabled in /proc and /run by:
https://github.com/Canop/broot/commit/aecfe73ba9947e2a1c04f70526cab87e49f4baef

However, usb disks are auto-mounted under /run/media, so is it possible to enable size computation in this dir? 

Or, since broot already detects if the current dir is in a removable disk ("HDD" or "SSD" in the top line), maybe enable size computation in a removeable disk, even if it's mounted under /run?

**Comment by Canop** [comment]
We could probably decide to hardcode
- disallow /run except /run/media
- disallow /proc

(and hope that the Rust bug preventing computations in those dirs ends up fixed someday...)
