### ISSUE TITLE
No config option to change color of size and size graph in top line when `-s` flag is used.

### ISSUE THREAD

**Issue by croyleje** [Canop/broot#705]
When the `-s` flag is used in the top line you get a display of the SIZE CWD DEV TOTAL USED/TOTAL SIZE then a ASCII GRAPH then PERCENTAGE USED.  There is no config option to change the green color used to display the GRAPH and PERCENTAGE.  I looked through the stylemap and code but was unable to locate any option to change this area.  It is possible I have missed it and if so please let me know I have a nice dracula skin I would like to submit but I would really like to change this green first.
Thank you,
Jason

**Comment by Canop** [comment]
That's exact.

Today, this color is computed to express the state of the available space, from green (lot of space) to red (low space).

The scale is hardcoded as

```
static SHARE_COLORS: &[Color] = &[
    Color::AnsiValue(28),
    Color::AnsiValue(29),
    Color::AnsiValue(29),
    Color::AnsiValue(29),
    Color::AnsiValue(29),
    Color::AnsiValue(100),
    Color::AnsiValue(136),
    Color::AnsiValue(172),
    Color::AnsiValue(166),
    Color::AnsiValue(196),
];
```

So the goal would be to allow parameterization of the colors of a "good to bad" scale.

**Comment by croyleje** [comment]
First off I am sorry I should have never opened this ticket I realized your discussion group after I had opened it and then realized the ticket was posted there automatically so I did not want to double post it.  As for the colors, would it be unreasonable to expose them all to configurable options?  I think a nice transition could be obtained with a maximum of 4 colors.  I don't think most people would be able to distinguish between 10% difference in full space.  Mostly when I use it I am just looking to see what is eating up space in whale mode or seeing if there is some large log file that isn't getting rotated.  I would love to be able to change them all but honesty I would probably only use 3 or 4 at most.  Empty to 30%, 30-60%, 60-90% and critical over 90%.  If you don't mind leaving this ticket open for a little bit I'am trying to workout a simple way to enter a single color and get a gradient back in Ansi color codes.  Is that is something that would work?  Should be a fairly simple bit of code I know there are ways for generating colors that are complementary to each other and would be happy to look into it.

**Comment by Canop** [comment]
First, there's no reason to be sorry. In case of doubt you're welcome on the [Miaou chat](https://miaou.dystroy.org/3490) but your issue is OK, no problem.


You can define the number of colors of your choice by just repeating them. Here for example if you want only 2 colors:

```
    good_to_bad_0: ansi(28)
    good_to_bad_1: ansi(28)
    good_to_bad_2: ansi(28)
    good_to_bad_3: ansi(28)
    good_to_bad_4: ansi(28)
    good_to_bad_5: ansi(28)
    good_to_bad_6: ansi(28)
    good_to_bad_7: ansi(196)
    good_to_bad_8: ansi(196)
    good_to_bad_9: ansi(196)
```

As for automated color transitions, it's already hard in a big color space when you want a path between colors as different as green and red, and it's much harder in the ANSI space which has about 200 colors. I'm the author of the [coolor](https://crates.io/crates/coolor) library which computes color transitions in the ANSI space and I still prefer to have such scales being human defined for better results.
