### ISSUE TITLE
using modal but, but start in search/input mode

### ISSUE THREAD

**Issue by mokasin** [Canop/broot#708]
There doesn't seem to be an option to use the modal mode, but start in input/search mode.

To me it would be useful to start in input/search mode, but switch to command mode when pressing <kbd>ESC</kbd>.

[telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) works similarly.

**Comment by clamydo** [comment]
Thank you! Eager to test it 😄

**Comment by Canop** [comment]
@clamydo I'll release a new version so that you can

**Comment by Canop** [comment]
The [setting](https://github.com/Canop/broot/blob/v1.32.0/resources/default-conf/conf.hjson#L56) is available with the newly released 1.32.0. 

_thanks, btw_
