### ISSUE TITLE
nushell support

### ISSUE THREAD

**Issue by mystique09** [Canop/broot#712]
The documentation:
> broot --print-shell-function bash (you can replace bash with zsh, fish, or nushell) outputs a recommended shell function.

but when I try to run `broot --print-shell-function nushell` it doesn't work.

```nushell
/data/data/com.termux/files/home〉broot --print-shell-function nushell
Unknown shell: nushell
/data/data/com.termux/files/home〉          05/21/2023 10:58:28 PM
```

**Comment by Canop** [comment]
It works for me. What's your version of broot ?

**Comment by mystique09** [comment]
> It works for me.
> Can you launch broot with the debug log enabled (eg with `BROOT_LOG=debug broot --print-shell-function nushell`) and show the content of the broot.log file ?
> 

oof
```bash
~ $ cat broot.log
16:33:27.454 [INFO] cli_log::init: Starting broot v1.13.1 with log level DEBUG
16:33:27.454 [DEBUG] broot: env::args(): [
    "broot",
    "--print-shell-function",
    "nushell",
]
16:33:27.455 [WARN] broot: Error: Unknown shell: nushell
16:33:27.455 [INFO] cli_log::mem: Physical mem usage: current=4.7M, peak=11G
16:33:27.455 [INFO] broot: bye
~ $
```

**Comment by mystique09** [comment]
From the download section of docs
https://dystroy.org/broot/download/aarch64-linux-android/broot

**Comment by Canop** [comment]
OK, I get it. I stopped building the android version due to local build problems. I'll clean that.

**Comment by mystique09** [comment]
Thanks, I was able to use the latest verson now.

![Screenshot_20230524-143358.jpg](https://github.com/Canop/broot/assets/50514928/2920e503-5c75-428f-84e4-848b1a6a8be6)

**Comment by Canop** [comment]
Ok, so you're another termux user ?
I guess I should fix that compilation problem (which probably involves a big internal change in broot, replacing git2 with gitoxide)

**Comment by mystique09** [comment]
Thanks, I was able to use the latest verson now.

![Screenshot_20230524-143358.jpg](https://github.com/Canop/broot/assets/50514928/2920e503-5c75-428f-84e4-848b1a6a8be6)

Yeah
