### ISSUE TITLE
stage_all_files does not work under Windows

### ISSUE THREAD

**Issue by AeliusSaionji** [Canop/broot#714]
Sorry, I've got another Windows specific quirk for you 😛 

As the title indicates, ctrl-a or `stage_all_files` seems to do nothing except toggle the staging area.
ctrl-g and `stage` do work, however.

Tested against 1.22.1

**Comment by Canop** [comment]
> As the title indicates, ctrl-a or stage_all_files seems to do nothing except toggle the staging area.

This is weird. I see no reason for that to work differently on Windows. Can you please show me the [debug log](https://dystroy.org/broot/community/#log) ?

**Comment by AeliusSaionji** [comment]
More strangely it decided to work, and works on two different PCs now.

¯\_(ツ)_/¯
