### ISSUE TITLE
unwrap path given in argument when it's between double quotes - windows

### ISSUE THREAD

**Issue by Canop** [Canop/broot#72]
If we do

    broot "D:"

broot should open `D:`

**Comment by Canop** [comment]
This is normally the job of the shell. I'm not sure of why exactly it doesn't work on windows. I'll probably have to experiment with a windows-only unwrapping.

**Comment by Canop** [comment]
I wrote help wanted because I'd need a Windows tester here

**Comment by Hrxn** [comment]
I can help testing with Windows. But as you said, this is usually handled by the shell.

**Comment by Canop** [comment]
@Hrxn  In fact the problem comes because one of my users made a .reg thing to add a broot action on right click in windows explorer.
It works for most folders but not for disk roots because it looks like it calls `broot "D:\"`. But we suspect the real problem is a little more subtle.

**Comment by Canop** [comment]
If you look at current master, there's a commented out unwrapping code in `read_launch_args`. It may help with the testing.
