### ISSUE TITLE
Should `broot --set-install-state installed` print to stdout?

### ISSUE THREAD

**Issue by dontlaugh** [Canop/broot#721]
I just upgraded to `1.23.0`. Installation method: Void Linux package manager.

For a long time, I've had this in my Zsh config 

```zsh
if type broot > /dev/null; then
    source <(broot --print-shell-function zsh)
    broot --set-install-state installed
fi
```

Recently I've been seeing this output on stdout when opening a new shell.

```
Removing /home/coleman/.config/broot/launcher/installed-v4.
```
Here is what's printing: https://github.com/Canop/broot/blob/main/src/shell_install/mod.rs#L158

Am I "installing" wrong? For now, I'll pipe to /dev/null, e.g.

```
broot --set-install-state installed > /dev/null
```

Here is the build recipe for the Void distro https://github.com/void-linux/void-packages/blob/master/srcpkgs/broot/template

Could this be a packager problem?

**Comment by Canop** [comment]
> Am I "installing" wrong? 

This is certainly non standard. The idea of the installation was that it would happen only once, not every time you start a shell.

In my design, there was 2 ways to install the br script:
* by letting broot do it on first run
* by calling manually the functions you use, but once. There's no reason to call `--set-install-state` at each shell start

With that design, in order for the user doing the manual operations, it is preferable to inform the user of what's exactly done. 
Your setup does work, though. I don't have any reason not to support it.
There could be a `--silent` flag for installation purposes, maybe.

**Comment by Canop** [comment]
Sending the output to `dev/null` seems to be the simpler solution. Without further comment, I won't clutter broot launch arguments with a `--silent`.
