### ISSUE TITLE
remove the outdated pate https://dystroy.org/broot/documentation/configuration/ form site

### ISSUE THREAD

**Issue by maxim-uvarov** [Canop/broot#724]
I entered 'broot configuration' in Google.
It gave me this link:
https://dystroy.org/broot/documentation/configuration/

As far as I can understand, this page is outdated. There is a more recent version available at:
https://dystroy.org/broot/conf_file/

I discovered this only after spending some time trying to understand why the config is a TOML file when I have a bunch of HJSON files.

I would suggest deleting the old page and creating a 301 redirect to the new page.

**Comment by Canop** [comment]
Thanks.
I've set up a redirect and removed all links I could find to this old page.
