### ISSUE TITLE
Ignore symbolic object's size

### ISSUE THREAD

**Issue by Erimus-Koo** [Canop/broot#727]
Is there some way to ignore the size of the symbolic folder/file while counting or sorting?

For example, while I count a project folder size, there's a node_module folder created by `pnpm`, and I want to count the REAL SIZE of this folder.

In Python, `os.walk` has a param is `followlinks`, the default value is False and won't go in the symbolic folder.

**Comment by Canop** [comment]
You mean as a global setting or for a one-shot computation ?

Following links for size computation, even with deduplication (which I can only do on unix-like systems), might lead to misleading results.

**Comment by Erimus-Koo** [comment]
In my case, I want to know if `pnpm` really saves disk space, I can count it in some complex ways, but I wonder if I can do that in broot directly.

And some days ago, I found the `powertoys` on Windows has the same issue, and a little tool occupied 3.1G space (that's a wrong count).

**Comment by Canop** [comment]
By REAL SIZE you mean not the size inside the folder but the addition of the size inside the folder and the linked folders, right ?

**Comment by Canop** [comment]
I'm sorry, I think I misunderstood you.
You say broot follows symbolic links on your system when summing sizes ? This shouldn't happen. What's your operating system and filesystem ?

**Comment by Erimus-Koo** [comment]
Okay, that's my mistake, I've misunderstanding about the pnpm, it uses a symbolic link inside but a hard link outside, so that still hard to count the size of the module folder.
![](https://res.cloudinary.com/practicaldev/image/fetch/s--hW_DUPBV--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://pbs.twimg.com/media/FGx92b4aUAEAfn5%3Fformat%3Djpg%26name%3D4096x4096)

And broot doesn't count the symbolic links.
<img width="620" alt="image" src="https://github.com/Canop/broot/assets/17139670/64996821-31d3-42b1-bdc9-b23434ccd152">
