### ISSUE TITLE
Possibility to type argument for internal command

### ISSUE THREAD

**Issue by ww7** [Canop/broot#728]
I'm new with `broot` and searching way for simple and quick exact browsing/filtering

`ep/` don't accept completion with `Tab`, and `:focus` works fine, but I want to assign a key that paste `:focus` and allow to type after that, is it possible? 

Such verb not working

```
    {
        invocation: goto
        key: F4
        auto_exec: false
        internal: ":focus {args}"
    }
```

**Comment by Canop** [comment]
You were almost right. You just missed the `{args}` needs to be declared in the invocation:

        {
            invocation: "goto {args}"
            key: F4
            auto_exec: false
            internal: ":focus {args}"
        }
