### ISSUE TITLE
Positional argument (filepath) focus

### ISSUE THREAD

**Issue by ww7** [Canop/broot#729]
Currently, the path to file passed as positional argument `broot` opening as directory of file.

It would be useful if `broot` make the focus on the file specified, that allow also open a preview 

E.g. `br --exe :open_preview Downloads/readme.md`

**Comment by Canop** [comment]
Right now, you can open broot on a file preview with

    br -c 'README.md;:open_preview'

I aggree it's not terribly convenient.

broot doesn't like to be given a path to anything else than a directory. I could change that and have the file selected. Maybe also have the preview immediately opened. I'll look into this.

**Comment by ww7** [comment]
```
br -c 'README.md;:open_preview'
```
it searches and not allow specifying path to file
