### ISSUE TITLE
1.25.0 error => /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found

### ISSUE THREAD

**Issue by Heart1010** [Canop/broot#732]
Didn't have problems until now executing broot on my debian but with latest v1.25.0 I get:
```bash
root@cp:~#  broot
broot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by broot)
broot: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by broot)
broot: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by broot)
broot: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by broot)
```
```bash
root@cp:~# cat /etc/debian_version
11.7
```

**Comment by Heart1010** [comment]
Used the compile binary all the time until now
```bash
root@cp:~# rm broot && wget https://dystroy.org/broot/download/x86_64-linux/broot && cp broot /usr/local/bin/ && br --version
```
Also tested the github zip file and tested all broot binary files in there - every time the same error(s).

**Comment by Canop** [comment]
> root@cp:~# rm broot && wget https://dystroy.org/broot/download/x86_64-linux/broot && cp broot /usr/local/bin/ && br --version

Can you retry now ?

**Comment by Heart1010** [comment]
It's working agin now 👍  Thanks!!!

**Comment by Canop** [comment]
Reopening. I must find a reliable way to build for older GLIBC without the hack I just did...

**Comment by Canop** [comment]
> Also tested the github zip file and tested all broot binary files in there - every time the same error(s).

Did you really try the `x86_64-unknown-linux-gnu/broot` from the archive ? It should work on debian 11.7

**Comment by Heart1010** [comment]
Perfect - so in the future I have to download the github zip (and extract from x86_64-unknown-linux-gnu folder) or can I still use the https://dystroy.org/broot/download/x86_64-linux/broot download url?

**Comment by Canop** [comment]
There's a direct link to the x86_64-unknown-linux-gnu binary in https://dystroy.org/broot/install/#from-precompiled-binaries, you don't have to download the whole archive.

This one should keep working.

I don't know if I'll be able to propose a binary for older linux with clipboard support.
