### ISSUE TITLE
Characters that are entered while pressing shift are "selected"

### ISSUE THREAD

**Issue by chtenb** [Canop/broot#733]
When I enter characters while holding the shift mode, they get "selected", meaning 
- they are highlighted
- when pressing backspace, the whole bunch of them is removed, instead of just the last character.

![image](https://github.com/Canop/broot/assets/1030961/33abe3ff-44a2-4aad-bc6c-5e79a9ec4267)

This happens both on Windows and ubuntu linux, in different terminal emulators. No config other than the default.
I'm assuming this is a bug.

**Comment by Canop** [comment]
>  I'm assuming this is a bug.
Looks like one

**Comment by Canop** [comment]
Fixed in version 1.2.1
