### ISSUE TITLE
Property content_search_max_file_size not accepted in toml format?

### ISSUE THREAD

**Issue by chtenb** [Canop/broot#734]
I'm using the toml format for my conf, but it seems that content_search_max_file_size does not work in toml:

Setting 

```toml
content_search_max_file_size = "10MB"
```

yields

```
Bad configuration file "....\\conf.toml" : unable to parse TOML: TOML parse error at line 90, column 32
   |
90 | content_search_max_file_size = "10MB"
   |                                ^^^^^^
unrecognized special handling: "10mb"
```

It does work in hjson it seems

**Comment by Canop** [comment]
Move that declaration at the start of your TOML file ?

Here you have it past an array declaration, which makes it an element of that array.

**Comment by Canop** [comment]
> Sorry for bothering your.

No worry. It's not your fault, it's TOML being badly designed and absolutely not "obvious". This kind of problem is why Hjson is now the preferred configuration format of Broot.
