### ISSUE TITLE
Directory missing

### ISSUE THREAD

**Issue by romamik** [Canop/broot#736]
I have a directory that just does not show up in `broot`. It is normally visible with `ls`. After copying it to another directory it also becomes visible by `broot`. The directory is called 'data' and it has the same owner and access rights as other directories. Why can this be?

I'm on MacOs, broot 1.25.0.

'broot' with search for 'data':
![image](https://github.com/Canop/broot/assets/3735734/a37a930b-85cf-4f95-8ad8-b87477a34f58)

'ls' is the same directory:
![image](https://github.com/Canop/broot/assets/3735734/a396007c-ca5e-4a79-bb09-e82205b3f4b2)

**Comment by Canop** [comment]
Try to show hidden and gitignored files with `alt-h` and `alt-i`.

**Comment by romamik** [comment]
> It's very probable there's a "data" entry either in a local .gitinore file or in the global one.
Yes. Thank you for your help!
