### ISSUE TITLE
Predefined skin for light background

### ISSUE THREAD

**Issue by birkenfeld** [Canop/broot#74]
Skin support is nice, but I'd rather not have to start adapting 20 colors to work well on light background terminals.

I'd be happy with another set of commented-out values in the generated `conf.toml` that I can just uncomment and work well with light background.

Thanks!

**Comment by Canop** [comment]
It's indeed easier to define the values when you know exactly what they do.

I think I'll do as you suggest.

If somebody already did the work, please show me.

**Comment by birkenfeld** [comment]
Thanks! I don't know of an existing config though.
