### ISSUE TITLE
How to hide .git folders reliably?

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [Canop/broot#744]
Probably a bug; even after adding these, `.git` folders still show randomly.
`"/home*.git" = "hide"`
OR
`"*.git" = "hide"`

**Comment by Canop** [comment]
Are you sure you don't want `"/home/**/.git"` or `"**/.git"` ? A `*` in glob syntax doesn't match a `/`.

**Comment by limaceous-bushwhacker** [comment]
I see, somehow that skipped my mind. Though `.git` folder still shows up (randomly) after doing that. Here's what I have in my `special_paths`:
```
"~/a" = "no-hide"
"**/.git" = "hide"
```
Does `special_paths` some kinda precedence rule?

**Comment by limaceous-bushwhacker** [comment]
> Are you sure you don't want `"/home/**/.git"` or `"**/.git"` ? A `*` in glob syntax doesn't match a `/`.

I see, somehow that skipped my mind. Though `.git` folder still shows up (randomly) after doing that. Here's what I have in my `special_paths`:
```
"~/a" = "no-hide"
"**/.git" = "hide"
```
Does `special_paths` some kinda precedence rule?

**Comment by Canop** [comment]
OK, I had a second look at how "hide" is defined.
What the "hide" special-path rule do, is it puts the file/directory in the "hidden" category.
But your .git directories were already in this category: they're not shown unless you toggle showing the hidden files, and they're revealed when all hidden files are displayed.

**Comment by limaceous-bushwhacker** [comment]
> OK, I had a second look at how "hide" is defined. What the "hide" special-path rule do, is it puts the file/directory in the "hidden" category. But your .git directories were already in this category: they're not shown unless you toggle showing the hidden files, and they're revealed when all hidden files are displayed.

Thank you, this makes sense. Looks the issue was on my end due to conflict between entries in `special_paths`.
