### ISSUE TITLE
:e has `$EDITOR +0`, should default be `$EDITOR`?

### ISSUE THREAD

**Issue by thomasaarholt** [Canop/broot#745]
Hiya! New to broot here, really cool project! 🔥 

I was trying to open a python file using `:e`, which made it look like it opened a blank file in my editor even though the file should have contents. 

I see from the docs that the intention is for the editor to realise that we want to open it on line 0 - that `$EDITOR +N <filepath>` means to open the filepath at line N. During writing this issue, I learnt that vim supports this syntax, but I observe that neither [helix](https://github.com/helix-editor/helix) or VScode do.

I notice that helix supports e.g. `hx main.py:10` to open on line 10 (and even `hx main.py:10:5` to open on line 10 column 5). And VSCode supports `code --goto main.py:10`. 

Could I suggest that you remove the +0 by default, and make options to add them in?

It wasn't obvious from the [docs](https://github.com/Canop/broot/blob/main/website/docs/file-operations.md#edit-a-text-file) _how_ to change this behaviour, so if the default is kept, then I suggest making it a bit easier to change.

![image](https://github.com/Canop/broot/assets/2721423/f3452c5e-7751-4b9d-bbf0-d0234b3bbbd2)

**Comment by Canop** [comment]
You're right.
This will be a regression for vim users but will make it work for some other editors.

I'll change the default conf and improve the documentation.
