### ISSUE TITLE
Case insensetive search for non Latin letters.

### ISSUE THREAD

**Issue by nklybgn** [Canop/broot#746]
It looks like search engine becomes case sensetive when enter cyrilic letters. It would be very good for search model to be consistent for all languages.

**Comment by nklybgn** [comment]
Sure. I run Broot on linux (Ubuntu 22.04) and here is my /home on pictures.
On the first screenshot one you can see the directory "Устройства" at the very bottom of the screen.
![Broot1](https://github.com/Canop/broot/assets/145597450/ed3aff15-df5d-495f-a2d8-133edb823f09)
On the second you see attempt to search for sting  "устр" and the filtering result for that string with no directory "Устройства" among them.
![Broot2](https://github.com/Canop/broot/assets/145597450/1cc0db25-cae6-45f1-a0ad-08a38079e160)
On the third there is attempt to search the same string but case sensitive this time and now directory "Устройства" is matched.
![Broot3](https://github.com/Canop/broot/assets/145597450/46a7a77c-2a9e-420d-bff1-1b7e0c161968)
With best regards,
Nikolay

**Comment by Canop** [comment]
OK, I see the problem.
Broot is compiled with a light version of the normalization table.
When I include the full table, there's no problem anymore.
Broot becomes 195kB heavier but I don't measure any slowdown.

**Comment by nklybgn** [comment]
Thank you a lot for help. I recompiled Broot and now it works as expected. Thanks again!
