### ISSUE TITLE
Fish prompt is not updated after cd'ing when broot is launched with a keybind

### ISSUE THREAD

**Issue by Schweber** [Canop/broot#748]
I am using the fish shell with the tide prompt with broot 1.25 on NixOS and launch broot with the br shell wrapper. I don't know if this is an issue with `fish` or with `broot`:

When i launch `broot` with the `br` command in the terminal and use `{ key: "enter", from_shell: true, execution: "cd {directory}" }`, then broot exits, the cwd is changed and the prompt of my shell is updated to reflect that. This is the behaviour that i expect. 

However, when i launch `broot` with a keybind in `fish`, e.g. `bind \ch 'br -gi'` in `configuration.fish`, then the cwd is changed but the prompt is not updated/redrawn. Only after i run a command in the shell the prompt is updated and shows the correct path.

**Comment by 0xfea5** [comment]
Not sure if this is a bug but a temporary workaround would be to repaint the fish prompt like this
```bind \ch 'br -gi; commandline -f repaint'```

**Comment by Schweber** [comment]
That works, thank you!

**Comment by Canop** [comment]
Let's keep this open until it's determined whether it's a bug, and if that's a bug, whether it's fish, tilde, or broot.

**Comment by Schweber** [comment]
I found the [following](https://fishshell.com/docs/current/cmds/bind.html):
```
Note:
Special input functions cannot be combined with ordinary shell script commands. The commands must be entirely a sequence of special input functions (from bind -f) or all shell script commands (i.e., valid fish script). To run special input functions from regular fish script, use commandline -f (see also [commandline](https://fishshell.com/docs/current/cmds/commandline.html)). **If a script produces output, it should finish by calling commandline -f repaint to tell fish that a repaint is in order.**
```

So if the last sentence is meant as a general statement, then the behaviour is not a bug and the workaround by @0xfea5 is the correct thing to do.
