### ISSUE TITLE
Invoking multiple internal commands with a single key binding.

### ISSUE THREAD

**Issue by adriel-tech** [Canop/broot#750]
Hello,

I am a huge fan of broot, thanks for making such a great tool!

I would like to toggle multiple internal commands with a single key binding. I default to using tree mode and I would like the ability to toggle permissions and sizes together.

    {
        invocation: toggle
        key: alt-t
        internal: ":toggle_perm :toggle_sizes"
        leave_broot: false
    }

I tried a few ways:
 internal: ":toggle_perm :toggle_sizes"
 internal: [":toggle_perm" ":toggle_sizes"]
 internal: ":toggle_perm;:toggle_sizes"

Is there already a way to accomplish this?

Thanks for your time.

**Comment by Canop** [comment]
Use [cmd](https://dystroy.org/broot/conf_verbs/#verb-definition-attributes):

```
 {
    invocation: toggle
    key: alt-t
    cmd: ":toggle_perm;:toggle_sizes"
    leave_broot: false
}
```

**Comment by adriel-tech** [comment]
Thank you that works, much appreciated!
