### ISSUE TITLE
Alternative "SHELL"/increased scriptability

### ISSUE THREAD

**Issue by vanya-robertson** [Canop/broot#757]
Hello!

On pressing enter, I would like broot to not enter my shell, but enter a program called clifm.
I have a shortcut and a keybinding for it:
```
    {
        invocation: terminal
        key: ctrl-t
        execution: "clifm {file}"
        set_working_dir: false
        leave_broot: true
    }
```

But am unsure as to how to make this the default action.

If there were a mode to return the filepath of the selected file or directory (as in fzf), I could make my own script to integrate it with my workflow.

Merci,
Vanya

**Comment by Canop** [comment]
I'm not sure I understand the question. Are you looking for this: https://dystroy.org/broot/tricks/#change-standard-file-opening ?

**Comment by vanya-robertson** [comment]
That was exactly what I was looking for.
Thank you!
