### ISSUE TITLE
ctrl-i persistently mapped to :line_down

### ISSUE THREAD

**Issue by vanya-robertson** [Canop/broot#759]
I cannot map ctrl-i to :parent, :back or :escape, but can map other keys, like ctrl-k. ctrl-i seems to be fixed to :line_down.
It's not mapped in my inputrc, so I presume it is clifm-specific.

Could you remove this behaviour?
And sorry to keep hassling you today. I appreciate the help.

**Comment by Canop** [comment]
It's very probable your terminal is the one intercepting this key.

Can you get [print_key](https://github.com/Canop/print_key) and see what it prints when you hit ctrl-i ?

**Comment by vanya-robertson** [comment]
It tells me I typed "Tab". It does this in both st and kitty. Everything I read indicates that this is pretty much unfixable.
Thanks for the pointer.

**Comment by markus-bauer** [comment]
I think it's fixable using kitty's extended keyboard protocol, which is supported by crossterm.

There's already an issue: #648

**Comment by b1nhack** [comment]
You can map Tab to any key you want, so Ctrl-i will also be mapped to the corresponding key. However, you'll need to give up using the Tab key because Tab and Ctrl-i can't be separately mapped unless you accept the delay caused by enable_kitty_keyboard.
```hjson
{
		key: Tab
		internal: “:focus”
		apply_to: “directory”
}
```
