### ISSUE TITLE
Automatically open text files with `$EDITOR`

### ISSUE THREAD

**Issue by musjj** [Canop/broot#764]
Terminal file managers like `nnn`, `lf`, `yazi` can automatically detect text files and open them in your `$EDITOR`, instead of `xdg-open`. `broot` requires you to specify an explicit key for this, I think it'd be more convenient if we can use a single key to open anything.

**Comment by Canop** [comment]
@musjj Can you check this PR ? https://github.com/Canop/broot/pull/769
