### ISSUE TITLE
How to move files to current directory?

### ISSUE THREAD

**Issue by limaceous-bushwhacker** [Canop/broot#767]
Is it possible to locate a file using broot and then move/copy it to current open directory in the terminal/shell? I'm looking to avoid having to open two different panels and then `mvp` amongst them.

**Comment by Canop** [comment]
**First solution:** use some `..` 

![image](https://github.com/Canop/broot/assets/617006/b8a63c13-0d6f-4508-bce0-e6f280dcd05b)

As the command is previewed while you type, this is convenient IMO.

**Second solution:** declare a dedicated verb

    {
        invocation: mr
        external: "mv {file} {root}"
        leave_broot: false
    }

![image](https://github.com/Canop/broot/assets/617006/a09b3dc9-df29-4cc3-97a6-23ba15eccf3f)

**Comment by limaceous-bushwhacker** [comment]
> **First solution:** use some `..`
> 
> ![image](https://user-images.githubusercontent.com/617006/275808379-b8a63c13-0d6f-4508-bce0-e6f280dcd05b.png)
> 
> As the command is previewed while you type, this is convenient IMO.
> 
> **Second solution:** declare a dedicated verb
> 
> ```
> {
>     invocation: mr
>     external: "mv {file} {root}"
>     leave_broot: false
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/617006/275808647-a09b3dc9-df29-4cc3-97a6-23ba15eccf3f.png)

Thank you, this'll do for now. broot's amazing :)
