### ISSUE TITLE
homebrew v0.11.7 upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [Canop/broot#77]
Relates to https://github.com/Homebrew/homebrew-core/pull/48138

Right now test step failed on CI.

**Comment by Canop** [comment]
Hum... what test exactly failed ?

**Comment by chenrui333** [comment]
The test step failed:
```
$ brew test --verbose broot
Testing broot
/usr/bin/sandbox-exec -f /private/tmp/homebrew20191221-16954-1d107jb.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/broot.rb --verbose
Error: broot: failed
An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /private/tmp/broot-test-20191221-16955-5kskaa/output.txt
```

**Comment by chenrui333** [comment]
But when I run locally, it did work well for me though

```
$ /usr/local/Cellar/broot/0.11.0/bin/broot --cmd ":pt" --no-style --out ./output.txt formula

$ cat output.txt
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
├──Aliases
│  ├──0mq -> ../Formula/zeromq.rb
```

**Comment by Canop** [comment]
I don't understand this command. Is it supposed to be

```
broot --cmd "formula :pt" --no-style --out ./output.txt
```

?

**Comment by chenrui333** [comment]
I was just trying to see it works locally though, but in the CI or `brew test broot` do not work.

**Comment by chenrui333** [comment]
I tried the latest 0.11.2 locally on my machine, still failed:

```
$ brew test broot
Testing broot
Error: broot: failed
An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /private/tmp/broot-test-20191230-54445-gwe3qi/output.txt
```

**Comment by chenrui333** [comment]
@Canop If you got chance, can you take a look at the setup?

**Comment by dakira** [comment]
The test that failed is defined in the formula itself:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/broot.rb

**Comment by Canop** [comment]
The test looks fine but I don't know the homebrew test environnement. It might be anything including a failure to initialize the terminal things.

**Comment by alebcay** [comment]
The issue might be the installation prompt:
```
Broot should be launched using a shell function (see https://github.com/Canop/b
root for explanations).
The function is either missing, old or badly installed.
Can I install it now? [Y n]
```

I've attempted to pass `n` as input into the test environment but it still doesn't seem to be working.

**Comment by Canop** [comment]
There could be a --no--install option but is a test really necessary ?

**Comment by chenrui333** [comment]
@Canop if we cannot ignore the `shell installation` step, all the actual tests for broot cannot be done then, including simple test (like `broot --dates`)

**Comment by dakira** [comment]
I think "broot --version" should be enough for testing, shouldn't it? Homebrew recipes shouldn't test if a program works as expexted, they should test if it was properly installed.

**Comment by chenrui333** [comment]
Thanks for the comment, the interesting fact is the formula test block was working prior to `0.11.0`. 

And in the ideal world, homebrew side is trying to catch any undesired changes while building from the source code.

**Comment by Canop** [comment]
Please note that version prior the 0.11.7 are **dangerous**.
It's important that nobody can install them anymore.

**Comment by alebcay** [comment]
> I think "broot --version" should be enough for testing, shouldn't it? Homebrew recipes shouldn't test if a program works as expexted, they should test if it was properly installed.

We have had plenty of instances where programs successfully "installed" but the only way that we found out that it had not installed properly was by testing some of the actual features of the program (e.g `SIGABRT` due to issues with a compiler). That's why we try to have a meaningful test of program functionality rather than just `broot --version`.

> Please note that versions prior the 0.11.7 are dangerous. It's important that nobody can install them anymore.

If we can't find a solution to the test issue, another option is just to remove `broot` from Homebrew's core repo, and you can host the Homebrew formula in your own tap, for which a `test...do` block is not required.

**Comment by Canop** [comment]
@alebcay  I have no mac. I don't know how brew works. So if I were to host the brew formula myself, I'd appreciate a detailed how-to.

**Comment by alebcay** [comment]
[This document has the details]. This is not to say that `broot` is not welcome in the core repo at Homebrew; rather, just trying to bring up some other options in case things don't work out.

**Comment by alebcay** [comment]
In other news, [we've been working on getting the version shipped in Homebrew updated](https://github.com/Homebrew/homebrew-core/pull/48138). The test is getting tweaked but hopefully it will work soon.

**Comment by chenrui333** [comment]
I managed to improve the test part and filed a new PR on the latest release v0.11.8 (https://github.com/Homebrew/homebrew-core/pull/48947).

Once the CI passed, I will merge that PR and close this issue. Thanks!

**Comment by chenrui333** [comment]
Closing the issue now. Thanks everyone!!

**Comment by acalism** [comment]
`--no-style` is no longer a valid option now for broot 1.12.0

**Comment by Canop** [comment]
@acalism You probably want `--color no` instead
