### ISSUE TITLE
device_* keys missing in documentation

### ISSUE THREAD

**Issue by cgahr** [Canop/broot#770]
In the [documentation](https://dystroy.org/broot/skins/), the following 3 keys are missing:
- device_id_major
- device_id_sep
- device_id_minor

**Comment by Canop** [comment]
There's no real documentation of all the keys.

I guess you're referring to the example skins. As I don't see anything more convenient, I should probably strive to make them use all the keys.

Besides the keys you noticed, the `parent` ones is also missing from the examples.
