### ISSUE TITLE
UTF-8 split codepoints

### ISSUE THREAD

**Issue by 9999years** [Canop/broot#781]
I don't have a reproducer yet, but sometimes Broot will render several U+FFFD � REPLACEMENT CHARACTERs as part of the tree visualization. This usually happens when a Unicode codepoint, encoded as multiple bytes in UTF-8, is split and decoded. The decoding fails, as only half of the data is present, resulting in U+FFFD � REPLACEMENT CHARACTERs where the bytes are split.

<img width="393" alt="A screenshot of Broot showing U+FFFD � Replacement Character" src="https://github.com/Canop/broot/assets/15312184/ffeecde1-1b57-4991-9dcf-90ec8bf05b2d">

**Comment by Canop** [comment]
As I never observed this, data for reproduction would indeed be very useful.

**Comment by 9999years** [comment]
- OS: macOS Sonoma 14.1
- Terminal: iTerm2 3.4.21
- Multiplexer: tmux 3.3a

**Comment by Canop** [comment]
This looks like another tmux bug :(

**Comment by 9999years** [comment]
Actually, I missed a detail: it's a Neovim bug! I can't reproduce this outside of Neovim, even in Tmux. I'll report this upstream.

**Comment by Canop** [comment]
Good find!

**Comment by Canop** [comment]
BTW, people may not realize that: dealing with "characters" which may be several bytes long, and several terminal cells long, is half the work ^^
