### ISSUE TITLE
gitignore inconsistencies

### ISSUE THREAD

**Issue by dvic** [Canop/broot#782]
what kind of gitignore parsing approach is being used? Because I'm seeing inconsistencies, for example:

this works:

`/foo/bar/baz.txt`
![image](https://github.com/Canop/broot/assets/1214337/4037b7fc-9c30-49da-96c3-cffc5fcba18f)

but this does not:

`foo/bar/baz.txt`
![image](https://github.com/Canop/broot/assets/1214337/97b2b7e1-8caa-4103-8820-2470028f285d)

while git status is fine with both. Any idea?

**Comment by dvic** [comment]
I haven't checked explicitly, but this seems the only thing. At first I thought a gitignore file in the parent directory was not picked up, but the issue was the absent / in the gitignore file.

**Comment by Canop** [comment]
Thanks for the report. Did you see inconsistencies other than this one (path not starting with a `/` but with several items) ?

**Comment by Canop** [comment]
This should be fixed with #792. Tests would be welcome.

**Comment by dvic** [comment]
> This should be fixed with #792. Tests would be welcome.

Works like a charm, thanks!
