### ISSUE TITLE
Image preview in kitty is slow

### ISSUE THREAD

**Issue by dev-ardi** [Canop/broot#789]
(On kitty) Image preview takes much longer than one would expect. 

If you hold down the down key in an image directory broot lags incredibly hard.

**Comment by leira** [comment]
I'm on Wezterm. The image preview with `br` is significantly slower than [yazi](https://github.com/sxyazi/yazi) and [ranger](https://github.com/ranger/ranger). To load a 6000*4000 picture, yazi was almost instant. ranger loaded within half seconds. It took around 5 seconds with br. How can I provide more information?

**Comment by Canop** [comment]
@dev-ardi @leira can you try the version of [this PR](https://github.com/Canop/broot/pull/835) ?
