### ISSUE TITLE
Clarify docs regarding `default_flags` usage

### ISSUE THREAD

**Issue by cohml** [Canop/broot#790]
Regarding default flags, [the docs](https://dystroy.org/broot/conf_file/#default-flags) currently state:

> If you almost always want those flags, you may define them as default in the configuration file file, with the `default_flags` setting.
>> Hjson
>> `default_flags: gh`

However, using long options for readability doesn't seem to work. For example, my entry ...

> default_flags: show-git-info

... results in an error:

> Bad configuration: invalid default flags: "show-git-info"

I also tried several variations, such as prepending `--` or wrapping the flag in `"..."`. But the error persisted.

So I'd propose one of the following changes:

1. **feature request:** if long options ARE NOT allowed in the conf file, allow for them **(my strong preference)**
2. **improve documentation:** if long options ARE NOT allowed and will never be, make this explicit in the docs
3. **improve documentation:** if long options ARE allowed, clarify in the docs how to use them, incl. examples

broot 1.26.1

**Comment by Canop** [comment]
You're right, it's time to upgrade this syntax which predates all the more complex launch arguments. I'll go for 1.

**Comment by Canop** [comment]
It should be OK with this PR: https://github.com/Canop/broot/commit/64b166559f3150f6f6e58e7a63679fb50c97e22b
