### ISSUE TITLE
gitignore inconsistencies

### ISSUE THREAD

**Issue by dvic** [Canop/broot#795]
It seems the fix for #782 broke the git ignore files where you use `/`! I only checked the usecase of removing the `/` prefix, sorry about that!

So now 

this works:

`foo/bar/baz.txt`
![image](https://github.com/Canop/broot/assets/1214337/97b2b7e1-8caa-4103-8820-2470028f285d)

but this does not:

`/foo/bar/baz.txt`
![image](https://github.com/Canop/broot/assets/1214337/4037b7fc-9c30-49da-96c3-cffc5fcba18f)

(before 1.28 it was the other way around)

**Comment by Canop** [comment]
Damn.. I thought I had checked that but obviously I messed at some point!

**Comment by Canop** [comment]
Should be good now. Can you test ?

**Comment by dvic** [comment]
> Should be good now. Can you test ?

Yup, I can confirm now both usecases work!

**Comment by Canop** [comment]
Fix released in 1.28.1.
Thanks for noticing the bug
