### ISSUE TITLE
Allow configuration of color of selection bar

### ISSUE THREAD

**Issue by ghuls** [Canop/broot#8]
Allow configuration of color of selection bar.

My terminal has a dark background color.
Now the selection bar is not very visible.

**Comment by ghuls** [comment]
For the other colors, you could maybe use [lscolors](https://crates.io/crates/lscolors) like `fd`
https://github.com/sharkdp/fd/issues/363

**Comment by magnetophon** [comment]
This is what it looks like here:
![2019-02-13-130542_1600x900_scrot](https://user-images.githubusercontent.com/7645711/52710755-6baff300-2f90-11e9-9cee-eebcde7d195c.png)

Configurable colors would be great!

**Comment by ghuls** [comment]
Did you change hard coded values in the source code? or how did you change it?

**Comment by Canop** [comment]
I didn't change them yet. I think.
In any case making the colors configurable is now at the top of my TODO list but isn't done.

**Comment by ghuls** [comment]
No hurry. I was just a bit confused by magnetophon's post.

**Comment by magnetophon** [comment]
> Did you change hard coded values in the source code? or how did you change it?

Nope, didn't change anything.

**Comment by Canop** [comment]
Almost ready

![selection_999 190](https://user-images.githubusercontent.com/617006/52915212-5d840e80-32d1-11e9-9226-16ddb869979a.png)

**Comment by Canop** [comment]
It's done.

But not yet merged into master. Right now it's in the `custom_colors` branch. Testers welcome.

**Comment by ghuls** [comment]
That branch seems to crash:
```
$ RUST_BACKTRACE=1 broot
thread 'main' panicked at 'index not found', src/libcore/option.rs:1008:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:227
             at src/libstd/panicking.rs:491
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   4: rust_begin_unwind
             at src/libstd/panicking.rs:325
   5: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   6: core::option::expect_failed
             at src/libcore/option.rs:1008
   7: <toml::value::Value as core::ops::index::Index<I>>::index
   8: broot::conf::Conf::from_default_location
   9: broot::main
  10: std::rt::lang_start::{{closure}}
  11: main
  12: __libc_start_main
  13: _start
```
Same think after moving my old configuration file.

**Comment by Canop** [comment]
@ghuls I fixed this error, thanks for the report

**Comment by Canop** [comment]
It's merged.

**Comment by ghuls** [comment]
Thanks. It seems to work.
