### ISSUE TITLE
For a symlink to another partition, opening it in a new panel shows a wrong fs size

### ISSUE THREAD

**Issue by jinliu** [Canop/broot#804]
STEPS TO REPRODUCE:
1. Create a symlink to a dir in another partition.
2. `broot --show-root-fs`
3. Press `right` on that link.
4. The fs size on the header bar updates correctly.
5. Press `left` to go back.
6. Press `Ctrl+right` to open the symlink in a new panel.
7. The fs size in the new panel is still that of the left panel.

**Comment by jinliu** [comment]
Perhaps one solution is to make `ctrl-right` behave like `right`: the current directory is set to the target of the symlink, not the symlink itself.

**Comment by Canop** [comment]
I reproduce the problem. I'll have a look.

**Comment by jinliu** [comment]
Yes, it works. Thanks!

**Comment by Canop** [comment]
BTW I'll push another change, I think: removing the filter when doing :panel_right on a directory

**Comment by alexn-s** [comment]
i think this fix or at least version 1.30.0 > breaks something on windows @Canop .
the right/ second panel is broken and commands like cpp and mvp wont work.

the path is not correct

### version 1.30.0, 1.30.1
![image](https://github.com/Canop/broot/assets/60710873/605d0aee-a5c0-4949-b6ad-b3d976eced47)

### version 1.29.0
![image](https://github.com/Canop/broot/assets/60710873/c00a853c-688c-401a-a230-c11a1acc957d)

### sys info
OS: Windows 11 Home x86_64
Terminal: Windows Terminal
shell: nushell

let me know if i can provide more information
