### ISSUE TITLE
When creating a new pane under Windows, the path contains garbage

### ISSUE THREAD

**Issue by AeliusSaionji** [Canop/broot#812]
![image](https://github.com/Canop/broot/assets/4342746/4eb300a7-3980-49d4-afc8-2a9745bb1fba)

This happens with `panel_right`. This syntax looks like some code might be trying to referring to the device ID of the disk, but failing.

This bug was not present earlier this year. Subsequent operations in broot DO fail because the garbled path gets passed to powershell, rmdir, xcopy, etc.

**Comment by Canop** [comment]
I thought I fixed this with broot 1.30.2. Can you check you have the last version ?

**Comment by Canop** [comment]
BTW it's not really garbage but what's called UNC paths: https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths

**Comment by AeliusSaionji** [comment]
You're right, it is fixed!
Sorry, I compile broot locally and I had 1.30.2 on my desktop but not my laptop

**Comment by AeliusSaionji** [comment]
This bug appears to have been reintroduced in version 1.39.1.
Last known working version 1.38.0
1.39.0 untested

**Comment by Canop** [comment]
Oh, thanks for noticing. I know where this comes from.

**Comment by Canop** [comment]
@AeliusSaionji Can you check https://github.com/Canop/broot/pull/899 ?

**Comment by AeliusSaionji** [comment]
done 👍

**Comment by AeliusSaionji** [comment]
It occurs to me that my br.ps1 _could_ be modified to handle UNC paths if this is desirable. Powershell can process them with a certain flag.

It would probably not be desirable though, given that any custom command users may write would have to be aware of this gotcha (need to use flag `-LiteralPath`) across several commands.

![image](https://github.com/Canop/broot/assets/4342746/90cae836-ce5e-44a9-9fd5-2f0068088856)
