### ISSUE TITLE
not a known internal: cp

### ISSUE THREAD

**Issue by Schweber** [Canop/broot#815]
The dystroy website [lists](https://dystroy.org/broot/conf_verbs/#internals) `:cp {newpath}` as an internal. However, if i add `{ invocation: "backup", shortcut: "tb", execution: ":cp {file}~", leave_broot: false }` to `verbs.hjson` and launch `br`, it says `Bad configuration: not a known internal: cp`.

Is the documentation outdated or am i doing something wrong? I am using broot 1.30.2

**Comment by Canop** [comment]
The documentation is wrong, and I have no idea how I ended up pasting this line about `cp` in it. Thanks for noticing. I guess I have to check the whole table now.


You probably know it already, but for your backup verb, the correct execution, given that cp isn't an internal, would be `execution: "cp {file} {file}~"`.

**Comment by Canop** [comment]
This internal table is full of errors... I have to regenerate it from the code

**Comment by Schweber** [comment]
> The documentation is wrong, and I have no idea how I ended up pasting this line about `cp` in it. Thanks for noticing. I guess I have to check the whole table now.
> 
> You probably know it already, but for your backup verb, the correct execution, given that cp isn't an internal, would be `execution: "cp {file} {file}~"`.

I didn't know that, thank you for pointing it out!

**Comment by Canop** [comment]
I fixed the table of internals. There really was a lot of errors...

**Comment by Schweber** [comment]
Thanks!
