### ISSUE TITLE
:trash internal doesn't work in staging area

### ISSUE THREAD

**Issue by Schweber** [Canop/broot#816]
The new `:trash` internal works when applied to a file in a normal window but if i select multiple files and apply it in the staging area it does nothing.

So this does nothing: `{ invocation: "trash", shortcut: "tt", execution: ":trash {file}", leave_broot: false }`

And this works as expected: `{ invocation: "trash", shortcut: "tt", execution: "[trash put](https://github.com/oberblastmeister/trashy) {file}", leave_broot: false }`

**Comment by Canop** [comment]
Did you try it with the release I made yesterday ?

**Comment by Schweber** [comment]
Oooops sorry, i wasn't aware of that. Thank you for fixing it!
