### ISSUE TITLE
Add a --verb-output launch argument

### ISSUE THREAD

**Issue by Canop** [Canop/broot#825]
Similar to the existing `--outcmd`, but the file whose path is given as argument would contain what the verb decides to  write.

The verb could for example be `:write {file}:{line}` or `:write {path}`.

Each time there's a write after the first one, a `\n` would be inserted.
There could be several lines, for example when a verb doesn't quit broot, or when the verb is called in the staging area.

Such a file would mainly be the basis for a rewritten br shell function, which would solve some escaping problems.

Related: https://github.com/Canop/broot/issues/824

**Comment by AndydeCleyre** [comment]
Thanks! To be clear, in your example, `:write` is a new internal that appends to the file specified by `--verb-output`?

Like a manual logger?

**Comment by Canop** [comment]
> Thanks! To be clear, in your example, :write is a new internal that appends to the file specified by --verb-output?

Yes.

**Comment by AndydeCleyre** [comment]
FWIW, I happen to be using a verb with that particular name:

```yaml
  {
    invocation: write {subpath}
    external: $EDITOR {directory}/{subpath}
    leave_broot: false
  }
```

And I'm inclined to think of the upcoming internal as "append line"

**Comment by Canop** [comment]
For a verb similar to yours, which is dedicated to creating new files, I use "create" with shortcut "cr".

`append_line` wouldn't really convey the intent, which is most often to write only one path and exit.

**Comment by AndydeCleyre** [comment]
No! Thanks for the work and the ping!

I'll test today or tonight.
