### ISSUE TITLE
Unreadable text

### ISSUE THREAD

**Issue by kstenerud** [Canop/broot#83]
**Describe the bug**

![Screenshot at 2020-01-09 12-29-29](https://user-images.githubusercontent.com/245857/72064243-c4405b00-32db-11ea-8c27-cdfb59b07c57.png)

**To Reproduce**

```
cargo install broot
broot
```

**Configuration (please complete the following information):**
 - OS: Ubuntu 19.10
 - Version 0.11.3

**Comment by Canop** [comment]
Thanks for the report. I'll fix the skin so that it works with a black text too.

**Comment by Canop** [comment]
It should be OK now
