### ISSUE TITLE
Tagged version 1.33.0 still claims to be 1.32.1-dev

### ISSUE THREAD

**Issue by creideiki** [Canop/broot#830]
While packaging 1.33.0 for Gentoo, I noticed that running `br --version` with it prints `1.32.1-dev`.

I can easily include a patch like the one below so our build has the correct number, but I'm not sure what would suit your release procedure best.

I think the most technically correct way, which doesn't retroactively change anything that has already been made public, would be to update the version to 1.33.1 and make a new tag and release. But that may be unnecessary extra work.

```patch
diff --git a/Cargo.lock b/Cargo.lock
index a24dc4d..f89c6b3 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -217,7 +217,7 @@ checksum = "0d8c1fef690941d3e7788d328517591fecc684c084084702d6ff1641e993699a"
 
 [[package]]
 name = "broot"
-version = "1.32.1-dev"
+version = "1.33.0"
 dependencies = [
  "ahash 0.8.7",
  "ansi_colours",
diff --git a/Cargo.toml b/Cargo.toml
index d77ae58..8e8b2c0 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -1,6 +1,6 @@
 [package]
 name = "broot"
-version = "1.32.1-dev"
+version = "1.33.0"
 authors = ["dystroy <denys.seguret@gmail.com>"]
 repository = "https://github.com/Canop/broot"
 homepage = "https://dystroy.org/broot"
```

**Comment by Canop** [comment]
Damn. I forgot to push the commit with the version update before running the build.

I'll do a 1.33.1

**Comment by creideiki** [comment]
Thanks, 1.33.1 looks good.
