### ISSUE TITLE
Open with preview_text pane open

### ISSUE THREAD

**Issue by jamischarles** [Canop/broot#832]
I LOOOOVE broot. Esp the intuitive commands and using space to use commands. Genius!

Is there any way at all to open broot with the preview_text pane open?

**Comment by Canop** [comment]
2 ways:

1) give broot the path to a file:

`br some/file.txt
`    
 
2) ask broot to open the preview with the -c argument:
 
`br -c :open_preview`

**Comment by jamischarles** [comment]
PERFECT! I combined that with `:focus [currentFolder]` in neovim to open and focus on the current folder. Amazing. Thanks!

**Comment by edrozenberg** [comment]
Looked around for a while to find a way to always open preview via `~/.config/broot/conf.hjson` setting and such as setting does not appear to exist. For ex. I blindly tried `open_preview: 1`.

This `-c` approach works ok, and it's easy enough to create a shell alias to always use this. Would still be nice to be able to spec this as a setting in the broot config file as well.
