### ISSUE TITLE
Installation script does not patch .bash_profile on macOS

### ISSUE THREAD

**Issue by hugodutka** [Canop/broot#84]
**Describe the bug**
On macOS the installation script patches .bashrc instead of .bash_profile. Since Bash on macOS sources from .bash_profile and not from .bashrc on startup, br is not found in path. Moving the patch to .bash_profile fixes the issue.

**To Reproduce**
Install broot on macOS and using Bash try running `br`.

**Expected behavior**
`br` should be found in path and open.

**Configuration (please complete the following information):**
 - OS: macOS
 - Version: Catalina, 10.15.2

**Comment by bluetidepro** [comment]
@hugodutka Do you have a snippet of what the patch is that you moved? I didn't get anything added to `.bashrc` (I think cause it didn't exist for me?).

**Comment by mkborregaard** [comment]
`source /Users/michael/Library/Preferences/org.dystroy.broot/launcher/bash/br`

**Comment by bluetidepro** [comment]
@mkborregaard Perfect, thank you!
