### ISSUE TITLE
Add features for Trash management

### ISSUE THREAD

**Issue by Schweber** [Canop/broot#855]
As broot now includes the `trashy` crate for the `:trash` internal (if i understand it correctly), it could make use of more of its features for managing the Trash.

I would like to have commands to
- `cd` into the system trash directory
- restore files
- clear the Trash directory

This way, broot could replace [trashy](https://github.com/oberblastmeister/trashy), which is not up-to-date anyway.

**Comment by Canop** [comment]
It makes sense

**Comment by Canop** [comment]
@Schweber tests of the PR welcome
