### ISSUE TITLE
How do I move around locations?

### ISSUE THREAD

**Issue by madprops** [Canop/broot#858]
I'm liking broot quite a bit. I hit a roadblock when I tried to cd to another location.

1) Is there a way to use cd inside broot?

2) Is there a way to save bookmarks or visited locations and jump between them?

**Comment by Canop** [comment]
For the **1**, you seem to want `:focus`. 

You can use it in the input by typing `:fo /var` for example.

For the **2**, there's no function to add bookmark but you can define shortcuts in your verbs configuration. You can see some exemples in the default configuration:  https://github.com/Canop/broot/blob/main/resources/default-conf/verbs.hjson#L109

**Comment by madprops** [comment]
Thanks that works nicely. I can backup the verbs and add locations when I need to.
