### ISSUE TITLE
Color scheme produces unexpected output since 1.33.0

### ISSUE THREAD

**Issue by mzanibelli** [Canop/broot#860]
Hello!

I've been experiencing issues with my color scheme since 1.33.0. It happens inside Tmux. Both on Linux + Wayland + Foot (terminal emulator) and on MacOS + Kitty.

The `selected_line` disappears.

I tested a range of things including compiling the project myself and tinkering with it - to no avail. I'm seeing some _similar_ issues [here](https://github.com/Canop/broot/issues/840) and [there](https://github.com/Canop/broot/issues/854) so there might be something wrong still.

Let me know if you need my complete configuration.

Broot 1.32.0:
![image](https://github.com/Canop/broot/assets/16936745/9adb9269-9b96-4d57-8210-533fb1e4aace)

Broot 1.36.1:
![image](https://github.com/Canop/broot/assets/16936745/1ec29ae0-2251-4296-9be8-85016754493c)

**Comment by mzanibelli** [comment]
Found the cause. It's because I had `NO_COLOR` set to 1.
Note: there is a bug in Broot where setting `NO_COLOR` to 0 doesn't re-enable colorschemes. You need to unset the variable for it to work as expected.

**Comment by Canop** [comment]
Regarding your note: I'm following [this](https://no-color.org/)

> Command-line software which adds ANSI color to its output by default should check for a NO_COLOR environment variable that, when present and not an empty string (regardless of its value), prevents the addition of ANSI color.

**Comment by mzanibelli** [comment]
> If you think `NO_COLOR=0` should behave like the variable being absent, please fill an issue. It would probably be better IMO.

Actually I read the NO_COLOR spec again and your implementation is correct. That's why I edited my comment (maybe you read it via mail and didn't see the strikethrough text, no worries). I think it's good to follow the "official" behavior.
