### ISSUE TITLE
Does not compile on Termux (Android) any more

### ISSUE THREAD

**Issue by dead10ck** [Canop/broot#861]
Since #803 introduced a dependency on the `trash` crate, broot does not compile any more, presumably because Android does not have a trash.

```
error[E0433]: failed to resolve: use of undeclared crate or module `platform`
  --> /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/trash-3.3.1/src/lib.rs:67:35
   |
67 |         Self { platform_specific: platform::PlatformTrashContext::new() }
   |                                   ^^^^^^^^ use of undeclared crate or module `platform`

error[E0433]: failed to resolve: use of undeclared crate or module `platform`
  --> /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/trash-3.3.1/src/lib.rs:63:24
   |
63 |     platform_specific: platform::PlatformTrashContext,
   |                        ^^^^^^^^ use of undeclared crate or module `platform`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `trash` (lib) due to 2 previous errors
```

Ideally trash support would be behind a feature so that there is a way to opt out of this feature on platforms which do not have a trash. The feature could be on by default since most major platforms do, but at least it would be easy to make builds on platforms that do not.

**Comment by Canop** [comment]
> Ideally trash support would be behind a feature so that there is a way to opt out of this feature on platforms which do not have a trash. The feature could be on by default since most major platforms do, but at least it would be easy to make builds on platforms that do not.

This looks good. Do you prefer to make a PR or that I do it ?

**Comment by dead10ck** [comment]
Cool, thanks for your support. I can make a PR when I get some time.
