### ISSUE TITLE
broot fail to recognize `suid` and `sgid` bits when showing permission

### ISSUE THREAD

**Issue by Jisu-Woniu** [Canop/broot#863]
This is a comparison between `broot` and `lsd`, both showing the same file `mount.cifs`, which has permission `rwsr-sr-x`:

![comparison between `broot` and `lsd`](https://github.com/Canop/broot/assets/31986081/c1e7c014-1fb9-4295-bb11-74a8fbc6b4c9)

The two `s` in permission means `setuid` and `setgid` respectively, but broot does not recognize those bit and only shows `x` instead.

**Comment by Jisu-Woniu** [comment]
I think this is the code involved:

https://github.com/Canop/broot/blob/df315d6b11a74b289c5276e741b854c0d47738ae/src/display/permissions.rs#L63-L67

The [`has_extra`](https://docs.rs/umask/latest/umask/struct.Mode.html#method.has_extra) method can check the correspond permission.

**Comment by Canop** [comment]
Yes. 
As you searched til the umask crate, you may as well make a PR, right ?
