### ISSUE TITLE
Detect if terminal is black on white and propose to change them accordingly

### ISSUE THREAD

**Issue by Canop** [Canop/broot#87]
This could be done at first launch.

**Comment by rofrol** [comment]
Yup

![image](https://user-images.githubusercontent.com/28787/72139148-82242180-338e-11ea-9c78-965f04d22157.png)

**Comment by Canop** [comment]
I'm on this. Wondering about a reliable solution to use indexed colors. Background are easy: I can remove them. But what about the barely readable gold ? And the magenta if the user has a magenta background ?

**Comment by rofrol** [comment]
https://dystroy.org/broot/documentation/configuration/#opening-the-configuration-file

and this is my black on white (not on gray):

```
[skin]
default = "rgb(0, 0, 0) rgb(255, 255, 255)"
tree = "gray(23) none"
file = "gray(1) none"
directory = "ansi(20) none bold"
exe = "ansi(178) none"
link = "Magenta none"
pruning = "gray(5) none"
permissions = "gray(4) none "
selected_line = "none gray(20)"
char_match = "ansi(28) none"
file_error = "Red none"
flag_label = "gray(16) none"
flag_value = "ansi(202) none bold"
input = "ansi(0) none"
status_error = "ansi(196) gray(22)"
status_job = "ansi(220) gray(18)"
status_normal = "gray(2) gray(22)"
status_italic = "ansi(202) gray(22)"
status_bold = "ansi(202) gray(22) bold"
status_code = "ansi(17) gray(22)"
status_ellipsis = "gray(1) white"
scrollbar_track = "gray(20) none"
scrollbar_thumb = "ansi(238) none"
help_paragraph = "gray(2) none"
help_bold = "ansi(202) none bold"
help_italic = "ansi(202) none"
help_code = "gray(5) gray(22)"
help_headers = "ansi(202) none"
```

**Comment by Canop** [comment]
@rofrol  screenshot of broot with your conf?

Regarding the previous screenshot: this is on installation, before any skin is used. That's the main problem.

**Comment by rofrol** [comment]
Just changed

```diff
-default = "rgb(0, 0, 0) rgb(255, 255, 255)"
+default = "gray(2) gray(23)"
```

![image](https://user-images.githubusercontent.com/28787/72140516-3757d900-3391-11ea-9555-2c7c1aa392b3.png)

**Comment by Canop** [comment]
Version 0.11.5 just released : should not exhibit really unreadable texts during installation process
