### ISSUE TITLE
Multiple arguments to custom verbs.

### ISSUE THREAD

**Issue by BigCrow** [Canop/broot#876]
Option to define a verb that could take a list arguments rather than a single argument. Use case would be something like this:

```[search pattern] MakeMulipleDirs dir1 dir2 dir3```

where the verb in this case wouldn't have only 1 argument "dir1 dir2 dir3", but rather 3 arguments allowing you to create multiple directories with a single verb as you would on the command line.

**Comment by Canop** [comment]
What would be `MakeMulipleDirs` in this case ? An `internal` (predefined operation in broot) or an external program ?

**Comment by BigCrow** [comment]
MakeMultipleDirs would be a custom verb. Something like
```
{
        invocation: MakeMultipleDirs [dirs]
        shortcut: mmd
        execution: "mkmuldirs {directory} [dirs]"
        leave_broot: false
    }
```
here I've used square brakets to indicate a list of arguments compared to 1 argument as an example.
In this case mkmuldirs would be a simple script - something like:
```
#!/bin/bash


dir="$1"
shift

for var in "$@"
do
    mkdir -p "$dir/$var"
done
```

**Comment by BigCrow** [comment]
@SamuelSwartzberg That is exactly what I wanted! Thanks a lot!

**Comment by BigCrow** [comment]
This approach does still have 1 issue though - you are unable to use " for arguments in this case, since broot is automatically managing ". 

I guess a better issue would be to ask for a way to toggle this behaviour depending on the verb. @Canop Should I open a new issue for that or can we reuse this one since it is related?
