### ISSUE TITLE
Put selected path into shell input

### ISSUE THREAD

**Issue by Nama** [Canop/broot#878]
Hi,
would be nice to select a directory or file, run a verb to exit broot and get the path in the input of the terminal to use it with any command and parameters.

Thank you for this awesome project!

**Comment by Canop** [comment]
@Nama Unless I miss something with your specific use case, it's already possible with the `:pp` verb.

It's described here: https://dystroy.org/broot/tricks/#a-generic-fuzzy-finder

**Comment by Nama** [comment]
Ya, I meant something without preparing the command beforehand and using `$(bo)`, but thats good enough.
Thank you!

**Comment by Canop** [comment]
You don't *have* to prepare anything.

Run `echo "hi $(br)"`  for example, select your file, type `:pp`.
