### ISSUE TITLE
Version 1.37.0 image preview works fine, but 1.38.0 and 1.39.0 is broken. MacOS; WezTerm;

### ISSUE THREAD

**Issue by i-api** [Canop/broot#885]
# 1.37
<img width="1105" alt="broot_version_1 37" src="https://github.com/Canop/broot/assets/87678394/f40a345a-6b24-4f05-b573-4294402f8fbf">

# 1.39
<img width="1109" alt="broot_version_1 39" src="https://github.com/Canop/broot/assets/87678394/35625369-53f7-4382-a5c3-6d94a2827a08">

**Comment by Canop** [comment]
As in tradition, this is a weird libc problem.

[This call to ioctl](https://github.com/Canop/broot/blob/main/src/display/cell_size.rs#L33) doesn't work when broot is compiled in release mode but works when broot is compiled in debug mode or if I add stuff to prevent optimization.

**Comment by Canop** [comment]
@i-api Can you check PR https://github.com/Canop/broot/pull/897 fixes the problem for you ?

**Comment by i-api** [comment]
Can confirm! It fixes it!

**Comment by i-api** [comment]
Thank you!
