### ISSUE TITLE
 how do i copy path of selected object

### ISSUE THREAD

**Issue by mrlee14** [Canop/broot#890]
When selecting dir or file would like to copy path to clipboard, this probably exist?

**Comment by Canop** [comment]
Please don't add the "bug" tag when you ask a question.

The `:copy_path` standard verb puts the path of the selection in the clipboard. It's available when broot is compiled with the [clipboard feature](https://github.com/Canop/broot/blob/main/features.md#the-clipboard-feature). If this is something you often do, you may set up a keyboard binding to `:copy_path`.
