### ISSUE TITLE
Is there a way to print the file list and exit, just like `ls`?

### ISSUE THREAD

**Issue by leira** [Canop/broot#895]
I like broot. It of course supersets the features of `ls`. I'd like to use it to fully replace `ls`. Can `br` behave like `ls`, that to print the list of files and exit right away, for the use cases to just have a peak of the files list? Thanks!

**Comment by Canop** [comment]
Yes. You can launch `br -c :pt`.

I recommend having a shortcut for that, so that it's easier to add other arguments. See https://dystroy.org/broot/tricks/#replace-tree

**Comment by Canop** [comment]
I frequently run commands like `tree -s`:

![image](https://github.com/Canop/broot/assets/617006/d19e5985-a73f-49f0-a881-65e9836bace3)

**Comment by leira** [comment]
This is great! Thanks!

One more question. Is it possible to show a simple list of files, just like `ls`, for shell one liners? I tried `br --no-tree -c ":pt"`. It still shows the tree structure lines.

```
󰈺 br --no-tree -c ":pt"
.../nix-config
 ├──dim-screen.sh
 ├──flake.lock
 ├──flake.nix
 ├──home-manager …
 ├──modules …
 ├──nixos …
 ├──nixpkgs.nix
 ├──overlays …
 ├──pkgs …
 ├──README.md
 ├──shell.nix
 ├──xrandr-dim.sh
 └──xrandr-dim.sh~
```

**Comment by Canop** [comment]
Why ? I mean what would be the difference with `ls` ?

**Comment by leira** [comment]
You are right. I should just use `ls` for this use case. I have `eza` installed as a drop in `ls` replacement through an alias. Now I'm thinking about ditching `eza` in favor of `br`. In the same mindset, I want `br` to cover all the use cases I use `eza` for.

Anyway, thanks for the response and this amazing project!

**Comment by Canop** [comment]
ls is always installed on your computer. I'd recommend keeping it for just the case you need to pipe a list into another program, not alias it, and use br for all other cases.

If you'd like broot features (like searching, computing sums, etc.) but still dump a raw list, then a feature request as a dedicated GitHub issue is welcome.
