### ISSUE TITLE
The `broot --install` is not aware of the ZDOTDIR configuration for ZSH

### ISSUE THREAD

**Issue by gumieri** [Canop/broot#90]
**Describe the bug**
The `broot --install` is not aware of the ZSH configuration for the `.zshrc` location.
It is possible to change the default location of `.zshrc` by setting the `$ZDOTDIR` environment variable ([documentation](http://zsh.sourceforge.net/Intro/intro_3.html)).

**To Reproduce**
Define the `$ZDOTDIR` environment variable with a value different of the user's home directory and move the `.zshrc` to this directory and try to install the broot:
```zsh
export ZDOTDIR=$HOME/.config/zsh/
mkdir -p $ZDOTDIR
mv ~/.zshrc $ZDOTDIR
broot --install
```
It will not insert the necessary command at the `.zshrc` file. If does it find the `.bashrc` it will not warn but if it also does not exist it will warn:
```
I found neither .bashrc nor .zshrc.
If you're using bash or zsh, then installation isn't complete:
the br function initialization script won't be sourced unless you source it yourself.
```

**Expected behavior**
The installation process to find the `.zshrc` at the configured location.

**Screenshots**
![Imgur](https://i.imgur.com/jLSWD5J.png)

**Configuration (please complete the following information):**
 - OS: Fedora / Linux
 - Version: 30 / 5.4.7-100.fc30.x86_64
 - ZSH version: zsh 5.7.1 (x86_64-redhat-linux-gnu)

**Additional context**
In my case, I am defining the `$ZDOTDIR` environment variable to all my user session, so when I open the terminal, the zsh start with it already defined.
The location that I am setting it up is at `~/.config/environment.d/zsh.conf`
For more information about  this `environment.d`, [look here](https://www.freedesktop.org/software/systemd/man/environment.d.html), but I think that there's no need of these things for this issue.

**Comment by mkborregaard** [comment]
I've got this same issue on MacOS

**Comment by jounathaen** [comment]
Can confirm. 
Workaround: I create an empty ~.zshrc, run `broot --install`, and copy the contents of that .zshrc to the real .zshrc, everything works.
