### ISSUE TITLE
Version 1.39.1 Breaks Paths on Windows

### ISSUE THREAD

**Issue by Alfamari** [Canop/broot#900]
`\\?\` Is prepended to path causing it to break on windows when attempting to CD.

![mpv_F3fV0nuofV](https://github.com/Canop/broot/assets/132071593/2e477b92-e72f-457b-a040-6b33f9a0d99e)

Rolling back to Version 1.39.0 resolves it.

**Comment by Canop** [comment]
Yes.
I [fixed it yesterday](https://github.com/Canop/broot/pull/899) but didn't release a new version yet. I'll try to do it tonight.

Please don't close this issue until I've released or it won't be visible to other windows users.

**Comment by Alfamari** [comment]
@Canop Sure thing!

**Comment by Canop** [comment]
Done: https://github.com/Canop/broot/releases/tag/v1.39.2

**Comment by Alfamari** [comment]
Thanks for all your work!
