### ISSUE TITLE
Searching from a Root Directory will cause the search to break if first character is included in search

### ISSUE THREAD

**Issue by Alfamari** [Canop/broot#904]
Steps to reproduce:
Go to a root directory and start searching while including first character.

![image](https://github.com/user-attachments/assets/f25da67b-327b-49ce-b04d-c71188060a88)

Workaround:
Omit the first character and start searching from the second character.

![image](https://github.com/user-attachments/assets/cc5e29c5-aa10-44fa-854e-cfbbc583f532)
-
Additional Notes:
Works correctly in Non-root directories
--no-tree flag is set to improve search times though unknown if this has any interaction with the bug

Bug occurs in version 1.39.2 but works correctly in 1.39.0
OS: Windows

**Comment by Canop** [comment]
Thanks for the report, this is a serious bug. I'll try to release a new version of broot today.

**Comment by Alfamari** [comment]
Didn't realize it was serious, but glad to help. And thanks for your speedy updates and constant improvements! :)
