### ISSUE TITLE
.bak files excluded?

### ISSUE THREAD

**Issue by OsicKwon** [Canop/broot#915]
Hello,

I tried to find a keyword inside of many .bak files using:
`f/.bak/&cr/return/i`
but, broot was not able to show the 'return' keyword inside many .bak files even neither .gitignored nor hidden files.

environment:
- Windows 11
- using Windows Terminal app

**Comment by Canop** [comment]
There's really a bug here: the `bak` extension is erroneously in my list of extensions denoting binary files.
