### ISSUE TITLE
Mark excluded files in `toggle_git_file_info`

### ISSUE THREAD

**Issue by kidonng** [Canop/broot#916]
It would be awesome excluded files are given special marks when `toggle_git_file_info` is enabled, in addition to current marks (e.g. `M` for modified).

Example: [eza](https://github.com/eza-community/eza) (an alternative `ls` implementation) supports listing files with [git file info](https://github.com/eza-community/eza/blob/65a08a672ad9fe92cf12f508c0ea8b38e82ccf11/docs/images/screenshots.png). Notice how in the screenshot some files are marked with an `I`, which means the files are ignored by Git.

**Comment by Canop** [comment]
The reason I didn't care about the `Ignored` status is that you can only see those marks when ignored files are shown so I found it to be useless to me. But I have no objection against having it.

**Comment by Canop** [comment]
@kidonng can you confirm that https://github.com/Canop/broot/pull/917 seems to do what you want ?
