### ISSUE TITLE
ctrl-esc/shift-esc to go back to the first match.

### ISSUE THREAD

**Issue by adriangalilea** [Canop/broot#919]
<kbd>ctrl</kbd>-<kbd>esc</kbd>/<kbd>shift</kbd>-<kbd>esc</kbd> to go back to the first match.

Is this possible already?

**Comment by Canop** [comment]
By first match, you mean the first in the list, or the best match ?

**Comment by adriangalilea** [comment]
> By first match, you mean the first in the list, or the best match ?

First in the list, my initial location. Where I started br.

**Comment by Canop** [comment]
To return to where you started broot, you can now define this verb:

    {
        key: ctrl-esc
        execution: ":focus {initial-root}"
    }

But ctrl-esc will only work if you have a modern enough terminal and you enabled the kitty keyboard protocol (see https://dystroy.org/broot/conf_file/#keyboard-enhancements). So you'll probably need to find another key combination. You may look for one with https://github.com/Canop/print_key
