### ISSUE TITLE
Use the nucleo_matcher crate instead of custom fuzzy search

### ISSUE THREAD

**Issue by Martin1887** [Canop/broot#922]
This is not a high-priority feature but https://docs.rs/nucleo-matcher/0.3.1/nucleo_matcher/ would probably increase the performance and the precision of fuzzy search with low-effort, so please consider it.

Thanks!

**Comment by Canop** [comment]
If you have cases which you think aren't well rated by broot's fuzzy pattern matcher, please create a dedicated issue with your test cases.

But I won't just tried any one of the many engines which exist without reason (I tried a few ones, like fzf, and I found them bad, which is why I built one).
