### ISSUE TITLE
Remove the minus in the help file to show hidden files

### ISSUE THREAD

**Issue by Niko72** [Canop/broot#923]
To show hidden files, `default_flags: -gh` should be added to `conf.hjson`. But with the minus sign, you get an error. Without it works as expected.  So it should be removed from the help file.

https://github.com/Canop/broot/blame/728a356987ec2b95a2bbd61b79ac955832c8633c/website/docs/conf_file.md#L91

**Comment by Canop** [comment]
I don't reproduce this. Can you show the error you get and the [log file](https://dystroy.org/broot/community/#log) ?

**Comment by Niko72** [comment]
Sure, no problem! The error I got was `Bad configuration: invalid default flags: "-gh"` And here the [log file content](https://pastebin.com/TWPL1WKC).

**Comment by Canop** [comment]
01:10:56.259 [INFO] cli_log::init: Starting broot v1.24.2 with log level DEBUG

You're using a *very* old version of broot. You need to upgrade in order to get the features and behaviour of the web documentation.
