### ISSUE TITLE
Something like :panel_right_no_open for staging area -- :focus_staging_no_open ?

### ISSUE THREAD

**Issue by AndydeCleyre** [Canop/broot#926]
Maybe I'm thinking about this wrong, but basically, sometimes I add a bunch of files to the staging area, then want to `rm` them. But the way it works makes it easy to accidentally `rm` some selected file in the left pane, whereas I want `rm` to apply to the staging area if and when there *is* one.

So I would want to define my own `rm` verb that does something like `:focus_staging_no_open` (has no effect if there is no staging area, even if there is a right-hand pane), then `rm`.

**Comment by Canop** [comment]
Filtering verbs by the kind of panel might find more use.

Something like

```
    {
        invocation: my_rm
        internal: trash
        panels: staging_area
    }

```
?

**Comment by AndydeCleyre** [comment]
Oh, thanks! I'm looking at that filter description (docs say it should be `stage`) but am unclear on the behavior.

If I assign that to the invocation `rm`, and invoke it while the non-staging panel has focus, will that run and apply to the staging panel? And if no staging panel is open, it will continue to do the default `rm` thing?

**Comment by Canop** [comment]
That's the idea. 
But it looks like this filter is broken (implementation is missing). I'll have a look.

**Comment by Canop** [comment]
With https://github.com/Canop/broot/pull/934, if you define a `rm` with a `panels: ["stage"]` filter, it will be applied when called in the staging area, while the other one will be applied in other panel types.

**Comment by AndydeCleyre** [comment]
I think there may have been a misreading of the behavior I'm after, especially as written in my last comment. I just tested with 1.43.0 and the `my_rm` verb from here, with the following setup (Zsh):

```console
$ mkdir rmtest
$ touch rmtest/do_{,not_}trash_{1,2,3}
$ br rmtest
```

I then mark/select the three `do_trash_*` files, and move focus to one of the `do_not_trash_*` files.

If I try `my_rm` here it says "verb not found" (because of the filter). I was looking for something that would act on the non-focused staging panel. 

But also, when I change focus to the staging panel and try the `my_rm` verb, nothing happens when I hit enter (it still says "Hit enter to my_rm: :trash").

**Comment by Canop** [comment]
> I think there may have been a misreading of the behavior I'm after

This is exact. I reopened.

**Comment by Canop** [comment]
@AndydeCleyre Is https://github.com/Canop/broot/issues/926 better ?

I named it `:focus_staging_area_no_open` to be more consistent with the existing `:open_staging_area`.

**Comment by AndydeCleyre** [comment]
Thank you, yes when I explicitly build with the trash feature enabled that works! The only thing is that the hint text before I hit enter reflects the currently focused file, which is misleading, because the value of `file` changes during the action.

```
Hit enter to my_rm: :focus_staging_area_no_open;:trash /home/andy/.config/broot/rmtest/do_not_trash_1
```

After hitting enter, `do_not_trash_1` is not deleted, which is good.
