### ISSUE TITLE
composite pattern, searching .rs files only

### ISSUE THREAD

**Issue by FrancescElies** [Canop/broot#927]
Using 1.41.0, let's say I want to search `clipboard` on rust files only, I would do a composite pattern.
<img width="726" alt="grafik" src="https://github.com/user-attachments/assets/16105b27-5a56-45f5-be3d-cd7253ac9568">

From [here](https://dystroy.org/broot/navigation/#composite-patterns) I get the feeling I could use `/rs$&c/clip`

<img width="726" alt="grafik" src="https://github.com/user-attachments/assets/76b65de1-3f2d-45b1-951c-4c40fa679669">

As I understand this is not supported because it would be difficult to know to know if & belongs to the regex or to the composite pattern?

What would be the way to search in the broot repo without seeing matches in other files appart from rust files only? 
I tried with tokens `t/.rs&c/clipb` but that is not supported either.

**Comment by Canop** [comment]
This is totally supported but you have to close the first pattern with a `/`:

    /rs$/&c/clipb
    
 I try to explain how it works here: https://dystroy.org/broot/input/#the-filtering-pattern
 
 I'd welcome comments regarding how to make it clearer

**Comment by FrancescElies** [comment]
I think just searched in the wrong [part of the docs](https://dystroy.org/broot/navigation/#composite-patterns), your readme and the link you sent explains that.

I would see this as my fault, it works.
![image](https://github.com/user-attachments/assets/c0a83c6a-e129-47ab-b4d5-e969ee224f1e)

I guess I just simply missed it.

Thanks for your reply, closing.
