### ISSUE TITLE
Suggest adding brew to installation instructions

### ISSUE THREAD

**Issue by mstudio** [Canop/broot#93]
**Feature request for installation instructions on website**
This may be obvious to some, but it may be helpful to add `brew install broot` to the installation instructions on:
https://dystroy.org/broot/documentation/installation/
Great tool. Thank you.

**Comment by Canop** [comment]
The problem is: I'm not the maintainer of this brew formula and I don't really know how I shall do to guarantee people there's no Trojan inside.

**Comment by Joshfindit** [comment]
Not even being a rust user, I’m perfectly ok with just using cargo.
I understand people who want everything in brew, but as cargo deployment gets more common it’ll make more sense to just use it directly.

**Comment by mstudio** [comment]
Thanks @Canop, I didn't realize you weren't the maintainer. @Joshfindit good point.

**Comment by Canop** [comment]
I do see a problem in using cargo: it takes a lot of space on your disk and rust compilation is very slow.

**Comment by dstroot** [comment]
I have no understanding of cargo but have used homebrew for years and years.  I didn't even think broot supported macOS from the installation page since only windows and linux binaries are listed.  I installed via Homebrew
