### ISSUE TITLE
Open broot with a default selected file/directory.

### ISSUE THREAD

**Issue by jdrupal-dev** [Canop/broot#936]
I am using broot as my file manager and file navigator in neovim.
I would like to be able to have the current file preselected when I open broot in neovim.

Currently I achieve this with this command `"broot -c ':select " .. vim.fn.expand("%:") .. "'"` e.g. `broot -c ':select some/dir'`.
This works fine when the directory or file is expanded in broot, but does not work for very nested directories or files.

Would it be possible to auto-expand the tree when passing `some/very/long/and/nested/dir/file.txt` to the :select command?

This would be very helpful as I would be able to navigate in the files that are close to the one that I am currently working with.

**Comment by Canop** [comment]
Just to be sure: the reason you don't use `broot some/very/long/and/nested/dir/file.txt` is because you want to keep the current tree root ?

**Comment by jdrupal-dev** [comment]
Yes, I would still like to be able to search for files in the entire project.

**Comment by Canop** [comment]
ok, noted.

**Comment by Canop** [comment]
@jdrupal-dev Can you test https://github.com/Canop/broot/pull/937 ?
