### ISSUE TITLE
Termux: Termimad Error : IO error: Permission denied (os error 13)

### ISSUE THREAD

**Issue by dilongx** [Canop/broot#940]
Using broot version after 1.41.1 in Termux, I get "Termimad Error : IO error: Permission denied (os error 13)" May I ask why this happens and how to solve it?

**Comment by Canop** [comment]
I don't maintain anymore any solution to build the termux version.

May I ask you how you managed to build the recent versions of broot for termux ?

**Comment by dilongx** [comment]
> I don't maintain anymore any solution to build the termux version.
> 
> May I ask you how you managed to build the recent versions of broot for termux ?

It's an official build.
https://github.com/termux/termux-packages/blob/master/packages/broot/build.sh

I'm not sure if that's the reason, I'm just looking for a solution, maybe I should ask in the termux-packages project?

**Comment by dilongx** [comment]
@Canop Thanks for the reply, they fixed it!

**Comment by Canop** [comment]
for reference: https://github.com/termux/termux-packages/issues/21424
