### ISSUE TITLE
Fails to build with GCC 15 (dependency onig_sys)

### ISSUE THREAD

**Issue by creideiki** [Canop/broot#956]
I'm not sure if broot can actually do anything about this, but other packagers will hit it eventually once GCC 15 is released, so here's a heads up:

Gentoo has started experimenting with using prereleases of GCC 15 as the system C compiler. When that is the case, `onig_sys`, which is a dependency of broot, fails to build. Downstream bug: https://bugs.gentoo.org/943785

`onig_sys` contains a copy of the Oniguruma C source code, which is used by default. That copy is very old, and in particular does not include the fixes from kkos/oniguruma#312 for GCC 15 compatibility.

I've filed a bug (rust-onig/rust-onig#191) and asked for an updated snapshot in `onig_sys`, but that project does not seem to be particularly actively maintained.

What I did instead in Gentoo was to tell `onig_sys` to use the system copy of the Oniguruma library (in Gentoo this is release 6.9.9 + GCC 15 patches), by setting the environment variable `RUSTONIG_SYSTEM_LIBONIG=1`. This seems to work, but means we're using a newer Oniguruma than intended.

Would you be interested in building other packages the same way, so we'll at least all be testing with vaguely the same version of Oniguruma? Or do you have some other suggestion of how to handle this problem?

**Comment by Canop** [comment]
I think we can just build without onig. I'm testing whether it has some impact (might impact the performances of code preview).

**Comment by Canop** [comment]
@creideiki Is the problem solved with https://github.com/Canop/broot/pull/957 according to you ?

**Comment by creideiki** [comment]
Seems to work, with my limited testing - #957 builds with GCC 15 and still gives me syntax highlighting in source code.

**Comment by Canop** [comment]
I didn't remove syntect, just compiled it so that it uses another regex lib, a pure rust one. So it probably works ok but there *might* be subtle bugs...
