### ISSUE TITLE
Alt-Enter does not exit to shell on Mac

### ISSUE THREAD

**Issue by curioustolearn** [Canop/broot#96]
**Describe the bug**
On mac if I press the alt-enter, it does not return to shell. It just navigates to that directory But stays in broot (as if only enter was pressed).

**To Reproduce**
Open broot using br. Choose a directory and the press alt and enter together.

**Expected behavior**
The same outcome as one obtains when typing the :cd command.

**Configuration (please complete the following information):**
 - OS: macOS Mojave
 - Version: 10.14.4

**Comment by Canop** [comment]
I think this is the same as https://github.com/Canop/broot/issues/86

**Comment by Canop** [comment]
Can you tell whether you used the brew installation or another one ?

**Comment by dstroot** [comment]
Why isn’t MacOS and Brew listed under installation instructions?

**Comment by Canop** [comment]
@dstroot  I suggest we discuss this specific part here: https://github.com/Canop/broot/issues/93

**Comment by dstroot** [comment]
Thanks - sorry.  I am seeing the same behavior after installing via homebrew on macOS catalina.  Using "option" + "enter" since the Mac keyboard does not have "alt".

**Comment by aleris** [comment]
I installed it with `cargo install broot` and facing the same problem, does not seem to handle `option-enter`, also probably should print `option-enter` instead of `alt-enter` on mac?

**Comment by Canop** [comment]
@aleris What terminal are you using ? Does [this](https://github.com/Canop/broot/issues/86#issuecomment-572641935) work for you ?

**Comment by Canop** [comment]
I'm closing this duplicate issue.
Please continue discussions on this topic here: https://github.com/Canop/broot/issues/86

**Comment by aleris** [comment]
> @aleris What terminal are you using ? Does [this](https://github.com/Canop/broot/issues/86#issuecomment-572641935) work for you ?

Yes, it worked.
