### ISSUE TITLE
Terminal title is not restored upon exit

### ISSUE THREAD

**Issue by kidonng** [Canop/broot#966]
Terminal: iTerm 3.5.10
Shell: fish 4.0b1-60-gb97598fa6

When `terminal_title` option is enabled, terminal title will change (as expected) as changing directory in broot, but not restored (to before launching broot) upon exit, either via the `:quit` command or corresponding shortcut.

**Comment by Canop** [comment]
> not restored (to before launching broot)

I can reset the terminal title to its default state (with  `write!(w, "\u{1b}]2;\u{07}");w.flush();`), but I have no idea how to restore in a reliable way the title the terminal had just before launching broot.
