### ISSUE TITLE
Use ctrl-c to quit?

### ISSUE THREAD

**Issue by canadaduane** [Canop/broot#97]
**Is your feature request related to a problem? Please describe.**
As a new user, I had to look at help to figure out how to quit. I think this is bad UX for a command-line tool.

**Describe the solution you'd like**
Make `ctrl-c` quit. This could be in addition to `ctrl-q` or instead of.

**Describe alternatives you've considered**
`ctrl-d` is also a common way to quit an interactive CLI, but less so.

**Additional context**
I know `:q` quits, and this works fine for people familiar with vim, but it's also a classic frustration of vim when newcomers try to leave.

**Comment by Canop** [comment]
I'd welcome other opinions on that one. I don't see any immediate objections.

(of course this shorcut can already be added in config)

**Comment by eaubin** [comment]
I'd prefer ctrl-c to be the default as it's the typical way to kill a running process in bash.
